### ISSUE TITLE
Hair color fail

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1000]
![pic1](https://cloud.githubusercontent.com/assets/22244296/18610610/fdd20694-7d20-11e6-84d1-4355878c7e75.png)
![pic2](https://cloud.githubusercontent.com/assets/22244296/18610611/fde80bec-7d20-11e6-995d-45ea828081a2.png)
![pic3](https://cloud.githubusercontent.com/assets/22244296/18610612/fdf6a576-7d20-11e6-963c-5454251b4c66.png)

**Comment by unknownforces** [comment]
This is the same on official

**Comment by Uppermost** [comment]
Yes same on official, we can do nothing :/
