### ISSUE TITLE
Server crash, seem's to be removesp problem.

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1002]
![crash](https://cloud.githubusercontent.com/assets/22244296/18610813/51cec3a4-7d26-11e6-8dce-f22dfc3d7cc5.png)

**Comment by Uppermost** [comment]
RemoveSp problem again

**Comment by The-Art-Of-War** [comment]
yeah it seems to be tricky.. dunno why exactly it happens it often happend while using speed command

**Comment by chucktheripper** [comment]
somehow the iteminstance hasn't been created for the inventory, whats the history of the Wildkeeper Card? Has it been generated directly, traded, dropped, anything like that?
