### ISSUE TITLE
Error in Login Server Console

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1003]
![login](https://cloud.githubusercontent.com/assets/22244296/18615083/57f9b744-7d9d-11e6-9f1c-e4cd0842dd5c.png)

**Comment by 0Lucifer0** [comment]
Wtf How did You USE battle Packet Handler in Login ?

**Comment by MyTaleON** [comment]
@0Lucifer0  i dosn't use the battle packet..^^

**Comment by MasterDomino** [comment]
but the exception is clearly thrown in battlepackethandler

**Comment by 0Lucifer0** [comment]
Yes It does just read the exception... It try to USE use skill

**Comment by chucktheripper** [comment]
LoginServer also instantiates the Handlers as it seems, using skill packet on the Server seems to trigger the method but it has no valid session.

**Comment by chucktheripper** [comment]
to fix this Problem we should exclude other handlers for Login server

**Comment by chucktheripper** [comment]
in future, add more Information how you produced the Errors.
