### ISSUE TITLE
review revive function not displaying death animation on vehicle removal

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1004]
All is on the tittle, when you dead on official vehicle is removed.

**Comment by MasterDomino** [comment]
should be already done o.O

**Comment by Uppermost** [comment]
It doesn't work on MyTale server on the latest version, I go test it on my local server

**Comment by chucktheripper** [comment]
Whats up with this issue?

**Comment by Uppermost** [comment]
Blocked

**Comment by chucktheripper** [comment]
By what?

**Comment by Uppermost** [comment]
The character dead, the locomotion is removed, but there is nothing dead animation.

**Comment by 0Lucifer0** [comment]
need to wait a little delay between remove and dead animation packet :)
