### ISSUE TITLE
implement monster mp usage

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#1005]
When Monsters use skills or magical skill, they should loose mp. And they can't attack if the monster have only magical skill, he can't attack.

**Comment by Uppermost** [comment]
Now monster use mp after martazza commit, need to cancel magical attack or skill now if there is no enough mp !

**Comment by 0Lucifer0** [comment]
seem's to work

**Comment by MasterDomino** [comment]
rememeber that he can attack by using skill that doesnt use mp(aka basic skill)

**Comment by Uppermost** [comment]
Monster continue to attack after all MP lose (reload)

**Comment by chucktheripper** [comment]
Add a check if the mob has mp left to use before monster skill usage
