### ISSUE TITLE
Wrong ID or Password

### ISSUE THREAD

**Issue by multicaglar** [OpenNos/OpenNos#1006]
Hi,
I have just created server. I created an account but it isnt work. When I try to log in, it say wrong id or password. I tried sha256 and sha512. How do I fix this?

**Comment by Uppermost** [comment]
Password is not recognized : verify that your password is hash in sha512 and that your launcher(made it yourself) is done with the most recent nostaleX.dat

**Comment by Brvortex** [comment]
Bro you need to check nostale updates. Probably u didnt update your game . I mean just check it. Ve Türkmüsün?

**Comment by multicaglar** [comment]
Okay. I'll check it. Nerden anladın?

**Comment by Brvortex** [comment]
Because ismin multi"caglar"(çağlar) Burdan Anlaşılıyor ^^

**Comment by Brvortex** [comment]
İf u have skype adress give your name to me I'll add u.

**Comment by multicaglar** [comment]
İt worked. I guess the problem was launcher. I changed launcher and it works. Skype ismim ayni bu arada.

**Comment by Brvortex** [comment]
Tamamdır ekledim.

**Comment by 0Lucifer0** [comment]
that's why it's written in readme to do your own launcher...

**Comment by Brvortex** [comment]
xD
