### ISSUE TITLE
Replace a lot of things by mapping

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#1007]
There is a lot of gameobject that can be replace by mapping
(search  //Replace by MAPPING) we need to look at a way to make all Mapping possible just with BaseDAO

**Comment by chucktheripper** [comment]
The Mappings should be registered automatically, if a GO derives from a DTO, the Automapper should cast the Entity directly to the GO without the DTO between them. This is achieved with RegisterMapping and MapEntity atm thru SerializableBaseDAO
