### ISSUE TITLE
Points on specialists always 0

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#1011]
Whenever I set points on specialists, it says "Points set" but it just goes to 0

**Comment by Uppermost** [comment]
Because you need to do like that $SPRefill VALUE and it set always to the max ;)

It work fine 
![image](https://cloud.githubusercontent.com/assets/15254478/18709343/f3e02b66-7fff-11e6-8e97-83b9c07f5e70.png)

**Comment by chucktheripper** [comment]
Doesnt he mean specialist skillpoints?

**Comment by Uppermost** [comment]
Ah sorry yes maybe

**Comment by chucktheripper** [comment]
Recognition of sp was int id previously, this seem to have problems with new guid, we need a temporary recognition for sp
