### ISSUE TITLE
Error Login.

### ISSUE THREAD

**Issue by Nicolr3** [OpenNos/OpenNos#1012]
He tried to login with the data base default data and it does not work.

![d566ee91c3d398c639d02964ec6bfc52](https://cloud.githubusercontent.com/assets/6991295/18712067/06151bd6-800d-11e6-87f6-6829cb269f39.png)

![07bc68cd89ca27d15956c88794061725](https://cloud.githubusercontent.com/assets/6991295/18712070/08ce1558-800d-11e6-8d44-4c73adae80ee.png)

I've tried everything and nothing.

**Comment by Legend92** [comment]
controll navicat.. Id correct and password

**Comment by Nicolr3** [comment]
I have this in Navicat
![442bec5ed0ba23eb6299f27e4847485a](https://cloud.githubusercontent.com/assets/6991295/18712222/b1c48d90-800d-11e6-91fa-a82c6544a408.png)

**Comment by Uppermost** [comment]
Sha512 and launcher at the latest version.

**Comment by Nicolr3** [comment]
I am trying to run the launcher to play locally and on sha512 I have already tried and nothing

**Comment by 0Lucifer0** [comment]
Because you use old launcher. Read the FAQ

**Comment by Nicolr3** [comment]
And as I set it up to use it in the last launcher?

**Comment by 0Lucifer0** [comment]
Just do your own launcher

**Comment by Nicolr3** [comment]
You mean change the IP in the NostaleX.dat?

**Comment by 0Lucifer0** [comment]
Exactly after update client
