### ISSUE TITLE
Monsters

### ISSUE THREAD

**Issue by Nicolr3** [OpenNos/OpenNos#1014]
Thanks for the help before, and I could solve. I would like to know how to make the monsters can move, I put the "mv parse packets" in parser and does not work. Some help?

**Comment by Uppermost** [comment]
You need to connect on the official nostale, recolt all data with packetlogger and after use the parse to parse all and it work, it's not here to ask a question...

**Comment by 0Lucifer0** [comment]
Seriously read the fucking readme!!!!!

**Comment by Uppermost** [comment]
Yes, we are tired of always repeating the same things ...
