### ISSUE TITLE
monster move problem

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1019]
Monsters move too often in the same direction example monster move 4 case to the left, we need to fix that to 2/3 case maximum because we feel that the monster runs very fast and it is not normal (It cause a problem sometime the monster go to 5/6 case and seems teleported (because i go on some case very quickly)
https://gyazo.com/8a0c29dea5a67798863ba53b9c696af1 (Monster seems too much speed)

We need to talk about this system because it's not good yet

**Comment by 0Lucifer0** [comment]
You just need to change the delay the system is good
