### ISSUE TITLE
Connection impossible> Account blocked ?

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1020]
![image](https://cloud.githubusercontent.com/assets/15254478/18732915/0fa8524e-8067-11e6-9dfd-95962dbfac2b.png)

Edit : This problem appear after equip an item (item 4280) and disconnect, and the account is blocked, but with an other account it work fine. New item cause this problem.

**Comment by chucktheripper** [comment]
Equipment slot is missing or wrong
