### ISSUE TITLE
name  no support Chinese

### ISSUE THREAD

**Issue by ixren** [OpenNos/OpenNos#1021]
System.Text.RegularExpressions.Regex rg = new System.Text.RegularExpressions.Regex(@"^[a-zA-Z\u4e00-\u9fa5][a-z0-9\u4e00-\u9fa5]{2,15}$");

 support Chinese name?

**Comment by Uppermost** [comment]
Not supported yet. Can you send me all chinese char please ?

**Comment by ixren** [comment]
[a-zA-Z\u4E00-\u9FA5-\u4E00-\u9FFF]{2,20}

char?

**Comment by chucktheripper** [comment]
a character to test the regex (letter)

**Comment by Martazza** [comment]
中华人民共和国

**Comment by ixren** [comment]
thank
OpenNos.Import.Console How to support Chinese data import?
I tried, the results garbled mysql

http://v1.freep.cn/3tb_160923140720vbvd512293.png

**Comment by ixren** [comment]
Strange or not supported, you can manually modify the display.

![qq 20160923143132](https://cloud.githubusercontent.com/assets/22013930/18776346/35298602-819b-11e6-8fe7-e3da235749a5.png)
![qq 20160923143452](https://cloud.githubusercontent.com/assets/22013930/18776353/40d9138c-819b-11e6-92a8-ded2790fb8ac.png)
![qq 20160923143507](https://cloud.githubusercontent.com/assets/22013930/18776352/40d8a3ac-819b-11e6-86fa-1a1968994d45.png)
![qq 20160923143530](https://cloud.githubusercontent.com/assets/22013930/18776354/4165289a-819b-11e6-8b56-57bebcd74d78.png)
