### ISSUE TITLE
Character stuck after attack monster 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1023]
![image](https://cloud.githubusercontent.com/assets/15254478/18751139/3b8a175e-80de-11e6-90c4-cd5cb48da1af.png)

I don't know how to reproduce it, and monster life was empty for some seconds...

**Comment by 0Lucifer0** [comment]
so that was just a server lag ^^

**Comment by Uppermost** [comment]
This problem is again occur and very often after use skill.

**Comment by Uppermost** [comment]
We need to fix that it's very very boring to teleport all player every time because they go out the map after use portal etc

**Comment by 0Lucifer0** [comment]
Disconnection when attack already in issue
