### ISSUE TITLE
Teleporter bug again (bug when there is some people connected)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1025]
![image](https://cloud.githubusercontent.com/assets/15254478/18752800/d72799ac-80e3-11e6-9412-f6baee85cd18.png)

**Comment by Uppermost** [comment]
I receive the packet in double

eff 2 1950 857
eff 2 1966 857
eff 2 1957 3002
eq 22 0 0 1 7 2 -1.107.32.78.-1.4130.-1.-1.-1 108 00
pairy 1 22 4 2 50 41
eff 1 1 4379
eff 1 21 871
eff 1 20 871
eff 2 1966 857
eff 2 1950 857
drop 1046 100 32 143 240 0 0 -1
eff 1 22 6
eff 1 22 198
ct 1 22 3 1752 -1 -1 240
su 1 22 3 1752 240 8 11 257 31 142 0 0 933 0 0
eff 2 1957 3002
ct 1 22 3 1753 -1 -1 240
su 1 22 3 1753 240 8 11 257 33 141 0 0 1035 0 0
out 9 50
eff 1 1 4379
eff 1 21 871
eff 1 20 871
ct 1 22 3 1751 -1 -1 240
su 1 22 3 1751 240 8 13 270 33 141 0 0 907 0 0
in 3 24 1752 30 142 2 100 100 0 0 0 -1 1 0 -1 - 0 -1 0 0 0 0 0 0 0 0
eff 3 1752 7
eff 2 1950 857
eff 2 1966 857
in 3 24 1753 32 141 2 100 100 0 0 0 -1 1 0 -1 - 0 -1 0 0 0 0 0 0 0 0
eff 3 1753 7
drop 1012 106 30 142 1 0 0 -1
eff 1 22 6
eff 1 22 198
ct 1 22 3 1752 -1 -1 240
su 1 22 3 1752 240 8 11 257 33 141 0 0 997 0 0

**Comment by 0Lucifer0** [comment]
same reason as #1032
