### ISSUE TITLE
Problem with group

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1033]
When one player is in group with me and I disconnect, when I reconnect I see under the character "In group"

or that : 
![image](https://cloud.githubusercontent.com/assets/15254478/18761032/a9afb55c-8103-11e6-9910-7e241128988e.png)

or that : 

![image](https://cloud.githubusercontent.com/assets/15254478/18787399/05829008-81a3-11e6-967e-fd4f5f74e716.png)

**Comment by Uppermost** [comment]
#992

**Comment by MasterDomino** [comment]
also theres error thrown when relogging and in group
