### ISSUE TITLE
Need to reduce delay to transform

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#1041]
Like when my char stops walking, it takes too long before it allows me to transform into SP

**Comment by Uppermost** [comment]
MasterDomino add a delay to remove a bug, if we remove that the problem can be back again. We need to find an other way to do that (I don't remember what it was...)

**Comment by DarkCacos** [comment]
I think this was the problem, when you spam G while walking: [This](https://gyazo.com/e0022f98a166873b85b736d3e407c81b)

**Comment by Uppermost** [comment]
Yes maybe I not sure too. Thank xD

**Comment by unknownforces** [comment]
Yeah i'm aware of that but idk.. you can do the same thing with transforming into mount, I don't think it is an issue. The only reason you can't see it on official is because delay is too strong. (imo)

**Comment by MasterDomino** [comment]
its same as on official i tested it a lot of times and its even lower than official.
