### ISSUE TITLE
You can't equip fairy in SP pirate (for example)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1043]
Can't equip fairy when you use SP pirate...

**Comment by 0Lucifer0** [comment]
Should we accept all fairy ?

**Comment by Uppermost** [comment]
Not all, all fairy with element yes. Chicken fairy no, only for chicken and I don't know if the chicken sp accept all fairy I think yes but pirate no don't accept fairy chicken etc...

**Comment by 0Lucifer0** [comment]
so pirate only accepte fairy elemental?

**Comment by Uppermost** [comment]
not completly fix, we don't want to wear this fairy it's only for chicken sp

![image](https://cloud.githubusercontent.com/assets/15254478/18808014/95cef5d0-8256-11e6-9a2e-833e96a96a8d.png)

**Comment by 0Lucifer0** [comment]
are you sure we can't use it ?
