### ISSUE TITLE
Console Login Error

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1050]
![screenshot_5](https://cloud.githubusercontent.com/assets/22244296/18797027/2bacc9d2-81cc-11e6-802c-05897a379078.png)

![screenshot_6](https://cloud.githubusercontent.com/assets/22244296/18797051/47a72146-81cc-11e6-91c2-133e63ada343.png)

**Comment by Uppermost** [comment]
#1034
