### ISSUE TITLE
Shop bug when you use CTRL+Z

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1059]
All on the tittle.

**Comment by itemhack** [comment]
it is like the official 
if someone try a trade option and you press ctrl+z the windows disappear

**Comment by 0Lucifer0** [comment]
Yes but we want to provide a fix for this ;)

**Comment by chucktheripper** [comment]
I already tried to do this but the items inside the shop are clientside and i didnt find a solution to reload them from Server into this window.
