### ISSUE TITLE
World Server Error

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1062]
https://cdn.discordapp.com/attachments/228222938996801539/229337247281971201/craz.png

**Comment by BelminBIH** [comment]
https://cdn.discordapp.com/attachments/228222938996801539/229337247281971201/craz.png

**Comment by Uppermost** [comment]
This errpr cause the crash of server?

**Comment by BelminBIH** [comment]
https://cdn.discordapp.com/attachments/228222938996801539/229337247281971201/craz.png

**Comment by 0Lucifer0** [comment]
Your vps problem
