### ISSUE TITLE
Act 6 items wrong stats

### ISSUE THREAD

**Issue by PonyWarrior** [OpenNos/OpenNos#1064]
Level 95 Bow has higher stats than +25 Bow
![screen shot 09-25-16 at 01 41 am](https://cloud.githubusercontent.com/assets/22421356/18811922/0e4b97c8-82c2-11e6-8c1d-2fee2c59cd89.PNG)
![screen shot 09-25-16 at 01 40 am](https://cloud.githubusercontent.com/assets/22421356/18811923/11252e1e-82c2-11e6-8431-cee7529121e9.PNG)

**Comment by Martazza** [comment]
8930cc88a4307650609d50800c48b84974b03543
