### ISSUE TITLE
SP Inventory issues

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#1071]
1) Whenever I remove SP from SP inventory, I get disconnected and this error shows up.
2) I can't put SP into SP inventory
3) when re arranging order, the last 2 SP's keep swapping spots with each other.

These issues are producible when you remove an sp leaving a gap and then refresh the inventory.
![untitled](https://cloud.githubusercontent.com/assets/19580091/18815130/4e5e7a58-836a-11e6-939e-a43cd733c560.png)

**Comment by Uppermost** [comment]
Delete the database and update all we don't have this problem on test server at the latest version ;)

**Comment by unknownforces** [comment]
@Uppermost I did that and the issue is still here..
