### ISSUE TITLE
Private shop problem

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1075]
![image](https://cloud.githubusercontent.com/assets/15254478/18816849/3b412c1c-8352-11e6-9b34-c4f70b364932.png)

**Comment by MasterDomino** [comment]
whole shop function doesnt work try using debug on loop and it wont work need to check every slot

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/19073913/df28ad9a-8a3d-11e6-83b1-713e3f2d1ed3.png)
 Work fine on my local game, but it doesn't work online >< WTF

**Comment by chucktheripper** [comment]
Check receive packet order.

**Comment by Uppermost** [comment]
+ Name incorrecte

Example chucktheripper buy an item to me It show MyName buy x1 and not the good name > chucktheripper

**Comment by Uppermost** [comment]
When you buy an item it doesn't work, you don't have the item and nothing happens just say "Item buy"

**Comment by chucktheripper** [comment]
Should be already fixed
