### ISSUE TITLE
Priority of packet send

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1076]
You see nobody on the map after change map, there is a lot of latence cause by packet no send etc
There is some problems and we need to see.

Seem's to be laggy by moment etc...

https://gyazo.com/1327d10d7a47baee21e4cebc225af2b9 : Spam at the maximum speed

This problem seem's to be the next the packet is send to all person on the me (I see that with packetlogger but my session display nothing.)
PS : Latency is not everytime here
If someone have the same problem in multiplayer please tell it here

After some test packet are send but not receive at the good moment ;)

This problem, don't appear in local but appear on VPS when there is nobody. The number of player on the map change nothing. Sometime I work and sometime it doesn't.

**Comment by Uppermost** [comment]
[.Send | 01:05:00.] rest 1 1 3
[.Recv | 01:05:01.] rest 1 3 0

Sometime there is 1 second of difference beetween they 2 informations why it's not at the same time?

**Comment by Uppermost** [comment]
Ok after client redownload this problem seem's to be gone ! Need more time to see if now it's ok :) but #1091 it's not link to this problem in fact

**Comment by Uppermost** [comment]
The problem returned after the reboot of the server... Again the same problem...

**Comment by chucktheripper** [comment]
We need to add a priorities for packets which are sent thru the handlers, not from a map or mob task.

**Comment by chucktheripper** [comment]
No priority as it is instant send thru BroadcastableBase eventhandler
