### ISSUE TITLE
Invisible doesnt allow to attack monsters

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#1078]
if you try to attack monsters when youre invisible by command $Invisible you will get stuck
we need to make it works with killing monsters and also send killed monster info to rest of players

**Comment by Uppermost** [comment]
Worked fine 1 week ago.

**Comment by MasterDomino** [comment]
now it sometimes does other times it cancels your skill, other times it shows the living creature for others

**Comment by Uppermost** [comment]
Yes because $Invisible command don't send the in packet it's logic...

**Comment by 0Lucifer0** [comment]
We cant do anything for this issue it's an client problem >< invisible don't show you on map and client use this to understand death

**Comment by MasterDomino** [comment]
but its not player death its monster death

**Comment by 0Lucifer0** [comment]
Yes but You need a owner of the skill >< if you don't send in Packet you cant be owner of skill

**Comment by Uppermost** [comment]
Close it then, We don't want to send in packet like official...

**Comment by Uppermost** [comment]
On official I already see GM kill monster in invisible and there is the same problem.

**Comment by 0Lucifer0** [comment]
You just need to send cancel
