### ISSUE TITLE
Add remove monster command

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1083]
We need to remove monster added by $AddMonster like portal remove.

Because they monster are definitive we need to find a way to remove them whitout go in database.

**Comment by 0Lucifer0** [comment]
Just keep last monster ncif id ;) You CAN delete after select it :)

**Comment by Uppermost** [comment]
Nice idea luci

**Comment by Martazza** [comment]
To do:
Add a Delete Method to remove mob from DB.

**Comment by Martazza** [comment]
#1085
