### ISSUE TITLE
Its not possible to Send Items with + and rarity

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#1084]
It's maybe not possible on official too ^^

**Comment by The-Art-Of-War** [comment]
But it would be good BTW IM DOING A CONVERSATION WITH MY SELF?!?! xD

**Comment by 0Lucifer0** [comment]
Thats normal ;) rarity should be random ;)

**Comment by The-Art-Of-War** [comment]
really is it random on official too?

**Comment by 0Lucifer0** [comment]
Yes because we only can have equipment by drop
