### ISSUE TITLE
Add monster health command

### ISSUE THREAD

**Issue by SC909** [OpenNos/OpenNos#1085]
On official, there is a command that lets you to decrease every monsters health to 1.
This command has an effect on all monsters around the GM.

**Comment by 0Lucifer0** [comment]
Good idea :)

**Comment by Legend92** [comment]
nice idea :)

**Comment by Zeshyu** [comment]
Maybe we/you could also add a command to instantly despawn them.. so we can weaken and despawn them.^^
Just sayin.

**Comment by MasterDomino** [comment]
For me its useless we already have godmode
