### ISSUE TITLE
Add Notice-System $GiftItem command

### ISSUE THREAD

**Issue by Zeshyu** [OpenNos/OpenNos#1087]
Hello.

For the Notice-System , i was thinking about how u get the Items from minigames. I think it would be nice to be able to do that as a GM too.

Example for the command:
$GiftItem ITEMVNUM CHARNAME 
Then it will be send over the notice-system as a gift.
Thats possible on the official too as far as i know..

**Comment by The-Art-Of-War** [comment]
What do you sxactly mean?

There is allready a command for that to send gifts to other player "$Gift CHARNAME VNUM AMOUNT"

**Comment by Zeshyu** [comment]
Oh really? didnt know that.
Will it be send over the notice-system? Like if u would buy items from NosMall ?
if yes - im sorry.

**Comment by The-Art-Of-War** [comment]
yeah it shows up an box at the "Notice-Bar" like on the official servers, if you click on that box you can recieve your loot
