### ISSUE TITLE
Problems with Mail System.

### ISSUE THREAD

**Issue by DarkCacos** [OpenNos/OpenNos#1090]
I tested sending the mails to myself:
1) After reconnection, all the sent mail in list will vanish.
2) The color of Punk Hair and similar item on the character is still showed wrong if you open a received or sent mail in lists.
3) If you transform into an SP, then detransform, write a mail and sent it, the receiver will see you transformed into that sp even if you aren't anymore.
4) The title you write in the message isn't showed in the list. The internal message is showed instead.

**Comment by 0Lucifer0** [comment]
3 Is volonteer (like official)
