### ISSUE TITLE
CPU Leak optimisation

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1092]
It's just an idea to optimise the system perfomance because there is a problem with the CPU when there is a lot of item maybe when there is more like 100 items on the same time on the map, We can delete they older item and always the same process to have maximum 100 items maximum on the ground in the same time

![image](https://cloud.githubusercontent.com/assets/15254478/18856951/f12602ce-845f-11e6-8e85-4e9ab206691f.png)
CPU Up to like 50% 

And I think there is a problem because the emulator is always at 40% after that, if item dissapear etc why the system have again this CPU usage take? Same for monster $Summon after monster dead, there is again a high CPU usage

On usage normal CPU is to 1%~ With worldserver.

**Comment by 0Lucifer0** [comment]
That will change nothing the problem is only the drop event the server don't use cpu to maintaining item on the floor
