### ISSUE TITLE
Can't delete character 

### ISSUE THREAD

**Issue by Elendan** [OpenNos/OpenNos#1095]
When I try to delete a character, I get disconnected, I don't know if it's a bug but I've tried many times and I always get disconnected :)

Edit : Ok, I succeeded deleting a character, I don't know why, sorry for disturbance >.<

**Comment by Uppermost** [comment]
There is a problem or no?

**Comment by chucktheripper** [comment]
This is caused by sending wrong index for character deletion, we should just do nothing when sending wrong (empty) character slot
