### ISSUE TITLE
Others problems with Mail System.

### ISSUE THREAD

**Issue by DarkCacos** [OpenNos/OpenNos#1097]
Tested sending mails to myself:
1) Now the send list works, but: 
- When you write a mail and send it, immediatly it is added to the send list. 
- When you receive the mail, another is added in send list: [Screenshot](https://s12.postimg.org/9hmije3t9/20160927_3_Dark_Cacos.jpg)
- After you relog, the other surplus mail in send list vanish, and all return good.

2) I write about this problem in my earlier thread about mail system, but maybe I did not explain well. I tested it on official just now to be sure.
If you on OpenNos:
- Transform into an SP
- Detransform and return normal
- Write a mail from normal state: [Screenshot](https://s16.postimg.org/kx8xx1eyt/20160927_4_Dark_Cacos.jpg) 
- The receiver see you in that mail not normal, but transformed in the last SP you transformed in, even if you written the message in normal state: https://s21.postimg.org/vx2x45pzr/20160927_5_Dark_Cacos.jpg

**Comment by 0Lucifer0** [comment]
Like official

**Comment by 0Lucifer0** [comment]
Need to fix the 1 but 2 is same on official

**Comment by DarkCacos** [comment]
Strange, on Nostale ITA Official it isn't. I tested it just now. °-°

**Comment by DarkCacos** [comment]
However, regarding bug 1, after I write the second mail for test and relog, the send list return abnormal with double message: [Scrrenshot](https://s16.postimg.org/wnhrtcoth/20160927_7_Dark_Cacos.jpg)

**Comment by 0Lucifer0** [comment]
seems fixed
