### ISSUE TITLE
Implement true level & job system

### ISSUE THREAD

**Issue by SC909** [OpenNos/OpenNos#1098]
[http://pastebin.com/nCqJvgPp](url)
[http://pastebin.com/hyTFDDva](url)

In future I will add Act 4 exp from monsters & both penalties (1. level between ... 2. level higher from enemy). 
I will try to complete it without warmth system but it depends on you. 

I nearly finished the Act 4 but I only need to finish penalty 1. level between, and understand why do I gain 12 to job from monsters when I should get only 6 but I think you gain 12 as the warmth does so only for the lowest of job level gain which is 60. But on SP I also get 12, and I gain the same amount even from chickens lv1.

**Comment by Uppermost** [comment]
Link dead and  already in issue #692
