### ISSUE TITLE
Skill have a weird problem

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1099]
https://gyazo.com/36db06def47e9c86dd8d3a134a55b2af
https://gyazo.com/335ec4c7ba412a7dce26fca677738903

And when you change your character, you don't have this problem...

https://gyazo.com/0a88d8229687152b059de9825737fe9e

The skill effect seem's to be apply before the attack animation... Need test

Seem's to be caused by skilladd, sometime you learn some invisible skills.

**Comment by itemhack** [comment]
Have you buy the calvin's passive ? because that are bugged

**Comment by Uppermost** [comment]
What is bug ? Passive skill adds are just not coded yet

**Comment by 0Lucifer0** [comment]
Uppermost it Is partialy coded

**Comment by itemhack** [comment]
i know that upper but when you buy 1 skill of that your basic attack need 7 second to start (like your gif)
