### ISSUE TITLE
Missing null check

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1100]
![1](https://cloud.githubusercontent.com/assets/15254478/18885512/429e3bd0-84ec-11e6-9d79-e75ab1c287b4.png)

On the latest version ( 03/10/2016 )
(Error log)

and #1129 need to be fixed here

**Comment by Ciapa1** [comment]
I'll look at it when back in germany

**Comment by chucktheripper** [comment]
I can also fix that @Ciapa

**Comment by chucktheripper** [comment]
But yes, useless message with outdated lin.

**Comment by Uppermost** [comment]
#1170

**Comment by 0Lucifer0** [comment]
code was moved so idk where is the error.
