### ISSUE TITLE
Randoms with Seed

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#1106]
Using the same Random variable for each entity which uses random values is a bottleneck, as static resource sharing always makes problems with tasks, take the Random object back to the entity (for instance MapMonster) ans add a seed based on your current informations (name + id, or something like that)

Usage: Random rnd = new Random(seed);

**Comment by chucktheripper** [comment]
For MapMonsters we could use the x and y of their starting position for seed, for instance

**Comment by 0Lucifer0** [comment]
Or just use map for all random because we use map task not mapmonster task
