### ISSUE TITLE
RATE DEFINITION + ADDITIONS

### ISSUE THREAD

**Issue by Zeshyu** [OpenNos/OpenNos#1109]
Hello!
I think it should be splitted into these categorys:
(I mean that u can modify them more specific than before.)

EXP_RATE: normal EXP
JOB_EXP_RATE: normal JOB EXP
FAIRY_EXP_RATE: fairy EXP
FAMILY_EXP_RATE: family EXP (may be added with family system)
PET_EXP_RATE: (Pet & Partners (Bob,Tom,Kliff,Sakura)) PET & PARTNER EXP (Not for Partner-SP's just for Bob etc)
GOLD_RATE: AMOUNT OF GOLD THAT U GAIN WHEN U DROPP IT
GOLD_DROP_RATE:  AMOUNT OF GOLD-DROPS ON THE GROUND
ITEM_DROP_RATE: AMOUNT OF ITEM_DROPS ON THE GROUND

To split item & gold drop would be more awfull

Hope u see it like this too.

**Comment by MasterDomino** [comment]
Send suggestions on discord
