### ISSUE TITLE
Add a function to have +100 perfection SPs

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#1111]
It would be cool, cause right now it takes hours to do unless you go into database but idk thats a lot of hassle xD

**Comment by Zeshyu** [comment]
agreed

**Comment by unknownforces** [comment]
Well, i was thinking that you could do lets say, $CreateItem 901 15 13 100 <- for perfection
and then it can randomize the stats

**Comment by Ciapa1** [comment]
Why? This is an Emulator. We can fix critical issues in the original gameplay, but the rest should stay vanilla, atleast for now....

**Comment by unknownforces** [comment]
Because you should be able to get everything as a GM, but you can't get +100 perf sps.. my friends wanted to do that when they were playing and there was no way to do it unless I went into database but then it wouldtn be random (how its suppose to be) and i'd have ot sit there calculating how much points to give to what and crap, its a lot of effort.

**Comment by Dactylr** [comment]
@unknownforces you're right that GM's should be able to get everything but not at the current stage/phase maybe after a stable release candidate (the best would be an external GM tool in my opinion)
