### ISSUE TITLE
Create Packet definitions for CharacterScreenPacketHandler

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#1112]
Create all packet definitions for packets which are used inside the Handler Methods.

All Packet definitions are derived from PacketBase and they exist in GameObject project, Packets folder.
ServerPacket is packet which is sent from server to client and ClientPacket is a packet which is sent from client to server.

**Comment by chucktheripper** [comment]
A Packetdefinition is an index based template for the packet string. Take a look at OpenNos.Test CoreTest.cs to see how its used.

**Comment by Uppermost** [comment]
Done

Effect
Stat
In
Clist
Move

**Comment by chucktheripper** [comment]
There are a few headers missing on top of the classes
