### ISSUE TITLE
Problems with mute/unmute

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#1117]
So my friend muted me ALOT of times and then he unmuted me ALOT
We realized 1) Unmuting the player only removes 1 mute, so if you were muted twice, you need to do unmute twice, which shouldn't be. It should just wipe all mutes.
2) when I relogged, I got muted again even though he wiped my mute
3) the time started counting up instead of down

**Comment by 0Lucifer0** [comment]
1st is volonteer.

**Comment by MasterDomino** [comment]
tell me if the fix patched that ;)

**Comment by 0Lucifer0** [comment]
no it won't and you don't need to fix the first part. btw you just copy 2 thing because IsMuted() is exactly the same (with mute) now it's with all sanction... so you can revert this commit

**Comment by 0Lucifer0** [comment]
i don't understand the 3rd part

**Comment by Zeshyu** [comment]
The Issue-Creater menas:
If u press "Blacklist" on someone it adds him on the blacklist.
But if u press "Blacklist" afterwards again , u have to delete him 2 times from the blacklist.
Thats not like official. Thats what he said as far as i've understand him.

**Comment by 0Lucifer0** [comment]
No he was talking about gm ban and mute ^^ no one Know How It Is on official

**Comment by Zeshyu** [comment]
oh ok.

**Comment by unknownforces** [comment]
@MasterDomino Seems fixed except the first issue (with having to spam unmute if you've been muted more than once) but i'm not sure if thats important.
