### ISSUE TITLE
monster with friends system

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#1119]
Need to find a way to find friends monster, like pidgeon, worlf etc they attack you when you attack their friends

**Comment by chucktheripper** [comment]
Funny issue title

**Comment by Uppermost** [comment]
* Pidgeon
* Wolf
* Minor
* Chief Minor (All minor monster attack you when you attack him)
* Lion-Wolf

**Comment by Digitalis87** [comment]
Just a little thing. 
Minors & Chief Minors don't attack if you wear Kovolt Mask. (206)

**Comment by Uppermost** [comment]
Good précision ;)

**Comment by Digitalis87** [comment]
Do you want me to take a look on officials about friendly system mobs ? (Don't attack you untill you attack one of the same name ?)

**Comment by 0Lucifer0** [comment]
hum so it's a skill effect :)
