### ISSUE TITLE
Ncif packet unsafe

### ISSUE THREAD

**Issue by Martazza** [OpenNos/OpenNos#1122]
![image](https://cloud.githubusercontent.com/assets/17277512/18931091/013e45ce-85cb-11e6-9818-79bf5593c86d.png)

Server seems to crash after sending random value to packet
ncif 2 1895a a

**Comment by Martazza** [comment]
Same for Walk Packet
example:
`walk 3a0 115 1 11`

**Comment by chucktheripper** [comment]
Please use the PacketFactory

**Comment by chucktheripper** [comment]
Now i got you, ill fix it as soon as possible
