### ISSUE TITLE
Use Packetfactory instead of stringsplit

### ISSUE THREAD

**Issue by Martazza** [OpenNos/OpenNos#1123]
Seems that every packet that have been serialized uses unsafe convert method
#1122

**Comment by chucktheripper** [comment]
Please use PacketFactory

**Comment by chucktheripper** [comment]
Or is there a Problem? LEL

**Comment by chucktheripper** [comment]
Why did you reopen it?

**Comment by chucktheripper** [comment]
We should use the Packetfactory for serializing received strings, take a look at walk handler implementation. Free strings and packets with #header^value1^value2 arent supported atm.

**Comment by chucktheripper** [comment]
@Uppermost  this is actually really pointed to everyone ;)

**Comment by Uppermost** [comment]
Never happens again
