### ISSUE TITLE
Console Window Bug

### ISSUE THREAD

**Issue by Dactylr** [OpenNos/OpenNos#1125]
[Console Window Bug](http://sendvid.com/bg4msgmj)
when you change the width of the console all Lines disappear

**Comment by Uppermost** [comment]
Maybe just a bug in windows :/

**Comment by MasterDomino** [comment]
In fact i noticed it on some other projects, and i belive it shows only on w10

**Comment by 0Lucifer0** [comment]
Yes only on anniversary windows 10

**Comment by MasterDomino** [comment]
Is there like way to fix this by changing settings in console,

**Comment by Dactylr** [comment]
@MasterDomino there is a way when you deactivate the `wrap text output on resize` on the layout tab
[Screen](http://i.epvpimg.com/PseYg.png)
