### ISSUE TITLE
Some skill in one.

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1136]
When you use skill like wild keeper, some skill have many animation. and use 2 skills in 1.

**Comment by valdek1999** [comment]
When use ivy skill for wild keeper
![image](https://cloud.githubusercontent.com/assets/17438672/19015176/0b095ce4-8808-11e6-9c42-339acc99215e.png)

**Comment by unknownforces** [comment]
I reported this ages ago.. xD

**Comment by MasterDomino** [comment]
Im curious what have you done i fixed it already twice xD

**Comment by Uppermost** [comment]
@MasterDomino Lucifer revert your commit, because he thinked it caused the problem with SP6 swordsman.

**Comment by Digitalis87** [comment]
Hello. 
The right way to reproduce the bug in 1.0.3.31980. 
With Monk SP (VNUM 4497).
1- Go VS any monsters.
2- Open your skill window by pressing "K" then -> Skill.
3- Target a mob with Space bar. 
4- Spam Divided Sea skill (Skill 1 of the SP)
5- Repeat untill Mighty Hurrican's (Skill 3) animation.

Note : Works also if you don't have enough mana for the Divided Sea Skill. Looks like the unwanted skill use no mana.
Note 2 : Works with almost all offensives skills from Monk SP.
Note 3 : Some other SP have this kind of bugs.


![20161003-3-silwink](https://cloud.githubusercontent.com/assets/22579041/19048013/bc49d4aa-89a4-11e6-9b84-1f92072c65da.jpg)

**Comment by Uppermost** [comment]
Caused by wrong packet

**Comment by chucktheripper** [comment]
Ah lel i fixed this
