### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1139]
[Err] 1452 - Cannot add or update a child row: a foreign key constraint fails (`opennos`.`inventory`, CONSTRAINT `FK_Inventory_ItemInstance_Id` FOREIGN KEY (`Id`) REFERENCES `iteminstance` (`Id`))
[Err] INSERT INTO `inventory` VALUES ('58be987d-1567-47ce-8de6-ab564fdcc8aa', 3, 0, 1);
[Msg] Finished - Unsuccessfully
--------------------------------------------------

[Err] 1136 - Column count doesn't match value count at row 1
[Err] INSERT INTO `iteminstance` VALUES ('0067c39c-6ccf-406c-a8bf-0ebed9fbc0b6', 99, 0, NULL, NULL, 2282, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ItemInstance');
[Msg] Finished - Unsuccessfully

**Comment by chucktheripper** [comment]
Inventory.Id and ItemInstance.Id Need to have to same value.

**Comment by BelminBIH** [comment]
How that?
