### ISSUE TITLE
Review antispam packet protection

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1143]
After 4 hour of emulator use, the CPU is to 35-40% and not down. I have no information about this problem but it's not normal at the boot the CPU usage is at 0/1%. Maybe drop, summon or other thing up the CPU and never down. We need to find the problem and optimize the system.
![image](https://cloud.githubusercontent.com/assets/15254478/19020604/fd545d8c-88ad-11e6-8d81-a828994688e4.png)

There is a loop I think.

Edit : Seem's to be caused by a player try to crash the server with packetspam. : https://gyazo.com/6921c2a71e7e779589aca4b4ce78aee0
- [x] We need to disconnect the player after cheat detect
- [ ] We need to find a other way to don't disconnect good player and disconnect only player If we are sure they use a cheat etc. My opinion just calculate the number of packet send by second and if the amount is superior at 25 > disconnect the player. (Already done by martazza but doesn't work fine, sometime a lot of people are disconnected 
- [x] Review Speedhack protection

**Comment by Uppermost** [comment]
We need to do the same for send packet not only for receive @Martazza

**Comment by Pescatore981** [comment]
I miss the server :(
 XD

**Comment by Ciapa** [comment]
Okay, you will be banned now, sorry.

**Comment by Pescatore981** [comment]
ninth sorry I just wanted to tell you that I was missing

**Comment by MasterDomino** [comment]
there was never our official server opened please stop spamming our issues

**Comment by Pescatore981** [comment]
ok

**Comment by MasterDomino** [comment]
its pointless to delay packets sent by server and really inperformant

**Comment by 0Lucifer0** [comment]
#1556
