### ISSUE TITLE
Add upgrade and rarify on gift 

### ISSUE THREAD

**Issue by itemhack** [OpenNos/OpenNos#1144]
what do you think if we can send some item with upgrade/rarify with the command "gift x x x x x"
?

**Comment by Uppermost** [comment]
We already talk about this, we can't.

**Comment by 0Lucifer0** [comment]
will add them when will be back.

**Comment by Uppermost** [comment]
Ok I thinking it was impossible.

**Comment by 0Lucifer0** [comment]
Nothing is impossible we just need to change the database table a little

**Comment by L3niaK** [comment]
I think that would be helpful make a similar command, for example "$GiftAll" for give items at all players registered

**Comment by 0Lucifer0** [comment]
Just put * as username will send to all connected users

**Comment by L3niaK** [comment]
Sorry, i didn't know

**Comment by MasterDomino** [comment]
why this got closed?

**Comment by 0Lucifer0** [comment]
Because someone use it for a request and I didn't see it was on an other issue...

**Comment by MasterDomino** [comment]
okay then will leave this open ;)

**Comment by Uppermost** [comment]
doesn't work

**Comment by Uppermost** [comment]
Doesn't work again
