### ISSUE TITLE
review Revive system

### ISSUE THREAD

**Issue by earthnash** [OpenNos/OpenNos#1145]
![bug](https://cloud.githubusercontent.com/assets/15151087/19021914/2e34958c-88f6-11e6-876d-8b38b0adc8b3.jpg)
it occur when someone died and disconnect
the character in this picture can't do anything except walking
(EKIMKAK4)

**Comment by earthnash** [comment]
i think maybe client problem or network
because when i use "$Teleport EKIMKAK4 "
it show user didn't connect.

**Comment by MasterDomino** [comment]
another issue that showed up after changes sometimes randomly you will get stuck in death state and you cant revive tho you have above required hp

**Comment by MasterDomino** [comment]
not seen for a long time
