### ISSUE TITLE
Item price sell is wrong

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1150]
Your item price is 1000 and you sell it for 400 gold etc etc, all is wrong after they new update

Item 2333 by example

**Comment by chucktheripper** [comment]
Implementation expects the Sell-Price to be Price / 20, we Need a SellPrice field in Database and calculate it on Import. For those "only for sell items" we should add SellPrice = Price

**Comment by chucktheripper** [comment]
Or we only add a flag which says SellPriceIsPrice and if this is true, we dont divide the price by 20

**Comment by 0Lucifer0** [comment]
so they changed the algo? isn't it /20 anymore?

**Comment by MasterDomino** [comment]
@chucktheripper the problem is idk if theres way to find if that flag should be true or false, and yes @0Lucifer0 it seems like sometimes items arent divided by 20 :/

**Comment by chucktheripper** [comment]
Sometime price is sellprice like some gold nuggets..

**Comment by Digitalis87** [comment]
Most of divided prices are for Equips inventor such as EQ's. 
Almost every little material like dander seed & others cost the price it's write in the right clic description...

**Comment by 0Lucifer0** [comment]
so all inventory 0 divided by 20 and all other not divided?

**Comment by Digitalis87** [comment]
I'll do test this afternoon. EQ's are divided i'm sure 99.9%. I would say yes. Inventory 0 divided & others are nt.

**Comment by Digitalis87** [comment]
Yes you must be right. Inventory 0 divided, others are not.


![item prices](https://cloud.githubusercontent.com/assets/22579041/19182184/3aa1ae84-8c72-11e6-9556-7664a4b6b400.png)

**Comment by 0Lucifer0** [comment]
ok :) will fix it
