### ISSUE TITLE
SP Perfection visual bug.

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1152]
A little bug found. 

Whene trying to upgrade SP perfection, the amount of perfection gems are not updated. 
Rates are the same. 
Perf 1 to 20 = 1 Material of Completion
Perf 21 to 40 = 2 Material of Completion
Perf 41 to 60 = 3 Material of Completion
Perf 61 to 80 = 4 Material of Completion
Perf 81 to 100 = 5 Material of Completion

No matter if you win or loose the bet, the amount of material is not updated in the perf window

Screens in attachements

EDIT: Looks like the amount of perf required is good for the first try. So i log on, do a perfection try, it's the good amount in the window. At the second try, it come back to 1 material needed.

EDIT 2: Same for the gold required.
![20161002-2-silwink](https://cloud.githubusercontent.com/assets/22244296/19049296/2161a9bc-89aa-11e6-91a5-eb5fde640e72.jpg)
![20161002-3-silwink](https://cloud.githubusercontent.com/assets/22244296/19049297/216441d6-89aa-11e6-88c1-c0b888678b2f.jpg)

**Comment by chucktheripper** [comment]
Packet order problem maybe!

**Comment by 0Lucifer0** [comment]
Nope inv/ivn  Packet to change for sp ;)
