### ISSUE TITLE
Skill Bugs

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1154]
![screenshot_1](https://cloud.githubusercontent.com/assets/22244296/19049416/ac7e9f6e-89aa-11e6-8e97-259236657f9e.png)

**Comment by Uppermost** [comment]
Issue with TargetHit

**Comment by MyTaleON** [comment]
![image](https://cloud.githubusercontent.com/assets/22244296/19075508/718ba334-8a45-11e6-8ac0-54efbef4f1b6.png)

**Comment by Digitalis87** [comment]
Add mages issues.

https://gyazo.com/18de0f5ec7918f52ee149fa78797417a

**Comment by MasterDomino** [comment]
please make list of all issues and make checkmark on it

**Comment by Digitalis87** [comment]
News about skill bug. 

Sometime you can use combos skills from SP ( As Dragon Harpoon & Dragon Spear).
https://gyazo.com/3b5b51c391f22021c16dbc8be887cbd8

- Create a (Time-Space) Specialist [4494-4495-4496]. It must be $4495  0 0 (+0 Upgrades & no wings)

- Open the Skill window by pressing "k" then -> Skill tab. in some verry low times, the "combos" skills are not grey. It mean you can add em to the skillbar and use them as normal skills. 

ADDITIONALS NOTES:
_Works with Archer & Swordsman SP6's (TS Only). May works on Mage SP, i was just unable to redo the issue.

It's hard to redo this bug. I think this bug happend depending of the created SP and can't happend with the same SP. 

After wearing the SP, if the combos Skills was available and you hit once anything, the combos skills won't be availables. It mean if you don't put them in the skillbar, you can't use them._

BONUS: 
https://gyazo.com/fc6639ecd73d8d37ef2c0fd8bdbab1d0

**Comment by 0Lucifer0** [comment]
doublon
