### ISSUE TITLE
Map + $TEleportToMe Bug

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1159]
When a player is on the map (MapId: 2540) and the player have Black Screen.

When i Teleport the player with the $TeleportToMe Command than i kicked from the server.

i hope you understand me.. :D

**Comment by Uppermost** [comment]
Seem's to be caused by instance map we can do nothing for the moment. Wait instance map implementation :)

**Comment by Digitalis87** [comment]
190 & 186 bugged for me.

**Comment by Uppermost** [comment]
Edit : Work fine on our test server, maybe a problem with the order of packet sometime.

**Comment by chucktheripper** [comment]
Take a look at the Packet receive / send order (Server -> Client), sounds like the order is wrong.

**Comment by Legend92** [comment]
$Teleport 2540 10 10 works!

**Comment by Uppermost** [comment]
#1171

**Comment by Uppermost** [comment]
Issue seem's to be fix for MyTale and I never have this problem > close
