### ISSUE TITLE
update-database command error

### ISSUE THREAD

**Issue by celiswen** [OpenNos/OpenNos#1161]
![image](https://cloud.githubusercontent.com/assets/22429685/19075269/c8292cbc-8a76-11e6-9d6f-d14edaeeac98.png)
![image](https://cloud.githubusercontent.com/assets/22429685/19075278/d65f8d94-8a76-11e6-8a61-fcf3c6fa5511.png)

**Comment by Uppermost** [comment]
I want to see all the screen. I don't see all here and for question like this it's on discord. Please send me the complete screen

**Comment by chucktheripper** [comment]
Restore your nuget packages and choose the correct Project.

**Comment by celiswen** [comment]
![image](https://cloud.githubusercontent.com/assets/22429685/19075579/1d4f25ec-8a78-11e6-8ae5-7d260e87858d.png)

**Comment by Zeshyu** [comment]
Had the same problem yesterday , i did the same as i did last time (it worked last time) but this time i've got this error aswell.
Didnt fix it yet

**Comment by Uppermost** [comment]
It's a package problem install stylecop 4.7 and redownload opennos and retry

**Comment by Zeshyu** [comment]
Installed StyleCop 4.7.54 from this site: https://stylecop.codeplex.com/
Redownloaded OpenNos and opened visual studio 2015 Premium.

NuGet-manager console -> update-database -Verbose
Still get the same error
