### ISSUE TITLE
Some Bugs with Maps

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1162]
![image](https://cloud.githubusercontent.com/assets/22244296/19075364/ead839f6-8a44-11e6-895b-d3ca28643ce0.png)
![image](https://cloud.githubusercontent.com/assets/22244296/19075375/f1d45c30-8a44-11e6-989f-ba812bc70b8a.png)
![image](https://cloud.githubusercontent.com/assets/22244296/19075383/fc6f3cbe-8a44-11e6-9f80-6d929935be61.png)

**Comment by Uppermost** [comment]
1.) It's the same on official

2.) We already know and already in issue

3.) Already in issue too

**Comment by Liuk1** [comment]
@Uppermost 
2- I upgraded this skill on Krem on day 1 of MyTale , now I see that in Nos Wiki there is only one upgrading for it but I remember I upgraded the skill on Krem.
4- Ping problem of server or player? When it happens you can write and use emoticons without  lag problems , I'm sure it's not a ping problem of player.
5- Just to say xD 

Thanks :+1:  :)
