### ISSUE TITLE
OpenNos.Login error

### ISSUE THREAD

**Issue by celiswen** [OpenNos/OpenNos#1163]
![image](https://cloud.githubusercontent.com/assets/22429685/19079540/8ddc372e-8a86-11e6-99ef-6d15520eaf9d.png)

Missing attribute value on attribute 'cn'.

**Comment by 0Lucifer0** [comment]
You made this error on your own...

**Comment by Uppermost** [comment]
Yes you add "cn" and try to reinstall package > redownload opennos and run with F5 PS : Join discord server for they question it's not here :/

**Comment by celiswen** [comment]
![image](https://cloud.githubusercontent.com/assets/22429685/19080178/d1bb96d6-8a88-11e6-9406-4f92310e0d8f.png)
i didn't touch anything. it error when i run it

**Comment by 0Lucifer0** [comment]
The * mean you change something in it just do ctrl+z
