### ISSUE TITLE
owner system in party problem

### ISSUE THREAD

**Issue by earthnash** [OpenNos/OpenNos#1164]
![f2bb93117ccf46fde73fcc230c657970](https://cloud.githubusercontent.com/assets/15151087/19086616/10ecdea4-8a99-11e6-9238-bd9b73aae1b1.gif)

as can you see I killed monster 
but it show member in group drop
**I set drop by order**

**Comment by Uppermost** [comment]
It's share 1/2 the item for you is the dander seed I don't see any problems

**Comment by Uppermost** [comment]
It's normal because the group is share his member don't need to attack a monster to have the drop if the Group is share

**Comment by earthnash** [comment]
i didn't set share i set **drop by order**
