### ISSUE TITLE
Drop seems not be dropped for each mob

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#1166]
all drops are on the same place where you killed the latest monster

https://gyazo.com/8eab7b0cdc4ae6d774364d7e4bcbf746

**Comment by Uppermost** [comment]
I think it's normal because they drop should be beside the character it's maybe the same on official but you can't see that because you can't use a kill with this range. I'm not sure

**Comment by The-Art-Of-War** [comment]
no some days ago it wasnt like that :D

**Comment by The-Art-Of-War** [comment]
and on official it isnt like that :D for example if you kill something with the wale (mage) it dropps everthing besides the killed monster

**Comment by The-Art-Of-War** [comment]
and that is a really wide range :D

**Comment by chucktheripper** [comment]
Maybe the drop point is calculated too fast.

**Comment by The-Art-Of-War** [comment]
The problem isn't fixed yet :D

**Comment by MasterDomino** [comment]
up

**Comment by 0Lucifer0** [comment]
for me it's fixed https://gyazo.com/77ce7b8a3165edaeace019edefd74e2f i think you're not up to date.
