### ISSUE TITLE
Mapping Bug

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1167]
![screenshot_1](https://cloud.githubusercontent.com/assets/22244296/19114260/86b1c5ae-8b0d-11e6-96ce-0e2f6f8f694d.png)

**Comment by chucktheripper** [comment]
@MD can you look at ItemInstance.DarkResistance Enitity and DTO type?

**Comment by MasterDomino** [comment]
sbyte in entity and byte in dto pushed commit that fixed that
