### ISSUE TITLE
Add new items.

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1168]
After 5996 (I think or 6000) I use the command $CreateItem to have they new item (example nosmall costume) id 8271 already implemented on the official and it's impossible it say " Item acquire NAME " but nothing appear on my flag.

**Comment by 0Lucifer0** [comment]
what the differences between this item and others?

**Comment by Uppermost** [comment]
We think about a problem with the synthax on they news items. We don't know for the moment

**Comment by 0Lucifer0** [comment]
synthax of what?

**Comment by Uppermost** [comment]
They maybe change it on the item.dat we need to verify that

**Comment by 0Lucifer0** [comment]
it's because inventory type is set to 8 or 10 idk why

**Comment by Uppermost** [comment]
Edit : It's maybe useless because all item are doublon for the moment we can maybe just block it to 6000 because if you summon an item with this type your character can be load at the login.

#1169

**Comment by 0Lucifer0** [comment]
just not parse type 8 and 10.

**Comment by Uppermost** [comment]
reopen item 9038 work fine on official by example and invisible on opennos

**Comment by 0Lucifer0** [comment]
what is this item?

**Comment by Digitalis87** [comment]
Airwaves Sweet (also 1338).

**Comment by 0Lucifer0** [comment]
Those items work fines on our test server
