### ISSUE TITLE
Big Maps Problem! 

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1171]
![image](https://cloud.githubusercontent.com/assets/22244296/19121744/d2c9970e-8b27-11e6-8565-c293b674c758.png)

and than i teleport in the lod and than come this message in the world console:
![image](https://cloud.githubusercontent.com/assets/22244296/19121715/c21ce4a6-8b27-11e6-9de6-e1bde01a3a5c.png)
PS: I just try 1x ! 

than i have an blackscreen it's same problem with a5.2 maps

**Comment by MyTaleON** [comment]
PS: i can't create an Portal to the LOD

**Comment by MyTaleON** [comment]
here is the packet:

`$Teleport 10000 7 5
at 1 1 1 1 2 0 0 -1
c_map 0 1 0
mapout
c_close 
f_stash_end 
spk 1 15 5 Liuk Can you please tell me ID of 
c_close 
f_stash_end `

**Comment by Uppermost** [comment]
Already in issue
