### ISSUE TITLE
HP BUG

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1174]
Hello, So as this way as in the subject while beating the certain boss for me such a situation happened

![image](https://cloud.githubusercontent.com/assets/22244296/19124809/f87eb7ec-8b34-11e6-9b71-3ba328eb673b.png)

**Comment by 0Lucifer0** [comment]
need more details. is the target of horn was dead ?

**Comment by 0Lucifer0** [comment]
no info i close.
