### ISSUE TITLE
Freeze and crash > very big amount of player 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1175]
When there is a big amount of player it's unplayable and all are slow and after a some time the server crash

You know what you want to do @chucktheripper all information send on skype

**Comment by aerzy** [comment]
Crash server
http://pastebin.com/5raC7fbw

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/19163100/d7d08f86-8bfa-11e6-96ad-c4d3c94d5f19.png)
Need to be fixed asap.

**Comment by Uppermost** [comment]
After they update, problems know
-------------------
* After 40 player connected the server become unplayable... (Big latency for everyworld) CPU 70-100%
* When a big amount of player are connected and you disconnect you can't reconnect : ID already used
* Monster move and respawn seem's to be slow

**Comment by Uppermost** [comment]
- [ ] Implement some packet in once
