### ISSUE TITLE
Add gauge system for SP

### ISSUE THREAD

**Issue by Zeshyu** [OpenNos/OpenNos#1178]
Hello.

Maybe u have to change the Issue-Title. :P 

If u transform into an Specialist for the First time on your character (Doesnt matter which sp) u gain a full 10.000/10.000 SP Gauge (Purple gauge).
OR
10.000 On the yellow gauge and 10.000 additional on the purple one.. I dont know exactly but its one of these for sure.

ALSO:
If u create a new Character the SP-Gauges under ur character hp etc is not shown. (Official) But in OpenNos i does show that. I just shows when u transform into sp for the first time aswell.

Greetings.
- [x] Need to find algo lose by monster
- [x] Need to add 10000 points by day (reset main points)
- [x] Need to unwear sp when the amount is too low
- [x] Need to add additionnals point system
- [x] Need to excluse some sp (I think some SP don't lose some points)
- [x] Need to add item to recover it (check all items, some of them doesn't work fine. eg : snack) + normal additionnal point + 10000 (item 1078) 26/11/2016 12:54 1078 doesn't work again same for snack but it's not an obligation to do now
- [x] Need to block sp wearing when point are empty
- [x] Need to show sp point when sp is equiped but not wear
- [x] Add the message when you receive instant sp ticket "You have win 1000 sp points" (item 1114)

- [x] Fix All points are restored after disconnection/reconnection

**Comment by 0Lucifer0** [comment]
In fact each day it should be reset the bar

**Comment by Zeshyu** [comment]
Did EDIT it.

**Comment by 0Lucifer0** [comment]
No need to edit all the point system need to be added

**Comment by Uppermost** [comment]
* Need to find algo lose by monster
* Need to add 10000 points by day (reset main points)
* Need to add additionnals point system
* Need to excluse some sp (I think some SP don't lose some points)
* Need to add item to recover it

**Comment by 0Lucifer0** [comment]
I think it's 1point each second of battle- all sp loose point

**Comment by Zeshyu** [comment]
@Uppermost 
- Every SP loses Points as far as i know (even pirate etc).
- We/You need to add that the Gauge bar should be hided as long as u translate into a specialist for the first time. then it will show up (Like Official)

**Comment by SC909** [comment]
If you have a look at SP card (right click) Just above required reputation, it says how many sp points you will lose every second (PS - 3 on SP1 warrior)

[11:21:01] sp 689480 1000000 9850 10000 <-- start point
[11:21:57] ct 1 107681 1 107681 14 -1 820 <-- this one is just a character position when using a skill
[11:22:03] sp 689480 1000000 9832 10000 <-- already used at 11:21:58 1 point & 15 points after 5 sec
[11:22:08] sp 689480 1000000 9817 10000 <-- uses 3 points every second, sends sp ... every 5 sec
[11:22:13] sp 689480 1000000 9802 10000
[11:22:14] sp 689480 1000000 9802 10000 <-- stops after 15 seconds of last attack, skill or being hit

You will lose sp points if: You are still attacking/using skills or being attacked.
After 15 seconds when you attacked/used skill or been attacked, you will stop losing sp points.
During losing points or after: If you again, use any skill, attack a moob, or be attacked, you will lose points for 15 seconds until you no longer, use any skill, attack a moob or be attacked.

**Comment by 0Lucifer0** [comment]
Ok Nice so thats the amount of point ;) It should be in the item.dat

**Comment by Ciapa** [comment]
algo is somewhere documented

**Comment by Uppermost** [comment]
Yes the amount is in item.dat for items :)

**Comment by Ciapa** [comment]
Not yet finished, missing Refill Items and Removal of SP

**Comment by Ciapa** [comment]
@MasterDomino Please Implement Refill Items. Just work with Session.Character.SpPoint and / or .SpAdditionalPoint and do Session.SendPacket(Session.Character.GenerateSpPoint()); after updating the Values.

**Comment by Uppermost** [comment]
Everything you need to add is there
---------------------------------------

Sp points potions

- Id : 1078 (Additionnal)
- Id : 1118 (Additionnal)
- Id : 1119 (Additionnal)
- Id : 1120 (Additionnal)
- Id : 1143 (Basic + Additionnal)
- Id : 9014 (Additionnal)
- Id : 9015 (Additionnal)
- Id : 9016 (Additionnal)


Drop by monster restauration

- Id : 1114 (Basic)


Restauration SP resurection restore all basics points

- Id : 1365 (Just restore all basic points)
- Id : 9039 (Just restore all basic points)


Snack for SP points

- Id : 2290 (Basic)
- Id : 2291 (Basic)
- Id : 2309 (Basic)
- Id : 10034 (Basic)

**Comment by Zeshyu** [comment]
Do not forget to hide the gaugebar of SP unless u transformed into a SP for the first time.

**Comment by MasterDomino** [comment]
@Zeshyu It should be hidden if you dont wear sp afaik

**Comment by MasterDomino** [comment]
items for restoration has already been added, in my commit e39657b
