### ISSUE TITLE
ItemInstance.Id duplicate entry bug

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1179]
![image](https://cloud.githubusercontent.com/assets/22244296/19194074/c6b43c68-8cac-11e6-84b5-66576b1708a6.png)

**Comment by chucktheripper** [comment]
If everyone knows how to reproduce this Problem, gets a Cookie.

**Comment by Uppermost** [comment]
Again now way to know it's caused by the community :/

**Comment by 0Lucifer0** [comment]
that's because you forget to reparse all...
