### ISSUE TITLE
Specials characters problems

### ISSUE THREAD

**Issue by Digitalis87** [OpenNos/OpenNos#1181]
https://gyazo.com/7735a9070d58b3f5f0d2bb49cccb2c4c

- the ???? are a problem fo whispers, and speakers

- the ? Characters can be used for Players Creation & in General chat.

Found on MyTale, tested also on TestServer. Both bugged.

**Comment by Uppermost** [comment]
#1187

**Comment by 0Lucifer0** [comment]
fixed
