### ISSUE TITLE
Monster to map addition not working correctly

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1184]
AddMonster command lag 
![addmonster](https://cloud.githubusercontent.com/assets/22352357/19211383/30d3aae6-8d3b-11e6-96d7-540b73ed507c.png)

https://gyazo.com/28dba9ac2490c78ae8dafb03cc075c83

**Comment by BelminBIH** [comment]
https://gyazo.com/28dba9ac2490c78ae8dafb03cc075c83

**Comment by MasterDomino** [comment]
should be fixed with #1195
