### ISSUE TITLE
Login-Server Error

### ISSUE THREAD

**Issue by Zeshyu** [OpenNos/OpenNos#1185]
![error](https://cloud.githubusercontent.com/assets/22459574/19211647/c1ed3596-8d41-11e6-9528-7035acc46228.png)

**Comment by 0Lucifer0** [comment]
that's an IIS trouble. use real IIS not express you will not have that. @chucktheripper could you catch this and restart ? :)

**Comment by chucktheripper** [comment]
WCF seems to be offline or anything different running on the wcf port

**Comment by Zeshyu** [comment]
@0Lucifer0 What do u mean by that? Im not rly experienced in that topic. Could u explain how to fix that for me if its possible?

**Comment by chucktheripper** [comment]
WCF project needs to be part of multiple startup projects

**Comment by Zeshyu** [comment]
So i have to wait until u fixed it? right?
