### ISSUE TITLE
Encryption issue with special characters

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1187]
https://gyazo.com/7d16fc96cd5c48eed06db93949e9850e

**Comment by Uppermost** [comment]
already in issue

**Comment by BelminBIH** [comment]
Ah sorry i not look xD

**Comment by Uppermost** [comment]
same problem with € for example...

**Comment by 0Lucifer0** [comment]
On the last version ?

**Comment by Digitalis87** [comment]
Yes. Current version on TestServer (1.0.3.35722) 
€ is still bugged.
