### ISSUE TITLE
$SearchItem - U cant search every item

### ISSUE THREAD

**Issue by Zeshyu** [OpenNos/OpenNos#1188]
For Exampel in German Firewings does mean Feuerflügel
but i cant search for "flügel" for example. U can try urself.

I think u cant use üäö .

And if i type in the amount 100 instead of 99 i still get 99.

**Comment by chucktheripper** [comment]
not fixed with #1181 ?

**Comment by 0Lucifer0** [comment]
amount is normal max is 99 search is fix
