### ISSUE TITLE
Crash World Server

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1192]
![crashhhhh](https://cloud.githubusercontent.com/assets/22352357/19215501/616befd2-8da0-11e6-92a5-3e993843be90.PNG)

**Comment by BelminBIH** [comment]
Drop problem --'

**Comment by Uppermost** [comment]
Never happens with 150 player on nosland and 11 hours openning. Maybe this bug is not on the latest version @chucktheripper what do you think?

**Comment by 0Lucifer0** [comment]
This seems to be a database problem

**Comment by BelminBIH** [comment]
What exactly?

**Comment by BelminBIH** [comment]
Ah ok its my item.sql xD
