### ISSUE TITLE
Sending walk allows to speedhack

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#1197]
When you send for example this packets:

walk 165 143 0 10 
pulse 180

you are teleported there.

**Comment by MasterDomino** [comment]
should have been fixed in #392, we need to take a look at it as it is lore breaking

**Comment by SC909** [comment]
After some sniffing I got this for you

//speed 12
x 0  y 12
x 1  y 12
x 2  y 12
x 3  y 12
x 4  y 12
x 5  y 12
x 6  y 11
x 7  y 10
x 8  y 9
x 9  y 8
x 10 y 7
x 11 y 6
x 12 y 5

//speed 14
x 0  y 14
x 1  y 14
x 2  y 14
x 3  y 14
x 4  y 14
x 5  y 14
x 6  y 13
x 7  y 12
x 8  y 11
x 9  y 10
x 10 y 9
x 11 y 8
x 12 y 7
x 13 y 6
x 14 y 5

Speed defines how far you can move, but also it seems in both cases it will add 5 if you move x & y (x7 y10, x10 y9) It can also go the other way round (x14 y5 -> x5 y14) From that you have - the limit how far you can go so no one will be able just to teleport to anywhere. 
A bit later I will have a look at smaller speeds (with debuffs, also I think pets and partners have this too so it would be easy to check this even on chickens and other stuff)

**Comment by MasterDomino** [comment]
is the postion after using that walk speedhack saved? or is it reset to last coords?

**Comment by SoraPlays** [comment]
the position is save after using this walk speedhack.

**Comment by SoraPlays** [comment]
The same with the packet at and probably also with tp

**Comment by MasterDomino** [comment]
#1143 is already here with 3rd point
