### ISSUE TITLE
About $Ban Command

### ISSUE THREAD

**Issue by Digitalis87** [OpenNos/OpenNos#1199]
Change 

$Ban NAME REASON TIME for NAME TIME REASON

Why ?

$Ban NAME REASON Dont_works_for_more_than_1_word_with_space. The TIME fucked up everything.
(Can be good to add a reason like that Bug Using and not BugUsing)
Any REASON message more than 1 word will be set in TIME. Change this :).

Because max characters in NosTale Chat, in TIME add (*) to set the Ban Time to the default timer.
Also adding a GMNAME could be great to avoid Ban Abuse (in database) !

**Comment by Zeshyu** [comment]
Same goes for $SearchItem Command , u cant use a Space between the words.

**Comment by MasterDomino** [comment]
idk how to split names then we should use proper string splitting method soo name or reason should always be at the end and if packetsplit > 5 then search if theres item that contains name like this
