### ISSUE TITLE
Perfection of Log Users

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1200]
Hey guys i have an idea to perfection log the users..

the Server create an Folder:

![image](https://cloud.githubusercontent.com/assets/22244296/19224592/39637c28-8e89-11e6-9ca5-02777293086b.png)

Server creates for each account folder:

![image](https://cloud.githubusercontent.com/assets/22244296/19224599/5d063864-8e89-11e6-9440-5edf7e6a91da.png)

In the folder then the character 'of the account:

![image](https://cloud.githubusercontent.com/assets/22244296/19224606/7fc779ee-8e89-11e6-9a31-06a795c164a8.png)

and in the character's folder is then the respective log from Charackter:

![image](https://cloud.githubusercontent.com/assets/22244296/19224610/9f4d7408-8e89-11e6-812e-093c5b8d402f.png)

**Comment by Uppermost** [comment]
Can be cool to punish a player and get some usefull information but I don't know if it's easy to do and the size of the log can be very big if we do it. @0Lucifer0 What do you think?

**Comment by 0Lucifer0** [comment]
useless and you can already split it by changing the configuration of log4net
