### ISSUE TITLE
dignity actualisation

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#1202]
the dignity not actualise when we dies only if you change map

**Comment by MyTaleON** [comment]
it's at the official too.

**Comment by Zeshyu** [comment]
no. if u die and get -dignity and reach a new negative level it instanly changes. :) i've already opened an issue about this but it got closed for no reason. Still not fixed.
It should be instantly actualized.

**Comment by 0Lucifer0** [comment]
Already in issue

**Comment by 0Lucifer0** [comment]
Ah no It was closed
