### ISSUE TITLE
GM resistances issue.

### ISSUE THREAD

**Issue by Digitalis87** [OpenNos/OpenNos#1203]
Hello !

I've found some problems with the GM resistances (921 to 924)

After summing the resistances at least sum 5 or sum 6, wearing them on the player and relogging, the resistances are not on the player.

Also, with 924 someone had a bug from sum5 & sum4 to sum 2 after relogging.

also to test all resistances a GM commands may be good... (and any sum)

**Comment by 0Lucifer0** [comment]
all resistance in item need to be changed to short

**Comment by MasterDomino** [comment]
resistances changed to short on iteminstance branch

**Comment by 0Lucifer0** [comment]
fixed
