### ISSUE TITLE
Sp upgrading issue

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#1204]
when upgrading and you have below required amount of gold your gold will fall below 0

**Comment by 0Lucifer0** [comment]
You verify gold after substract so It cant work

**Comment by MasterDomino** [comment]
no no, its already fixed look at my commit

**Comment by 0Lucifer0** [comment]
I've looked at your commit the verification is after

**Comment by 0Lucifer0** [comment]
Ah no Its not the same function

**Comment by MasterDomino** [comment]
then which function is it? ive already checked rarify,upgrade eq/sp, perfection and summing

**Comment by 0Lucifer0** [comment]
No i mean thats my bad I didn't see that it was not the same function in commit ;)
