### ISSUE TITLE
portals causing issues and sometimes teleports out-of-bounds

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#1205]
all in name sometimes it causes issues

**Comment by 0Lucifer0** [comment]
When ?

**Comment by MasterDomino** [comment]
its random and happens of example on nosland, its not directly portal issue players tell me that it teleports them out of bounds after trying to move away from portal

**Comment by SoraPlays** [comment]
It's not completely random (for example on nosland when you go in LoD) there is for couple of seconds a lagg, and when you go inside this lagg through a portal you're outside of the map (NosVille).

Video: [out-of-bounds](http://sendvid.com/5mfv5jz4)

**Comment by Uppermost** [comment]
Important problem need to fix soon

**Comment by Uppermost** [comment]
Ok I have reproduce it like that, when you go on a map the loading is very slow, if you go on a portal beetwen the loading time, your are disconnected and you are out the map. Need to fix soon it's a priority

**Comment by Uppermost** [comment]
We need to add a flag like idk
 IsChangingMap
And only if it's false, we let him change
hat also means that TeleportToMe wont work if he is changing map

**Comment by Uppermost** [comment]
Update : Problem occur very less but it's not solved.

**Comment by Uppermost** [comment]
Better but not fix, some people tell me this problem occur again (on the latest version)

**Comment by Uppermost** [comment]
Now player tell me it's when they attack monster, on map sometime they can go out

**Comment by Uppermost** [comment]
Seem's to be fix after change grid to static

**Comment by Uppermost** [comment]
20h whitout have this problem, before this problem occur 10x by hour mini I guess it's fix by @Martazza 

#Close

**Comment by Uppermost** [comment]
Occur again very less but again possible after use teleport > disconnection > reconnection out the map

Player tell me I was at NosVille and take teleporter to NosVille plain and after reconnection I'm out the map at NosVille.
