### ISSUE TITLE
SP inventory issue

### ISSUE THREAD

**Issue by Digitalis87** [OpenNos/OpenNos#1209]
https://gyazo.com/5062e988150ec49bcfc5f21a82eb8c8e.

You can add all SP into the SP inventory.
But some slots are bugged.

**Comment by 0Lucifer0** [comment]
Its supposed to reorder automatically >< How did you get this sp in the bottom of the inventory ?

**Comment by MasterDomino** [comment]
propably graphical bug and bad refresh, at least it looks like this

**Comment by Digitalis87** [comment]
Well, I was doing some test for #1154 and i needed more space. sp i took all the SP in EQUP inventory into SP inventory, and lately i just deleted my "usuless" and keep the +15 one, including the war.

@0Lucifer0 no automatic reorder, at least on MyTale.

**Comment by 0Lucifer0** [comment]
Ah i think I Know why's

**Comment by unknownforces** [comment]
This is the same as my issue on #1071 but it got closed lmao. Even though it wasn't fixed.

**Comment by chucktheripper** [comment]
Sp inventory was redone while some mve bugs have been fixed, refresh also was redone
