### ISSUE TITLE
Buy, Upgrade or so..  not too far away possible, ideally

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1213]
When a player use packetlogger he can upgrade or buy when  even if it is on a different map than the NPC

![image](https://cloud.githubusercontent.com/assets/22244296/19256004/63fb3e28-8f63-11e6-8662-ea29e02b84b0.png)

**Comment by The-Art-Of-War** [comment]
i think you can even do this on official

**Comment by The-Art-Of-War** [comment]
tell me if im wrong :D

**Comment by Digitalis87** [comment]
Your right. Packetlogger allow you to do some stuff like that....

**Comment by 0Lucifer0** [comment]
Not if you are not on the same map(on official)

**Comment by The-Art-Of-War** [comment]
ah okay, didnt know that

**Comment by MasterDomino** [comment]
maybe we could check if player is around 5 cells the npc (or max range you can see it) and disable this functionalities of npcs

**Comment by 0Lucifer0** [comment]
Yes

**Comment by Uppermost** [comment]
It's broken shop can't be use sometime.

**Comment by chucktheripper** [comment]
The range check has already been added to npc shop, is it also verified for crafting?

**Comment by MasterDomino** [comment]
should be opened when we desire to fix this as it is for future now
