### ISSUE TITLE
Shopping null reference error

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1214]
![image](https://cloud.githubusercontent.com/assets/22244296/19256082/f4ba3612-8f63-11e6-9e4e-dfd8155bf138.png)

**Comment by MasterDomino** [comment]
it should be fixed after changes of iteminstance branch ;)

**Comment by Martazza** [comment]
Does this still happen?

**Comment by chucktheripper** [comment]
Shouldn't happen anymore. If it still exists, create a new Issue with the updated Code line.
