### ISSUE TITLE
When you kills some monster in act 4 your xp is decrease

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1217]
All is on the title you lose xp when you kill act 4 monster (not all?)

**Comment by SC909** [comment]
I think it is because you have negative amount set for each monster
Have a look in your database, you can see it for monsters like: 545 627 544 559

**Comment by 0Lucifer0** [comment]
That mean that the xp by monster algorithm isn't ok

**Comment by MasterDomino** [comment]
indeed some monsters have negative xp we might need to add condition on if xp is below 0 set it to 0 + add basicxp

**Comment by MasterDomino** [comment]
or just turn negative numbers around because i think that would do the trick

**Comment by MasterDomino** [comment]
this shall stay open in waiting for review

**Comment by SC909** [comment]
I hope this will help you a bit, I am not 100% sure about higher level moobs as I have to deal at least 10% dmg to get 100% exp from each monster, but I thnik this should do. Later on I will try to finish level penalty, add the rest of the moobs from act 4 and have a look at some moobs again to be sure like (when you wear sp you get *2 | *20 more jexp but that depends on the penalty level and sp level 1-??, ??-98.

About jexp and SP jexp I will look into it more. But for now you can use this, it's always something and sorry I couldn't do it better http://pastebin.com/r4FRH7ie

**Comment by MasterDomino** [comment]
set as blocked as it is already done with Math.Abs() <- value absolute but waiting for review you can find it in parser

**Comment by 0Lucifer0** [comment]
should be fixed by #1237
