### ISSUE TITLE
Drop issue

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1225]
When you use some skill sp5 magician or sp8 swordsman skill, you drop only the same item on all monster kill by this hit

![image](https://cloud.githubusercontent.com/assets/15254478/19332866/6f316eb4-90f0-11e6-81ea-028f5c4d7ef5.png)

**Comment by chucktheripper** [comment]
This is caused because the random drop implemenation uses the same calculation as that aren't real random values.

**Comment by MasterDomino** [comment]
we cant randomize it based on time because they're all killed in the same time? also how can we randomize randomization more (not using DateTime)?

**Comment by 0Lucifer0** [comment]
Juste USE mapmonsterid

**Comment by MasterDomino** [comment]
good idea will push commit if it works out
