### ISSUE TITLE
Remove SP world server crash

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1226]
![removesp](https://cloud.githubusercontent.com/assets/22352357/19343785/f452ca9c-9137-11e6-8e01-ec146f0f7acb.png)

**Comment by Uppermost** [comment]
More details please?

**Comment by BelminBIH** [comment]
Logs ?

**Comment by Uppermost** [comment]
Not reproducible should be fixed at the latest update
