### ISSUE TITLE
GodMode don't show damage

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1227]
All on the tittle damage are not displayed

**Comment by MasterDomino** [comment]
its caused by overflowing the internal damage of client we do it around 1024 times and we deal about 67 milions of damage soo its pretty casual it doesnt work xD

**Comment by 0Lucifer0** [comment]
but that's supposed to be shown with a modulo of ushortMax

**Comment by MasterDomino** [comment]
its not, then its issue of someone who wrote that modulo, its exactly 1024 * maxvalue.short

**Comment by 0Lucifer0** [comment]
Damage need to be displayed
