### ISSUE TITLE
Sometime all monster stop respawn

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1228]
All is on the tittle, sometime all monster on all map never respawn after this bug (maybe a loop problem again)

**Comment by 0Lucifer0** [comment]
If its a loop problem they won't move anymore so that's not the problem

**Comment by 0Lucifer0** [comment]
how to have this bug?

**Comment by Uppermost** [comment]
Happens only 1x a lot of people don't get they drop etc and after a freeze like 10 seconds monster never respawn again (153 player at the moment of the problem) we already have more player connected on the same time whitout problem the CPU usage seem's to be not stable... I have no more informations.

**Comment by chucktheripper** [comment]
Maybe it's because of the packet amount, if the amount of packets for the player is so high, then maybe 30 packets / 10 ms are causing this problem

**Comment by Uppermost** [comment]
I don't know but there is a very big problem after this update (send multiple packet in once) maybe not link but CPU to 50% (never down) and ram usage to 3000 MB... please check my rapport, but I think this problem is not on the rapport...

**Comment by aerzy** [comment]
This problem happened to me 3/4 times
