### ISSUE TITLE
WORLD SERVER ERROR HANDLER GENERATEKillBonus

### ISSUE THREAD

**Issue by JOAOMASTER** [OpenNos/OpenNos#1229]
A MONSTER attack when the error occurs
![erro 9](https://cloud.githubusercontent.com/assets/17860577/19366769/5e1e7d76-9166-11e6-8234-bc1010e3b511.png)

**Comment by Uppermost** [comment]
Already in issue

**Comment by JOAOMASTER** [comment]
ok
