### ISSUE TITLE
Mail non threadsave iterator problem

### ISSUE THREAD

**Issue by JOAOMASTER** [OpenNos/OpenNos#1230]
when it is trying to move up on the roof of the house Nashville any house
![error 8](https://cloud.githubusercontent.com/assets/17860577/19367096/bb8fd9fe-9167-11e6-927c-f8d9ea9822c4.png)

**Comment by 0Lucifer0** [comment]
please avoid CAPSLOCK!

**Comment by JOAOMASTER** [comment]
ok
