### ISSUE TITLE
WORLD SERVER ERROR HANDLER INVENTORY LIST.MOVE INVENTORY

### ISSUE THREAD

**Issue by JOAOMASTER** [OpenNos/OpenNos#1231]
![error 7](https://cloud.githubusercontent.com/assets/17860577/19367312/9a74a1f4-9168-11e6-86dd-7c1d628f4760.png)

**Comment by 0Lucifer0** [comment]
CAPSLOCK!!!!!!!!!!!!!!!!!!!!!!!!!!! STOP THAT KIND OF MESSAGE WE ARE NOT YOUR BITCH.

**Comment by JOAOMASTER** [comment]
that was the last sorry when you gave me the change

**Comment by JOAOMASTER** [comment]
ready sorry not happen again

**Comment by 0Lucifer0** [comment]
Thats already in issues
