### ISSUE TITLE
Equip scroll problem / npc

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1234]
(Equipment scroll) Sometime, scroll use cella but the upgrade is cancelled... the waiting bar work but after that nothing happens... Seem's to be a problem with the amount of items requiere

Edit when the upgrading is cancelled it remove only cella.

Seem's to be caused by principal upgrade function same on Teomann after +5 it's imposible for a lot of them to upgrade equip

#1259

**Comment by MasterDomino** [comment]
it has been fixed on some of my commits now it should return before removing the items
