### ISSUE TITLE
use packetfactory for gop

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#1235]
- [ ] OPTIONAL: create unittest based on WalkMoveTest
- [x] create new ClientPacket gop with header and Properties:
Index 0: CharacterOption Option
Index 1: Activate

- [x] replace packetsplit with packetfactory in the GroupOption method in BasicPackethandler and all references to it

**Comment by MasterDomino** [comment]
need to add WalkMoveTest

**Comment by chucktheripper** [comment]
You need to add a test based on WalkMoveTest

**Comment by chucktheripper** [comment]
Unittest will follow with correct Unittesting environment
