### ISSUE TITLE
implement exp dependant on level of player - monster level

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#1237]
"Well I can say I finished my job for now.
Please read it carefully, if you don't understand something you can always ask.
http://pastebin.com/KKeQ5QFj
I will also have a look at Act 4 moobs again as I might have done some errors, I will publish more stuff soon." - SC909 thanks goes to him

**Comment by SC909** [comment]
I did some work on group exp with someone. 
The results should be available soon.

**Comment by chucktheripper** [comment]
Thanks for your contribution @SC909

**Comment by SC909** [comment]
A small update
It uses a lot of numbers with decimal places.

(EXP * (exp pot, tarot, flower, ancelloan ...) *pets)) *Event

I think it is also level dependant exp, if you look previously at http://pastebin.com/KKeQ5QFj
You can see that you can get 150% xp from mobs at level 1-5 from mobs that have 4 or more levels than you.

Note that it have to be the same as below or it won't work, I tried changing things round without success.

Fire Dog Lv88
1-5: 138000
6-18: 92000
19-99: 46000

//The goal is 45 lvl gets 40596 from the dog
//Calculate ratio to use it later(6/lvl+lvl -> 6/99+45 -> 6/144)
6/144 = 0,0416666666666667
0,0416666666666667 *45 = 1,875000000000002

For lv 19-99 it will be:
46000/3 = 15333,33333333333
15333,33333333333*0,575 = 8816,666666666665



//8816,666666666665
8816,666666666665
8816,666666666665 (100% is ancelloan blessing)
1763,333333333333 (20% exp pot)
1322,5 (15% tarot card (star))

8816,666666666665 + 8816,666666666665 + 1763,333333333333 + 1322,5 = 20719,16666666666

//You have to turn it to integer (lv1 mobs(102) 34,5*3 = 103,5 34*3 = 102)
20719,16666666666 -> 20719
20719*1,875000000000002 = 38848,12500000004 (to int again)
38848 +4,5% = 40596,16 -> 40596

With guide of (EXP * (exp pot, tarot, flower, ancelloan ...) *pets)) *Event
It should look like this:

long Exp1 = int GetLevelDependantExp /3 *0,575
long PotExp = Exp1 *1,2
long StarTarotExp = Exp1 *1,15

int Exp2 = StarTarotExp + PotExp + Exp1 +Exp1 //Exp1 twice as one of them is ancelloan blessing
int Exp3 = Exp2 * ((6/Group.TotalLevel) *Character.Level //Just add up each player level in party
int Total = Exp3 *1,045

Or for now:

long Exp1 = int GetLevelDependantExp /3 *0,575
int Exp2 = long Exp1 //convert to int

//Add up each player level in party *char level for which exp is being calculated for
int Total = Exp2 * ((6/Group.TotalLevel) *Character.Level



The only thing missing is when you have too high level from mob, I will have a look later at that.
And also I don't know exactly how it works for high level on low level mobs (when there is too high level in party like 90+1 etc.)


That's all from me for now on.
I will also have a look at it again on act 6.1 just to confim it.

**Comment by SC909** [comment]
What I have just discovered will help you a lot with XP from monsters. 
I've just had a look at something that someone posted about 2 weeks ago.
And this works on all mobs.

//Xp for each mob
1-18, 19-99 is what level a mob is.

1-18: 60 * mobLv + assigned xp
19-99: 70 * mobLv + assigned xp

assigned xp (You can find it in monster.dat file)
EXP 0 0


Just to let you know, it's not perfect for act 4 mobs, but it works fine for bosses there, some mobs are tricky.


//Level Dependant EXP
Going back to level dependant exp, it has to be changed from /2 and /3 to *2 and *3.
1-5: *3 xp & jxp
6-18: *2 xp & jxp
19-99: *1 xp & jxp


You can do the same with jxp, monster HP and MP (with jxp it's a bit tricky as I will have to test moobs between lv 45 to 56 to check it.)





//Hero Level XP
Base xp /50 = Hero xp

Base xp is also processed through Level Dependant EXP and Level Penalty (when you have too big level)

//Bacoom 94 lvl
94*70 = 6580
EXP	26000	4000
6580+26000 = 32580

//Elite Bacoom 97 lvl
97*70 = 6790
EXP	100000	8000
100000+6790 = 106790
8105 jxp



Well at least I hope you will get it, cause it's just a big mess.

**Comment by 0Lucifer0** [comment]
Thanks for this cool job ;)

**Comment by MasterDomino** [comment]
the problem now i need to fix algo for monsters other than lvl for jxp and add separate penalty for this algo, and seems like we need more info about how the official does that :/ but good job SC

**Comment by MasterDomino** [comment]
!Missing! splvl algo, and group penalty needs to be fixed

**Comment by MasterDomino** [comment]
done \o/

**Comment by MasterDomino** [comment]
reopening cuz needs a little review on it theres a few problems with documents, unreadable mainly cuz too much mess for now will try to understand those
