### ISSUE TITLE
Crash server caused by remove SP

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1240]
![image](https://cloud.githubusercontent.com/assets/15254478/19387550/226c7660-921b-11e6-9b42-c617a1d2784d.png)

This error cause server crash. I have no idea how to reproduce it, text in white is not normal.

that's not normal to have issue in white
we need to review exception management because all exception need to be catch in red

**Comment by 0Lucifer0** [comment]
#1198
