### ISSUE TITLE
Problem with damage when transform or set point of an SP.

### ISSUE THREAD

**Issue by DarkCacos** [OpenNos/OpenNos#1246]
I tried this with a Vulcan 99+15, 0 points setted at the beginning.
I was in Map 46 and hit the Zombie Trees, but it happens with all monsters.

If I am in a map, transform into the SP and hit the monsters with the basic move without leaving the map, the damage will be lower than normal. (In my specific case, around 2000)
But if I change map and re enter, the damage return normal (I suppose), and it became around 11000.

This happens also when I right click on the sp card to check the point setted, and exit. Even without adding points or do anything. Changing map return it to normal again.

**Comment by Ciapa1** [comment]
This is a bug in the underlying system. Still need to find out what causes
this. For now: Remove Fairy and Wear it again fixes this

Am 15.10.2016 12:00 vorm. schrieb "DarkCacos" <notifications@github.com>:

**Comment by Uppermost** [comment]
It's not only on sp, same problem whitout sp.

**Comment by Ciapa1** [comment]
We already tested and found out that sometimes, the Fairy Element gets lost in Session.Character. I may think of a hotfix for now.

**Comment by MasterDomino** [comment]
wasnt it fixed with your last commits? can it be closed?

**Comment by Ciapa1** [comment]
Fixed.
