### ISSUE TITLE
Ram/Cpu usage leak

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1249]
I see this problem since today seem's very recent, Ram usage begin at 400 MB and up to very high like 3000 MB... There is a big memory leak, seem's to be caused by JPS+

And the CPU is constant to 45% (with a low number of people, number of people don't cause this problem) I think it's a loop problem or similar thing only 19 problem cause this problem and sometime with 200 player we don't have anything

**Comment by Uppermost** [comment]
Seem's to be a problem with foreach on MapNpc & NpcTeleporter I try to add some screens but the rapport is too high and impossible to see it again on Visual Studio (He always crash)

**Comment by 0Lucifer0** [comment]
how do you know that the leak is here? because this is loading part

**Comment by Uppermost** [comment]
Performance analysis

**Comment by 0Lucifer0** [comment]
yes but what's the problem in the performance analysis because that's only a storrage so i don't understand where there can have cpu leak here

**Comment by Uppermost** [comment]
Sometime ram up to 3000 MB I don't know the reason, but when I have launch the analysis test I have see a problem with Grid, SaveAll and MapNpc, I don't have more information the rapport is impossible to open now (the size to openning was 8 go) I have remove it because "Visual Studio stop to working" everytime I tried to open it :/

**Comment by 0Lucifer0** [comment]
but you talk about ram or cpu leak because here i don't see how a cpu leak can occure and if it use a lot of ram that's normal here but that should be only at startup...
