### ISSUE TITLE
Console not loaded. (World)

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1253]
![image](https://cloud.githubusercontent.com/assets/22244296/19408185/96626efc-92b7-11e6-8211-b41fe13438be.png)

**Comment by Uppermost** [comment]
It work fine for me

**Comment by MyTaleON** [comment]
me too. But sometimes come this ... o.o

**Comment by 0Lucifer0** [comment]
i think you have a trouble somewhere just update.
