### ISSUE TITLE
spam skill

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#1261]
When you spam skill u can spam attack ( with special skill zone of SP6 archery ) idk for other sp

**Comment by Uppermost** [comment]
I want to add if you spam skill you can sometime use 2x the same skill at the same moment :) whitout refresh time

**Comment by MasterDomino** [comment]
the thing you talk about anthony is caused by wrong cooldown system

**Comment by 0Lucifer0** [comment]
will be fix by #910
