### ISSUE TITLE
Time recolt problem

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1263]
For the moment recolt time say always "Wait 0 second" we need to add a superior delay but I don't know how it work

**Comment by MasterDomino** [comment]
what do you mean with recolt and how to reproduce it?

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/19837097/1430ddbc-9eb3-11e6-87ca-9b2e4c724427.png)

The needed time to retry your recolt, it's wrong because it's always show 0 seconds just spam that and you can have the time needed but as you can see it's always 0 seconds then it's useless 0 seconds we need the true time

**Comment by MasterDomino** [comment]
as i said were missing this because idk what the algo to count it but okay i think its one of these issues that we will never have correct data

**Comment by Uppermost** [comment]
Just add approximately algo then in function of the number of try I don't know
