### ISSUE TITLE
You are disconnected when you equip a fairy now

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1270]
All on the title > latest update

We need to fix it soon

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/19460333/0304c9fe-94db-11e6-9233-51e7dc9d4369.png)
I don't know if this error is link to that but now there is a now error

**Comment by chucktheripper** [comment]
Please send example of custum shop. Works perfectly for me.
