### ISSUE TITLE
Right on sp doesn't work after latest update

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1273]
Right click on sp doesn't work now...

**Comment by chucktheripper** [comment]
Test with latest update

**Comment by aerzy** [comment]
When u equip the SP right click don't work but when is only in inventory work

**Comment by chucktheripper** [comment]
So when you're wearing it, it causes the error on rightclick

**Comment by Uppermost** [comment]
fix by my latest commit
