### ISSUE TITLE
More than 3 characters in group

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1274]
![e4b7f0d5602bfb35e1ba2ee880614f0436ee7b51d12b89aee8 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/22352357/19466217/b98c6758-9509-11e6-8739-b6a24d5a14a6.png)

**Comment by chucktheripper** [comment]
Nice feature

**Comment by chucktheripper** [comment]
Please add a description how to reproduce this error.

**Comment by BelminBIH** [comment]
I don't know it's my friends who send this picture

**Comment by chucktheripper** [comment]
Ask them
