### ISSUE TITLE
Where is inventory table ? #SQL

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1275]
![inventaire](https://cloud.githubusercontent.com/assets/22352357/19475633/6e1c9b54-9535-11e6-8a9d-2b66a56f37c5.png)
![inventaire1](https://cloud.githubusercontent.com/assets/22352357/19475636/7364d144-9535-11e6-8ad7-c21d7c308e54.png)

**Comment by chucktheripper** [comment]
Inventory has been removed, it's only ItemInstance which is left

**Comment by 0Lucifer0** [comment]
There is no more inventory table
