### ISSUE TITLE
Drop "?"

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1280]
![20161018-9-suo](https://cloud.githubusercontent.com/assets/22352357/19487288/721f4242-9562-11e6-97f4-8614d5034dcd.jpg)
![20161018-10-suo](https://cloud.githubusercontent.com/assets/22352357/19487294/77653b1c-9562-11e6-836c-516e9f73c5ff.jpg)

**Comment by Uppermost** [comment]
already in issue ;)
