### ISSUE TITLE
Invalid operation exception, SourceInstance

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1286]
![image](https://cloud.githubusercontent.com/assets/15254478/19489750/be561da2-956c-11e6-8308-041a6e824c01.png)

**Comment by chucktheripper** [comment]
How did this happen? Please provide a way to reproduce.

**Comment by chucktheripper** [comment]
We need to check source and target existance before moving.

**Comment by chucktheripper** [comment]
Please validate source and Target. Source for existance and target for freeness
