### ISSUE TITLE
Specialist Inventory broken

### ISSUE THREAD

**Issue by mazinthebox** [OpenNos/OpenNos#1287]
Right now (18/10/2016) i have found some issues when I try to wear some SP (in my case second and third one); the second one when I try to wear doesn't show any result, or messagge or nothing, 0 actions; the third one hide itself when i double-click and iI have to relog to see it again.

-- Edit --
Now I can't move specialist card to and from my bag (all of my SPs).

**Comment by themazitto** [comment]
News:
Now I can't move specialist card to and from my bag.

**Comment by Uppermost** [comment]
Some player tell me, my SP dissapear after equip and impossible to use it

**Comment by mazinthebox** [comment]
I think to know how to spot this bug, but i have to try again and again to see response.
So when you have equipped a SP you should try to change your SP without change you fairy and after this roll back those ones; in my case now all the item start to bug itself.

**Comment by aerzy** [comment]
So
When one puts a PSP that comes from the inventory map
MS disappears
and take the first inventory item EQUIP. in place

**Comment by Uppermost** [comment]
Ok inventory SP cause SP "dissapear" and the first item in your inventory go on your sp slot (I think)
