### ISSUE TITLE
ACT4 Item is drop but nothing appear on the inventory

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1290]
It show me "Item get" but nothing in my inventory.

**Comment by chucktheripper** [comment]
Whats the item type? Is it dropped by player or monster?

**Comment by chucktheripper** [comment]
Works for all droppable types.

**Comment by chucktheripper** [comment]
ACT4

**Comment by MasterDomino** [comment]
should be fixed after 434cb52bd642ff696d2214ad6115573fcb2e2893

**Comment by chucktheripper** [comment]
Did someone test it?

**Comment by Uppermost** [comment]
fix
