### ISSUE TITLE
Stat low with item send by gift

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1293]
![image](https://cloud.githubusercontent.com/assets/15254478/19522499/bef32100-9617-11e6-8f91-cd2ec33b7463.png)
They stats are low when you send an item with $Gift command (object with rarity) 

(R0 rarity)

**Comment by chucktheripper** [comment]
Is it the same with normal rarify?

**Comment by Uppermost** [comment]
yeah

**Comment by chucktheripper** [comment]
Also please check what GiftAdd does when inventory is full.
