### ISSUE TITLE
Disconnection on low level target hit

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#1298]
when you hit monster with low level you get disconnect ( not all time )

**Comment by aerzy** [comment]
![capture](https://cloud.githubusercontent.com/assets/16693364/19581242/f18f200e-972b-11e6-9a26-e5575bdd0f77.PNG)

**Comment by chucktheripper** [comment]
Probably caused by threadsafe skill implementation

**Comment by aerzy** [comment]
when you take groupe for levelling with low level and use skill on monster you get discconection
