### ISSUE TITLE
wrong text

### ISSUE THREAD

**Issue by earthnash** [OpenNos/OpenNos#1309]
i'm adventure so i can't wear mage card
it **should send** 
`session.SendPacket(session.Character.GenerateMsg(Language.Instance.GetMessageFromKey("BAD_CLASS"), 0));`
but in **opennos it send**
`session.SendPacket(session.Character.GenerateSay(Language.Instance.GetMessageFromKey("BAD_EQUIPMENT"), 10));`

**Comment by Uppermost** [comment]
No it's ok because on official it show "You can't wear this item !" and in French "Ton personnage ne remplit pas les conditions d'utilisation pour porter cet objet"
