### ISSUE TITLE
Error sql

### ISSUE THREAD

**Issue by Halim980** [OpenNos/OpenNos#1312]
I have this error when I try to excute sql 
[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DECLARE @CurrentMigration [nvarchar](max)

IF object_id('[dbo].[__MigrationHisto' at line 5
[Err] -- ========================================== --
-- Current Migration: 201610211827432_Ares
-- ========================================== --

DECLARE @CurrentMigration [nvarchar](max)

IF object_id('[dbo].[__MigrationHistory]') IS NOT NULL
    SELECT @CurrentMigration =
        (SELECT TOP (1) 
        [Project1].[MigrationId] AS [MigrationId]
        FROM ( SELECT 
        [Extent1].[MigrationId] AS [MigrationId]
        FROM [dbo].[__MigrationHistory] AS [Extent1]
        WHERE [Extent1].[ContextKey] = N'OpenNos.DAL.EF.Migrations.Configuration'
        )  AS [Project1]
        ORDER BY [Project1].[MigrationId] DESC)

IF @CurrentMigration IS NULL
    SET @CurrentMigration = '0'

IF @CurrentMigration < '201610211827432_Ares'
BEGIN
    CREATE TABLE [dbo].[Account] (
        [AccountId] [bigint] NOT NULL IDENTITY,
        [Authority] [smallint] NOT NULL,
        [LastCompliment] [datetime] NOT NULL,
        [LastSession] [int] NOT NULL,
        [Name] [nvarchar](255),
        [Password] [varchar](255),
        CONSTRAINT [PK_dbo.Account] PRIMARY KEY ([AccountId])
    )
    CREATE TABLE [dbo].[Character] (
        [CharacterId] [bigint] NOT NULL IDENTITY,
        [AccountId] [bigint] NOT NULL,
        [Act4Dead] [int] NOT NULL,
        [Act4Kill] [int] NOT NULL,
        [Act4Points] [int] NOT NULL,
        [ArenaWinner] [int] NOT NULL,
        [Backpack] [int] NOT NULL,
        [Biography] [nvarchar](max),
        [BuffBlocked] [bit] NOT NULL,
        [Class] [tinyint] NOT NULL,
        [Compliment] [smallint] NOT NULL,
        [Dignity] [real] NOT NULL,
        [EmoticonsBlocked] [bit] NOT NULL,
        [ExchangeBlocked] [bit] NOT NULL,
        [Faction] [int] NOT NULL,
        [FamilyRequestBlocked] [bit] NOT NULL,
        [FriendRequestBlocked] [bit] NOT NULL,
        [Gender] [tinyint] NOT NULL,
        [Gold] [bigint] NOT NULL,
        [GroupRequestBlocked] [bit] NOT NULL,
        [HairColor] [tinyint] NOT NULL,
        [HairStyle] [tinyint] NOT NULL,
        [HeroChatBlocked] [bit] NOT NULL,
        [HeroLevel] [tinyint] NOT NULL,
        [HeroXp] [bigint] NOT NULL,
        [Hp] [int] NOT NULL,
        [HpBlocked] [bit] NOT NULL,
        [JobLevel] [tinyint] NOT NULL,
        [JobLevelXp] [bigint] NOT NULL,
        [Level] [tinyint] NOT NULL,
        [LevelXp] [bigint] NOT NULL,
        [MapId] [smallint] NOT NULL,
        [MapX] [smallint] NOT NULL,
        [MapY] [smallint] NOT NULL,
        [MasterPoints] [int] NOT NULL,
        [MasterTicket] [int] NOT NULL,
        [MinilandInviteBlocked] [bit] NOT NULL,
        [MouseAimLock] [bit] NOT NULL,
        [Mp] [int] NOT NULL,
        [Name] [varchar](255),
        [QuickGetUp] [bit] NOT NULL,
        [RagePoint] [bigint] NOT NULL,
        [Reput] [bigint] NOT NULL,
        [Slot] [tinyint] NOT NULL,
        [SpAdditionPoint] [int] NOT NULL,
        [SpPoint] [int] NOT NULL,
        [State] [tinyint] NOT NULL,
        [TalentLose] [int] NOT NULL,
        [TalentSurrender] [int] NOT NULL,
        [TalentWin] [int] NOT NULL,
        [WhisperBlocked] [bit] NOT NULL,
        CONSTRAINT [PK_dbo.Character] PRIMARY KEY ([CharacterId])
    )
    CREATE INDEX [IX_AccountId] ON [dbo].[Character]([AccountId])
    CREATE INDEX [IX_MapId] ON [dbo].[Character]([MapId])
    CREATE TABLE [dbo].[CharacterSkill] (
        [Id] [uniqueidentifier] NOT NULL,
        [CharacterId] [bigint] NOT NULL,
        [SkillVNum] [smallint] NOT NULL,
        CONSTRAINT [PK_dbo.CharacterSkill] PRIMARY KEY ([Id])
    )
    CREATE INDEX [IX_CharacterId] ON [dbo].[CharacterSkill]([CharacterId])
    CREATE INDEX [IX_SkillVNum] ON [dbo].[CharacterSkill]([SkillVNum])
    CREATE TABLE [dbo].[Skill] (
        [SkillVNum] [smallint] NOT NULL,
        [AttackAnimation] [smallint] NOT NULL,
        [BuffId] [smallint] NOT NULL,
        [CastAnimation] [smallint] NOT NULL,
        [CastEffect] [smallint] NOT NULL,
        [CastId] [smallint] NOT NULL,
        [CastTime] [smallint] NOT NULL,
        [Class] [tinyint] NOT NULL,
        [Cooldown] [smallint] NOT NULL,
        [CPCost] [tinyint] NOT NULL,
      
[Msg] Finished - Unsuccessfully
--------------------------------------------------

**Comment by 0Lucifer0** [comment]
RTFM.

**Comment by Halim980** [comment]
it means rtfm?

**Comment by Uppermost** [comment]
Read the readme
