### ISSUE TITLE
$RemovePortal should update to each player on map

### ISSUE THREAD

**Issue by SC909** [OpenNos/OpenNos#1315]
http://imgur.com/a/KvjFH

You are using:
ServerManager.Instance.ChangeMap(Session.Character.CharacterId);

While you should send that the portal is disabled:
gp {portal.SourceX} {portal.SourceY} {portal.DestinationMapId} {portal.Type} {i} 1

//Caligor portal
gp 111 159 154 -1 3 0

//When it closes, every user receives this
gp 111 159 154 -1 3 1

**Comment by MasterDomino** [comment]
youre sure thats the only packet that you receive after closing of portal yes?
