### ISSUE TITLE
qslot empty when using $JLvl

### ISSUE THREAD

**Issue by SC909** [OpenNos/OpenNos#1316]
https://gyazo.com/65d0f7e77a014dbeeeb644c2e5def5b5
As you can see it will empty entire qslot until you get a skill, the next skill is on job 4.
If you do a relog, the qslot will be still empty but, if you used $JLvl 3 and then $JLvl 4, everything will go back to normal. This works on each new skill you get.

https://gyazo.com/52a73251e3c9dd355795cdf078f0603b
https://gyazo.com/6d02ec08553e6f966ad86c8b7bdda84a
If you use this command to get job 20 and then downgrade to job 1 all the skills will remain and skill points that you use to learn skills will be negative.

**Comment by Uppermost** [comment]
You don't fix the issue and create a new issue Martazza.

The problem is when you use this command ($JLvl) you lose all skill on your bar skills and we need to keep them etc...
