### ISSUE TITLE
Monster movement/teleport

### ISSUE THREAD

**Issue by SC909** [OpenNos/OpenNos#1318]
I was not able to get a better shot of this, but I lured them where a portal to port is (bottom right corner of the map). I logged out with that account and all the mobs returned back to where they were.
https://gyazo.com/2f8f0d394467f584d27d6ae6f2cff427

On official if you lure mobs and leave them somewhere, if they are not able to go back they will stay there.

**Comment by 0Lucifer0** [comment]
That's volunteer our pathfinding is better.
