### ISSUE TITLE
Aggressive monsters range (notice and attack)

### ISSUE THREAD

**Issue by SC909** [OpenNos/OpenNos#1319]
Monsters like mandragora are able to notice you with the range of their attack
I've looked at two mandragoras on Sunny Meadows, one was able to notice me from distance of 5 while the other 7. Both attack range is 8.
I've looked in monster.dat at VNUM 20 and VNUM 21.

PREATT 1 0 5 5 600
PREATT 1    0 7 5    800

PREATT 1 0 {notice_distance} 5 {respawn_time/10 = resp_in_seconds}

And in both of those I noticed that they have 8 so I think this represents attack distance that every monster is able to. And I think I can confirm that as I've just looked at Darko (fire dog pet)
//Mandragora
VNUM 20
ZSKILL 2 8 3 2 12 0 0
WEAPON  26 8 0 0 0 0 0

//Darko
VNUM 823
ZSKILL 0 2 3 1 10 0 0
WEAPON  1 2 50 60 9 3 10

//Lord Draco
PREATT 1 0 20   7 2400 - Can notice from 20 blocks away.

//Magmaros
PREATT 1 0 12   9 1200 - Can notice from 12 blocks away.

//Monster stats - I will work on it
ZSKILL {level} 2 3 1 10 0 0
WEAPON  {level} 2 50 60 9 {crit_chance} {crit_damage}
The {level} might be attack level or something like level\* ...

**Comment by Uppermost** [comment]
Now any monster attack you when you come beside them. Please check that, example map 150.

**Comment by Uppermost** [comment]
Nevermind just update the database (npcmonster)
