### ISSUE TITLE
Monsters should stop following you if they are unable to hit you

### ISSUE THREAD

**Issue by SC909** [OpenNos/OpenNos#1320]
//OpenNos
Even non aggressive monsters will follow you from one end of the map to the other even if you set your speed to 50.

//Official
Small Dander will stop following you after 15-17 seconds
Jackpen after 15-17 seconds.
Young Battle Scout Gnoll (aggressive monster) 15-16 seconds

You can test it by hitting a mob or going too close to one of aggressive mobs so he becomes aggressive. And then just run around so a mob can't hit you.
## Small Update

You could also add a delay before first attack to all monsters; 
take a dander/chicken as an example of that, when you attack it on OpenNos, it registers that you have hit the monster, which causes it to attack you just before the attack animation of the player ended (during the animation of an attack).
I think on official, monster attack will be triggered when player animation attack ends and the first monster hit is after about 0,5 to 1,5 seconds. I don't know exactly as I have not looked at it much.

**Comment by Martazza** [comment]
a647a66c428ab49cd6661ab74cb885b88b645f62
