### ISSUE TITLE
AddMonster not works

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1324]
hello I would like posted a solution on a bug, the AddMonter does not work everywhere, for example on the map raid Castra this command and unusable, no error message is displayed, the mob simply does not appear

**Comment by Kyoraku** [comment]
it depend, if the data of the monster doesn't exist in the data file it's normal. it will not be shown. which monster you're adding ? x)

**Comment by BelminBIH** [comment]
The monster that I want to add is in the database. Example: $ AddMonster 24 1 (dander is in the database) PS: I noticed something weird on the (mapmonster.sql)
![sans titre](https://cloud.githubusercontent.com/assets/22352357/19629765/eebec918-997b-11e6-9cc1-b77c10e0769b.png)

**Comment by Uppermost** [comment]
Warning some monster are not visible like circle monster in raid etc

**Comment by SC909** [comment]
@Uppermost You're right, those monsters that are invisible don't have sprites and they can't be selected even by spacebar, but if you change the vnum of a monster in the IN packet or you just send u_s ... id you can hit that monster. Most of those monsters that are invisible are:

Xys raid rock, fire raid rock (act 4), Ibrahim/robbers raid rock (act 5.1 raid), angel and deamon ice spikes (act 4) - I think only those ones never disappear (they don't die when they attack).
Zenas (act 6.1) vortex, Kertos and Grenigas raid - lava fountains, top 3 rep skill spikes, sp5/6 raid etc. - those will be used only once until they are spawned again. 


For now I don't think it is important to make them work as they should, and most of those monsters attack are pointed at them self 
(first they make an effect at which place their attack will be and after about 2-5 seconds, they will use their attack and deal damage to any entity that is not a monster in that place).

**Comment by BelminBIH** [comment]
So for me to put mob in the RAID, without any change how I done?

**Comment by MasterDomino** [comment]
depends what monster you want to add, we've had issues with new items over 8k because official added duplicates soo try to find lowest possible vnum for monster and use it maybe theres also some duplicates, and close if it works.
