### ISSUE TITLE
Bug after disconnection

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1326]
Me, and some player have this bug sometime, they have a black screen and they can't do anything on the map I can see the player with this bug but he can't do anything always black screen and only with the bugged character. I already have this problem and impossible to solve it whitout delete character et recreate, seem's to be new bug 1 week ago maximum. Block only the buggy character you can play with they others whitout problems and this problem seem's to occur always after a disconnection I already had this problem after use $Invisible but I don't know more about that

**Comment by chucktheripper** [comment]
Which Packets on Startup are depending on $Invisible?

**Comment by Uppermost** [comment]
Some player have already this problem, very rare, I don't know how to reproduce it when it occur the character is blocked and you can do nothing to debug it

**Comment by Uppermost** [comment]
Not reproducible.
