### ISSUE TITLE
 Can do anything

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#1328]
Can do anything and after 1 minuts ~ this error com
![img_25102016_131731](https://cloud.githubusercontent.com/assets/16693364/19684476/a66a546a-9ab7-11e6-86bd-48cb031d48f9.png)

**Comment by chucktheripper** [comment]
Is your database up and running?

**Comment by aerzy** [comment]
yes this crash com 5/6 time in 1 hours

**Comment by Uppermost** [comment]
Never had this problem

**Comment by chucktheripper** [comment]
Restart your SQL Server and Try again
