### ISSUE TITLE
add item information

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#133]
add item information on right click (e_info)

**Comment by 0Lucifer0** [comment]
e_info 0 141 2 0 0 63 251 345 283 12 200 0 100 69552 -1 0 0 0 //sword

e_info 1 4006 4 5 1 80 385 430 355 10 110 24 100 120000 -1 4 351484 5 1.15.6 1.23.6 2.24.114 2.27.8 10.35.11/crossbow with shells

e_info 1 292 4 7 0 67 318 365 322 7 130 50 100 78256 -1 4 715297 4 1.1.65 2.25.100 2.23.15 10.35.9 //crossbow with shells

e_info 2 106 1 0 0 62 185 171 126 259 69440 -1 0 0 0 // armor

e_info 3 224 20 13 0 0 0 0 0 0 0 2400 0 0 -1 //mask hat resistance
e_info 3 204 18 5 3 1 0 0 0 0 0 1980 0 0 -1 
e_info 3 220 20 4 4 4 4 0 0 0 0 2400 0 0 -1
e_info 3 221 20 3 6 4 2 0 0 0 0 2400 0 0 -1
e_info 3 218 20 2 10 3 0 0 0 0 0 2400 0 0 -1
e_info 3 217 20 12 0 0 0 0 0 0 0 2400 0 0 -1
e_info 3 215 20 4 5 4 0 0 0 0 0 2400 0 0 -1
e_info 3 712 42 7 4 3 1 0 0 0 5 10584 0 0 -1
e_info 3 227 20 0 0 0 0 0 0 0 0 2400 0 0 -1
e_info 3 385 45 18 2 0 0 42 0 0 0 11970 5 0 -1
e_info 3 315 42 7 2 1 0 48 0 0 0 10584 5 0 -1
e_info 3 379 45 5 5 5 2 0 0 0 42 11970 5 0 -1
e_info 3 387 45 7 4 3 1 0 0 0 42 11970 5 0 -1

e_info 4 275 2 0 0 0 280 1 //fairy
e_info 4 276 3 42 0 278 480 2
e_info 4 803 4 0 0 0 720 0
e_info 4 801 2 0 0 0 280 0
e_info 4 802 3 0 0 0 480 0
e_info 4 331 1 2 1 0 120
e_info 4 303 62 6 2 0 132928
e_info 4 306 69 6 4 0 163392//jewels
e_info 4 303 62 6 2 0 132928
e_info 4 800 1 29 0 82 120 0
e_info 4 306 69 6 4 0 163392
e_info 4 303 62 6 2 0 132928
e_info 4 307 65 6 2 0 145600

e_info 5 155 0 0 0 63 266 313 70 0 0 0 100 69552 -1 0 0 0 //stick

**Comment by 0Lucifer0** [comment]
i don't understand how to determine the e_info first number and i don't find any way to send all the correct information with only 1 function...

**Comment by MasterDomino** [comment]
e_info 1 757 4 0 0 73 343 436 336 6 100 0 100 98039 -1 3 354336 2 1.3.2 2.9.8 // archer
e_info 1 147 2 0 0 54 200 315 245 2 50 0 100 48600 -1 0 0 0
e_info 1 756 2 0 0 68 289 375 311 10 170 0 100 80512 -1 2 354336 2 1.11.6 1.23.6
e_info 1 148 1 0 0 63 248 346 279 10 210 0 100 69552 -1 0 0 0
e_info 1 265 3 5 0 45 213 303 232 12 110 4 100 32130 -1 2 354336 1 1.11.2 // bow loaded arrows

**Comment by Ciapa1** [comment]
For functions: you could directly pass the requested item to the function
and then in the first part separate it to the respective item type. Then
for each mode there is a predefined e_info string which gets formatted with
all the required data from the item and all is fine.

**Comment by 0Lucifer0** [comment]
reception is made see eqinfo and add content to GenerateEInfo()

**Comment by 0Lucifer0** [comment]
done
