### ISSUE TITLE
Overflow of password encryption

### ISSUE THREAD

**Issue by earthnash** [OpenNos/OpenNos#1333]
![image](https://cloud.githubusercontent.com/assets/15151087/19697311/160cc50c-9b15-11e6-96b3-104b20c37d36.png)
IDK how to reproduce it

**Comment by MasterDomino** [comment]
looks like the password was too long, or maybe because you use Thai it might have overflow the byte.

**Comment by 0Lucifer0** [comment]
Nope because sha512 so the problem is that you have something not sha512 in database
