### ISSUE TITLE
 Or put the ip xx.xx.xx.xx in opennos in software  Please visual studio?

### ISSUE THREAD

**Issue by Ziratoxdu36** [OpenNos/OpenNos#1334]
Here is my problem I tried to put the ip in app.config wholesale in the truck but OpenNos.Login Imposible to me Can you help me please log?

**Comment by Ziratoxdu36** [comment]
Here is my problem I tried to put the ip in app.config wholesale in the truck but OpenNos.Login Imposible to me Can you help me please log?

**Comment by Uppermost** [comment]
Discord sever for that in the readme...

**Comment by Ziratoxdu36** [comment]
you can say more because I did not understand I'm french me: '(
