### ISSUE TITLE
Negative rarity & equip effect

### ISSUE THREAD

**Issue by SC909** [OpenNos/OpenNos#1336]
//it should be r-1 (-10 to minimal & total damage) r-2 (-20 to minimal & total damage)
https://gyazo.com/b90e52cbf06e0a323cb5b3109b42fe2e

//RARITY
//OpenNos: r0+0, r-2+10, r-1+10
equip 00 00 0.1.0.0.0 1.12.0.0.0 5.8.0.0.0
equip 10-2 00 0.1.-2.10.0 1.12.0.0.0 5.8.0.0.0
equip 10-1 00 0.1.-1.10.0 1.12.0.0.0 5.8.0.0.0

//official r0+0, r-2+0
equip 0 0 0.1.0.0.0 1.12.0.0.0 5.8.0.0.0
equip 0 -2 0.1.0.0.0 1.13.-2.0.0 5.8.0.0.0

//r-2+0, r-2+1, r-2+2, r-2+3
equip 0 -2 0.1.0.0.0 1.13.-2.0.0 5.8.0.0.0
equip 0 8 0.1.0.0.0 1.13.-2.1.0 5.8.0.0.0
equip 0 18 0.1.0.0.0 1.13.-2.2.0 5.8.0.0.0
equip 0 28 0.1.0.0.0 1.13.-2.3.0 5.8.0.0.0

https://gyazo.com/6e864a3e012b46b43bdbd46930d2a1d7

//r0+1
equip 0 10 0.1.0.0.0 1.12.0.1.0 5.8.0.0.0

//official (weapon r7+8) (armour r7+9)
equip 87 97 0.4900.7.8.0 1.4918.7.9.0 2.4490.0.0.0 3.4931.0.6.0 4.4933.0.5.0 5.4909.7.7.0 6.4940.0.0.0 7.4938.0.0.0 8.4936.0.0.0 9.4928.0.0.0 10.4129.0.0.0 11.4503.0.0.0 12.901.0.12.80 13.4248.0.0.0 14.4256.0.0.0

//official (weapon r-2+10)
equip 98 97 0.4902.-2.10.0 1.4918.7.9.0 2.4490.0.0.0 3.4931.0.6.0 4.4933.0.5.0 5.4909.7.7.0 6.4940.0.0.0 7.4938.0.0.0 8.4936.0.0.0 9.4928.0.0.0 10.4129.0.0.0 11.4503.0.0.0 12.901.0.12.80 13.4248.0.0.0 14.4256.0.0.0

So + must be _10 and then + or - rarity.
((WeaponUpgrade_10) +/- rarity)
r0+n 0 10 20 30 40 50 60 70 80 90 100
r1+n 1 11 21 31 41 51 61 71 81 91 101
r7+n 7 17 27 37 47 57 67 77 87 97 107
r-2+n -2 8 18 28 38 48 58 68 78 88 98

And I can't expalin this one
https://gyazo.com/4ecadfff4655ce2861fd08e82b02edb3
https://gyazo.com/eef6d9f208bdbdd3d711fe04337b3649

https://gyazo.com/cae3cad041cc79bc361153c157d689da

//r-1 and r0
https://gyazo.com/71127453027904bfd65f40c10ddfa2b2
//r-2 and r0
https://gyazo.com/f60a4fcfe32994823c460d605d30b6e7

//r-1 +1 +2 +3
https://gyazo.com/a76d4e7934c586c32c2c2ce5ce816464

With this one
https://gyazo.com/8e8ca37db519400e2e92cc3351708054
I think the dodge have been used as close defence as from what we can see r-2 decreases every stat by 20, and leave the rest as 0 (normally it would be 0 0 0 32)
And to let you know, those stats 0 0 0 32 or if you prefer 32 0 0 0 have changed only when I upgraded it. before it was -4 -2 -4 32

**Comment by MasterDomino** [comment]
thanks for your hard work, but please explain in detail what exactly should've been changed in your opinion

**Comment by SC909** [comment]
Negative rarity doesn't work 
r-1 = -10 min & max damage
r-2 = -20 min & max damage
with armour it would be -10/-20 to all stats except dodge similar to accuracy/speed you can see images  on previous post.

While negative stats
If the base stats are 16 18 16 32 it will be -4 -2 -4 32 when you get r-2
They made it to be 32 0 0 0 because if you try to upgrade it for example from +0 to +1 (which is +10%)
-4*1,1 = -4,4.
