### ISSUE TITLE
SSQL FOR DATABASE?

### ISSUE THREAD

**Issue by Japles** [OpenNos/OpenNos#1340]
I have to use ssql for the database?

**Comment by Ciapa1** [comment]
no you have to whip your ass

Am 27.10.2016 3:42 nachm. schrieb "Japles" <notifications@github.com>:

**Comment by Uppermost** [comment]
Seriously read the readme

**Comment by Japles** [comment]
I read, I followed all the steps, there is nothing for that error.

**Comment by Uppermost** [comment]
You can't use sql file at the latest version on mssql
