### ISSUE TITLE
Review Ban and Mute commands

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#1342]
looks like theres problem with them sometimes adminname is null and sometimes the insert adds two keys https://gyazo.com/d3f9d3613b5728e874b4105a164ac187

**Comment by aerzy** [comment]
time with mute bugued

**Comment by MasterDomino** [comment]
its not read how to use this command

**Comment by chucktheripper** [comment]
stop spamming commands, even if you lag.
