### ISSUE TITLE
Review teleporter

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1346]
Some teleporter have a problem but all is good on the packet.txt, If I use the teleporter on the other map after that I can use the teleporter for a few time and doesn't work again you can try with this teleporter on this map https://gyazo.com/8d72960730f050d27db0275be01ab854

I guess it's caused by your teleporter modification Martazza

**Comment by Uppermost** [comment]
[14:37:25] Martazza: Go on that teleport
[14:37:28] Martazza: And do $Position
[14:37:45] Martazza: it should return MapId 11, X 71, y= 5
[14:37:59] Martazza: if you do: $RemovePortal
[14:38:16] Martazza: The portal cords are x 67, Y 1
[14:38:17] Martazza: |:

**Comment by MasterDomino** [comment]
^it exactly subtracts 4 from x and y ;)

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/19890929/ebecf66a-a03d-11e6-98a6-ee2ca9a06823.png)

I also see a problem, on my packet.txt all portal are inside but why on this map this portal is not showed? maybe because two portal teleport at the same place on the map 153 to > 134 ?
