### ISSUE TITLE
I die for other people

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1347]
![image](https://cloud.githubusercontent.com/assets/15254478/19833577/20bd78c8-9e46-11e6-80e6-2b5e14470434.png)
A people die and it's me who die with all of my HP it's weird, this problem already occur on the test server with 2 people connected.

**Comment by SC909** [comment]
Try doing this will Laurena(id: 2326) and Lord Draco(id: 2034), you will have the same result and even more as Laurena was attacking the other player instead of the one that attacked her and even when she have had an aggro char1, she was attacking char2.

**Comment by Uppermost** [comment]
More information : The message is sent to the good player, but the death animation no.

**Comment by 0Lucifer0** [comment]
So that's a su packet problem we use not the for each character but the targeted one ;)

**Comment by Uppermost** [comment]
Seem's to never occur again
