### ISSUE TITLE
Inventory SP bug cause disconnection when you open it

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1349]
![image](https://cloud.githubusercontent.com/assets/15254478/19837140/bf9d8ce0-9eb3-11e6-8f4b-ead347edbe9d.png)

**Comment by chucktheripper** [comment]
Please provide more Informations on this Bug

**Comment by Uppermost** [comment]
A player have this problem but impossible to have more information, his sp inventory was empty and he can't open it whitout crash
