### ISSUE TITLE
Add additionnal HP MP (snack)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1356]
Add additionnal HP, MP, or HP + MP  (snack)

**Comment by Uppermost** [comment]
Additionnal HP packet's 

u_i 1 626114 2 40 0 0 
guri 4 800 0

eff 1 626114 203

eff 1 626114 6000

ivn 2 40.-1.0.0

When you use they snack you always receive effect 203, I don't know about the effect 6000.

**Comment by MasterDomino** [comment]
no additions for now

**Comment by Uppermost** [comment]
I don't know luci tell me 2 months ago, "Open an issue for that if you want"
