### ISSUE TITLE
Add monster fix receive damage/give

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1359]
A lot of monster like new map or boss lose always the same hp amount and stuff etc change nothing like Halloween boss, cuby new monster on map 260 We need to code it ( maybe we can find and parse they information) should be in life %

**Comment by SC909** [comment]
I noticed that in monster.dat file, but I don't know exactly about other moobs like kfc, jack o'lantern etc. as I only did look at those new monsters, for example it says 9 so it will deal 9% of damage to a player and will lose 9% each time it gets attacked but, it doesn't deal 9% of damage of player's hp but of it's own (monster's hp).

Example
6,000 HP
Deal 10% damage (to player) 600
Recive 10% damage (to monster) 600

With bosses it might be tricky like Foxy as she deals true damage and % damage
If your hp is too low even if it is 100%, she can kill you (this also applies to pets).

I will have a better look soon.

**Comment by Martazza** [comment]
It's a defense effect of a mob

http://prntscr.com/d21mk5
ST 20 2

Link do sheet
https://docs.google.com/spreadsheets/d/13S54Lm9rgvTmkYics55NqjwnmRBXMsBG37JV1xf68qA/edit?usp=sharing

**Comment by SC909** [comment]
For mobs that deal % damage and are not bosses, the data from BCard.dat will be the easiest approach.
For bosses that deal % damage, it will require more research (also looking at Skill.dat).

**Comment by Ciapa** [comment]
Is the Data already parsed?

**Comment by Uppermost** [comment]
No

**Comment by MasterDomino** [comment]
@Uppermost Because ive broke it, someone needs to fix it unless i come back

**Comment by Ciapa** [comment]
I honestly don't know if it should be implemented now, as it is part of BCard, which we probably won't finish with 1.0.4 release.

**Comment by Ciapa** [comment]
Moved to 1.0.5, maybe even 1.0.5 R2
