### ISSUE TITLE
After change map or AFK i get this 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1361]
![image](https://cloud.githubusercontent.com/assets/15254478/19936932/98e7f5fe-a11f-11e6-8202-dcaeb6a4f368.png)
And the server disconnect me whitout reasons... Even if I'm just afk for a moment 

![image](https://cloud.githubusercontent.com/assets/15254478/20041162/97dbef96-a465-11e6-94b5-e61fa9970505.png)
![image](https://cloud.githubusercontent.com/assets/15254478/20041388/834744ec-a468-11e6-94cf-ec592a568590.png)

Occur everydays if you play a lot you can have it very often (90% of the time it's when I speedhack ($Speed + Change map)

Never add this problem on the official in 7/8 years of game

**Comment by Uppermost** [comment]
Same problem when I afk and back sometime

**Comment by friends111** [comment]
I think it's from receiving 'out' packets with your ID. The text is clientside and after you click "Close", you got kicked (client logs out).
You should check your 'out' packets.

**Comment by chucktheripper** [comment]
Out packet should be unique

**Comment by SC909** [comment]
mapout does the same on official. I think it is like an exception when you don't do anything.
As friends111 said it can be out packet as well.
This message that you are going to be logged out from server doesn't appear all the time as I use mapout a lot when I log on 20 accounts on official to make points/% on act 4 flowing. With mapout I would say there is maybe 50% chance for this message to appear. I even had some of my accounts disconnected by server automatically after up to 2h, and this happened on those accounts mentioned above too.
I will have a look on the latest OpenNos.

**Comment by Uppermost** [comment]
Someone to check try out packet?

**Comment by friends111** [comment]
Definitely not 'mapout'. This message appear after receiving 'out' packet with your ID. If you click "Confirm", it logout you, but if you just CTRL+Z, the message will disappear and you won't get logout. The logout is clientside, so the server does not kick you.
It can be sometime reproduced by $Teleport'ing a lot, but idk why exactly does it happen.
