### ISSUE TITLE
Whisper blocked not complete

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1362]
On official if you block your whisper player can't sent to you a message, but it's the same for you. You can't use whisper with nobody.

**Comment by 0Lucifer0** [comment]
Since when ? Because i remember a lot of people mp me with no way to answer because locked

**Comment by Uppermost** [comment]
I don't know but I have try today because I remember that, If I block my private message I can't send anything

**Comment by Ciapa1** [comment]
Just checked, you can Whisper someone else even if you have whisper block.

**Comment by Uppermost** [comment]
Maybe on my test the player was MP blocked and I have no luck, I have retry and yeah I can mp people with blocked message sorry
