### ISSUE TITLE
Sometime player can see GM in $Invisible

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1364]
Sometime they see like SP2 archer invisible, and sometime no... The $Invisible command seem's to have a problem sometime. And see the GM talk. I guess player receive the in packet and we need to fix that
Already occur a lot of time, it's rare but it's not the first time.

**Comment by Uppermost** [comment]
Again occur today.

**Comment by SC909** [comment]
I think all players recive in packet of GM but I can not confirm it, but I don't think that official uses in packet for invisible GM when they enter a map.
You can add an exception when a chacracter is GM, is invisible and changes map to only send local in packet (to that GM)
While when GM uses a command to be invisible, GM will receive a new in packet and the rest players an out packet. But I don't think this will fix the issue as it will also require blocking all other packets like say, guri, eff etc. that are made by GM.

**Comment by MasterDomino** [comment]
i think you should ask players why they see you, it might be fixable by just not sending any packets to players that dont have IsInvisible bool as true and allowing other admins to receive it, that can add possibility for admins to see eachother and maybe pw chat :P

**Comment by Uppermost** [comment]
I cant provide information about that, just sometime they see me like a SP2 A invisible just partially invisible when I move they see me.
