### ISSUE TITLE
Server is slow, and finish to crash > World kick everyone

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1366]
I play and all don't move 

Edit : Sometime you can move but monster stop to move.

I don't know the reason but the server kick everyone
![image](https://cloud.githubusercontent.com/assets/15254478/19970679/03a2e9cc-a1dd-11e6-9e5e-fa110d2f5121.png)

**Comment by aerzy** [comment]
this error com in login when this bug in world
http://pastebin.com/DusNk4jG

**Comment by Uppermost** [comment]
Occur a lot since 2/3 days

**Comment by Uppermost** [comment]
Because i'm this week not very often on PC i write it here via Mobile.
The first way to Duplicate Items is to Spam the packet "put" but the Duplication is not the only what it does you can crash the server with that because if you do it with buy/put you drop something like 1k items/s and after some seconds server get laggy and all get kick and to 95% server needs to be restarted. To fix it make a easy delay of 1 seconds a normal user can use the "put" only 1time per second so if its faster just ignore the packet and server dont need to care about it.

The problem is here.

**Comment by Uppermost** [comment]
I have an analysis performance test for that ask me on skype to have it

**Comment by chucktheripper** [comment]
caused by VPS, not by opennos
