### ISSUE TITLE
problem with open

### ISSUE THREAD

**Issue by Nico678** [OpenNos/OpenNos#1369]
![problem](https://cloud.githubusercontent.com/assets/23260981/20007337/100dab92-a29c-11e6-89bf-77336aa7773c.png)
![problem-](https://cloud.githubusercontent.com/assets/23260981/20007339/14822e96-a29c-11e6-89a6-49124336d3f7.png)

**Comment by Uppermost** [comment]
Download style copy 4.7 and install it :)
