### ISSUE TITLE
Act IV Drop Bug

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1371]
Example: I receive a single potion instead of 3

**Comment by Uppermost** [comment]
Give more detals please what item need to be x3 ? it's the same on official?

**Comment by BelminBIH** [comment]
On the one Official RECEIVE 3 potions and server there mark "Object received x3" and when I look at the inventory I had only one

**Comment by BelminBIH** [comment]
On the server, instead of receiving eg 2 seed power potions and 3, we get a single in the inventory

**Comment by MasterDomino** [comment]
have you tried moving the item if it shows any more of the item?
