### ISSUE TITLE
You can receive packet from other player (SendPacket)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1376]
Sometime when I change map I receive packet from other play like for example the packet for unfix item I can listen the sound of this item but how it's possible, it's a SendPacket then only the user can receive it. 
Weird, occur often

**Comment by Uppermost** [comment]
After test, when you change map you can receive some packet from others map like pidx, guri etc... at the moment of the changemap

**Comment by chucktheripper** [comment]
LowPriority Packets will be deleted on ChangeMap as they're not neccessary anymore on another map.

**Comment by Uppermost** [comment]
Same problem whitout change map? I was afk with the sound and I can listen the sound from guri packet (unfix) item, and on the code it's just a sendpacket.

**Comment by chucktheripper** [comment]
There must be somewhere a bug with Broadcast or Sendpacket
