### ISSUE TITLE
Sometime someone can be connected on your account in the same time of you

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1380]
Sometime someone can be connected on your account in the same time of you, you are disconnected but we need to block at the login : ID already use (not always I don't know how to reproduce)

**Comment by Digitalis87** [comment]
Maybe it can happend with the same way than Old Nostale Bug for duplication. 
It was possible to connect twice at the same time an account by changing accountname to Accountname or ACCOUNTNAME whene trying to disconnect.

**Comment by 0Lucifer0** [comment]
That's happen if someone restart login server thats normal

**Comment by MasterDomino** [comment]
Is it closeable then?

**Comment by chucktheripper** [comment]
You get this error if you only restart Login Server while Player is connected to the world Server. The Login Server tells the WCF to vanish all the Information about current connected Players.
