### ISSUE TITLE
Mtlist hack

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1384]
= Infinite gold + Mlist cheat

mtlist 1 10 MonsterId You drop the item at 100% luck (people report)

You can use the skill unlimited and whitout lose MP

**Comment by Uppermost** [comment]
Our mlist is broken because he should be like : mtlist <amountOfMobsInList> [3 mobId]

For example : mtlist 5 3 123 3 124 3 125 3 126 3 127

Thanks friends111 for the report !

**Comment by SC909** [comment]
mtlist <number_of_targets> <entity_type> <id>

in 3 2304 9455 126 72 2 100 100 0 0 0 -1 1 0 -1 - 0 -1 0 0 0 0 0 0 0 0
in <entity_type> <monster_id> <id> ........
