### ISSUE TITLE
Ice flowers

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1399]
Ice flowers (Act IV) do not disappear after the drop

![20161108-5-test](https://cloud.githubusercontent.com/assets/22352357/20098348/a3ef2ad8-a5b3-11e6-9556-e572b75b7692.jpg)
![20161108-6-test](https://cloud.githubusercontent.com/assets/22352357/20098355/a805258c-a5b3-11e6-9b97-0c7727655807.jpg)

**Comment by Uppermost** [comment]
Maybe we need to send the out packet after use that but on official they don't respawn at the same spot.

**Comment by MasterDomino** [comment]
not a bug, its an enchancement, because not yet coded

**Comment by Uppermost** [comment]
On official the respawn of them is random.

**Comment by MasterDomino** [comment]
but we havent coded their vanishing yet afaik

**Comment by Uppermost** [comment]
Of course it's not coded yet and it's maybe useless for 1.0.4 version (my personnal opinion) it's more for act 4 part.
