### ISSUE TITLE
Unlimited members in group

### ISSUE THREAD

**Issue by Martazza** [OpenNos/OpenNos#1403]
https://vid.me/Ury1
Step to reproduce:
Create a group of 2.
Other 2 characters send a group request to a single group member
Accept the requests
Now you can invite everyone and they will join without any error :)

Enjoy

**Comment by SC909** [comment]
On official, nothing will appear if you do the same way as above. 
The cause is because you are only checking party size when sending an invite. 
Just add when you accept the invite it will check the party size too.
