### ISSUE TITLE
Mail date in the wrong order. We need to add new message to the up by order date.

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1405]
![image](https://cloud.githubusercontent.com/assets/15254478/20119236/080355b8-a608-11e6-9875-9e35899b08b0.png)

**Comment by chucktheripper** [comment]
So order by Received Date

**Comment by MasterDomino** [comment]
the problem is client autosorts it by id it receives soo we would need to use something like id by char
