### ISSUE TITLE
Shop Item Bug

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1411]
All shops items bug

![20161109-16-suootbo](https://cloud.githubusercontent.com/assets/22352357/20145023/d4fd67ac-a69e-11e6-82b0-765b3cb95a66.jpg)
![shop lag](https://cloud.githubusercontent.com/assets/22352357/20145030/dbd17122-a69e-11e6-871a-951cdf3cd925.png)

**Comment by Uppermost** [comment]
Something is broken

**Comment by BelminBIH** [comment]
Wait xD

**Comment by chucktheripper** [comment]
Due to a bug in our Imports which has been fixed by our latest DAO architecture updates, **please re-import your Shop-ShopItem ShopSkill Data**.

**Comment by BelminBIH** [comment]
Omg ...
