### ISSUE TITLE
$CreateItem Gold kicks after dropping.

### ISSUE THREAD

**Issue by friends111** [OpenNos/OpenNos#1413]
If you use $CreateItem 1014 and then drop the gold item from your Main EQ tab, it becomes bugged and kicks users who are trying to get it (similliar to 'mve' bugged items)

**Comment by chucktheripper** [comment]
I guess Gold is not considered to be dropped thru CreateItem, maybe we need to handle it like the MonsterDrop.

**Comment by chucktheripper** [comment]
Cant we just use the same method for CreateItem and Drop?

**Comment by MasterDomino** [comment]
Drop is adding item to list of drops per map where CreateItem is adding it to your inventory

**Comment by chucktheripper** [comment]
So why should i want to do $CreateItem for Gold if there is $Gold command?

**Comment by MasterDomino** [comment]
theres gold item that gm can use to receive gold item to drop it on map but its useless in my opinion, just that we should ensure the crash doesnt happen add condition on this item to not be able to drop it, we might as well add $Drop command to drop item thats not droppable or with custom amount on the map around player

**Comment by chucktheripper** [comment]
@MasterDomino i guess it's ment to work with $Drop but not with $CreateItem and afaik is $Drop not exactly implemented like the MonsterDRop

**Comment by MasterDomino** [comment]
theres no $Drop command its just my idea to add it, and well it should be the same just with condition on if  dropping of undroppable items is allowed because its admin command
