### ISSUE TITLE
Sometime monster stop to move every 5/10 seconds or they never stop to move 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1415]
All on the tittle 
![image](https://cloud.githubusercontent.com/assets/15254478/20167410/bc47c59a-a71b-11e6-8d60-6336cc809ab0.png)

I don't know if this error is linked, maybe was just a problem on the VPS I don't know

(After AutoMapper update)

**Comment by chucktheripper** [comment]
the error says that the DB cannot be reached

**Comment by chucktheripper** [comment]
This could be caused by restarting the SQL Server while running the server

**Comment by Uppermost** [comment]
Good to know
