### ISSUE TITLE
Review drop rate + review a little bit this system

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1417]
I need to review all chance % and the gold chance to drop seem's to be to much high.

Act 1 Statut : Done
Act 2 Statut : Done
Act 3 Statut : Done
Act 3.2 Statut : Done
Act 4 Statut : Done
Act 5 Statut : Done
Act 5.2 Statut : Done
Act 6 Statut : Done

@MasterDomino or @Martazza , someone remove the limit of item can be at the ground it was 3 maximum by monster please add it again, drop spot (X-Y) seem's to be weird.

Search it on the code, but seem's to be here, then it doesn't work.
if (rndamount <= ((double)drop.DropChance * RateDrop) / 5000.000)

**Comment by Uppermost** [comment]
Just need to add the limit of item can be drop on one monster (3)

**Comment by MasterDomino** [comment]
limit is already here

**Comment by Uppermost** [comment]
Then I close it
