### ISSUE TITLE
SP equipment failure. 

### ISSUE THREAD

**Issue by AzogDE** [OpenNos/OpenNos#1419]
If I try to SP from SP Inventory and there is a slot without SP between 2 SPs there SP after it will not be equiped. 

https://gyazo.com/44f327f122dfbd58c16e805597f82bfb

Reason:  

u_i 1 50371 6 **1** 0 0
u_i 1 50371 6 **5** 0 0
u_i 1 50371 6 **0** 0 0
u_i 1 50371 6 **1** 0 0
u_i 1 50371 6 **2** 0 0
u_i 1 50371 6 **3** 0 0
u_i 1 50371 6 **5** 0 0

The first Slot is numbered 0. So u_i 1 50371 6 0 0 0
The second numbered 1  So u_i 1 50371 6 1 0 0
And the point is, he tries to equip Slot Number 6 (num 5) while Slot 5 (Num 4) is empty. 

After I filled the empty slot with a SP the SP didnt filled it, it replaced the Deathbringer and left the Slot empty. After closing the inv and opening it again all was fine.

**Comment by AzogDE** [comment]
Actually after equping the Monk and reloading the inv, he disappeared.

https://gyazo.com/1b6a1f9697d60b88fa06b22c431bdc2b

He doesnt fill the empty slot. The Monk was there invisble.
After moving the sp8 out (where the space was before) i crashed

sortopen
mve 0 4 6 4
pulse 1620 0
npinfo 0
sc_p_cts
pulse 1680 0
u_i 1 50371 6 5 0 0
npinfo 0
remove 12 0
sc_p_cts
mve 0 4 6 4
sortopen
u_i 1 50371 6 5 0 0
walk 67 94 0 11
sortopen
pulse 1740 0
npinfo 0
sortopen
remove 12 0
sc_p_cts
wear 4 0
sortopen
mve 6 6 0 4
csp_e
c_close 
f_stash_end 

After Relogg everything was fine. 
Its just buggy with stacking and filling empty slots.

**Comment by AzogDE** [comment]
Got it finally. You have to watch the Invetory reloading/filling progress.

https://youtu.be/Tnu_iHc5PKI

**Comment by Uppermost** [comment]
Just requiere item problem :)

**Comment by chucktheripper** [comment]
Thanks for the report, i'll have a look at it
