### ISSUE TITLE
Sp pirat can be upgrade

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1421]
I tried with scroll, and the my pirat SP is +0 I try to up it to +1 and it doesn't work. It show me "You don't have theirs items to upgrade" But I have all of them.

**Comment by AzogDE** [comment]
Maybe just relogg.

Someone got to Upgrade the Pirat. Maybe wrong scroll?

https://gyazo.com/c6f815b40d282fbb8f1e397da68ec89f

**Comment by Uppermost** [comment]
All items are ok and blue scroll.

**Comment by AzogDE** [comment]
I really dont know what the problem is.

https://youtu.be/7_cUJmBCD0Q

**Comment by Uppermost** [comment]
Amount of item necessary is the problem.
