### ISSUE TITLE
Pii bug.

### ISSUE THREAD

**Issue by AzogDE** [OpenNos/OpenNos#1422]
Well it doesnt Spawn mini piis.

https://gyazo.com/60c9127f3228c4f5a5ea4f7f2b544564

**Comment by Uppermost** [comment]
Not a bug, pii spawn is a buff.

**Comment by Mistero5050** [comment]
What does that mean? It's still a bug, it should be open. or you should at least link the open one

**Comment by 0Lucifer0** [comment]
This mean that it was a buff and the buff system wasn’t implemented when the issue was opened.

**Comment by Mistero5050** [comment]
And now it is? Pii doesn't spawn after killing plants on the server I am playing

**Comment by 0Lucifer0** [comment]
Depends on the version they use and if they correctly parse the bcards but yes it works fine.

**Comment by Mistero5050** [comment]
And which version does it require? Thanks :)

**Comment by BlowaXD** [comment]
The latest.

**Comment by Mistero5050** [comment]
So it's been introduced recently this feature?

**Comment by BlowaXD** [comment]
It has been fixed recently due to someone that broke the types/subtypes in parsing.
Anyway, here it's an issue, not a support channel if you can't get it work.
There are Epvpers and Discord for that.
