### ISSUE TITLE
SP Point Card in Inv.

### ISSUE THREAD

**Issue by AzogDE** [OpenNos/OpenNos#1423]
Usually you drop this card and get instantly +1000 Sp Points.
If your inventory is full, you get it in mail and own it in Inventory.

https://gyazo.com/0e34145853d697c1186e59c42f936b3e

You can't use it, you can drop it afterwards outta inventory and catch it up again and dont gain any points.

**Comment by SC909** [comment]
Justvadd that if you pick up that item it will increase basic sp points by a 1,000 but it will never go above 10,000.
Like if (basicSpPoints + 1000 => 10000)
basicSpPoints = 10000

**Comment by 0Lucifer0** [comment]
Already an issue about the point système
