### ISSUE TITLE
New mount item missing

### ISSUE THREAD

**Issue by Xarenii** [OpenNos/OpenNos#1425]
https://gyazo.com/4856dcc22fffdbb9ab0c7a87330dc197

**Comment by Uppermost** [comment]
Which item id?

**Comment by Xarenii** [comment]
9076

**Comment by Uppermost** [comment]
Not implemented yet then, I will add them when I can

**Comment by friends111** [comment]
9076 isn't the right ID. 8k+ IDs are event-like item duplicates. Real Nossi ID is 5196, which do work.

**Comment by MasterDomino** [comment]
they want everything working soo also event items should work

**Comment by Uppermost** [comment]
I do it now
