### ISSUE TITLE
MonsterLifeManager

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1429]
![monstermaplag](https://cloud.githubusercontent.com/assets/22352357/20222741/ca90d35a-a836-11e6-9a74-bc10ef36a09e.png)

**Comment by chucktheripper** [comment]
@BelminBIH When did this problem happen and by any chance with $AddMonster or $Summon?

**Comment by BelminBIH** [comment]
With $Summon

**Comment by chucktheripper** [comment]
@BelminBIH Please get the latest version, this bug has already been fixed.

**Comment by BelminBIH** [comment]
@chucktheripper Ok sorry
