### ISSUE TITLE
Put packet can cause duplication

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1430]
<<to Duplicate Items is to Spam the packet "put" but the Duplication is not the only what it does you can crash the server with that because if you do it with buy/put you drop something like 1k items/s and after some seconds server get laggy and all get kick and to 95% server needs to be restarted. To fix it make a easy delay of 1 seconds a normal user can use the "put" only 1time per second so if its faster just ignore the packet and server dont need to care about it.>>

Team know what we need to do for that

Thanks xSensitive.

**Comment by chucktheripper** [comment]
Maybe we should implement something like a using scope for inventory and lock it for any interaction.

**Comment by chucktheripper** [comment]
lock() the Session.Character.Inventory until the adding / removing / moving operations have been finished
