### ISSUE TITLE
Shout = Crash

### ISSUE THREAD

**Issue by AzogDE** [OpenNos/OpenNos#1432]
While Shouting the Worldserver crashed.

**Comment by Uppermost** [comment]
Wrong, all work fine on the latest version.

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/20226301/dfd3268a-a847-11e6-92f0-e0042a5fb571.png)

**Comment by BelminBIH** [comment]
XDDDDDD "AAAAAAAAAAAAAAAAAAAAAAAA"
