### ISSUE TITLE
Dupe 255 Stacks

### ISSUE THREAD

**Issue by AzogDE** [OpenNos/OpenNos#1433]
Steps to Dupe.
(Works only with Cella as far as we know).

- You Trade with somebody
- Put Amount of 17 of any item into the trade. Next to it Amount 50 of Cella and next to it Amount 1 of Cella.
**IMPORTANT** The 17|50|1 Stacks must be splitted before trading.
The Number 17 and 1 are important.
-Finish the Trade.

**NOW IMPORTANT**
- You have to Log out completly outta server. **FAST!!**
-If you were fast enough you got a 255 Stack of Cella.

Greetings!

https://youtu.be/OyO1hffh5nE

**Comment by chucktheripper** [comment]
Trade is absolutely Buggy atm, after my Review tomorrow it should work again ;)

**Comment by chucktheripper** [comment]
even with emulated lags, i cant reproduce it, maybe it depends on the items in your inventory

**Comment by Uppermost** [comment]
Try with cella

**Comment by friends111** [comment]
It does work, I tested it with my friend and we got a 205 (not 255) stack of Cylloan Water, event Gum emote and Cella.
He was giving me 17|50|1, and after accepting trade i $Kick'ed myself and he got 205 and i got 68 (17+50+1).

**Comment by chucktheripper** [comment]
@friends111 Maybe i need some tcp ip lag to reproduce that ;)

**Comment by AzogDE** [comment]
Its important to relogg fast.

**Comment by chucktheripper** [comment]
@AzogDE I tried with Alt+F4 neraly immedeately

**Comment by AzogDE** [comment]
Naaah.. you have to logout by entering channelmenue and then logout completly and rejoing by logging in with ID and Pw ingame. You got kinda 10 seconds.

**Comment by chucktheripper** [comment]
@AzogDE We will reproduce this together, thank you ;)

**Comment by AzogDE** [comment]
NP :) Join FagTale if you wanna or PM

**Comment by chucktheripper** [comment]
Please write me on skype: aleqs92

**Comment by Uppermost** [comment]
Problem occur again. FagTale upload a video to show us how to do it.

**Comment by xKaddo** [comment]
https://www.youtube.com/watch?v=JESK7keGUAo&feature=youtu.be

Still working. Exactly as shown in the video.

**Comment by MasterDomino** [comment]
cant reproduce it on localhost

**Comment by chucktheripper** [comment]
Please test it with the latest Version ;)

**Comment by AzogDE** [comment]
You need to put high traffic on the server, remember chuck? :D

**Comment by Uppermost** [comment]
The part of code is rewrite, just retry please

**Comment by xKaddo** [comment]
Still works on fagtale.

**Comment by chucktheripper** [comment]
Reproducable means Reproducable for a Developer on localhost, exactly.
