### ISSUE TITLE
R7 = R8 = Fail but success 

### ISSUE THREAD

**Issue by AzogDE** [OpenNos/OpenNos#1435]
If you bet Hero equipment.. it says **Green font** Upgraded to Rare: 7 Next Line: **Red font** Betting was a fail.

What does the Equipment say? Rare 8.

http://puu.sh/seW8Y/c469018378.jpg

**Comment by Uppermost** [comment]
R8 don't need to be available to NPC. On official you CAN'T upgrade a weapon R8 on NPC. You can only if the weapon is heroic. Then the max rarity upgrade on npc should be for the moment R7. For the next yeah there is a displaying bug then

**Comment by AzogDE** [comment]
Its upgrading by a scroll not by npc.

I tested it. I created a H25 Sword 0+0 and when it says R7 you get R8.
