### ISSUE TITLE
Heroeq Gold.

### ISSUE THREAD

**Issue by AzogDE** [OpenNos/OpenNos#1436]
You need for ex. 5kk for upgrading herosword and for same upgradelevel on norm. eq. 500k.

If you upgrade hero eq. you'll lose 500k instead of 5kk.

**Comment by Uppermost** [comment]
It's not implemented now If I'm right, We need to add it

**Comment by AzogDE** [comment]
Its a feature of a game. Who wants to use hero equip with high upgrade should pay more :P
