### ISSUE TITLE
If you use vehicle when you create private shop, when you close it you can't move

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1440]
If you use vehicle when you create private shop, when you close it you can't move

**Comment by Uppermost** [comment]
It's not fixed :/

**Comment by friends111** [comment]
Not tested, but maybe it's because of that shop makes you "stunned" in cond packet?

**Comment by Uppermost** [comment]
No because when I use $Speed command I can move :)

**Comment by chucktheripper** [comment]
@Uppermost Replace IsSitting = false with LoadSpeed in Character.CloseShop

**Comment by Uppermost** [comment]
This issue is not fix.

**Comment by Uppermost** [comment]
cond 1 3864 0 0 0

As you can see the speed is 0 on this cond packet from opennos. Should be load the character currently speed.

**Comment by MasterDomino** [comment]
it is fixed ive tested it and it didnt occur for me can you tell me what different you do, are you testing it localhost?

**Comment by chucktheripper** [comment]
https://gyazo.com/ccb630cf546eb1eb292f0feba14822b2

**Comment by chucktheripper** [comment]
With vehicled Magic Scooter where Speed is 20

shop 1 1 1 3 0 Test Shop 
info Shop has been opened
cond 1 1 0 0 0
rest 1 1 1
shop 1 1 0 0
cond 1 1 0 0 0
rest 1 1 0
shop_end 0
cond 1 1 0 0 20
