### ISSUE TITLE
Mapbug

### ISSUE THREAD

**Issue by AzogDE** [OpenNos/OpenNos#1442]
After beeing 30 min invisible I came back and Tped to old nosville. Mapname changed but graphic the same.

Can't tp anymore.

Relogg = Whole map purple.

**Comment by MasterDomino** [comment]
wrong ss :'D

**Comment by AzogDE** [comment]
Hups xD
Well Screen failed. But u should know what I mean :P

**Comment by chucktheripper** [comment]
Are you able to reproduce this?

**Comment by Uppermost** [comment]
Never had this poblem. It's a problem inside your client.

**Comment by Uppermost** [comment]
Close no other information and never occur for us
