### ISSUE TITLE
Monster are despawning

### ISSUE THREAD

**Issue by AzogDE** [OpenNos/OpenNos#1445]
After Serverrestart on a few Maps the monsters just got deleted.

**Comment by Uppermost** [comment]
Seem's to be just impossible WTF, I never see that again ><

**Comment by MasterDomino** [comment]
with server restart you mean reparsing of all data?
or just casual shutdown and start of executable?

**Comment by Uppermost** [comment]
When the server is restart all summon monster dissapear but it's the only way to remove them.
