### ISSUE TITLE
Remove Xp & Drop on $Summon

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1448]
We need to remove the XP & the Drop on $Summon.

**Comment by MasterDomino** [comment]
its useless why would you summon monsters in the first place then?

**Comment by Uppermost** [comment]
Because when GM summon monster it's like for event, or something like that. They can use $AddMonster if they want to keep it. For the moment if ou summon a lot of play of monster player can up level etc and it's a suggestion from @friends111 I'm not alone to think it's good

**Comment by SC909** [comment]
I don't know about official as I can remember that you can get items and xp but they might have changed it but I don't think so, but I think you should be able to get xp and items from summoned mobs.

**Comment by Uppermost** [comment]
It's very bad for private server you can't do an event whitout have 5000 items on the ground at 5000 player up level for me, friends111, Blowa & Kevin it's bad

**Comment by MasterDomino** [comment]
the problem here is theres 50/50 ppl that want it or not, because we dont support private servers as you can read in our readme, summoning with drops is useful for debugging

**Comment by SC909** [comment]
For those who want it you should make it possible to turn it on and off

**Comment by MasterDomino** [comment]
good idea for now we want to focus on bugfixing as adding next enchancements is kindof making the code more unstable, also SC909 have you joined our Discord server already? ive wanted to talk with you about those algos but didnt saw you :/
