### ISSUE TITLE
Review True XP Algorithm

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#1451]
our true xp algorithm seems off:
http://pastebin.com/cpB6ebK2
other guy that got values from official:
http://pastebin.com/eXgzbeKC
his job seems pretty accurate

**Comment by 0Lucifer0** [comment]
No our is good i had a 99

**Comment by 0Lucifer0** [comment]
Ah no it seems Someone touch our algoritm because the 2nd pastbin is correct

**Comment by MasterDomino** [comment]
then explain that:
3C 2J         | 3              | lev 3 1560 2 680 1800 2900 0 4 0 0 3 <- official
our 3rd lvl:
lvl 3:1500
and his : 
3 1800

**Comment by SC909** [comment]
There is a formula for it, I will get it for you from someone who have it

**Comment by MasterDomino** [comment]
the problem is noone touched our formula and its wrong if you do have better formula it would be great because myself i dont have trust to current one

**Comment by 0Lucifer0** [comment]
Our algoritm was working before so perhaps we miss a ()

**Comment by MasterDomino** [comment]
look @0Lucifer0 we have 2 basic values used in algo which are lvl 1 and 2 in orded
```csharp
            v[0] = 540;
            v[1] = 960;
```
and thats log 
```
lvl 1:540
lvl 2:960
```
which means that 2 basic values was wrong from the beginning

**Comment by 0Lucifer0** [comment]
Basic is for lvl 0 if i remember

**Comment by MasterDomino** [comment]
then it even worse xD when official has it base as 300 for lvl 1

**Comment by 0Lucifer0** [comment]
Are you sûre ? I get values from Packet

**Comment by MasterDomino** [comment]
the problem is you confirmed 2nd pastebin is correct when first is actually log of our code, it means were missing something in xpload, if actually theres better algo i would consider using it instead because like now it will be painful for me to finish coding the xp dependant algo

**Comment by MasterDomino** [comment]
okay small correct ive used v instead of xpData thats why there was such a big difference but looks like theres difference on higher levels, im still not sure about validity of this but i will work on it

**Comment by SC909** [comment]
http://board.pl.nostale.gameforge.com/board216-pomoc-pytania-i-pierwsze-kroki/board439-noswiki/board441-gra/111983-do-dodania-zdobywanie-do%C5%9Bwiadczenia-wzory-i-liczby/

But level 97 98 and 99 has 750 instead of 650 
120x((Level+1)^2)*750/6

To find out how much you need for level 10, you have to add all up from level 1 to level 10.

**Comment by SC909** [comment]
sp job between 1-?? gets *10 job.
