### ISSUE TITLE
Command '$Speed' - See Effect

### ISSUE THREAD

**Issue by Xarenii** [OpenNos/OpenNos#1454]
https://gyazo.com/42798fe27402644893faf63e4b0f8fbf

**Comment by MasterDomino** [comment]
youve added custom effect on speed command usage but why for? explain your issue always provide description and issues are here to provide authors with found bugs

**Comment by Xarenii** [comment]
![image](https://cloud.githubusercontent.com/assets/23105262/20248351/9e6d8130-a9e2-11e6-95d1-a242f1fa64c0.png)

What? Where I have something added?.. please xD

**Comment by Uppermost** [comment]
True but it's not $Speed, it's just when you tried to move when you are sitdown.
