### ISSUE TITLE
Reputation wrong refresh

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1458]
https://gyazo.com/d78edc2f52397a828e1c38a60638214e

The only way to refresh is disconnect/reconnect

**Comment by Uppermost** [comment]
Strange work sometime, and sometime no :/ I need your opinion guys if we reopen it or no. It's maybe just the client I don't know

**Comment by Zeshyu** [comment]
@Uppermost
it cant be the client because on Official it refreshes as soon as ur repuptation changes.
So its @ the Code obviously.

**Comment by friends111** [comment]
On official, when your reputation change, other people won't see your it updated under your character name, unless they changed map.
