### ISSUE TITLE
Disconnect (Serverkick) after Upgrading to the Max

### ISSUE THREAD

**Issue by vanela** [OpenNos/OpenNos#1459]
Hey there.
If I try to Upgrade Gloves or Shoes up to 6 and its a Success i become a Serverkick. Same with SPs.
Below Max Grade there are no Issues. Up to +14 SP is no Problem and works perfect. You also dont disconnect if you Fail the Upgrade (so its still +14).

How it happened:
1. Upgrading Gloves
2. As soon as you see the "Success" Screen (not even a second) you disconnect from the Server. (so you are at Login-Screen again)
3. Same for SPs

I guess Screens are not needed. Dont know what to screen there ^^
Greets, Vanela

- [x] Sum 

- [ ] Sp upgrade

- [x] Equipment upgrade

- [x] Stone upgrade

**Comment by Uppermost** [comment]
Thanks for the report we will check that
