### ISSUE TITLE
GM chat need little review after change official packet

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1461]
https://gyazo.com/27bdb7df00567434ef7ce4a2e33332f7
- [ ] As you can see the name is not keep, GM is cosiderer like a name should be saved to not rewrite it everytime

- [ ] And also, you can use /Admin or /GM Admin. Only /GM Admin should be work, not these two choose

**Comment by BlowaXD** [comment]
Actually, I think we should keep the fact that you can pm /Admin or /GM Admin (it doesn't change anything and it's simplier for users)

**Comment by 0Lucifer0** [comment]
I agree with Blowa and first problem is clientside
