### ISSUE TITLE
long basic attack range

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#1464]
https://gyazo.com/2f21a1d4a8a8953a578138d0da0bfc59

u_s 0 3 513475

I'm not sure, maybe it is also due to the database configuration (FaqTale)

**Comment by Uppermost** [comment]
Because FagTale is not up to date, this bug was caused by bad grid but it's fix now.

**Comment by SoraPlays** [comment]
I think the bug still exit.
(They should be on the latest version)

**Comment by MasterDomino** [comment]
can you send us confimation of its existence?

**Comment by Uppermost** [comment]
Their server are not up to date I'm sure

**Comment by Uppermost** [comment]
Edit : Their server are not updated...
