### ISSUE TITLE
switch from nu-get EpPathFinding to its project

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#1467]
as project allows us to optimize it to some extent its a discussable idea but lets consider it

**Comment by chucktheripper** [comment]
i always prefer nuget

**Comment by MasterDomino** [comment]
nuget doesnt allow us to edit package but if we would to switch to project it would allow us to edit it as @Martazza already suggested:
```because in this way we can convert X,Y maps cords
to short and we can use a byte WalkableZone type instead of boolean```

**Comment by 0Lucifer0** [comment]
Nuget is better

**Comment by MasterDomino** [comment]
please give a valid point why it is better ;-;

**Comment by 0Lucifer0** [comment]
Because there is no reason for us to change it...

**Comment by Uppermost** [comment]
All wok fine for the moment focus on finish 1.0.4 is maybe most important for now

**Comment by MasterDomino** [comment]
now because of our need to handle multiple zone types we need to switch to project because it will be a lot more performant that checking by bool if zone is walkable (theres more than 11 zone types)
