### ISSUE TITLE
Honorable Equip

### ISSUE THREAD

**Issue by SasukeTale** [OpenNos/OpenNos#1468]
Its doesnt show that the Equip is Honorable in the Info

Its not like Legendary Honorable +10
Only Legendary +10

**Comment by Uppermost** [comment]
Ah yeah I know what you mean, on right click we need to add the information if the equipment is honorable and if yes Legendary Honorable : +10

**Comment by MasterDomino** [comment]
can you get me e_info for honorable eq, and possibly same eq thats not honorable

**Comment by Martazza** [comment]
![image](https://cloud.githubusercontent.com/assets/17277512/20346929/04593aca-abff-11e6-8439-ff11cc6be837.png)
Update your client

**Comment by SasukeTale** [comment]
https://gyazo.com/6a3adb0546e6ec8d528edd79ab9f888a

...
