### ISSUE TITLE
ArenaWinner is enable when you use $Invisible / Still visible 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1472]
After use $Invisble you have the ArenaWinner effect we need to remove it

**Comment by Uppermost** [comment]
caused by the cl packet but if we remove this line we will not be "totaly inivisble"

**Comment by chucktheripper** [comment]
This seems to be client side and it vanishes after you change map, but maybe we can remove it simly (we do not add it explicitely, i checked that)
