### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by SasukeTale** [OpenNos/OpenNos#1473]
https://gyazo.com/834372fbde8b40c29327cefc94bbe7f4

Farmed 1, got 2

**Comment by Uppermost** [comment]
This link doesn't work please provide more information or an other link

**Comment by SasukeTale** [comment]
https://gyazo.com/834372fbde8b40c29327cefc94bbe7f4

**Comment by Uppermost** [comment]
Impossible for me to reproduce it at the latest version

**Comment by AzogDE** [comment]
Maybe cause of traffic the server didnt checked the value or kinda this problem.

**Comment by chucktheripper** [comment]
We will add a lock on get, so noone can access the inventory when currently getting the item.

**Comment by AzogDE** [comment]
But this wouldnt fix the dupe with x255

**Comment by chucktheripper** [comment]
The dupe bug should be fixed in the current version

**Comment by chucktheripper** [comment]
(255x dupe i mean)

**Comment by AzogDE** [comment]
Alright. :) Mind tell me the issue for producing that?
