### ISSUE TITLE
Uprates for R8

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1475]
In the new source there are different uprates and different costs for R8 weapons.
I'm confused. It says something like (line 508 in WearableInstance.cs):
if (this.Rare == 8) ....
People could cheat around that, if they first upgrade their weapon to +10 and then rare it to 8, making it cost way less gold.

Shouldn't it be:
if (this.Item.IsHeroic) ?

Just a bit confusing, don't know if it is intended like that.

**Comment by MasterDomino** [comment]
The problem is rates are clientsided sooo theyre not displayed for r7 and below like they are for r8, idk why entwell wanted to make it work like that
