### ISSUE TITLE
Authority System

### ISSUE THREAD

**Issue by SasukeTale** [OpenNos/OpenNos#1476]
Maybe you can create a new System, like Authority 0-3

0 User
1 Gamemaster
2 Super Gamemaster
3 Admin

So you can define in the Script who can use which commands, and not everybody the same Admin Commands.

**Comment by chucktheripper** [comment]
@SasukeTale The Authority is directly mapped to the outgoing packets, so that's why i dont support this idea.

**Comment by SasukeTale** [comment]
So its not even possible?

**Comment by chucktheripper** [comment]
@SasukeTale What's the benefit of Super Gamemaster and what should he be able to do beside Gamemaster?

**Comment by chucktheripper** [comment]
@chucktheripper So actually whats the difference between Gamemaster, Super Gamemaster and Admin?

**Comment by SasukeTale** [comment]
Like $Shutdown but not $Promote and $Demote
GM only the normal things $CreateItem $Teleport etc.

**Comment by chucktheripper** [comment]
@SasukeTale Thats actually not a bad idea but maybe it should be stored in a different Value than Authority, Authority is more for the Visibility and stuff. Maybe we could add something like Right or SubAuthority (with actually better naming)

**Comment by SasukeTale** [comment]
Yes that would be great!

**Comment by MasterDomino** [comment]
For now lets plan at which milestone, and for next time use our discord for suggestions ;)

**Comment by chucktheripper** [comment]
Future TODO:
- Create Enum with types Gamemaster, Super Gamemaster, Administrator called **Permission**
- Add a new Property for Character called Permission of type **Enum Permission**
- Create restrictions based on the Permission the Character got
- Create methods to Grant Permission
