### ISSUE TITLE
Group Bug

### ISSUE THREAD

**Issue by SasukeTale** [OpenNos/OpenNos#1479]
Hey,

if I get invited in a group, I am still leader if I accept x:

https://gyazo.com/337bc720183dc2ebf7c376702c0044f0
https://gyazo.com/7744546f515fb60950b264ccef21db66

**Comment by chucktheripper** [comment]
@SasukeTale The GroupJoin method needs to be checked if the Admin is set to the correct ClientSession

**Comment by Uppermost** [comment]
Crash : https://cdn.discordapp.com/attachments/231774497340915712/248587328904232960/unknown.png

**Comment by chucktheripper** [comment]
Im not sure with which Version you are testing, but in the latest Version the leader is set correct.
