### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SasukeTale** [OpenNos/OpenNos#1480]
https://gyazo.com/109e90c125cd37366b41cc25bc711910

Latest OpenNos Files

**Comment by chucktheripper** [comment]
@SasukeTale Please add the complete error message, see in the Log

**Comment by SasukeTale** [comment]
Where can I find the Log?

**Comment by chucktheripper** [comment]
@SasukeTale Just search for Log inside your output directory

**Comment by SasukeTale** [comment]
Cant find the log but it keeps crashin..

**Comment by chucktheripper** [comment]
@SasukeTale Then just Copy the error message from the console to the issue

**Comment by SasukeTale** [comment]
$Undercover crashes the Client.

**Comment by SasukeTale** [comment]
If it crashes again

**Comment by chucktheripper** [comment]
@SasukeTale Okay, we'll fix the $Undercover command, is there anything else which causes a crash with AddInventory?

**Comment by SasukeTale** [comment]
https://gyazo.com/2e927b881cfe34fadedca8bcd1483983

**Comment by SasukeTale** [comment]
https://gyazo.com/fcb84a40670fbb76e68dd1840ca913ea

**Comment by chucktheripper** [comment]
@SasukeTale Why dont you just Copy and Paste the error message from the Console ? Mark and Rightclick and Insert it!

**Comment by SasukeTale** [comment]
Okay

**Comment by SasukeTale** [comment]
Server is stable now without Undercover GMs :/

**Comment by MasterDomino** [comment]
this should not occur i will rework the command using boolean propably :/
