### ISSUE TITLE
$AddMonster

### ISSUE THREAD

**Issue by SasukeTale** [OpenNos/OpenNos#1484]
$AddMonster doesnt work sometimes.

**Comment by Uppermost** [comment]
Please provide more information it's hard if you don't tell us when exactly it doesn't work etc whitout screen and any information etc

**Comment by SasukeTale** [comment]
https://gyazo.com/83de14de33dca4f0b0aab90acf52fb06

**Comment by Uppermost** [comment]
Try whitout invisibility.

**Comment by SasukeTale** [comment]
It works sometimes, but sometimes it doesnt work https://gyazo.com/69e4399d25ce956da93b15d834df28d1

**Comment by MasterDomino** [comment]
check log please

**Comment by MasterDomino** [comment]
caused by undercover
