### ISSUE TITLE
$Gift

### ISSUE THREAD

**Issue by SasukeTale** [OpenNos/OpenNos#1485]
Hey guys, 

maybe I am annoying with my reports but I just want to improve ON so:

If you send a Gift with wrong ItemID you get kicked out.

**Comment by MasterDomino** [comment]
what exactly do you mean with wrong ItemID

**Comment by SasukeTale** [comment]
https://gyazo.com/0078383b39054538876f839575233f7a

**Comment by SasukeTale** [comment]
An Item thats not in the DB somehow

**Comment by MasterDomino** [comment]
thats really weird it should never exist are you on latest version?

**Comment by SasukeTale** [comment]
Yes

**Comment by SasukeTale** [comment]
https://gyazo.com/11e9117c6ed4bd4b4795af04bd169f33
