### ISSUE TITLE
Grid doesn't work fine, monster can go out the map.

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1489]
https://gyazo.com/8e902c29c11ba8206dffa66f7ecdff9a

All on the title. this problem was already fixed but come again

https://gyazo.com/984cff983cae208cecabc8d86ea4845a

**Comment by Uppermost** [comment]
Need to be fix asap

**Comment by Uppermost** [comment]
@Marty please check that and remove your change if it doesn't fine because grid is very fuck up now

**Comment by Uppermost** [comment]
https://github.com/OpenNos/OpenNos/commit/be8293cf1e1e131effb93f7e89fe3ce0143221ee

Maybe this commit cause the problem but if we revert it we lose a fix with bad grid position :/

**Comment by chucktheripper** [comment]
@Uppermost Maybe, but let @Martazza decide, because he did it.

**Comment by 0Lucifer0** [comment]
Thats the problem the 2 isnt walkable its 0= walkable Else not...
