### ISSUE TITLE
Gold rate need to be lower

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1491]
We need to change it on 25 monsters drop 22x (Map 47) it's wrong

OpenNos 25 monsters 22 drop
Official 25 monsters 3 drops

On forum people said the gold % is 10%~ with monster with a similar level of you
For the moment on opennos it's like 90-95%

**Comment by Uppermost** [comment]
We need an other way then for the rate drop. We need to have maximum 15% of chance to have gold on monster.

**Comment by MasterDomino** [comment]
we need to split drop chance with gold amound drop algo

**Comment by MasterDomino** [comment]
added to #692
