### ISSUE TITLE
Sometime drop item doesn't work.

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1492]
After kill some monster on the map, drop stop to working whitout reason. I mean nothing item on the ground please check it, it doesn't occur everytime

**Comment by Uppermost** [comment]
@chucktheripper for you that

**Comment by chucktheripper** [comment]
If there is no item, there was no drop ?!

**Comment by chucktheripper** [comment]
If you kill 1000 Mobs at once, you just have been unlucky, because we calculate this stuff by normal random which is defined by current System time
