### ISSUE TITLE
Recipe

### ISSUE THREAD

**Issue by SasukeTale** [OpenNos/OpenNos#1495]
Hey,

Recipe uses Weapon Slot and not your RecipeItem you used for it oO

https://gyazo.com/d959e2d1397d31a586fe705f1f19220a
https://gyazo.com/4d0f364484f50e461e9fcfba3042e2bc

**Comment by chucktheripper** [comment]
We need to take a look at the item crafting and if it correctly removes items

**Comment by Uppermost** [comment]
Seem's to be caused only if you use item in equipement inventory for a craft

**Comment by 0Lucifer0** [comment]
in fact that's because you've tried to make something that is impossible on official.

**Comment by Ciapa** [comment]
Recipes with Equip have to use other type for equipment. It is possible, you just failed miserably
