### ISSUE TITLE
Private shop, You didn't see the shop when you change map.

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1496]
![image](https://cloud.githubusercontent.com/assets/15254478/20399400/29aa7058-acf1-11e6-8d0c-67a36b7123f5.png)

I see only if I'm on the map when the player open his shop.

**Comment by chucktheripper** [comment]
this works.

**Comment by Uppermost** [comment]
FagTale on the latest version said the same things It doesn't work. I can reproduce it on local you will see with me in debug chuck

**Comment by Uppermost** [comment]
The problem is, after change map the shop packet receive don't have the good player ID then I can't work and 2st mistale the plag need to be like that pflag 1 <CharId> 501 The latest value is always 501

**Comment by chucktheripper** [comment]
Whats 501? Does anyone know?

**Comment by chucktheripper** [comment]
@Uppermost, Please test and Close if fixed
