### ISSUE TITLE
User has blocked trade ask

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1497]
![image](https://cloud.githubusercontent.com/assets/15254478/20399519/9efc1f32-acf1-11e6-964c-c915ca7e5618.png)

It show me "Player has blocked exchange" but it's true I don't know if it's caused by that but after close my private shop this problem is occur.

**Comment by friends111** [comment]
Are you sure it's not you blocking the trade? I think the message is the same, which is confusing.

**Comment by Uppermost** [comment]
100% this option was disable.

**Comment by chucktheripper** [comment]
We also can add different message, it doesnt matter

**Comment by chucktheripper** [comment]
Everything works fine
- Create Shop
- Close Shope
- Accept Trade or Send Trade Request
