### ISSUE TITLE
Monster can still notice you after changing map

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#1502]
If you attack a monster and than changing map (Its only happening if you change map with a Portal) and then return, the monster is still attacking you :D 

https://gyazo.com/e7e683d84018c88de647d1258573452b

**Comment by chucktheripper** [comment]
Tarets need to be cleaned after changing the map

**Comment by The-Art-Of-War** [comment]
For some reqason they are cleared if i use $Teleport but not if i use a Portal :D
