### ISSUE TITLE
ReorderGroup crash (non-negative exception)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1503]
https://images.discordapp.net/.eJwNyFEOgyAMANC7cAAKBFnxNgQJmmlLaM0-lt19fr73Nfc8zWp21SErwHZI5blZUZ6lN9uZ-9nKOMRWvqColrpfjVQgxCW8gse4pBgxuIhPYQ4Pfcbsk8vJwU1v4g_ZQd38_ghmIuk.BIym8hPLJjSsjHvcK-JdIPSOHBI

https://cdn.discordapp.com/attachments/245272184564482048/248928548587307009/unknown.png

I've tried that to fix it : https://github.com/OpenNos/OpenNos/commit/f49f15adbaf409ae62f07ef6b35f391d357f0b20

But i'm not sure if it's good :/ (When they disable group on their server all work fine. This problem occur after like 5 mins~)

Worked fine before a recent change.

Lucifer mean this function is strange, she access to an element of session who doesn't exist,

**Comment by chucktheripper** [comment]
https://github.com/OpenNos/OpenNos/blob/master/OpenNos.GameObject/Group.cs#L99

This needs to be changed to a single if, because if it*'s set to 0 and empty at the same time it will crash

**Comment by MasterDomino** [comment]
not fixed

**Comment by chucktheripper** [comment]
Please provide further informations to reproduce the problem

**Comment by Uppermost** [comment]
Impossible to provide it's caused by a community bug it occur very very often on all p-server. :/

**Comment by Uppermost** [comment]
#1521
