### ISSUE TITLE
Player teleported outside map.

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1504]
Player was standing somewhere around here:
https://gyazo.com/d3964d499f641a7fe293fa52676b72c5

Then he got kicked from the server for some weird reason and was here after he logged back in:
https://gyazo.com/3d91cb30884d175a3f1e581dc7f39c96 (Left side of the map where the dragons spawn)

**Comment by Uppermost** [comment]
Kick with a message or what else before this problem ?

**Comment by chucktheripper** [comment]
Please retry this

**Comment by Uppermost** [comment]
#1511 Teleporter > out the map sometime.

**Comment by AzogDE** [comment]
It also appears in "Kertos Fänge". It like they are on: Y=1 X= MAX Coord.

**Comment by 0Lucifer0** [comment]
but how did you get this?

**Comment by AzogDE** [comment]
It happens most by dashing into a portal.

**Comment by Uppermost** [comment]
I can explain it there is a lot of way to do I will tell you when I'm on my computer

**Comment by story342** [comment]
Happend too here people saying when die teleported in this map 0 4 0

**Comment by 0Lucifer0** [comment]
Because you have bad thing in database... thats not the same trouble

**Comment by MasterDomino** [comment]
should be fixed already, didnt occur for a long time
