### ISSUE TITLE
Snack bug

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1509]
Prerequisites:
 - Snack(Cookie HP: 100-50mp)
 - Meal(Ex: Baguette and Cheese 1,5HP - 1,5K Mp
Be full hp

Use the meal
Take some damage
Use the snack

You will gain 320 hp instead of 20

**Comment by Ciapa** [comment]
We need to end Meal regain when player is no longer sitting

**Comment by 0Lucifer0** [comment]
yes but keep snack so snack and meal regain should be splitted
