### ISSUE TITLE
addgift thru parcel null reference exception

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1510]
![image](https://cloud.githubusercontent.com/assets/22352357/20435133/31ac0626-adab-11e6-86aa-466c85a2a43e.png)

**Comment by Uppermost** [comment]
Are you sure to be updated? we fix this error yesterday

**Comment by Uppermost** [comment]
Source not up to date problem already fix

**Comment by Uppermost** [comment]
Finally it's not exactly the same error, then I'm not sure can you check it chuck?

**Comment by SasukeTale** [comment]
Same error here on my Server

**Comment by chucktheripper** [comment]
This is a new error.

**Comment by Uppermost** [comment]
Yes xD

**Comment by chucktheripper** [comment]
Retrieving Parcel Items & Receiving Gifts from Act4 works fine for me, any informations how to reproduce this Problem?

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/20455542/b94137ba-ae5e-11e6-951c-1d08d32ed2b9.png)

**Comment by Uppermost** [comment]
This error occur everytime on fagtale server maybe contact the admin on skype to see in debug mode it's a very serious bug

**Comment by chucktheripper** [comment]
This should already be fixed, does anyone still encounter a problem with receiving parcels?

**Comment by Uppermost** [comment]
No #Close
