### ISSUE TITLE
$Shutdown Error

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1512]
Used $Shutdown, when the counter reached 0 I got these error messages for the first time.

http://i.imgur.com/GTICKfl.png
http://i.imgur.com/pb2d3ql.png
http://i.imgur.com/t3tUbKW.png

**Comment by chucktheripper** [comment]
This bug is caused by the WCF, as the WCF will be cleaned after restart, we'll have a look at this Problem after we've implemented the Multi Channel - Server stuff, but for now it's not important and will be moved to Future Project.
