### ISSUE TITLE
Outside of the map help

### ISSUE THREAD

**Issue by danielno13** [OpenNos/OpenNos#1515]
![20161118-0-yuukihime](https://cloud.githubusercontent.com/assets/23557630/20436472/ad664704-adb0-11e6-8ba0-21d2a9df3901.jpg)

**Comment by Uppermost** [comment]
STOP OPEN THIS ISSUE 50X THERE IS ALREADY THE SAME ISSUE !!!! #1504

**Comment by MasterDomino** [comment]
already in issues use issues to only report bugs that happen on localhost of our code
