### ISSUE TITLE
R8 Upgrade to +5 never succeeds.

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1516]
Many players are reporting this after 200+ tries. Tried it myself and didn't work.

**Comment by MasterDomino** [comment]
it does theres 1% chance to upgrade soo its pretty hardcore to upgrade it

**Comment by xKaddo** [comment]
To +5? o_o It should be 20%, shouldnt it?

**Comment by MasterDomino** [comment]
yes something like this like i stated iirc means if i recall correctly
