### ISSUE TITLE
Another Group Crash :D

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1517]
https://cdn.discordapp.com/attachments/245272184564482048/249245626909327360/unknown.png

**Comment by MasterDomino** [comment]
exactly same exception, at least try to read exception message before adding an issue, check other issues for same exception message if it has exception tag

**Comment by Uppermost** [comment]
Not fixed at the latest version I can confirm it

**Comment by xKaddo** [comment]
Sorry, I was told to report it here.

**Comment by MasterDomino** [comment]
who closed issue if it wasnt fixed then?

**Comment by Uppermost** [comment]
ChuckTheRipper try to fix it but the fix doesn't work
