### ISSUE TITLE
Some sell values are wrong

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#1519]
For example item: 2116 = Fruit

https://gyazo.com/0240304807d24f8be92fcc0eda52b34f

**Comment by Digitalis87** [comment]
What is the sell price if you right click on the item ?

**Comment by chucktheripper** [comment]
It's calculating with the value it Shows on rightclick.

**Comment by Digitalis87** [comment]
After checking on Official server, all inventories have prices divided by /20.

Only item we can only resell to NPC have normal price (Berios raid stones, blues & violet stones, diamonds...)

I can do later a full list of NPC resell only items... (With ItemID if needed)

**Comment by chucktheripper** [comment]
We already discussed this Problem, i can remember

**Comment by Digitalis87** [comment]
Yep, me too . As far as i remeber, all thoes listed items are selled with the normal price value whene right clicked. 
All non listed items (maybe some Event Items exceptions) are /20.
- 2330, 2331 , 2332, 2333  -> Lump of gold from Nos$ 
- 2348, 2349 -> Violet & blues stones from Ibrahim's bags, and SP5/6 raids
- 2395 , 2396 , 2397 -> Yellow, green & blue stones from Berios raid (FC)
- 2806 , 2807 -> Relic from act 6.1
- 2900 ,  2901 -> Diamonds from act 5.2

**Comment by Ciapa** [comment]
Already fixed in hitqueue. Will prolly be merged this weekend.
