### ISSUE TITLE
WerableInstance null exception

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1522]
![image](https://cloud.githubusercontent.com/assets/15254478/20455294/d755555c-ae58-11e6-8664-4ae4d6709b96.png)

**Comment by chucktheripper** [comment]
How can Inventory be null in this case? O.o

**Comment by chucktheripper** [comment]
It seems like anyone Managed to put a Non WearableInstance Item on Hat Slot, can you please check your DB for EquipmentType.Hair on InventoryType.Wear with having a Discriminator called "ItemInstance" ?

**Comment by chucktheripper** [comment]
Wearing a hat, even colored works as expected
