### ISSUE TITLE
DropRate affects or equals GoldRate

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#1528]
If you use GoldRate it will be completely ignored from the entire Gold amount that is dropped but if you use DropRate, it will not only change how often things are dropped, it also affects what AMOUNT of gold is dropped

**Comment by MasterDomino** [comment]
GoldRate is amount dropped GoldDropRate is chance to drop gold, DropRate is used for items

**Comment by The-Art-Of-War** [comment]
yes but if you use DropRate gold AMOUNT RATE is higher for example DropRate * 1000 = NosVille monster like 100k Gold drops

**Comment by MasterDomino** [comment]
ooh thanks just noticed that i used DropRate instead GoldRate, sorry and thanks again :D

**Comment by The-Art-Of-War** [comment]
Like i said its a bit twisted GoldRate does nothing and DropRate does amount of gold and how often items are dropped

**Comment by The-Art-Of-War** [comment]
Haha no problem :DD

**Comment by MasterDomino** [comment]
yes it shouldnt be as twisted as this now xD
