### ISSUE TITLE
Skill use bad weapon

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1529]
![image](https://cloud.githubusercontent.com/assets/15254478/20458569/fc27f15a-aea8-11e6-9667-0a3889005a0f.png)
This skill should be use dagger but he use the bow.

**Comment by Uppermost** [comment]
Kaddo report :

 I created a second weapon with 100% on magic pistol to make sure it works and 0% crit dmg on main weapon.

https://gyazo.com/0074c0bae938e333c9544fbeb7af9ac8

**Comment by Ciapa** [comment]
Need to check Damage algo for specially these Skills

**Comment by Uppermost** [comment]
To reproduce it, wear SP2 archer use skill "Cut" unwear principal weapon and watch the damage different, you can see it use it use the principal weapon and not secondary.
