### ISSUE TITLE
Missing skills SP

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1532]
And Dark Gunner misses one skill:
https://cdn.discordapp.com/attachments/245272184564482048/249701176956813312/unknown.png

**Comment by friends111** [comment]
![image](https://cloud.githubusercontent.com/assets/10873097/20484692/b51d2f86-aff8-11e6-965e-0f545c25cf65.png)
Same here.

**Comment by Uppermost** [comment]
W-T-F ?

**Comment by 0Lucifer0** [comment]
Yes there was an issue about it for me (parser lvl skrill trouble)

**Comment by 0Lucifer0** [comment]
#739

**Comment by Ciapa** [comment]
This is not the same issue as #739 
Need to see what the issue is for these Specialists and their skills.

**Comment by 0Lucifer0** [comment]
fixed by my last commit(unvolontary)
