### ISSUE TITLE
Review elementary damage

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1533]
Now I am 100% sure it's wrong. Why?

On official on pigeons monster

Sp2 99+15 whitout buffs 

Bow 92 6+8
Dagger 92 7+9 
100 atq & 30 element
Fairy : 70%

Damage basic whitout cc are almost 20k~

On OpenNos with exactly all the same even if buff etc are not coded, it's not normal 5/6k max !

If you set the ElementaryBoot to 10 you have similar damage of official, but do it don't solve all problem it solve only the problem to dark > light... It's the same for all others elementary damage except Light damage to Darkness monster (skelleton for example) who are ok

I've tested on the same monster on official, if my sp is full attack I almost see nothing difference but if I attack a monster with a low element I see the difference very faster.

We need maybe more informations my idea is the next if we can't find that. If we can't find the "true " algo my idea is create an algo approximate because for the moment sp full attack are very better than full element because they damage advantaged by full attack and seem's to be nerf to element.

Or just modify the elementboost rate to balanced all... I think something is wrong with element points given by sp stat I'm not sure anyway attack algo is like official. If someone have an sp full element on official with like 90/100 element please tell us which equipment etc you use it's very helpful to verify with all elements.

Keep this issue open we need to have more informations about that I will post some complete informations soon about it.

You need to help? post some information about the official whitout buff, pet etc and only with basic hit

PS Markus : +10 upgrade doesn't work on official then even light damage is maybe not good because it's ok but it consider my weapon like a +10. On official it consider it like a +9.

Character Level : 
Weapon & Shell on it :
Sp stat : 
Damage :

**Comment by Uppermost** [comment]
After monster can maybe is the problem I will check tomorrow a lot.

**Comment by SC909** [comment]
You also need to consider skill bonuses
close/range/magic attack increased by ...
fire/water/light/darkness element increased by ...

I would suggest testing things in different ways that would include and exclude; 
SP (can be the same but without points set)
EQ (with and without shells +different types of it by that I mean levels)
Fairy (would suggest testing that out too alone)

**Comment by SoraPlays** [comment]
Has equipment bonus (the orange colored) already been implemented? 

like 'All element energies are incresed by 160' on the bow.

**Comment by Uppermost** [comment]
http://www.elitepvpers.com/forum/nostale/4189606-fairy-dmg-looking-formula.html

Not of course this thing is not add but it can't cause 10k of difference

**Comment by Uppermost** [comment]
I close it we need some others information in the future when buffs/etc will be add

**Comment by Ciapa** [comment]
When buffs and bcard in general is implemented, I just need to take care of their effects and damage algo will be 100% exact when everything is handled.
