### ISSUE TITLE
Monster damage can be 0. Should be 1 minimum 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1535]
When you wear armor / resistance and monster damage are decrease their damage are not visible because their = 0 the minimum damage should be 1.

**Comment by Uppermost** [comment]
Bad reference sorry it's not the same issue

**Comment by Ciapa** [comment]
This issue is invalid, Monster Damage can't be 0, look at MapMonster.cs, line 766

**Comment by Zeshyu** [comment]
@Ciapa On Official monster will deal a minimum damage. For Example LoD Monsters.

If u have full ressistence and armory they still deal around 200 dmg.
Just for exampl.e

**Comment by Uppermost** [comment]
Yes but depend of armor no?
