### ISSUE TITLE
$PortalTo dc

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1536]
If you use $PortalTo you get disconnected.
Afterwards, until you completely restart the client, the green circle under your character will do some magic tricks like this:
https://cloud.githubusercontent.com/assets/23246742/20464422/984315f8-af47-11e6-8c6e-d4ef803649ef.png

**Comment by earthnash** [comment]
The green circle and shadow are client bug.same on official

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/20464499/a418886c-af48-11e6-98b4-c32270520cfb.png)
Screen to know this information is there.
