### ISSUE TITLE
Review damage whitout weapon

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1537]
We need to check that together @Ciapa

**Comment by SC909** [comment]
This might help
http://www.elitepvpers.com/forum/nostale/4189606-fairy-dmg-looking-formula.html

Player Lv + damage (the one from stats) + skill attack (close/far/magic) +15
- enemy defence (if player's attack is close then it will use close defence) - enemy lvl.

I tested this on official too 'cause he asked me for help.

99 Lv
236~236 dmg
95 close dmg (spacebar attack)

99+236+95 = 430

430 (+15 def ) 0 lvl
426 (+18 def) 1 lvl
426 (+18 def) 1 lvl
423 (+20 def) 2 lvl
419 (+23 def) 3 lvl
338 (+80 def) 21 lvl

Meteorite
req_info 5 424
(+15 ef) 0 lvl
99 lvl
1069~1069
85 close attack
70 light
20 dark

Elements will be ignored if you don't have a fairy equipped.
//Damage from test
1253

//Calculation
99+1069+85= 1253

**Comment by SC909** [comment]
//SP 8 Warrior 1job (no bonueses etc) Light Fairy
//Basic Info
Lv + dmg + skill dmg +15 - enemy defence = damage
99+236+85+15-15 = 420

70 skill element light damage -> enemy non-elemental (*1,3)
70 *1,3 = 91

//No fairy
420 436

//0%
511 527

511-420 = 91
91 /1,3 = 70 (skill elemental damage)

//3%
527 543

//6%
544 562

//80%
963 996

**Comment by Uppermost** [comment]
Good thanks job ;)

**Comment by Uppermost** [comment]
Can you try for all class with and whitout weapon? adventurer also if possible. Thank

**Comment by SC909** [comment]
ONLY SPACEBAR USED!
Adventurer 50 lvl 109-109 dmg (some training was done that add dmg etc)
Dander/Chicken 1 lvl & 18 close def, 17 far, 13 magic
50+109+15 = 174
174 - 1 - 18 = 155

If you remember ski packet, the first two skills are the same as it is something like, the first one is used and then the second. While it is the same one but the damage changes a bit.

1st attack: 155
2nd attack: 155
3rd attack: 63, 39, 59 (161)

1st attack: 155
2nd attack: 155
3rd attack: 48, 56, 57 (161)


While wearing a weapon (129-137) (should be 175-183)
182
273 (crit)
181
180
175
176
182
183
179

//Buffs that adventurer can use
No weapon (buff that gives 4 morale)
Without: 155
With: 159
With & buff +10 dmg: 169
With & buff +40 dmg: 199
With & buff +50 dmg: 209

//Still have a buff +4 morale and +10 dmg
Spacebar: 169
Skill Energy Bolt (+80 magical damage): 239

The magical attack must be a thing as I can remember that it can be interrupted while casting by a enemy attack. Which means it must be using right now magical defence of a monster and player magical attack.

Player Level + Player Damage + Skill Damage - Enemy Level - Enemy Defence
50 + 109 + 80 - 1 - 13 = 225

80 (magical damage - the skill uses magic combat (close, far, magic)
13 (enemy magical defence)




//Now without buff
Spacebar: 155
Skill Beat Up (+80 close damage): 235 (it hits three times 111, 47, 77 & 91, 78, 66)

**Comment by Uppermost** [comment]
I think we will not check anymore because everything is still added and very similar of the official
