### ISSUE TITLE
adjust the TransportId range in TransportFactory

### ISSUE THREAD

**Issue by story342** [OpenNos/OpenNos#1540]

**Comment by chucktheripper** [comment]
Which Monster? Which Drop? How Long did the Server run?

**Comment by story342** [comment]
dander monsters i just updated i just try this with seed gold and if you drop any item you get disconected

**Comment by story342** [comment]
I just try with dander monster so i dont know if its more or not

**Comment by chucktheripper** [comment]
So you got disconnected on get, not on drop, right?

**Comment by story342** [comment]
right

**Comment by chucktheripper** [comment]
Does it also happen when you restart the Server?

**Comment by story342** [comment]
you drop any item and you get disconected reconect again and you have the same item

**Comment by chucktheripper** [comment]
Yes but what happens when you restart the Server?

**Comment by story342** [comment]
i restarted and now i can drop items and get items now seems normally

**Comment by chucktheripper** [comment]
Okay so we Need to adjust the TransportId range in TransportFactory.

**Comment by story342** [comment]
Ok nice i just want to try help because with bugs because im updating always -.-
