### ISSUE TITLE
Miss is not displayed on AOE & Critical Hit doesn't work

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1546]
https://gyazo.com/e7df600d96c469b6a7dd4bea22bd064d

Here it only hit 1 monster. Sometimes it doesn't hit any at all.

**Comment by Uppermost** [comment]
Already in issue #1535

**Comment by Uppermost** [comment]
My bad sorry it's not already in issue

**Comment by Ciapa** [comment]
I need to know how to reproduce it.

**Comment by Uppermost** [comment]
True when you miss on AOE it don't show MISS check it on land of the dead map I can reproduce it easily.

**Comment by Ciapa** [comment]
This issue is now part of the hitqueue branch. Will be fixed on master when hitqueue gets merged.
