### ISSUE TITLE
e_info exception

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1547]
When you go in game and right click on a monster you are disconnected also you see everyone level 0.

![image](https://cloud.githubusercontent.com/assets/15254478/20467902/63d44f64-af90-11e6-869f-04b35bcd3217.png)

![image](https://cloud.githubusercontent.com/assets/15254478/20468209/86f4637c-af94-11e6-8e04-270ba23871b7.png)

This problem occur ONLY with monster parsed by e_info.
Monster don't move, you can see their HP etc.

PS : Name, Race,... seem's to be null or 0 because that

- [ ] Fix exception/Monster life/Monster move

Edit : Forget what I have say about name null it's just monster with none name ;)

**Comment by Ciapa** [comment]
Seems like I have a fix for it, but I need to get the e_info data first
