### ISSUE TITLE
Very big CPU usage problem only on OpenNos (Client)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1549]
As I can see, on OpenNos my client use almost 25/30% of cpu on empty map ! 

On official on the same map 7/9%

Someone have an idea why? On OpenNos my computer burn a lot ...

We need to fix move monster etc after @MasterDomino commit to test it but I'm almost sure mv packet cause this trouble.

**Comment by Ciapa** [comment]
We have much less mv than on Official... So this can't be the issue

**Comment by chucktheripper** [comment]
@Ciapa CPU usage mostly created thru invalid anti-spam-protection and direct Database Access (SAVE, Parcel)

**Comment by Ciapa** [comment]
We Talk about Client, not Server

**Comment by chucktheripper** [comment]
@Ciapa Probably the "Old" Encryption we use causes problems as it's not as fast as the "New" one

**Comment by Ciapa** [comment]
Need to Check this

**Comment by chucktheripper** [comment]
@Ciapa Our Packets are about twice the size of the official ones.

**Comment by Uppermost** [comment]
My conclusion mean it's caused by mv packet. CPU usage 30%~ only for the client.

(2/3x more of official) I have a good CPU (i7))

**Comment by 0Lucifer0** [comment]
Its possible that the client USE more cpu to split Packet ;)

**Comment by Uppermost** [comment]
Now I understand why a lot of people said "Server lag" it's because if they have not a good CPU the usage is at 100% xD we need to check it

**Comment by Uppermost** [comment]
Seem's to be fixed after my latest commit now the cpu usage is 10% I close it?

**Comment by Uppermost** [comment]
Finally it's not fixed.

**Comment by Uppermost** [comment]
_sendTask = StartSending(SendInterval, new TimeSpan(0, 0, 0, 0, isLagMode ? 1000 : 100), cancellationToken); 

even change this like change nothing if I adjust the to 20 > 100 nothing change.
