### ISSUE TITLE
Implement monster minimum damage

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1552]
We need to implemented minimum damage from monster

**Comment by Uppermost** [comment]
Try on official 

Skelleton official : 1300/1400 on archer whitout stuffs & 2600/2800 on archer whitout stuff except fairy light

Skelleton opennos : 900/1000 & with fairy 2000 light there something a little bit wrong about damages

**Comment by Ciapa** [comment]
Fixed by fe471172
