### ISSUE TITLE
Sp Perfection and sps effects dont have any effect.

### ISSUE THREAD

**Issue by geiti94** [OpenNos/OpenNos#1557]
My Berseker on Fagtale have perfection 100 but that dont have any effect except hp. Other thing is berseker give by default 15% shadow resistance but i dont recive it. and perfection the same. normaly is 1atk perf= 10 more dmg, 1 def perf= 10 mor def, 1 ele perf= +1 ele, 1hp perf= 100hp more base hp. and ressistence perfection is normaly +1% but i dont recive it too.

**Comment by geiti94** [comment]
here a screenshot for show that: https://puu.sh/sq2df/52675c74e7.jpg
normaly my berserker need to give me 34% shadow resistance but it dont give that and i have only the 10% from eq. the atk and def perfection is showed in char info windows but dont makes any difference in dmg etc

**Comment by Uppermost** [comment]
Yes it's just not coded wait the fix :)

**Comment by Ciapa** [comment]
Mostly invalid. Ressistance Data is applied, Damage is applied, Defense is applied(Except magical)
Only Element and HP perfection are not implemented. Basic SP Data should be implemented too.

**Comment by geiti94** [comment]
resistence perfection too not because when you look on char info windows it shows only 10% shadow resistance. but it should show 44%. on official server where my sp6 have 21 fire resistance perfection it shows that in char info

**Comment by Uppermost** [comment]
Because it's not updated on info character for the moment we will do it soon.

**Comment by Ciapa** [comment]
I can only tell you what the code says, and it says it does count the stuff

**Comment by Ciapa** [comment]
Attack and Defense *are* applied. Even in current upstream.
Ressistance *is* applied, except that for Dark Ressistance, your Water Perfection is counted too. Will be fixed with next commit
HP and Element will be added too. Element will not be shown, but will be in calculation of damage.

**Comment by geiti94** [comment]
ok thx :D i installnow byself the server too for find if there are other things because on fagtale enought things are disabled

**Comment by Uppermost** [comment]
And fagtale is not always updated take it in consideration

**Comment by geiti94** [comment]
yes thats why i am installing it now byself on my server. i think 2x xenon quad core and 32gb ram are enought for test it with 10-20 player right?

**Comment by Uppermost** [comment]
XD this joke, of course it's enought you can even play with 150 player...

**Comment by Ciapa** [comment]
Oh, just saw that HP is also implemented in upstream. So really just Element and MagicalDefense missing
