### ISSUE TITLE
Pots Bug

### ISSUE THREAD

**Issue by geiti94** [OpenNos/OpenNos#1560]
The pots have a bug. even if hp and mana are full the pot will be used for nothing like he dont see hp etc are full

**Comment by MasterDomino** [comment]
Not a bug but a missing condition xD do you even read them code? We need bugtracker really bad

**Comment by geiti94** [comment]
i dont looked in code xD but i found an other bug xD and that bug is that sometime the world server stucks and no more drops comes and when we try to drop somethings from invetary it give disconnects xD but i need first to find out how to reproduce it xD

**Comment by Ciapa** [comment]
Closed, as it is invalid. Look here:
`                    if (session.Character.Hp == session.Character.HPLoad() && session.Character.Mp == session.Character.MPLoad())
                    {
                        return;
                    }`
