### ISSUE TITLE
Creating a shop dc's

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1561]
Everything is working fine after a serverrestart.
But after a while, you cannot open a shop anymore, it will disconnect you every time. So you have to restart the server again.
https://gyazo.com/deefdc7d5831e6b01972b1a4b27e4b5f

**Comment by Uppermost** [comment]
I agree what Ciapa say seem's to be someone ty to duplicate/bug using

**Comment by Uppermost** [comment]
Mhm what happens? only for you a method to reproduce it? :/

**Comment by xKaddo** [comment]
If my server is up for a longer time then you suddenly can't create shops anymore, it'll just disconnect you.
I don't know whats causing this error.

**Comment by Uppermost** [comment]
#1581

**Comment by Ciapa** [comment]
Tell me the exact way how I can reproduce the error. Or a debug session where I can work on it once the error appears.

**Comment by 0Lucifer0** [comment]
i will fix it i found the trouble ;)
