### ISSUE TITLE
EXP - First Monster

### ISSUE THREAD

**Issue by xAfterLife** [OpenNos/OpenNos#1562]
If you kill a LoD Skeleton with a level 1 Player in your Group, he will get Level 60
 If you kill a Dander Level 1(+99) and then the Skeleton, he will reach to around Level 41
Servers EXP-Rate: x100

[https://gyazo.com/4bdd7e0902c6f61bc7b1435d925b932f](url) Skeleton as first Mob
[https://gyazo.com/8283aafa012fb62387f672f0cee942ea](url) Skeleton after a Danda lvl 1(+99) without group

**Comment by 0Lucifer0** [comment]
So lvl différence should be reload on each up ;)

**Comment by 0Lucifer0** [comment]
in fact that's exactly the same on official you get more xp when you up because the lvl difference is calculated before.

**Comment by Uppermost** [comment]
true
