### ISSUE TITLE
Private Shops as mounts can move

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1563]
https://gyazo.com/364efbc97ada47718727c640358f0208

**Comment by story342** [comment]
its not happening to mee -.-

**Comment by Uppermost** [comment]
Ask him how he do it. It's maybe an hack or a bad refresh problem

**Comment by xKaddo** [comment]
Ok so:
- Open a shop
- Press Ctrl+Z
- Open Inventory with i and use mount
