### ISSUE TITLE
NpcLifeManager unlimited error

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1565]
![image](https://cloud.githubusercontent.com/assets/15254478/20550821/ecb7b10e-b139-11e6-9f1d-a266048c2d7e.png)
This error occur in loop, I guess it's after summon some monster they don't walk like monster id 1427.

Or maybe when I summon something else

**Comment by Ciapa** [comment]
Please provide exact steps to reproduce the problem
