### ISSUE TITLE
Block move monster on summon/addmonster if monster speed = 0

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1568]
All on the title you know what you need to do Ciapa

**Comment by Ciapa** [comment]
Already done by the Move() Function in MapMonster.cs

**Comment by Ciapa** [comment]
The Problem is we would need to somehow load it from the client files if it has animation or not, since for MobID 222 (Spiderking) it has Monster.Speed = 5. So this is not a bug, but more like it can't be known by the Server
