### ISSUE TITLE
PassNonParseablePacket = false with value not in enum pass the packet

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#1569]
When PassNonParseablePacket = false and when the value is not in an enum the packet is still pass to handler.
For exemple when you do $ChangeClass 5 it change your class to 5 even if the class enum is
  public enum ClassType : byte
    {
        Adventurer = 0,
        Swordman = 1,
        Archer = 2,
        Magician = 3
    }

cf #1542

**Comment by 0Lucifer0** [comment]
seems to be the same trouble #1536

**Comment by chucktheripper** [comment]
PassNonParseablePacket should just passt null as packet

**Comment by 0Lucifer0** [comment]
But thats not the case here it pass 5 as class

**Comment by chucktheripper** [comment]
@0Lucifer0 So it's capable of parsing byte value 5 to enum where the value 5 hasnt been set? What Value is it then?

**Comment by 0Lucifer0** [comment]
Yes thats what i mean its 5 idk why Try $ChangeClass 5 you Will see

**Comment by 0Lucifer0** [comment]
that's thread explain all http://stackoverflow.com/questions/29482/cast-int-to-enum-in-c-sharp
