### ISSUE TITLE
You can't right click on an item in the private shop & npc shop

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1570]
A player open a shop I want to show weapon stats or something else but it doesn't work, I guess it's just not implemented.

Same problem for npc shop, on official these two things work fine.

(screen from official)
![image](https://cloud.githubusercontent.com/assets/15254478/20583747/eb454274-b1ec-11e6-96be-be7fa5a9167a.png)

This problem seem's to occur only for equip right click

**Comment by Ciapa** [comment]
fixed
