### ISSUE TITLE
Mail shows wrong character gender

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1573]
https://gyazo.com/e91d7d6e7615697b9d4839f017d111e5
^Is actually a female character.

Also I sometimes get this in mails:
https://gyazo.com/355d7303ab9688d9c2df550c858acea6

**Comment by Uppermost** [comment]
Maybe after use magic lamp

**Comment by chucktheripper** [comment]
Or ChangeSex command

**Comment by 0Lucifer0** [comment]
the character sex is kept when mail is sended.
