### ISSUE TITLE
Mail displaying is wrong

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1574]
The character displaying is wrong on receive mail.

**Comment by Ciapa** [comment]
@Uppermost that is also in official

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/20610232/f027db76-b296-11e6-9b26-21e4db2d9df3.png)
No

**Comment by Uppermost** [comment]
#fix by 0Lucifer0
