### ISSUE TITLE
Dropped item doesn't go into inventory

### ISSUE THREAD

**Issue by Elendan** [OpenNos/OpenNos#1575]
Hey, sometimes, when you pick up an item dropped by a monster, the item just "disappears", it's not written in the cat that you picked up the item and it's not in your inventory :)

**Comment by 0Lucifer0** [comment]
how do you reproduce this because i didn't have this trouble and we need at list an error or something to reproduce.

**Comment by Elendan** [comment]
Just by farming a lot and dropping a lot of items
