### ISSUE TITLE
The server doesn't save right

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1576]
When you shutdown the server we need to restore/fix the save & some people tell me the save don't work fine with $Shutdown.

**Comment by 0Lucifer0** [comment]
(only on saveAll)

**Comment by Ciapa** [comment]
Might be the same as the issue in Account.Update() where the Mapper caused the Context.SaveChanges() call to not recognize changes correctly.

**Comment by Uppermost** [comment]
Disconnection/reconnection don't keep your save.

**Comment by Ciapa** [comment]
Need to have an example on how to reproduce this problem. For me, it saves correctly.

**Comment by 0Lucifer0** [comment]
walk from position A to a position B
click the X on the console
restart
you are at the position A
