### ISSUE TITLE
Algo sp wrong

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1577]
For example 100 points in attack should give you 1000 points in attack except bonus but it give you very more. maybe the same problem for all others algo (hp,element, def)

For attack true value

(give +5 points in attack for each point set and depend of rang 6 about 11 points etc...)

1-10 = +5
11-20 = +6
21-30 = +7
31-40 = +8
41-50 = +9
51-60 = +10
61-70 = +11
71-80 = +13
81-90 = +14
91-95 = +15
96 = +16
97 = +17
98-100 = +20

Total 1000 points

**Comment by 0Lucifer0** [comment]
work great for me

**Comment by Uppermost** [comment]
https://gyazo.com/208ff06eb417377fe52e528ed2b15bae
Secondary stats.

**Comment by Ciapa** [comment]
@Uppermost I will check code to know what's the issue

**Comment by 0Lucifer0** [comment]
trouble is here :      p = 0;
                    if (point <= 10)
                        p = point;
                    else if (point <= 20)
                        p = 10 + (point - 10) * 2;
                    else if (point <= 30)
                        p = 30 + (point - 10) * 3;
                    else if (point <= 40)
                        p = 60 + (point - 10) * 4;
                    else if (point <= 50)
                        p = 100 + (point - 10) * 5;
                    else if (point <= 60)
                        p = 150 + (point - 10) * 6;
                    else if (point <= 70)
                        p = 210 + (point - 10) * 7;
                    else if (point <= 80)
                        p = 280 + (point - 10) * 8;
                    else if (point <= 90)
                        p = 360 + (point - 10) * 9;
                    else if (point <= 100)
                        p = 450 + (point - 10) * 10;
                    MinDistance += p;
                    MaxDistance += p;

**Comment by Ciapa** [comment]
@0Lucifer0 Nope, that value is the base for both calculations...

**Comment by 0Lucifer0** [comment]
this is perhaps good algo but this is the explanation an sp with sl 100 will have 450+90*10 = 1350 so not 1000 ;)

**Comment by Ciapa** [comment]
@0Lucifer0 but why is it ok for primary then?

**Comment by 0Lucifer0** [comment]
because that's not the same algo this is primary :  int p = 0;
                    if (point <= 10)
                        p = point * 5;
                    else if (point <= 20)
                        p = 50 + (point - 10) * 6;
                    else if (point <= 30)
                        p = 110 + (point - 20) * 7;
                    else if (point <= 40)
                        p = 180 + (point - 30) * 8;
                    else if (point <= 50)
                        p = 260 + (point - 40) * 9;
                    else if (point <= 60)
                        p = 350 + (point - 50) * 10;
                    else if (point <= 70)
                        p = 450 + (point - 60) * 11;
                    else if (point <= 80)
                        p = 560 + (point - 70) * 13;
                    else if (point <= 90)
                        p = 690 + (point - 80) * 14;
                    else if (point <= 94)
                        p = 830 + (point - 90) * 15;
                    else if (point <= 95)
                        p = 890 + 16;
                    else if (point <= 97)
                        p = 906 + (point - 95) * 17;
                    else if (point <= 100)
                        p = 940 + (point - 97) * 20;
                    MaxHit += p;
                    MinHit += p;

**Comment by Ciapa** [comment]
@0Lucifer0 Actually, it should be exactly the same algo for both...

**Comment by 0Lucifer0** [comment]
i don't know why that's not the same algo i remember that i've found the primary one but i don't remember that i code another one for distance so yes that's strange or it was for defence or something like that but absolutly not for distanceHit

**Comment by Ciapa** [comment]
@0Lucifer0 that algo doesn't fit for anything tbh..

**Comment by 0Lucifer0** [comment]
it seem's i was tired the 1st of march ^^ https://github.com/OpenNos/OpenNos/commit/5bbd3a8d79c500d733bfea46a09cff2fd4dc4810#diff-ae34eb8abd5982c091721706d1d243db
