### ISSUE TITLE
SP Perfection - Display Bug

### ISSUE THREAD

**Issue by xAfterLife** [OpenNos/OpenNos#1578]
If you equip and un-equip your SP and go to the perfection menu, the display will count it as perfection 0. This is only a display error. The cost will stay the same.

[http://epvpimg.com/iVJnd](url) [http://epvpimg.com/Un9Hc](url)

**Comment by Ciapa** [comment]
Seems to be a clientside bug only, as the cost is calculated clientside, not serverside.
