### ISSUE TITLE
Private shop you can use a bug to be not sitdown

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1582]
Use ctrl+z when you open a shop private and you use this bug to be not sitdown

**Comment by Ciapa** [comment]
On official you can do the same.

**Comment by MasterDomino** [comment]
Yes but we want to try to fix issue that exist on official

**Comment by friends111** [comment]
maybe just disable rest while shopping?

**Comment by Ciapa** [comment]
Duplicate of #1059
