### ISSUE TITLE
Reviews some little things about damage

### ISSUE THREAD

**Issue by SC909** [OpenNos/OpenNos#1583]
Check if a skill that player used have the same element as the fairy.

Attack damage = weapon damage + skill damage + 15
Fairy damage = (Attack damage +100) * (Fairy % /100) 80% = 80/100 = 0,8
Attribute damage = (Fairy damage + skill attribute) * attribute factor

FINAL DAMAGE = (Player level - mob level + Attack damage - mob defence) + Attribute damage

99 lvl
236~236 weapon damage
85 skill damage
70 light attribute
80% light fairy
0 lvl mob
15 close combat defence

//80% fairy SP8 warrior 1job (hits 963)
236+85+15 = 336

(336+100)*(80/100)
436*0,8 = 348,8 -> 348

(348+70)*1,3 (attribute factor)
418*1,3 = 543,4 -> 543

99-0+336-15+543 = 963

If you want to check
https://github.com/OpenNos/OpenNos/issues/1537
http://www.elitepvpers.com/forum/nostale/4189606-fairy-dmg-looking-formula.html

**Comment by Uppermost** [comment]
Still added no? I will ask Markus but I think everything is ok

**Comment by SC909** [comment]
I was able to crack the fairies about 20 minutes ago. I can do later on some more tests. And no it was not added properly.

**Comment by Uppermost** [comment]
You mean our fairy damage is wrong?

**Comment by SC909** [comment]
I can see that the baseDamage is wrong. It should be something like:
baseDamage = new Random().Next(mainMinDmg, mainMaxDmg) + skill.Damage +15;

**Comment by Uppermost** [comment]
Also fairy 0% should be increase damage a little bit right, we will see that thank for that if you have some other information tell us

**Comment by SC909** [comment]
I cannot do it now. I will be able to do so tomorrow, as I will also do some more tests as there is also resistance, buffs (dmg, attribute and morale), armour and weapon + (% bonuses).

**Comment by Uppermost** [comment]
Don't do it for buff because it's not coded and take in count additionnal damage on the right click of your weapon etc are consider like a buff and they doesn't work yet.

**Comment by SC909** [comment]
I know and I will only do things like, damage from SP points, attribute as well from SP points. The same for SP perfection.

**Comment by Ciapa** [comment]
Your Formulas are wrong. Damage is now almost 100% accuracte compared to official. No need to do any reviews. Only thing is fairy damage where I need to edit it a bit.

**Comment by Uppermost** [comment]
Please just correct fairy damage on monster whitout element when you are whitout sp

**Comment by Uppermost** [comment]
SC909 you mean something about fairy hack no? there is a way to leveling them with a hack?

**Comment by Ciapa** [comment]
If there is something like this, please report it on http://redmine.ciapa.io and mark the issue as Private to make sure that it is not public until we fixed it.
