### ISSUE TITLE
BOT MESSAGE "^^"

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1584]
![20161125-29-test](https://cloud.githubusercontent.com/assets/22352357/20632303/c88c7d3c-b33c-11e6-9004-6eea67aeb76b.jpg)

**Comment by Ciapa** [comment]
What should be the issue there? #close

**Comment by Ciapa** [comment]
Edit: I don't have the issue with the "^" in the Message on my Private testing environment.

**Comment by BelminBIH** [comment]
Does it have to be because I'm not up to date?

**Comment by Ciapa** [comment]
Prolly, or you might have Double "^" in your ressources

**Comment by Uppermost** [comment]
Just remove ^ from your translation key...
