### ISSUE TITLE
Parser is buggy, you can't parse the same thing 2x

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1586]
All on the title when you re-use parser you have an error.

**Comment by The-Art-Of-War** [comment]
I think its only while it tries to parse Accounts? or am i wrong

**Comment by Ciapa** [comment]
Need to get error messages to check why it fails

**Comment by The-Art-Of-War** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/17483888/20634947/c1c96e00-b356-11e6-878e-4b05aa94067a.PNG)

**Comment by The-Art-Of-War** [comment]
The error message is damn long doe...

**Comment by Ciapa** [comment]
yep, issue found, fix in some minutes

**Comment by Ciapa** [comment]
Should be fixed now. If not, please post the *complete* Error Message on Pastebin and link it.
