### ISSUE TITLE
Xp Bug

### ISSUE THREAD

**Issue by BelminBIH** [OpenNos/OpenNos#1588]
https://gyazo.com/e17029a804d5a7ae3680cf9756292dfa

**Comment by MasterDomino** [comment]
what have you done?

**Comment by BelminBIH** [comment]
I just modify the job xp and increase the combat xp spleen to x30

**Comment by MasterDomino** [comment]
how did you modify jobxp? did you touch the code?

**Comment by BelminBIH** [comment]
![image](https://cloud.githubusercontent.com/assets/22352357/20634203/89082d66-b34e-11e6-8b6b-9d1e1b275cf7.png)
I modified it as its:

**Comment by MasterDomino** [comment]
use $ExpRate 10 same shit

**Comment by BelminBIH** [comment]
Sorry ?

**Comment by MasterDomino** [comment]
$RateExp command

**Comment by BelminBIH** [comment]
Sa did not solve my problem

**Comment by MasterDomino** [comment]
just dont edit db that way you propably edited something in code as that is not what we support its invalid

**Comment by BelminBIH** [comment]
What should I do now?

**Comment by Ciapa** [comment]
Reset your fooking database

**Comment by BelminBIH** [comment]
Do piss on my computer? What a good idea!

**Comment by story342** [comment]
its XpRate not ExpRate no?

**Comment by MasterDomino** [comment]
whatever just use $Help for list of all commends god damn it

**Comment by story342** [comment]
yea hahahaha
