### ISSUE TITLE
Sending U_S  allows you atk-range and -speedhack 

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#1589]
If you send for example:

"u_s 0 3 1692" you can atk the target from everywhere and faster than allowed to

you can also hit multiple targets (at the same time) for example if you send:

u_s 0 3 1692
u_s 0 3 1699
u_s 0 3 1691
u_s 0 3 1700
u_s 0 3 1690

**Comment by Uppermost** [comment]
already fix on hitqueue branch will be soon available

**Comment by The-Art-Of-War** [comment]
Oh okay :D
