### ISSUE TITLE
fix reput reading from database

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#159]
not updating in chracter screen(window (P)) 
when changed to 5000 in db it doesnt show it in game

**Comment by Ciapa1** [comment]
When the Server is running, you shouldn't mess with the DB, as the Server
alone changes it's content. So there isn't anything to fix IMHO.

**Comment by 0Lucifer0** [comment]
yes but he mean that reput isn't loaded at startup :D will change this

**Comment by 0Lucifer0** [comment]
fixed
