### ISSUE TITLE
High DMG Spikes

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1590]
Usually this player deals around ~40k dmg and ~50k crit dmg.
https://gyazo.com/0ed0e8e00be864a378e04f22c1c222d7

Since a few minutes ago (where I updated to the latest version) he sometimes deals 60k dmg WITHOUT a crit.
https://gyazo.com/2fe6606e76b934e63dc2f73e16d5f32f

When we TP'ed him into the GM Office and summoned monsters, he dealt normal damage again (~40k, ~50k crits).

**Comment by Uppermost** [comment]
Normal damage for sp full element in sp4+15...damage change in function of skill distance
