### ISSUE TITLE
World Server shutting down without any error

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1592]
After updating to the latest version, the world server keeps shutting down every 2-5 minutes without any error message, hence I can't provide any information about this.

Latest packets before the world server closed itself:
https://gyazo.com/0dd3308c3ec574707b1cf62404930d31

**Comment by Ciapa** [comment]
No Problem for me here...
Please run World from Visual Studio in debug mode(so the Debugger is attached)

**Comment by xKaddo** [comment]
https://i.gyazo.com/thumb/1200/_a25caa92809be7d26f5f7c878ab18e8f-png.jpg
Occured again. Couldn't get much more information out of it, sorry.
