### ISSUE TITLE
command $PortalTo handler error

### ISSUE THREAD

**Issue by JOAOMASTER** [OpenNos/OpenNos#1594]
When you put the command $ PortalTo the player is disconnected
![20161125-4-prueba](https://cloud.githubusercontent.com/assets/17860577/20637830/9cbda06e-b369-11e6-9973-dadeaa16e5a6.jpg)
![20161125-5-entwell](https://cloud.githubusercontent.com/assets/17860577/20637834/adda68b4-b369-11e6-92d8-e5b945a4717a.jpg)
![error 1](https://cloud.githubusercontent.com/assets/17860577/20637836/b628a6b6-b369-11e6-811c-b6ecc58eb21d.png)

**Comment by MasterDomino** [comment]
i love how you forgot to cut out the second desktop xD

**Comment by JOAOMASTER** [comment]
thanks
