### ISSUE TITLE
Parser errors

### ISSUE THREAD

**Issue by Skeetcher** [OpenNos/OpenNos#1595]
I've just deleted my whole DB, I did the update-database in VB and I've opened OpenNos.Import.Console (parser). After pasting the directory and clicking Y this is what happens: https://youtu.be/fnKRChAbYUg.

**Comment by MasterDomino** [comment]
are you on latest update? cuz that doesnt happen for us

**Comment by Skeetcher** [comment]
Yeah, just updated...
