### ISSUE TITLE
GiftAdd Exception

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1598]
https://cdn.discordapp.com/attachments/245272184564482048/252077808585539584/unknown.png
Is this enough? If not, I'll run another debug session.

**Comment by Ciapa** [comment]
@xKaddo You have this still open? Please Expand ServerManager.instance and drop in the Autos window

**Comment by xKaddo** [comment]
@Ciapa Argh, nope I sadly don't. I'll message you once I'm running in debug mode again and this occurs, since I ran this one for the worldserver crash.

**Comment by Ciapa** [comment]
@xKaddo I have an idea on what causes this
