### ISSUE TITLE
ClientSession handler

### ISSUE THREAD

**Issue by CryForMe9** [OpenNos/OpenNos#1600]
![errorrr](https://cloud.githubusercontent.com/assets/19311044/20641232/fb89c084-b3f3-11e6-86b3-fcf5336a6dfd.PNG)

I dont know why.

**Comment by Ciapa** [comment]
@CryForMe9 You cut the most important information(autos and stack) out of it

**Comment by chucktheripper** [comment]
@Ciapa Add ConcurrentQueue instead of Queue to ClientSession
