### ISSUE TITLE
Crit damage not marked as Crit

### ISSUE THREAD

**Issue by xAfterLife** [OpenNos/OpenNos#1603]
Crit damage doesn´t get marked as Crit damage.
https://youtu.be/vtER8eyh53I

Damage without crit:
http://epvpimg.com/fb3nf

**Comment by Ciapa** [comment]
Crit is only a visible Error. Will be fixed after I logged the correct packet from official.
The SpecialZoneHit Skills working only once seems to be a SkillReset Error, or the Cooldown Bypass Protection might be buggy.

**Comment by MasterDomino** [comment]
this should be fixed long time ago, can we get tests on if this still occurs?
