### ISSUE TITLE
berserker wrong skills range

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1605]
If you attack a monster with space in the berzerk sp, you will walk closer to it and then just stop (nothing happens). If you walk a bit closer manually, it will attack the monster.
Berzerk should attack on the first attempt, you have to get closer than the usual hitrange right now.

Edit: Same happening for other SPs, for example Icemage, Archmage, etc.

**Comment by Uppermost** [comment]
The distance calculation should be wrong

**Comment by Uppermost** [comment]
it's fucking broken like whole skill system ... If you try to attack with basic hit berseker you willl did 0 damage on first hit or will be stuck...

**Comment by Uppermost** [comment]
With bersek on basic hit you can see 

* Stuck bug something (Maybe not only with this sp but occur often)
* Animation bug/double hit?
