### ISSUE TITLE
add the respawn object functionality

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#1606]
need to add the respawn object functionality
The teleport functions is already done we just need to do the delay/dance and send correct packets

**Comment by Uppermost** [comment]
You mean for return amulet?

**Comment by Uppermost** [comment]
u_i 1 630933 2 0 0 0 
rp 4 167 55 #u_i^1^630933^2^0^1

u_i 1 630933 2 0 0 0 
rp 4 167 55 #u_i^1^630933^2^0^1

#u_i^1^630933^2^0^1
delay 5000 7 #u_i^1^630933^2^0^2

guri 2
guri 5 1 630933 0 7
guri 2 1 630933

guri 5 1 630933 20 7
guri 5 1 630933 40 7
guri 5 1 630933 60 7
guri 5 1 630933 80 7
guri 5 1 630933 100 7
#u_i^1^630933^2^0^2



//Whitout save position
u_i 1 630933 2 4 0 0 
dlg #u_i^1^630933^2^4^1 #u_i^1^630933^2^4^2 Souhaites-tu enregistrer ta position actuelle et retourner au village ?
Clique sur « Retour » pour retourner au village sans enregistrer ta position actuelle.


#u_i^1^630933^2^4^2
delay 5000 7 #u_i^1^630933^2^4^4

guri 2
guri 5 1 630933 0 7
guri 2 1 630933

guri 5 1 630933 20 7
guri 5 1 630933 40 7
guri 5 1 630933 60 7
guri 5 1 630933 80 7
guri 5 1 630933 100 7
#u_i^1^630933^2^4^4

With save point
u_i 2 1966 2 0 0 0 
dlg #u_i^1^1966^2^0^1 #u_i^1^1966^2^0^2 Souhaites-tu enregistrer ta position actuelle et retourner au village ?
Clique sur « Retour » pour retourner au village sans enregistrer ta position actuelle.


#u_i^1^1966^2^0^1
delay 5000 7 #u_i^1^1966^2^0^3

guri 2
guri 5 1 630933 0 7
guri 2 1 630933

guri 5 1 630933 20 7
guri 5 1 630933 40 7
guri 5 1 630933 60 7
guri 5 1 630933 80 7
guri 5 1 630933 100 7
#u_i^1^1966^2^0^3

**Comment by 0Lucifer0** [comment]
done
