### ISSUE TITLE
add share return point with group

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#1607]
add share return point(just need to use Character.SetReturnPoint(MapId,X,Y));

**Comment by Uppermost** [comment]
Receive share point group (ask)
dlg #pjoin^6^633833 #pjoin^7^633833 Veux-tu établir comme point de retour : SlayerD² ?


When I decline
msg 0 Tu as refusé de partager le point de retour avec les membres du groupe.



When you ask someone to share your point
pjoin 5
info Tu a envoyé une demande pour partager le point de retour avec les membres de ton groupe.


When player accept you receive
msg 0 SlayerD² a modifié le point de retour.



Packet receive when you accept
dlg #pjoin^6^633833 #pjoin^7^633833 Veux-tu établir comme point de retour : SlayerD² ?

#pjoin^6^633833
msg 0 Tu as changé le point de retour commun des membres du groupe.
