### ISSUE TITLE
(Ice?)Mage DMG sometimes won't go through

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1608]
https://www.youtube.com/watch?v=MpjBkvAX1c8&feature=youtu.be

You can see it at 0:25. Normaly mages never 'miss'. Maybe this is the similar to the "AOE" Bug where dmg won't go through sometimes and not displayed as a miss, since even IceMage Autoattack is AOE aswell? Just a thought.

Edit: The guy deleted the video.. wow... It was just him autoattacking a5.2 monsters and sometimes it just didn't display any dmg and the monster didn't lose any.

**Comment by Ciapa** [comment]
fixed
