### ISSUE TITLE
When you die, you don't respawn with 1 HP & 1 MP

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1611]
When you respawn you never have 1 HP/MP need to check that

**Comment by MasterDomino** [comment]
u do but we need to add delay on characterlife manager after death since it stats regen on exactly the same time as you respawn

**Comment by MasterDomino** [comment]
this should already have been fixed

**Comment by Ciapa** [comment]
Duplicate and fixed
