### ISSUE TITLE
Stuck after die

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1614]
1.) Summon Caligor at NosVille
2.) Die
3.) Revive
4.) Caligor will kill you again even if you are not beside, you have 0 HP now and you are stuck. You need to reconnect to fix this problem

**Comment by Uppermost** [comment]
https://gyazo.com/aeb33d3a4d2dc46fec9422da865b880a after that impossible to do nothing obligation to disconnect.

**Comment by Ciapa** [comment]
Fixed
