### ISSUE TITLE
Item Id 1078 for sp points

### ISSUE THREAD

**Issue by story342** [OpenNos/OpenNos#1616]
when i use saying your received 0 sp points

**Comment by Uppermost** [comment]
reparse your database it work if you do it

**Comment by story342** [comment]
how many times to reparse i just reparse like 10 hours ago

**Comment by Uppermost** [comment]
I don't know how much time ago but it work for me please retry with new version

**Comment by chucktheripper** [comment]
@story342 If you are using unstable development versions, you actually need to reparse after each update to be sure you have a working instance.
