### ISSUE TITLE
When a player dies in act 6 appears here

### ISSUE THREAD

**Issue by JOAOMASTER** [OpenNos/OpenNos#1617]
![20161127-1-prueba](https://cloud.githubusercontent.com/assets/17860577/20649130/477a6706-b48e-11e6-9151-ec60ea11d8b8.jpg)
![20161127-2-prueba](https://cloud.githubusercontent.com/assets/17860577/20649129/4778de22-b48e-11e6-9f7b-5ed138996488.jpg)

**Comment by 0Lucifer0** [comment]
Just add the correct respawn point in database

**Comment by Uppermost** [comment]
You need to reparse after my commit
