### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by CryForMe9** [OpenNos/OpenNos#1619]
![error](https://cloud.githubusercontent.com/assets/19311044/20651492/c467f85c-b4e6-11e6-8b26-968bc50efa16.PNG)
 
cant say more

**Comment by MasterDomino** [comment]
ill rape you

**Comment by Ciapa** [comment]
Error already found
fix in ~2 minutes

**Comment by CryForMe9** [comment]
Thank you
