### ISSUE TITLE
Always when you die you got teleport 0 10 0 or something like this

### ISSUE THREAD

**Issue by Uportorst** [OpenNos/OpenNos#1620]
Its updated to date... i think its something wrong here

**Comment by Uppermost** [comment]
No detals > Closed I'm also at the latest version and I don't have your problem

**Comment by Uportorst** [comment]
are you kidding me?

**Comment by Uportorst** [comment]
i updated this on pc. on vps. its usseles

**Comment by Uportorst** [comment]
always when you die you go in another map

**Comment by 0Lucifer0** [comment]
You need to parse correctly respawnmaptype

**Comment by Uportorst** [comment]
what you mean with corectly
