### ISSUE TITLE
monster HP refresh issue

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1622]
https://gyazo.com/d9bd2802843fe48ad32bcd2405df225f
As you can see his life bar is buggy

**Comment by earthnash** [comment]
I have reported in #958 comment 9
:/

**Comment by Ciapa** [comment]
Where the issue has fucking nothin to do with what you reported. It is an Issue with MonsterLife, not TargetHit...

**Comment by Uppermost** [comment]
Not fixed btw

**Comment by Uppermost** [comment]
Not fixed.

**Comment by MasterDomino** [comment]
Current state of this issue?

**Comment by 0Lucifer0** [comment]
Still here
