### ISSUE TITLE
If you die in lod you go here 0 10 0

### ISSUE THREAD

**Issue by Uportorst** [OpenNos/OpenNos#1624]
It happend only lod map 150 i think need to add this on maptype?

**Comment by MasterDomino** [comment]
@Uportorst can you send us ss of your database table of RespawnMapType and Respawn please

**Comment by 0Lucifer0** [comment]
Thats because lod Will be instantiate like act4 ts and raid map ;)

**Comment by Uppermost** [comment]
Uportorst funny nickname 😂 We can't add nosville by default for now ?

**Comment by 0Lucifer0** [comment]
just update

**Comment by Uportorst** [comment]
ok thx! now its working
