### ISSUE TITLE
DisconnectionForced Exception

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1632]
2016-11-28 22:37:32,517 [25] ERROR OpenNos.World.Program [(null)] - Client 21 forced Disconnection, login has not been registered or Account is already logged in.

After this error you can't log something you need to reset the loginserver to be allowed to connect. This problem is very problematic even if it occur not very often, we need to auto disconnect the account after like 3/5 minuts but I don't know If you have an idea Chuck

**Comment by xKaddo** [comment]
You only need to restart the login server, not the whole server.

**Comment by MasterDomino** [comment]
@xKaddo Already in issue with wcf

**Comment by MasterDomino** [comment]
"problem is very problematic", sorry but i had to xD

**Comment by MasterDomino** [comment]
does it still occur after usage of WebApi?

**Comment by Ciapa** [comment]
Auto Disconnect is still not working. Maybe add a Pulse call to WebAPI when World receives pulse Packet and if that packet is older than like 5 Minutes or too fast(Speedhack), dc the session and kick it from World
