### ISSUE TITLE
Drop by MapTypeId doesn't work on monsters without drops by MonsterVNum

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1635]
I just added Act 5.1 to my server yesterday.
Some monsters don't have any drops assigned to them in the database, but there are drops set by MapTypeId.
These don't seem to work on monsters that have no drops assigned to them by MonsterVNum, but works on monsters which have other drops assigned to them.

**Comment by MasterDomino** [comment]
not possible because of that 
```csharp
Where(s => Session.CurrentMap.MapTypes.Any(m => m.MapTypeId == s.MapTypeId) || (s.MapTypeId == null))
```
even if they dont have drops assigned they should have maptypeid drops assigned.
