### ISSUE TITLE
No connection string named 'OpenNosContext' could be found in the application config file.

### ISSUE THREAD

**Issue by ValerioBala** [OpenNos/OpenNos#1637]
When i run the command update-database -Verbase, this message "No connection string named 'OpenNosContext' could be found in the application config file." comes out. The file on the tutorial are older than mine, someone can help me?

**Comment by Uppermost** [comment]
Please use our discord server for question like that

**Comment by Ciapa** [comment]
@ValerioBala Not possible with clean Source. RTFM and then try again.
