### ISSUE TITLE
You get combat exp when you are dead

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1647]
You should only be able to receive job exp while you are dead (that#s how it is on official at least).

**Comment by Uppermost** [comment]
If we need to do like official we need to only allow joblevel.

**Comment by MasterDomino** [comment]
![image](https://cloud.githubusercontent.com/assets/16002990/20826960/df7df48a-b86e-11e6-8868-d7b01df6bc7e.png)
this cant be the thing theres already check for that

**Comment by MasterDomino** [comment]
fixed, propably :P
