### ISSUE TITLE
Add basic family system

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1648]
We need to add the family system :) packet will come there soon

- [x] Add creation familly system

- [x] Add family & characterfamily db

To add in db (maybe more)
------------
FamilyDate
FamilyEnterDate
FamilyRank
FamilyName
FamilyLevel
FamilyIntro
FamilyOwner
FamilyExpAmount
MemberCount
MaxMember
MemberRang/Authority

I can provide packets.

**Comment by Uppermost** [comment]
Once upon a time there was a courageous man named Lucifer. This man is assigned an obscure mission. **# CODING THE FAMILY SYSTEM**

**Comment by MasterDomino** [comment]
someone was faster than me and table is already done ;) or maybe it was me loong time ago

**Comment by Ciapa** [comment]
Need to check if family database is complete for my needs of implementing Family stuff

**Comment by Pescatore981** [comment]
an information server when this will open?

**Comment by MasterDomino** [comment]
sorry but we dont understand retard language

**Comment by Pescatore981** [comment]
one thing the server will open tonight because tomorrow I type in 8:30 that aspect lavevate opened 30 minutes and then you have it closed again XD

**Comment by Ciapa** [comment]
Can you please stop spamming our issues? If you keep doing this, we have to ban you!
Please be patient until our server arrives.

**Comment by MasterDomino** [comment]
we never opened the server yet, we are waiting for new dedicated machine cuz VPS was broken with threads, it should be here tommorow, or today if we want to test performance, please this discussion is not for github, connect to our discord and ask there

**Comment by Pescatore981** [comment]
I can not wait and at 14:30 I connected to the server I played there and 15 on time and I came out because it was disconnected; (

**Comment by Ciapa** [comment]
STOP SPAMMING OUR ISSUES! OUR SERVER WAS NOT ONLINE BEFORE! ONE MORE COMMENT AND I WILL BAN YOU PERMANENTLY!

**Comment by Uppermost** [comment]
@Ciapa this issue can be closed right now.
