### ISSUE TITLE
Add blacklist system

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1649]
//When you tried to blacklist someone (SlayerD²) on this example
blins 633833
blinit 648879|[Joker]™ 756887|Artkey 617879|MasterLars 743308|++El-Nariz 774620|†Slayon† 98671|Miraginaire 783589|smbfdp 715280|Plagu£ 747349|ArChEr-Du-MaL 98093|abderdulabo 725148|¤Styxe¤ 601648|XAirdemX² 709825|WhayRow\™/ 291478|¤£uffy¤ 648302|Dr@gonBleue 751532|Anthioumane 444687|bigpapajo 792279|leretour=) 486799|(TWO) 790877|ZerkPabloZoo 633833|SlayerD²
info Enregistré

blins 633833
info Tu ne peux pas ajouter des membres de ta famille à la liste noire.

blins 633833
info Tu ne peux pas ajouter des amis à la liste noire.

//Remove someone (SlayerD²) of your blacklist
bldel 633833
info Supprimé
blinit 648879|[Joker]™ 756887|Artkey 617879|MasterLars 743308|++El-Nariz 774620|†Slayon† 98671|Miraginaire 783589|smbfdp 715280|Plagu£ 747349|ArChEr-Du-MaL 98093|abderdulabo 725148|¤Styxe¤ 601648|XAirdemX² 709825|WhayRow\™/ 291478|¤£uffy¤ 648302|Dr@gonBleue 751532|Anthioumane 444687|bigpapajo 792279|leretour=) 486799|(TWO) 790877|ZerkPabloZoo

//When you tried to send a private message to someone who blacklist you
info Tu es déjà sur sa liste noire.

**Comment by Ciapa** [comment]
Fixed in private repo

**Comment by Uppermost** [comment]
fixed
