### ISSUE TITLE
Add friendlist system

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1650]
//Friend receive ask
dlg #fins^-1^633833 #fins^-99^633833 Veux-tu devenir ami avec SlayerD² ?

//When you sent a friend request
fins 1 633833

//Friend accepted
finit 702263|0|0|lefenek 685985|0|0|`°WaRRiORoX°` 767543|0|0|Saarah*-* 91159|0|0|Shunraï 457639|0|0|jack-atlus 202108|0|0|The-Link 494942|0|0|HexaYoan3 627812|0|0|guiguifoufou² 84085|0|0|Lego 720120|0|0|Mioute 719180|0|0|lucaslylou 739150|0|0|Tanjiro 650379|0|0|Ludokaira² 720119|0|0|Miout 396235|0|0|Babax-xXx 740506|0|0|Yzigor 654501|0|0|Shizoune 710661|0|0|-Akimaru 675012|0|0|Alexia¤~ 704532|0|0|~Veigar~ 664276|0|0|Voltana` 555291|5|0|CoOkies` 475461|0|0|Pikminus 626092|0|0|*LotuS* 767387|0|0|Kaary 425075|0|0|FredericLin785 571697|0|0|-¤NécroSkullz¤ 756559|0|0|Hamiel` 786513|0|0|•Erathia•™ 363001|0|0|¤Légendary¤ 787514|0|0|0Luçif£r0 422938|0|0|Luffy-kun 430758|0|0|Fail 714198|0|0|Entourage 558150|0|0|NiiSha_ 733188|0|0|Oasis’ 535082|0|0|Otaku~Girl 291219|0|0|devil-jojo 685803|0|0|Kyohai 704242|0|0|•Odin• 609054|0|0|hargon 768943|0|0|Patatosaure 698604|0|0|KuanYin 570243|0|0|pyrando 737179|0|0|Sayu` 574011|0|0|Milow* 286174|0|0|diablolordee 591344|0|0|~¤OCB¤~ 723794|0|0|ZeyNaa69 420516|0|0|*Hunter* 623673|0|0|NiiSha 319210|0|0|SilverTorch 741878|0|0|Aikona 736751|0|0|Kohina 692557|0|0|Crâpouille 652944|0|0|Arkasia 769584|0|0|†Yamaha† 104963|0|0|Elvin 727606|0|0|Akimitsu` 796508|0|0|*_kello_* 760709|0|0|¤°Fraise°¤ 521919|0|0|ChachaNeko 633833|0|1|SlayerD²
info Enregistré
finfo  702263.0 685985.0 767543.0 91159.0 457639.0 202108.0 494942.0 627812.0 84085.0 720120.0 719180.0 739150.0 650379.0 720119.0 396235.0 740506.1 654501.0 710661.0 675012.0 704532.0 664276.0 555291.0 475461.0 626092.0 767387.0 425075.0 571697.0 756559.0 786513.0 363001.0 787514.0 422938.0 430758.0 714198.0 558150.0 733188.0 535082.0 291219.0 685803.0 704242.0 609054.0 768943.0 698604.0 570243.0 737179.0 574011.0 286174.0 591344.1 723794.1 420516.0 623673.0 319210.0 741878.0 736751.0 692557.0 652944.0 769584.0 104963.0 727606.0 796508.0 760709.0 521919.0 633833.1

//Join mini land
guri 0 1 782387 3 0
guri 19 1 782387 1824
guri 0 1 782387 0 0
guri 19 1 782387 1825
guri 19 1 782387 1826
guri 2 1 626114
esf

//Delete friend
finit 702263|0|0|lefenek 685985|0|0|`°WaRRiORoX°` 767543|0|0|Saarah*-* 91159|0|0|Shunraï 457639|0|0|jack-atlus 202108|0|0|The-Link 494942|0|0|HexaYoan3 627812|0|0|guiguifoufou² 84085|0|0|Lego 720120|0|0|Mioute 719180|0|0|lucaslylou 739150|0|0|Tanjiro 650379|0|0|Ludokaira² 720119|0|0|Miout 396235|0|0|Babax-xXx 740506|0|0|Yzigor 654501|0|0|Shizoune 710661|0|0|-Akimaru 675012|0|0|Alexia¤~ 704532|0|0|~Veigar~ 664276|0|0|Voltana` 555291|5|0|CoOkies` 475461|0|0|Pikminus 626092|0|0|*LotuS* 767387|0|0|Kaary 425075|0|0|FredericLin785 571697|0|0|-¤NécroSkullz¤ 756559|0|0|Hamiel` 786513|0|0|•Erathia•™ 363001|0|0|¤Légendary¤ 787514|0|0|0Luçif£r0 422938|0|0|Luffy-kun 430758|0|0|Fail 714198|0|0|Entourage 558150|0|0|NiiSha_ 733188|0|0|Oasis’ 535082|0|0|Otaku~Girl 291219|0|0|devil-jojo 685803|0|0|Kyohai 704242|0|0|•Odin• 609054|0|0|hargon 768943|0|0|Patatosaure 698604|0|0|KuanYin 570243|0|0|pyrando 737179|0|0|Sayu` 574011|0|0|Milow* 286174|0|0|diablolordee 591344|0|0|~¤OCB¤~ 723794|0|0|ZeyNaa69 420516|0|0|*Hunter* 623673|0|0|NiiSha 319210|0|0|SilverTorch 741878|0|0|Aikona 736751|0|0|Kohina 692557|0|0|Crâpouille 652944|0|0|Arkasia 769584|0|0|†Yamaha† 104963|0|0|Elvin 727606|0|0|Akimitsu` 796508|0|0|*_kello_* 760709|0|0|¤°Fraise°¤ 521919|0|0|ChachaNeko

//When someone decline your friend ask
info Tu es bloqué.

//Friend full
???? (maybe info packet too)

//Already in friend
info Tu es déjà ami avec ce joueur.

//Information of your friend (only work if the problem is on same map of you)
req_info 1 633833
tc_info 20 SlayerD² 0 0 0 1 -1 - 3 1 1 0 0 1 0 0 1 2 0 0 0 246 0 0 0 -1 0 0 0 0 10 0 0 0 0 0 0 Pas de message de présentation.

**Comment by Ciapa** [comment]
Fixed in private repo

**Comment by Uppermost** [comment]
fixed
