### ISSUE TITLE
Add Family system command

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1655]
To invite a player in family
To send a message for every family member
To kick a player from the family
To change member rank...

Family command use "%"

**Comment by Ciapa** [comment]
Problem is, do we use customizable Packet Names? Since by default, it's different in each language(Family Command use native language)
I'd say to just implement the english ones by default. Can be changed by hand if someone wants different names

**Comment by 0Lucifer0** [comment]
we could use the language for something like @"%{language.Instance.getFromKey("REQUESTFAMILLYCOMMAND")}"
