### ISSUE TITLE
Worldserver shows someone with Session: 0, but you can't find him in the loginlog.

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1656]
2016-12-02 17:22:34,346 [29] DEBUG OpenNos.World.Program [(null)] - Session: 0 Method: RemoveItemAmount Packet: Remaining 30/30, removing item 1012 from Slot 0 with amount 99

Should be impossible to have session 0,, or am I wrong here?

**Comment by JOAOMASTER** [comment]
I recommend you make screenshot of the errors since when it occurs in the console or in the game

**Comment by xKaddo** [comment]
@JOAOMASTER  I'm always getting told NOT to post pictures.
It's just as I copy and pasted. Nothing else.

**Comment by MasterDomino** [comment]
well you actually just copy pasted 1 line from whole console thats not gonna help, instead taking ss of exactly whole exception would be good, and running in debug mode on vs also helps ;)

**Comment by xKaddo** [comment]
I couldn't find the exception, that was the problem..
Anyway, I'll try finding it once I see it happening again~

**Comment by MasterDomino** [comment]
@xKaddo sure, as always thanks for your help to the project :)

**Comment by xKaddo** [comment]
Okay, I just created a new logfile. No exception, lol. But again, there's a user with the Session 0.
