### ISSUE TITLE
Crash world

### ISSUE THREAD

**Issue by Uportorst** [OpenNos/OpenNos#1658]
https://images.discordapp.net/.eJwFwVEOgyAMANC7cABaCijzNgQJmmlLoGYfy-6-977mGZfZzKHa5wawn7PI2O1UGblV20TaVXM_py1yQ1bN5bgr6wQKr5Aw-eRpxUAYCSiG1WNcnAsOE-IS4eE3y4dt52Z-fwUxIsU.IxfU43H1YJShTsX8Lq6Ww1nKTNE

**Comment by Uportorst** [comment]
Sometimes not happening for 7 8 9 10 hours and sometimes happening all 30 mins or 20

**Comment by MasterDomino** [comment]
means your db is broken cuz there cant be more than 1 item per slot
