### ISSUE TITLE
Can't attack or move after hitting a monster that just started moving

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1659]
When you hit monsters as a **melee** and it just started moving, you won't be able to move or attack. You can still use mounts, sp's etc but are forced to relog to be able to play again.

It's easy to reproduce on fagtale.
If you want a gif, tell me.

Edit: Not only for meeles, happens to ranged characters aswell.

**Comment by Uppermost** [comment]
Since when?

**Comment by xKaddo** [comment]
Since I just updated earlier (not the code cleanup of domino)

**Comment by MasterDomino** [comment]
its for sure by my cleanup
but its small issue better find it and fix

**Comment by PainM4K3R** [comment]
Find it and fix it, please :)

**Comment by chucktheripper** [comment]
fix incoming

**Comment by Uppermost** [comment]
I can reproduce it again with adventurer.

**Comment by xKaddo** [comment]
Not fixed.
