### ISSUE TITLE
NRE targetSession

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1666]
https://gyazo.com/e798b9b5709c690652663d523308a459

**Comment by Ciapa** [comment]
@xKaddo Need to check against Session.Character.ExchangeInfo null

**Comment by xKaddo** [comment]
@Ciapa  uhh,I know that targetSession (at the start) was null, I closed it already, sorry. I'll check it again once it reoccurs

**Comment by Ciapa** [comment]
@xKaddo Nah, we found what causes the issue I think, Domino fixes it
