### ISSUE TITLE
Broken Command system

### ISSUE THREAD

**Issue by BlowaXD** [OpenNos/OpenNos#1668]
http://prntscr.com/di9st3

I'm looking forward, If i success to fix it i'll push it asap ;)

**Comment by Uportorst** [comment]
Really i have the same problem u.u i just want to report this too but you created an issue :)

**Comment by Uppermost** [comment]
How can we reproduce it  please give more details ? Since when?

**Comment by BlowaXD** [comment]
I'm looking forward over commits that has been done, i'll push a fix asap if i'm able to solve this :)

**Comment by BlowaXD** [comment]
Since last update
Doing most of the commands will help you reproduce it

**Comment by BlowaXD** [comment]
(Title is self explaining the issue btw)

**Comment by BlowaXD** [comment]
Seems fixed, i'm pushing it :) (bad changes were made)

**Comment by Uportorst** [comment]
u.u nice man nice work!

**Comment by BlowaXD** [comment]
Nothing hard, just a bad change that has been made in a commit that broke $Stat and more commands

**Comment by BlowaXD** [comment]
Pull request made !
