### ISSUE TITLE
Crash when type $Stat

### ISSUE THREAD

**Issue by ValerioBala** [OpenNos/OpenNos#1671]
Whenever i try to digit the command $Stat this appears
![image](https://cloud.githubusercontent.com/assets/24271200/21119920/0aa7b3ea-c0c5-11e6-8fc4-ab2d9686ae80.png)

**Comment by Ciapa** [comment]
invalid

**Comment by HolzingerAlexander** [comment]
@Ciapa Please bring it back before the next release.

**Comment by Ciapa** [comment]
There is no crash right now
