### ISSUE TITLE
World Crash

### ISSUE THREAD

**Issue by Uportorst** [OpenNos/OpenNos#1681]
![captura](https://cloud.githubusercontent.com/assets/24213444/21203771/6370bfea-c254-11e6-870f-b142057dcfbb.PNG)

**Comment by Ciapa** [comment]
Not enough information. Provide Local and Autos Window from Visual Studio Debugger

**Comment by Uportorst** [comment]
![captura](https://cloud.githubusercontent.com/assets/24213444/21204115/020b5db2-c256-11e6-958c-feb11a60e4e5.PNG)
