### ISSUE TITLE
double acc with one account

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#1685]
sorry delete please

**Comment by Ciapa** [comment]
@aerzy Not reproducible, shouldn't even work at all, Azerty in SHA512 is sth different than azerty

**Comment by aerzy** [comment]
ah yes sorry is only ID

**Comment by Ciapa** [comment]
@aerzy Still not reproducible

**Comment by aerzy** [comment]
first account in select character

**Comment by aerzy** [comment]
in channel select* sorry

**Comment by Ciapa** [comment]
@aerzy that is normal, you can then only login with one account, cause the first session gets invalidated

**Comment by aerzy** [comment]
![image](https://cloud.githubusercontent.com/assets/16693364/21242400/7faaaf0c-c314-11e6-8074-6b462e8975dd.png)

**Comment by aerzy** [comment]
@Ciapa on channel select u connect u're account with ID in upcase and pw normal and u have 2 acc connected
