### ISSUE TITLE
SP 8 WARIOR BUGG SKILL Double Ripping

### ISSUE THREAD

**Issue by Uportorst** [OpenNos/OpenNos#1686]
If you go to a portal and use this skill you are teleport out of the map This skill 
![captura](https://cloud.githubusercontent.com/assets/24213444/21243934/85924b3a-c31b-11e6-99a2-317c9f0f0add.PNG)

**Comment by MasterDomino** [comment]
@Uportorst already in hit issue

**Comment by Uportorst** [comment]
oh i didnt see
