### ISSUE TITLE
Poseidon skill not enough mana

### ISSUE THREAD

**Issue by Uportorst** [OpenNos/OpenNos#1687]
Not enough mp to use that skill:
![captura](https://cloud.githubusercontent.com/assets/24213444/21274476/bad79a22-c3c8-11e6-9543-8da0867b294a.PNG)
and the last you can use only 1 time something like this:
![captura](https://cloud.githubusercontent.com/assets/24213444/21274505/d093af36-c3c8-11e6-878c-70ee3bcc1cfa.PNG)
SP 6 SWORD Only 1 time:
![captura](https://cloud.githubusercontent.com/assets/24213444/21275053/492eb038-c3cb-11e6-8add-f51cb532559d.PNG)
Here another not enough mana skill on gladiator sp 5 warior:
![captura](https://cloud.githubusercontent.com/assets/24213444/21276271/f3085e24-c3d0-11e6-87c2-386e9ae9d92c.PNG)
Not enough mp to use that skill sp 7 warior:
![captura](https://cloud.githubusercontent.com/assets/24213444/21276362/4f5b0d20-c3d1-11e6-926d-410363d0a0f4.PNG)
Not enough mp to use that skill sp 8 warior:
![captura](https://cloud.githubusercontent.com/assets/24213444/21276421/a84ede16-c3d1-11e6-9fb3-3c14e014f24b.PNG)
![captura](https://cloud.githubusercontent.com/assets/24213444/21276451/cb782780-c3d1-11e6-882d-e69467040a8e.PNG)
SP 8 Mage not enough mp:
![captura](https://cloud.githubusercontent.com/assets/24213444/21276558/47a8d318-c3d2-11e6-9190-aef346cff44e.PNG)
SP 7 mage no mp
![captura](https://cloud.githubusercontent.com/assets/24213444/21276641/a849e8d8-c3d2-11e6-9f38-3add9c8e67f3.PNG)
Only 1 time SP 7 MAGE
![captura](https://cloud.githubusercontent.com/assets/24213444/21276769/2fed5040-c3d3-11e6-9d39-62ceb41c94d1.PNG)
![captura](https://cloud.githubusercontent.com/assets/24213444/21276803/59c473f8-c3d3-11e6-8a07-f7aac0746226.PNG)
SP 6 archer only 1 time:
![captura](https://cloud.githubusercontent.com/assets/24213444/21277606/824958da-c3d7-11e6-9b09-4d85f516fb54.PNG)
![captura](https://cloud.githubusercontent.com/assets/24213444/21277614/9069e2fe-c3d7-11e6-91ef-b510528e0fcf.PNG)
![captura](https://cloud.githubusercontent.com/assets/24213444/21277622/9bbdb590-c3d7-11e6-8c8c-6c0b17d2b833.PNG)

**Comment by xKaddo** [comment]
Also, the first renegade skill you mentioned can be used sometimes when there are more monsters, but will instasntly reset its cooldown for another use.
