### ISSUE TITLE
Cancel after everyhit

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1690]
https://gyazo.com/41a00635e36a91df52b7f3ae7ad770e5

![image](https://cloud.githubusercontent.com/assets/15254478/21287783/c287c980-c473-11e6-81b1-029ebc1ed100.png)
The problem come from there

**Comment by Ciapa** [comment]
Nope, either no weapon or skill can't be used

**Comment by Uppermost** [comment]
Not completly fixed try with SP1 Archer and don't move you will see again the problem...

**Comment by Uppermost** [comment]
Not reproducible
