### ISSUE TITLE
Trade

### ISSUE THREAD

**Issue by Uportorst** [OpenNos/OpenNos#1696]
You have inventory full something like this
![captura](https://cloud.githubusercontent.com/assets/24213444/21297101/da85d336-c579-11e6-944d-2dc81de721c7.PNG)
if someone send me any item but 99 like here saying i have full inventory 
![captura](https://cloud.githubusercontent.com/assets/24213444/21297130/ffec7238-c579-11e6-9184-5b93b72bfd89.PNG)
but if someone send you only 1 item or 87 deppends the item dissapearing and saying dont care about if someone send you trade and you have full items inventory the trade completing not saying the trade was cancel because not enough space its completing the trade and you lose the item and the other not receive anything

**Comment by Ciapa** [comment]
Duplicate
