### ISSUE TITLE
Hay Guys ! :]

### ISSUE THREAD

**Issue by Deluxe97** [OpenNos/OpenNos#1704]
Hello Guys I am new at the Opennos project and have a big problem, I do not know if this is the right place to write therefore so lease excuse me if it is not so. I have a lot of Experience about Visual Studio but nevertheless I come here not further I hope you can help me 

Link: http://www.fotos-hochladen.net/view/ladenfehlgesch0ksy4rl1cm.png

**Comment by chucktheripper** [comment]
@Deluxe97 Hay!

You try to open a Visual Studio project with Blend! Maybe you need to extend your experience before you contribute.

**Comment by Deluxe97** [comment]
i Open it because with Visual Studio 2015 but nothing happens
