### ISSUE TITLE
Wrong stuff taken for crafting

### ISSUE THREAD

**Issue by ValerioBala** [OpenNos/OpenNos#1717]
Hi! All my players had the same problem:
I made the 92 weapons and 95 craftable with the last one. The problem is that, even if they use a new one (due to keep the r6/7+x stuffs) when they try to equip the crafted weapon, their original r6/7+x suffs disappear. At the moment the only way without risks is to give to a friend the weapon and then craft the new weapons

**Comment by 0Lucifer0** [comment]
that's normal there is no such things on official.
