### ISSUE TITLE
wrong damage reduction for melee (archer)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1720]
1200 melee 2400 distance on official it's too much we should only reduce to like 30% of something like that 100% is very too much I've tried on official it's much like 30% of reduction and it's penalizing in pvp

**Comment by unknownforces** [comment]
Are you talking about the damage dealt? cause on official its 50% reduced

**Comment by 0Lucifer0** [comment]
will be fix by the new damage system
