### ISSUE TITLE
(maybe) Server/Client issue

### ISSUE THREAD

**Issue by NooCi** [OpenNos/OpenNos#1722]
I recognized an issue if u do PVP. When u try to hit with a close range SP a long range SP u won't attack. Maybe this is a server/client issue. While the long range guy attacks he can click away but his character in the game stays and hit 1 time, while he is doing that the server maybe "see" him at another position, due to his clicking at another position, as the client do. I hope u know what I mean^^.

**Comment by Ciapa** [comment]
@NooCi Same as on official. If i got you right: this is also called outrunning.

**Comment by NooCi** [comment]
okay, but is it a bug or a feature? Because I don't get it. For me, it seems not normal to hit one who is right in front of me. The result is i did 1k dmg in 1 min and I'm dead because I hit him twice. if I would see him running away, okay, fine, no problem but if I'm right in front of him standing still for 1 or 1 1/2 secs and don't do anything while he is hitting me it feels unbalanced and wired. I even cant use skills because of the delay (i hope it is one).

**Comment by NooCi** [comment]
dont hit one*

**Comment by Ciapa** [comment]
@NooCi Get better Network, movement and hit is fine. So problem on your end

**Comment by Uppermost** [comment]
Need to be checked I'm also sure this problem doesn't happens on official I'm often blocked on opennos after try to hit my character stop th follow the occurent and I never had this poblem on official I will try again...

**Comment by NooCi** [comment]
yes, it cant be my network. i can try to get some screens later and edit them so u know what i mean.^^

btw the "range guy" stands still and attacks me and just in this moment he click at the other site of the map. At "his" view and my view the character is right infront of me, really it is like I'm standing next to him and we are taking a pic, but I just dont attack (tested it with 2 pcs and other people wich all report the same problem).
