### ISSUE TITLE
Drop always on the same place

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1723]
All on the title when you drop an item it's ALWAYS at the same place and not random beside you.

**Comment by unknownforces** [comment]
Same as #1705

**Comment by Uppermost** [comment]
Not fixed... You always see other player drop at the same X Y

**Comment by MasterDomino** [comment]
that should be fixed long time ago, also noticed that with big drops on official files they tend to drop in 1 spot, now it works properly.
