### ISSUE TITLE
CLIENT ERROR

### ISSUE THREAD

**Issue by potsss098851** [OpenNos/OpenNos#1743]
![capture](https://cloud.githubusercontent.com/assets/25246774/22150302/3eee894c-df53-11e6-81e7-20a73e015c18.PNG)

I can't launch the client just now.

**Comment by potsss098851** [comment]
I thought this is some kind of issue, doesn't it?

**Comment by 0Lucifer0** [comment]
no this is github of opennos project not opennos server support system.

**Comment by MasterDomino** [comment]
you never report launcher issues here on opennos development github ._______________.
