### ISSUE TITLE
inform server sided about missing maps

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#175]
The server should tell you that you have no maps imported, otherwise nothing will work.

**Comment by 0Lucifer0** [comment]
for the moment the server tell you the amount of maps imported so 0maps = no maps imported^^

**Comment by chucktheripper** [comment]
yep but if there are absolutely no maps there need to be an error

**Comment by 0Lucifer0** [comment]
the problem is if you try to create the character on a inexistant map ^^(insert_error)

**Comment by chucktheripper** [comment]
We should just add this information to the server messages, that he cannot do anything without a map

**Comment by 0Lucifer0** [comment]
done
