### ISSUE TITLE
Speedbug: Warrior and means of transportation

### ISSUE THREAD

**Issue by Shortyoo** [OpenNos/OpenNos#1758]
A example with the Jeep:
If you use the jeep, the "transportation bar" will pop up. If you now, before you're transformated, use the moral skill, you transform and use the jeep in the same time. Now, if you unequip your vehicle, you have + permanent motionspeed. 
The bug is stackable, but you will get kicked if you use it two times and run for about a minute.

I hope someone understand what I mean.

**Comment by 0Lucifer0** [comment]
will be fix with buff review #1775
