### ISSUE TITLE
Wrong history shown when changing deputy/keeper

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#1762]
As title says, when changing someones rank, it says "*** Has changed the authorities : Family member - impossible" It should show "*** has made *** Keeper/deputy" Also it shouldn't change deputy/keeper authority each time you change someones rank

**Comment by unknownforces** [comment]
Also, when changing someones rankings, it stays the same in the thing (it should be refreshed to the new rank) and when using %Familyshout, it says "<familycall> message" it should just be "Message"

**Comment by Ciapa** [comment]
@unknownforces No, it's not just Message
