### ISSUE TITLE
Database Error How to update database

### ISSUE THREAD

**Issue by RiverCZE** [OpenNos/OpenNos#1765]
[ERROR] 19:25:56 -- Database may not be up to date. Please consider updating your database.

**Comment by MasterDomino** [comment]
@RiverCZE Update-database

**Comment by RiverCZE** [comment]
Error Number:547,State:0,Class:16
The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_dbo.FamilyCharacter_dbo.Character_CharacterId". The conflict occurred in database "opennos", table "dbo.Character", column 'CharacterId'.

**Comment by RiverCZE** [comment]
Please help
