### ISSUE TITLE
error in update db

### ISSUE THREAD

**Issue by RiverCZE** [OpenNos/OpenNos#1766]
Error Number:547,State:0,Class:16
The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_dbo.FamilyCharacter_dbo.Character_CharacterId". The conflict occurred in database "opennos", table "dbo.Character", column 'CharacterId'.

**Comment by RiverCZE** [comment]
![image](https://cloud.githubusercontent.com/assets/25406669/22563084/7f0c175c-e97f-11e6-98c1-77a082512596.png)

**Comment by CryForMe9** [comment]
Just delete the this in the Character Table
