### ISSUE TITLE
bug act 4

### ISSUE THREAD

**Issue by Fizo55** [OpenNos/OpenNos#1767]
![image](https://cloud.githubusercontent.com/assets/20739405/22618646/283707ca-eae2-11e6-9f2a-0c33e0b5ec82.png)

Demons and angels can talk and see their pseudo in act 4 The pvp is made between family while his it should be in the arena family x) and also when we kill a person act 4 the person loses of the reputation but we do not win it and I take advantage of it to say that we lose of the dignity when we die pvp there

**Comment by Ciapa** [comment]
@Fizo55 Well, you are just too stupid and cant read the Updates properly. No bug
