### ISSUE TITLE
finish/review buff system

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#1775]
My fam member still misses a ton on me even with morale (he uses 90 fake sword I use 96 armour) with morale on official, you basically never miss no matter what level they are and mobs + players still hit me and him very often even with morale, it is basically useless too.
and sin buff doesn't increase the dmg at all, it's useless.

**Comment by unknownforces** [comment]
I know it's already known but just so it's not forgotten ; Need to fix buffs not showing for other people

**Comment by 0Lucifer0** [comment]
Remove from CARD : Type Subtype FirstData SecondData

Create table BCard :
-BCardId(short)
-Type(CardType)
-Subtype(Byte)
-FirstData(int)
-SecondData(int)

Each Card can have 0 to many BCard(FK DirectBuff)
Each Card can have 0 to many BCard(FK DelayedBuff)
