### ISSUE TITLE
Range problem

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#1792]
When I attack with dg, even when it says i can attack at that range, my char just stands there and doesnt attack, i have to walk really close to the mob/person. Not sure if it is like this with other sps, but most likely.

**Comment by Ciapa** [comment]
@unknownforces It's range being missconfigured. Fixing dark gunner soon.

**Comment by unknownforces** [comment]
It also doesnt attack if you walk out of range a little bit, for example on swordie sps. but on official it still attacks regardless.  So hopefully that's changed too
