### ISSUE TITLE
Bug private shop - inventory

### ISSUE THREAD

**Issue by Fizo55** [OpenNos/OpenNos#1799]
Hello, Then 1-Double Account 2 - Have the full inventory on an account 3 - Open a store with the one who has no full inventory 4 - to Buy the item with the one who in the full inventory 5 - The gold of the one who buy the item do not fall but that of that who(which) in opened the store rises

**Comment by BlowaXD** [comment]
It's already fixed there.
I can push a fix if OpenNos team accept.

**Comment by 0Lucifer0** [comment]
we won't accept any push on this git because we will have history trouble.
