### ISSUE TITLE
wcf crash after a random time

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#180]
after a random time there is a System.ServiceModel.CommunicationObjectFaultedException
![capture d ecran 2016-01-24 14 16 11](https://cloud.githubusercontent.com/assets/15112753/12536435/4bfc3b00-c2a5-11e5-9648-7f886d1e7fe4.png)

**Comment by chucktheripper** [comment]
fixed with new initialzying the wcf client if its in faulted state
