### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by NosReturn** [OpenNos/OpenNos#1800]
![captura](https://cloud.githubusercontent.com/assets/19887335/22854168/3ceba3de-f068-11e6-8197-3ff8e2e0d531.PNG)

**Comment by NosReturn** [comment]
already in bug where here no bug with that issue im done 99,99

**Comment by Ciapa** [comment]
It's just your stupidity.

**Comment by 0Lucifer0** [comment]
that just because you missconfigured language check...
