### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by Asasin288** [OpenNos/OpenNos#1806]
I have a little problem .
I can not connect to the database or something blocking me.
I have installed:
-Mssql 2016
-SSMS
-Visual Studio (+ StyleCop)
-SSDT
screen:
![login](https://cloud.githubusercontent.com/assets/25817399/23017817/157fb114-f43c-11e6-83ed-21256058650b.PNG)
![word](https://cloud.githubusercontent.com/assets/25817399/23017837/1bfefc66-f43c-11e6-8544-0c1162aedcda.PNG)

**Comment by 0Lucifer0** [comment]
Seems to be a neuronal connection trouble.
