### ISSUE TITLE
Hello . Why can not I log into my account

### ISSUE THREAD

**Issue by ARRIS333** [OpenNos/OpenNos#1807]
Why can not I log into my account, I saw that he was a backup why and whether my items will be restored lost a lot of time collecting gold and improving equipment and cards

**Comment by 0Lucifer0** [comment]
That have nothing to do with opennos project...

**Comment by ARRIS333** [comment]
as it has nothing to do with the server, you did fucking backup and I lost a lot of items and do not want to play -.-

**Comment by 0Lucifer0** [comment]
This is opennos sources github nothing to do with any server.
