### ISSUE TITLE
Navicat

### ISSUE THREAD

**Issue by ObservatorSMKM** [OpenNos/OpenNos#1808]
![image](https://cloud.githubusercontent.com/assets/25832543/23103184/cb5f08aa-f66b-11e6-9287-65940bbe092e.png)
![image](https://cloud.githubusercontent.com/assets/25832543/23103187/daf93772-f66b-11e6-8372-750383a8f5a0.png)
![image](https://cloud.githubusercontent.com/assets/25832543/23103191/e84d0e30-f66b-11e6-9fc7-0382c1d0dd3c.png)

No have Table :/

**Comment by Ciapa** [comment]
@ObservatorSMKM Please kys.
Read the fucking Docs.

**Comment by damian5602** [comment]
He have other problem, he cant "update-database".
he got error about mysql error 40 or other i dont remember.

**Comment by 0Lucifer0** [comment]
Because that's not MySQL perhaps... we don't use MySQL we don't need the sql files and this is not the place for Support its for issues.

**Comment by damian5602** [comment]
I have other question, what is the default name and password for database in server?

**Comment by damian5602** [comment]
And where i can edit it? app.config?

**Comment by 0Lucifer0** [comment]
Seems to be in the same mall than your brain. Just read the fucking readme.
