### ISSUE TITLE
implement character login information

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#181]
if a character has been logged in, inform all clients which are registered on the CharacteLoginEvent thru the service callback, register and unregister a server / map for this event if necessary

**Comment by chucktheripper** [comment]
Every client should be informed about the character login

**Comment by genyx** [comment]
every character should only be informed if a player joins his MAP 
(or if they are friends or family)

**Comment by chucktheripper** [comment]
exactly
