### ISSUE TITLE
Dismounting-Speed bug

### ISSUE THREAD

**Issue by sLicky1337** [OpenNos/OpenNos#1812]
So when you have the Berserk Buff from SP4-Berserker while you are mounted, you gain additional speed. The buff gives you additional speed in the last 20 seconds. That does stack with the mount speed itself. Also, if you dismount, while having that increased speed buff from the last 20 seconds, you will remain with your 26+ unit speed, while dismounted. This bug is reproducable.

p.s.: sorry if this is a repost or not detailed enough

**Comment by 0Lucifer0** [comment]
Repost and btw buff not finished
