### ISSUE TITLE
Item disappear's while listing it to Bazar

### ISSUE THREAD

**Issue by PandemoniaAT** [OpenNos/OpenNos#1813]
As the title says, when I try to list an item to the Bazaar it just disappears.
But the listing message and the gold refund do work normaly its just the item itself that disappears.
In fact that this problem is already known just close this and ignore it .

Greetings Pandemonia.

**Comment by Ciapa** [comment]
@PandemoniaAT Not happening for us.

**Comment by 0Lucifer0** [comment]
@Ciapa because already fixed but will come on next push

**Comment by Nory23** [comment]
I have the same problem and show this in the console if helps to fix it
http://i65.tinypic.com/1572bec.png

**Comment by 0Lucifer0** [comment]
... read the conversation it's already fixed
