### ISSUE TITLE
Max level

### ISSUE THREAD

**Issue by Raimenx** [OpenNos/OpenNos#1815]
Hi,

Where i can set exp from level 100 to level 101 And from level 101-102 Tell me pls where.

**Comment by MasterDomino** [comment]
@Raimenx config files are often what you want to edit, also this is not a place for questions like this

**Comment by Raimenx** [comment]
But i can only set max level .. but from level 100 i dont get % And sorry i dont know who can Tell me this

**Comment by MasterDomino** [comment]
use discord forthis, also u dont need to edit algo, also client doesnt have xpload for lvls over 99 soo %GetExp is the command iirc
