### ISSUE TITLE
Cant leave from familly.

### ISSUE THREAD

**Issue by michal23pl** [OpenNos/OpenNos#1816]
Cant leave from familly, i try %familydismiss also boss of fam try kick me, but he cant. After a few restart, still have same problem. In familly wall "Tedunio leave from familly 1h ago" but im still in this familly.

**Comment by Uppermost** [comment]
Fixed on current branch, fix incoming

**Comment by Nory23** [comment]
Use %Rejetdefamille this command work for me.
