### ISSUE TITLE
Grid bug

### ISSUE THREAD

**Issue by Skaterkeks** [OpenNos/OpenNos#1819]
Item dropped out from Instant

https://www.pic-upload.de/view-32885413/20170321-0-Skaterkeks.jpg.html

**Comment by Masker91** [comment]
How to add Instant battle in my server?

**Comment by 0Lucifer0** [comment]
Not a place for those questions.

**Comment by H20-Rainny** [comment]
![20170510-0-rainny](https://cloud.githubusercontent.com/assets/18625483/25881872/b277df96-3569-11e7-950a-201f2db28bb0.jpg)
![20170510-1-rainny](https://cloud.githubusercontent.com/assets/18625483/25881871/b2760202-3569-11e7-9016-a2e374e0bda7.jpg)
still had this problem 💃

**Comment by MasterDomino** [comment]
It was fixed in private branch
