### ISSUE TITLE
I try to parse but it gives an error. [IMPORT CONSOLE]

### ISSUE THREAD

**Issue by Brvortex** [OpenNos/OpenNos#1823]
![image](https://cloud.githubusercontent.com/assets/21347271/24830622/9b6d2cce-1c92-11e7-9036-cde49e753f31.png)

Can someone help me ? I tried to change the names "de" to "en or uk" but it's not working.

**Comment by Brvortex** [comment]
Don't u have a answer for that Lucifer?

**Comment by 0Lucifer0** [comment]
I have :  "read the fucking manual"

**Comment by Brvortex** [comment]
Oops

**Comment by JOAOMASTER** [comment]
@Brvortex  Packet.txt is missing
