### ISSUE TITLE
New Source (Feedback)

### ISSUE THREAD

**Issue by PandemoniaAT** [OpenNos/OpenNos#1826]
Hello dear OpenNos Team, well I tested the new source so far and noticed one or two things that could disturb the player experience significantly.

1.Lagg spikes (Well I dont know exactly where they are coming from but the new source is causes kind of lagg waves during the uptime of a server , so till yet I think its coming from the source because our server is running well and very stable normally)(I can say it perhaps comes from Instant battle combat)

2.Missing Effects of Miniland Object (As the title says effects [graphic] of Minilandobject is missing completely)

3.Dead Pet (If you take Raid-Bosses as Pet it will only lie dead on the ground as mate)

(If it should be like that just close it at this point :) )

Thats all for now.
In the end I like to say that we from AniTale would like to thank you for your wonderfull work and we wanted to give you best wisches for the continuing project.

-Greetings Pandemonia :)

**Comment by 0Lucifer0** [comment]
Thanks for the review but all is known wd pushed all in un unsafe version.
