### ISSUE TITLE
Static Or Direct

### ISSUE THREAD

**Issue by senterol** [OpenNos/OpenNos#1829]
How to distinguish item from Static Buff or Direct Buff?

**Comment by MasterDomino** [comment]
not a place for a questions, but static buffs are buffs that stay even if logged out, and buffs are just normal usable skills and buffs to exp with time, something like backpack 30days is staticbuff

**Comment by senterol** [comment]
I know that... I said that badly ... I wanted to refer to in item reference to the string "public const bool StaticBuff = true / false"
