### ISSUE TITLE
Reputation bug

### ISSUE THREAD

**Issue by Raimenx** [OpenNos/OpenNos#1831]
After update... Players didnt get reputation... where is problem?

**Comment by 0Lucifer0** [comment]
I have the answer but you won't like it.

**Comment by Raimenx** [comment]
Can you answer me please?

**Comment by 0Lucifer0** [comment]
Yes i can.

**Comment by 0Lucifer0** [comment]
Yes i can.

**Comment by Raimenx** [comment]
I made all server new.. and i dont get reputation from monsters why?
