### ISSUE TITLE
Instant Battle Combat, Debugmode issue.

### ISSUE THREAD

**Issue by PandemoniaAT** [OpenNos/OpenNos#1832]
Case 1: (Start Instant Battle Combat , while source is running in Debug mode)

Working :
- Messages work fine ( like "Reinforcements are here" and stuff)
- Portal + end of Ic reward (Reput , Gold , SpPoint) works fine
Issues :
-Monsters are not spawning
-Dropps after Mobwave are not spawning
-Messages will get delayed
-Instant battle will end mistakenly by 7 minutes before closing

Case2:(Now we run the source without debug mode)
- Everything works just fine

Now I cant explain myself why it is like that its somehow working without debug and I havent parsed it but its working fine so maybe is something wrong with the gerenation of wave while running debug.

Have a great easter, greetings Pandemonia.

**Comment by Ciapa** [comment]
@PandemoniaAT Most likely just PEBCAK, as it runs in Debug for me too.

**Comment by PandemoniaAT** [comment]
Well I checked it several times ( 8~10 times) even tried to fix it somehow, well all I was able to was fixing it in a way that after 12 minutes wave 0 will spawn if you kill it , you have won instant battle combat get the reward and 5 minutes before closing, the dropwave 0 will spawn , like I said before tried it multiple times and there are more people than me that just got this problem :)
