### ISSUE TITLE
Error pathfinding Using JPSPlus Failed

### ISSUE THREAD

**Issue by JOAOMASTER** [OpenNos/OpenNos#1836]
![elite19](https://cloud.githubusercontent.com/assets/17860577/25117536/9b5e73dc-23e0-11e7-9756-6260321cc6e5.PNG)
![elite20](https://cloud.githubusercontent.com/assets/17860577/25117535/9b5df06a-23e0-11e7-8ff6-c8f5861ed0b4.png)

**Comment by 0Lucifer0** [comment]
Note: change the pathfinding name in debug message when this error will be fixed.

**Comment by JOAOMASTER** [comment]
ok I'll do it thanks

**Comment by 0Lucifer0** [comment]
That was a note for myself about the code ;)

**Comment by 0Lucifer0** [comment]
fixed on dev branch

**Comment by JOAOMASTER** [comment]
thanks :) :D
