### ISSUE TITLE
attack state disabled after attacking(should stay)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#1842]
opennos : https://gyazo.com/b01083e156e17b219836da46f795dde2

official : https://gyazo.com/6b598cc6e9779e2af0bfc51ca3969b70

On official you are not stopped because your character is in fight mode and you don't have this problem everytime. Probably caused by a wrong packet, packets on official looks different

**Comment by Uppermost** [comment]
#1721

**Comment by H20-Rainny** [comment]
Opennos : https://pastebin.com/PYuMsxth
Offical : https://pastebin.com/4i3XmkxB

**Comment by MasterDomino** [comment]
soo what i understand the character should walk to final destination instead of stopping after attacking the monster, is that right?

**Comment by 0Lucifer0** [comment]
No its about fight position (ready to fight) like bow need to stay banded after hit

**Comment by Uppermost** [comment]
Yes exactly @0Lucifer0
