### ISSUE TITLE
Error when lod event starts

### ISSUE THREAD

**Issue by JOAOMASTER** [OpenNos/OpenNos#1843]
If they close the issue I want to know why, in case ;) 
![elite21](https://cloud.githubusercontent.com/assets/17860577/25158817/343999d6-2479-11e7-8516-f801ca60b52f.PNG)
![sin titulo](https://cloud.githubusercontent.com/assets/17860577/25158818/343d8988-2479-11e7-980e-67dbcd5ca188.png)

**Comment by 0Lucifer0** [comment]
it seem's that you changed something because this line doesn't have any cast.

**Comment by JOAOMASTER** [comment]
#1790

**Comment by 0Lucifer0** [comment]
There is no reason to link this 2 issues...

**Comment by JOAOMASTER** [comment]
sorry
