### ISSUE TITLE
I have problem with OpenNos.login

### ISSUE THREAD

**Issue by HeadzyCZ** [OpenNos/OpenNos#1845]
Hi i have problem with start server.  System Messsage write OpenNos.Login.exe is missing can someon help me please ?
![dfdfdf](https://cloud.githubusercontent.com/assets/27771855/25181616/62be7bc0-2512-11e7-83eb-b2595da20909.png)

**Comment by MasterDomino** [comment]
sorry but its unreadabe, or its just not human language. also check rights for the access to the folder you try to compile.

**Comment by HeadzyCZ** [comment]
Visual Studio can not run debugging C: /Users/WoM/Detskop/OpenNos-master/OpenNos.Login./Bin/DE/OpenNos.Login.exe missing. Build the project and repeat, or set the target assembly suitable properties OutputPath AssemblyName and to show the correct location

**Comment by MasterDomino** [comment]
do as it says, just build the source, if doesnt help restart the vs

**Comment by HeadzyCZ** [comment]
Restart dont work. Ths is only on yours 1.0.6 and i have source 1.0.4 and this still works

**Comment by MasterDomino** [comment]
not source fail, u just miss something when building re read the readme and do everything exactly the same

**Comment by HeadzyCZ** [comment]
Oki thanks :)
