### ISSUE TITLE
How i Make Parser ?

### ISSUE THREAD

**Issue by HeadzyCZ** [OpenNos/OpenNos#1846]
Hi i have problem. How can i make parser in my National Language ?

**Comment by MasterDomino** [comment]
choose proper debug option if not existing create a new one, and share with us.

**Comment by HeadzyCZ** [comment]
Jak to myslíte ? I need parser do Navicatu v mém jazyce kamarád mi říkal že potřebuju unpacker

**Comment by HeadzyCZ** [comment]
What do you mean ? I need a parser to Navicat in my language a friend told me that I need an unpacker

**Comment by MasterDomino** [comment]
u need to start using google, and epvpers

**Comment by HeadzyCZ** [comment]
I look and dont found...

**Comment by MasterDomino** [comment]
go away stop spamming theres a discord for this you dipshit

**Comment by HeadzyCZ** [comment]
And i look on install video OpenNos and download his parser and dont work

**Comment by HeadzyCZ** [comment]
moment i send you foto

**Comment by MasterDomino** [comment]
no just fuck off use discord for fucks sake

**Comment by HeadzyCZ** [comment]
![xcv](https://cloud.githubusercontent.com/assets/27771855/25290352/082dc9dc-26ce-11e7-987b-104e4e82b919.png)
