### ISSUE TITLE
Lod  Uppermost

### ISSUE THREAD

**Issue by KurtMac** [OpenNos/OpenNos#1847]
screen 
![ejwnyesohcamanc7caa-fgg9dugczrqltmbfzo4-jm_1vuoep1rvltj5nwy7undynaun3kpuro2sur-sc10mi-syxxwfdvhilrgqfqq72wvkbwub5wqu-dccfjy3fpae1b2b-v0bbiei2q](https://cloud.githubusercontent.com/assets/28008595/25388686/c803fcc4-29ce-11e7-9ad0-fced95c69a91.png)

**Comment by Ciapa** [comment]
Already reported before

**Comment by 0Lucifer0** [comment]
And screen unreadable and there is no cast in this line so you changed something... be sure to be updated and not get sources from anywhere else than github.

**Comment by JOAOMASTER** [comment]
#1843
