### ISSUE TITLE
add current world server version to informations

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#185]
add a hero message or a chat message on login with the current server world version (1.0.3.x)

**Comment by 0Lucifer0** [comment]
i think a blue chat message is better with something like this 

*************WORLD INFORMATION*****************
Version : 1.0.3
************************************************************
but i think we need a way to able disable the information in config

**Comment by chucktheripper** [comment]
approved :P

**Comment by 0Lucifer0** [comment]
done
