### ISSUE TITLE
weird behavior of worldserver

### ISSUE THREAD

**Issue by blcksys** [OpenNos/OpenNos#1852]
After a while of playing, the worldserver get stuck and does not accept any incoming logins.
Login server works good, but on channel selection you will get stuck and can't get past that.

Worldserver does not crash however, just, won't let login. Who is online, can still play, but if he relog or go to char selection = stuck.

Also, the CPU usage is randomly bouncing from 20% to 80% with just 1 channel opened and 15 online, this wasn't happening with the previous release, I always had 5-15% max per channel and 160 online. However, the channel getting stuck was happening with the previous release aswell, it was some sort of worldserver issue tho, as if channel 1 doesn't allow to login, you may login successfully to channel 2, until it crashes such one aswell and won't let login.

I'm using Intel i7 950 as CPU

**Comment by Ciapa** [comment]
Web API is no longer existing, so closed.

**Comment by blcksys** [comment]
It's not Web API, it's World Server issue, else why would CPU boost to 80% on world server instead of selfhost?

**Comment by Ciapa** [comment]
@blcksys Then why you name it "bad performance of webapi"?!?

**Comment by 0Lucifer0** [comment]
@ciapa because @masterdomino renamed it
