### ISSUE TITLE
cooldown block skill transaction/upgrade

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#1854]
cooldown need to be finish before learn skill from calvin

**Comment by Zeshyu** [comment]
btw. the normal Status-Upgrades by Calvin Coach doesnt Apply

e.g: When u learn a [Easy]Skill with Deffence +5 then u dont get +5 deffence on your Status. Neither i doesnt get displayed or it just doesnt get added.
I dont know - just wanted to Report.

**Comment by BlowaXD** [comment]
It's not implemented yet that's why @Zeshyu

**Comment by 0Lucifer0** [comment]
Yes because that's part of buff

**Comment by Zeshyu** [comment]
btw. @BlowaXD do you know when i Change the SP Upgrade Ratio for example - ingame in the Client still the wrong numbers get displayed.
Where can i Change that? Can i Change that or not?

**Comment by 0Lucifer0** [comment]
Nope that's clientsided. For question use discord
