### ISSUE TITLE
logout after initalization of connetion cramping connected list

### ISSUE THREAD

**Issue by Zeshyu** [OpenNos/OpenNos#1856]
Topic.

Atleast its like that on local/hamachi..
I can easily connect and Login in game. but when i insta log out in the  Server/Channel-Menu i cant connect anymore cuz it says to much Connections..

**Comment by Zeshyu** [comment]
and if im ingame and logout to serverchoice then i always get kicked into Login Screen cuz losing Connection.

**Comment by MasterDomino** [comment]
@Zeshyu thats going to be fixed after change to Master Server

**Comment by PoliRot** [comment]
Zeshyu you dont want to wait a fucking month for the fixed you only need to go in networkmanager line 102 put this return true; thats all.. no more shits
![captura](https://cloud.githubusercontent.com/assets/20234230/25776808/829bc3b6-32c9-11e7-8d1a-adb94ee21472.PNG)

**Comment by MasterDomino** [comment]
@PoliRot Borderline stupid fix, if u cant fix entire code dont return it.

**Comment by MasterDomino** [comment]
this was already fixed, waiting in other branch.

**Comment by BlowaXD** [comment]
@PoliRot dont talk about "shits" when you are the one who suggest to someone to entirely wipe a function.

**Comment by Ciapa** [comment]
@PoliRot You clearly are a retard.

**Comment by PoliRot** [comment]
you dont see already? when they update every update its wrong ? they cant fix only a line for have that stabble only  every update will be critikal everytime going to have some shit no fixed and you cant do anything xD just wait 3 months and than another 3 months for the ''fix'' haha they dont give you support with your server because dont care about you

**Comment by Ciapa** [comment]
Well, if you'd take a look at the dev branch, the proper fix is there since ages. Now go back to your chamber, skid.

**Comment by Gromlox** [comment]
This not helped me dont work... 127.0.0 set to my ip or what?
