### ISSUE TITLE
using items stored in warehouse

### ISSUE THREAD

**Issue by xlHunterlx** [OpenNos/OpenNos#1861]
That bug appear randomly and let the Player us the scroll so often as they want (No item use)

I can not say how to do that, its random and will removed after relogg.

**Comment by Ciapa** [comment]
@xlHunterlx They have scrolls in their warehouse.

**Comment by MasterDomino** [comment]
can u use better descriptions of your issues in the names of issues? it gives me additional work to name them properly

**Comment by xlHunterlx** [comment]
@Ciapa I'll check this and if its true i'll close that by my own then
@MasterDomino I'll rename it if it's a warehouse bug

**Comment by MasterDomino** [comment]
thanks dude, like i said try describing in short whats the issue

**Comment by xlHunterlx** [comment]
@MasterDomino That's a weird bug, like @Ciapa said, if you have scrolls in the Miniland warehouse it will be used from there, (it will used all items in the Miniland warehouse)

**Comment by xlHunterlx** [comment]
@MasterDomino here is the video from a player:
https://youtu.be/7ZxzCLoYIEg
its a different bug as the other one, You must know if I should create a second issue for it
