### ISSUE TITLE
nosbazaar missing check on full inventory

### ISSUE THREAD

**Issue by GordonRamsay** [OpenNos/OpenNos#1862]
I tried to get back my 30 Blessing of Ancelloan on NosBazaar when my main inventory was full. However, i didn't receive any parcel #

**Comment by H20-Rainny** [comment]
it should send message." inventory was full."

**Comment by MasterDomino** [comment]
dont add [BUG] tag in front of your issue please :) we will understand tho

**Comment by GordonRamsay** [comment]
Sorry about the tag

**Comment by MasterDomino** [comment]
np dude its just i would say a 'how to' for good github issues ;) thanks.

**Comment by GordonRamsay** [comment]
It didnt send the message said " inventory was full."
It only said "your sale is completed. you receive 0 gold" something like that.

**Comment by GordonRamsay** [comment]
so the 30 blessing just disappear of the bug, will i get any compensation of this?

**Comment by Ciapa** [comment]
This is the wrong place for that stuff, this is Development Stuff and not Public Server Support.
Go to https://board.opennos.io and open a Ticket for this.
