### ISSUE TITLE
NRE in BoxItem

### ISSUE THREAD

**Issue by xlHunterlx** [OpenNos/OpenNos#1864]
![fault](https://cloud.githubusercontent.com/assets/27646003/25918693/9ebed398-35cc-11e7-9e6f-d36de06dd847.PNG)

Cant say more to this at the moment

**Comment by MasterDomino** [comment]
you should display whole window and show the code on that line

**Comment by xlHunterlx** [comment]
@MasterDomino Will send you with the next crash
![code](https://cloud.githubusercontent.com/assets/27646003/25962058/a900e840-367c-11e7-842f-46cb361a8e1c.PNG)

**Comment by MasterDomino** [comment]
can u send me the last packets youve received serverside? should be called log.txt in bin folder in ch-6

**Comment by xlHunterlx** [comment]
@MasterDomino Ive turned off the logs, because that ive said, I'll send you if the crash again

**Comment by MasterDomino** [comment]
okay thanks, im on it i think i know what it is actually :P

**Comment by MasterDomino** [comment]
fixed, waiting for merge
