### ISSUE TITLE
Buffs/Debuffs being removed after relog

### ISSUE THREAD

**Issue by blcksys** [OpenNos/OpenNos#1868]
Title says all, if you buff yourself, use a potion or whatever, and you change SP = everything gets removed
Same result if your relog, every buff/debuff disappear

**Comment by Ciapa** [comment]
@blcksys Did you ever play NosTale?

**Comment by 0Lucifer0** [comment]
Like official

**Comment by blcksys** [comment]
This includes experience potions, which on official are paid, whats the matter on deleting something you paid after a relog?

**Comment by MasterDomino** [comment]
@blcksys Welcome to world of nostale, this is how it is, this project is to emulate and fix game breaking bugs, this potions getting removed is a part of gameplay sadly
 Sincerely, Master.

**Comment by BlowaXD** [comment]
@blcksys as long as OpenNos is open source, you can modify this and make your server save your players' buffs after a relog. (but it's on your fork, not on OpenNos' official code)

Anyway, you should play a bit more on official before opening issues like this. (as @MasterDomino stated, OpenNos is here to emulate the official server)
