### ISSUE TITLE
family

### ISSUE THREAD

**Issue by InoriYui** [OpenNos/OpenNos#1873]
I can't leave my family

**Comment by Ciapa** [comment]
@InoriYui Such informative. Much detailed. Wow.

**Comment by InoriYui** [comment]
WOOOOOOW ?!!!?!!??? I can't leave my family! When i press leaving nothing happens nice help

**Comment by MasterDomino** [comment]
%Familyleave

**Comment by InoriYui** [comment]
Thanks for help MasterDomino!
