### ISSUE TITLE
Family arena works without a family

### ISSUE THREAD

**Issue by sd5986** [OpenNos/OpenNos#1878]
![20170520-0-hkg5986](https://cloud.githubusercontent.com/assets/24356811/26277045/cf449254-3db6-11e7-9d31-65c765111e8f.jpg)
Should add something like that:
if(packet.type != 0 && Session.Character.Family == null)
{
Session.SendPacket(UserInterfaceHelper.Instance.GenerateMsg(Language.Instance.GetMessageFromKey("NEED_FAMILY"), 0));
return;
}

**Comment by aerzy** [comment]
On official don't need family for enter in family arena u just can't kill player no family only player with family
