### ISSUE TITLE
Crash server $Shutdown

### ISSUE THREAD

**Issue by NosWorld** [OpenNos/OpenNos#1887]
![unknown](https://user-images.githubusercontent.com/29120693/27264411-ff5f4136-547d-11e7-8ec4-82ab7a40e465.png)

When I do the command: $ Shutdown, the crash server has the last second before it closes

**Comment by Uppermost** [comment]
Thank for the report, I will test it locally

**Comment by NosWorld** [comment]
np

**Comment by Uppermost** [comment]
Very weird, this problem doesn't occur on my version in local.

**Comment by NosWorld** [comment]
I use the latest version of the dev branch and I did the shutdown locally and the problem there is

**Comment by NosWorld** [comment]
I use the latest version of the dev branch and I did the shutdown locally and the problem there is

**Comment by Uppermost** [comment]
This problem could be caused by something else then

**Comment by NosWorld** [comment]
I close if the problem come from me?
