### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by NosWorld** [OpenNos/OpenNos#1888]
![image](https://user-images.githubusercontent.com/29120693/27271671-59e2482c-54c6-11e7-94e4-428a712eb409.png)

I do not know where the crash comes from

**Comment by Ciapa** [comment]
@NosWorld It's the new buff system which is not yet completely implemented. Keep in mind that you're on the Dev branch, which can cause issues

**Comment by NosWorld** [comment]
ah ok
