### ISSUE TITLE
Mini-games

### ISSUE THREAD

**Issue by NosWorld** [OpenNos/OpenNos#1891]
When I play only the mini-games you see below and when I press start the game does not start and my character remains frozen playing while the game is not showing! When I disconnect my character the server crashes
![20170619-0-worldie](https://user-images.githubusercontent.com/29120693/27296920-2ddf238c-5523-11e7-8255-a56d27a93e07.jpg)
![sans titre](https://user-images.githubusercontent.com/29120693/27296932-394fb6be-5523-11e7-9224-8bcd231de74c.png)

**Comment by EPVPAgen** [comment]
Could you post the line 533 (Character.cs) ?
Have you touched the code?

**Comment by 0Lucifer0** [comment]
Seems to be dev branch

**Comment by MasterDomino** [comment]
its is dev branch cuz i added dev at the end of console name and the string in startup to show its dev branch we shall remove it when merging and leave fordev

**Comment by NosWorld** [comment]
yes its dev branch
