### ISSUE TITLE
Upgrade Special Card

### ISSUE THREAD

**Issue by senterol** [OpenNos/OpenNos#1894]
In the official if you fail a upgrade the scroll save the Special Card and the green/red/blue souls

**Comment by MasterDomino** [comment]
@senterol Its same on opennos o.O

**Comment by senterol** [comment]
No, if you try you can see the opennos emu don't save the souls

**Comment by BlowaXD** [comment]
Actually, souls are not saved, the upgrade method has to be rewritten.

**Comment by MasterDomino** [comment]
@BlowaXD You mean on official if you fail the souls dont get removed, if yes the rewrite is useless just small condition swap n stuff

**Comment by senterol** [comment]
Ok, sorry for the useless report xD

**Comment by BlowaXD** [comment]
If it has not been changed in the dev branch, the code is too ugly to ignore souls properly

**Comment by MasterDomino** [comment]
@BlowaXD Like hell you know about look of the code

**Comment by BlowaXD** [comment]
Haha, you make me laugh a lot, C# developer.
You didn't even look at my code since march or something like this when you was under private repository development.

**Comment by Ciapa** [comment]
@BlowaXD What "your code"? I didn't saw anything productive...

**Comment by MasterDomino** [comment]
@BlowaXD Cuz you didnt develop since march, also this is not wish concert stop offtop in github issues, if you have a private issue with me send me a dm on discord.

**Comment by BlowaXD** [comment]
@Ciapa  You didn't **see** anything because I'm not working on OpenNos anymore, don't have time and have other more interesting projects.
@MasterDomino you complain about offtop while you are the one who actually offtop at first time.

**Comment by Ciapa** [comment]
@BlowaXD "I'm not working on OpenNos anymore" - then get the fuck outta here.
