### ISSUE TITLE
Get disconnected when i Login Forced Disconnect 

### ISSUE THREAD

**Issue by Gromlox** [OpenNos/OpenNos#1895]
https://cdn.discordapp.com/attachments/321047676747644929/325661253894799361/unknown.png here is my fail what issues?

**Comment by NosWorld** [comment]
@Gromlox I think it can help you https://github.com/OpenNos/OpenNos/issues/1856

**Comment by Gromlox** [comment]
dont work for me

**Comment by Gromlox** [comment]
Why close

**Comment by 0Lucifer0** [comment]
Cause its a pebcake

**Comment by Gromlox** [comment]
what pebcake hhh?

**Comment by MasterDomino** [comment]
http://lmgtfy.com/?q=urban+dictionary+pebkac
