### ISSUE TITLE
Little dupe bug

### ISSUE THREAD

**Issue by senterol** [OpenNos/OpenNos#1898]
If you receive a pack with the $ Gift command, reties and relog, you receive the same packet again

**Comment by Ciapa** [comment]
@senterol Happens because of the genius Mail Caching

**Comment by 0Lucifer0** [comment]
there is no mail caching only automatic retrieving... i'm quite sure the trouble come only when you give yourself an item
https://gyazo.com/826a1ed715bd83aab1c8164c6537bbc4
