### ISSUE TITLE
Bazaar Bug

### ISSUE THREAD

**Issue by Hohokkk** [OpenNos/OpenNos#1900]
I put a Phenomenal 92 bow +8 on the bazaar to sell, after that I change my mind and want to update the price, I click "quit" and my bag is full without empty place. 

Thus, the bow disappear  and no gift letter received. Please solve , Game ID FxxXCreation

**Comment by 0Lucifer0** [comment]
This is not the right place for server issue... btw should be fixed but it seems it isn't.

**Comment by earthnash** [comment]
I've tested.and doesn't have this problem.
