### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#1901]
![crash](https://user-images.githubusercontent.com/16693364/27577591-99eb1442-5b21-11e7-89b1-568a1be393a1.PNG)

**Comment by MasterDomino** [comment]
@aerzy will be fixed with release of fixed buff system.

**Comment by 0Lucifer0** [comment]
Any way to reproduce ? Any special buff ?

**Comment by xlHunterlx** [comment]
There is actually no special buff about that, i have to removed it for my Server to avoid it. Next issues followed.
