### ISSUE TITLE
Insert/Update StaticbonusDAO

### ISSUE THREAD

**Issue by xlHunterlx** [OpenNos/OpenNos#1904]
![20312b6a020cf43ff98bbaee66c835e9](https://user-images.githubusercontent.com/27646003/27595967-77dce050-5b5e-11e7-902d-92e45825adef.png)

It comes when you use a Bazzarmedal or other like that after a log out.

Useless or other just close it.

**Comment by NosWorld** [comment]
https://github.com/OpenNos/OpenNos/issues/1892 '-'
