### ISSUE TITLE
Grid System Bug

### ISSUE THREAD

**Issue by ERENKYI** [OpenNos/OpenNos#1906]
I am getting an error on startup from Map.cs > LoadZone(). I haven't done any changes to grid system.
![devenv_2017-07-01_13-48-18](https://user-images.githubusercontent.com/29287377/27761419-2fd435c0-5e64-11e7-8573-88b455c6bd4b.png)

**Comment by 0Lucifer0** [comment]
You don't use the correct file to parse

**Comment by ERENKYI** [comment]
Which file? Do you mean maps folder?

**Comment by 0Lucifer0** [comment]
Yes

**Comment by ERENKYI** [comment]
But I've extracted all of the files from original NosTale with [NosUnpack](https://www.elitepvpers.com/forum/nostale/4100603-release-v1-0-nosunpack.html)...

**Comment by 0Lucifer0** [comment]
Yes but you try to use nstp instead of nstcdata

**Comment by ERENKYI** [comment]
It still gives the same error when I use nstcdata

**Comment by ERENKYI** [comment]
Can you send me your maps folder so I can see if it works?
