### ISSUE TITLE
Magical damage and ranged damage from skills do not work.

### ISSUE THREAD

**Issue by Xano5000** [OpenNos/OpenNos#1913]
As in title all skills with magical or ranged damage type (including basics attacks) do not work at all.
For example I do the same amount of damage from basic attack as from every other skill.
To test it out I took off fairy and just compared damage done to enemies.

I do not know if magical/ranged damage was not done yet on this server or it is just bug so please respond I want to be assured that the system of damage is not completed yet or it is a bug.

**Comment by Ciapa** [comment]
@Xano5000 Old damage system is bugged with new buff implementation, new one hasnt been released yet, maybe later.

**Comment by Xano5000** [comment]
OK thank you for quick reply.

**Comment by MasterDomino** [comment]
Penis
