### ISSUE TITLE
OpenNos World Server crashed in the night returning an Error.

### ISSUE THREAD

**Issue by DarkCacos** [OpenNos/OpenNos#1915]
I am using the last stable public version of Open Nos.

In the middle of the night, when all account was already disconnected (For like 2 hours and 30 minutes), the World Server crashed by himself returning this error: https://s13.postimg.org/ibqz2stlz/Strange_Error.png

The last things I did before disconnecting was killing some monsters and using buff of Vulcan mage SP, and changing the various drop rate etc. of the server at 1000 each just a bit before that. I don't know if maybe some of these things can be related to this error.

**Comment by PoliRot** [comment]
Go to play nostale vendeta xD its the same like nostale normal with no crash

**Comment by MasterDomino** [comment]
@PoliRot he is testing the opennos theres a lot servers using our source as it is opensource and isnt stolen we create our own assets and provide you tools to create them, also youre boring with advertising the vendetta here GTFO outta here kid.

**Comment by DarkCacos** [comment]
Let me think, PoliRot...

...no. -_-

I am here for report the bug in OpenNos, and I am not interested in any pserver.

Also, this isn't a chat, so don't write useless things, like Master said.
Thanks. ;)

**Comment by varunhardgamer** [comment]
@MasterDomino Rr 64bit from redmi 2 booted when i ported using ur cm14

**Comment by MasterDomino** [comment]
@varunhardgamer Sorry m8 dont have redmi 2 i use op5
