### ISSUE TITLE
If you set SceneOnCreate on true, the video of ACT 1 will be showed every time a character connect, and not only the first time.

### ISSUE THREAD

**Issue by DarkCacos** [OpenNos/OpenNos#1918]
As the title say:
If you set SceneOnCreate on true, the video of ACT 1 will be showed every time a character connect, and not only the first time.

OpenNos utilized: Last Stable Version
Client: A Clean Nostale Client last updated on 12/07/2017.

**Comment by JOAOMASTER** [comment]
Just put it off 💯 
![1234](https://user-images.githubusercontent.com/17860577/28118255-56136396-66de-11e7-887b-e84c965f651d.PNG)

**Comment by MasterDomino** [comment]
@JOAOMASTER Thats not the issue here the issue is generallog not working properly or nit being respected
