### ISSUE TITLE
Find true algoritm

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#192]
-MP (mage and npcmonster)
-Basic data (Armor, etc.)
-XP give by monster (depends on the difference of level)

**Comment by 0Lucifer0** [comment]
if someone wan't to help it can start by find these algoritm

**Comment by Martazza** [comment]
`var gradebonus=	Array(0, 10,15,22,32,43,54,65,90,120,200)
  
//elements, fire, water, light, dark = 0,1,2,3   
   
var elementaladvantages=Array( 	Array(0,100,0,50,0), Array(100,0,50,0,0 ),Array(50,0,0,200,0 ),Array(0,50,200,0,0 ),Array(30,30,30,30,0 ) )
  


function calc() {
var sx0 = setnull(parseInt(document.getElementById('basic').value))
var sx1 = setnull(parseInt(document.getElementById('weapon').value))
var sx2 = setnull(parseInt(document.getElementById('attackbonus').value))
var sx2a = setnull(parseInt(document.getElementById('attackbonus2').value))
var sx3 = setnull(parseInt(document.getElementById('equipelement').value))
var sx4 = setnull(parseInt(document.getElementById('skillelement').value))
var sx5 = setnull(parseInt(document.getElementById('fairy').value))
var sx6 = setnull(parseInt(document.getElementById('attacklvl').value))
var sx7 = setnull(parseInt(document.getElementById('attackmorale').value))
var sx8 = setnull(parseInt(document.getElementById('defence').value))
var sx9 = setnull(parseInt(document.getElementById('defencebonus').value))
var sx9a = setnull(parseInt(document.getElementById('defencebonus2').value))
var sx10 = setnull(parseInt(document.getElementById('resist').value))
if(sx10>100)
{
sx10=100;
}
var sx11 = setnull(parseInt(document.getElementById('defencemorale').value))
var sx12 = setnull(parseInt(document.getElementById('defencelvl').value))
var sx13 = setnull(parseInt(document.getElementById('attackgrade').value))
var sx14 = setnull(parseInt(document.getElementById('defencegrade').value))
var grade=1
if (sx13-sx14>0)
{
var temp=sx13-sx14
grade= 1+gradebonus[temp]/100
}

var sx15 = document.getElementById('attackelement')
var sx16 = document.getElementById('defencelement')

var elementaladvantage=(100+elementaladvantages[sx15.selectedIndex][sx16.selectedIndex])/100


totalattack= (15 + sx0 + sx1 + sx2)*(1+sx2a/100);
var fairyelement=(totalattack+100)*sx5/100
var elementaldamage=(sx3+sx4+fairyelement)*elementaladvantage*(1-sx10/100)
var normaldamage=(totalattack-sx8-sx9)*grade*(1-sx9a/100)
var moraledamage=sx7-sx11+sx6-sx12

var finaldamage=normaldamage+elementaldamage+moraledamage
if(finaldamage<6)
{
finaldamage=rand(5)
}

var sx17 = setnull(parseInt(document.getElementById('crit1').value))
var sx18 = setnull(parseInt(document.getElementById('crit2').value))


var crit_bonus=(sx0+sx1+sx2)*((sx18)/100)
var finaldamage_crit=normaldamage+elementaldamage+moraledamage+crit_bonus
if(finaldamage_crit<6)
{
finaldamage=rand(5)
}

document.getElementById('totdmg').firstChild.nodeValue = Math.round(finaldamage*10)/10;
document.getElementById('critdmg').firstChild.nodeValue = Math.round(finaldamage_crit*10)/10;
document.getElementById('critavg').firstChild.nodeValue = Math.round((finaldamage_crit*sx17+(100-sx17)*finaldamage)/10)/10;

	
	

}

function rand ( n )
{
  return ( Math.floor ( Math.random ( ) * n + 1 ) );
}

function setnull ( m )
{
l=m
if(isNaN(m)){
l=0
}
return l
}
`
The real dmg calcualtor
Sources: http://relativeren.nl/nos/damage.html

**Comment by 0Lucifer0** [comment]
thank you :D

**Comment by Uppermost** [comment]
SP algo is false ? I think

**Comment by 0Lucifer0** [comment]
yes i think too :P will close this issue cause it's useless to keep it open
