### ISSUE TITLE
Pathfinding error 

### ISSUE THREAD

**Issue by NosWorld** [OpenNos/OpenNos#1923]
https://gyazo.com/61c1e99d524baca613e49fe57b428170
https://gyazo.com/c9a74832271e8fdcb0f268428335815b

**Comment by NosWorld** [comment]
I use the latest version of opennos (dev)

**Comment by 0Lucifer0** [comment]
how did you get any monster in the -1 X position ?

**Comment by NosWorld** [comment]
Idk

**Comment by NosWorld** [comment]
The players put the boss namaju in a corners of map and when namaju brings up the ninjas I think they are blocked outside the limit

**Comment by 0Lucifer0** [comment]
Summoning trouble
