### ISSUE TITLE
Jlvl problem when i use $ChangeClass

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#193]
When I make the drive to change classes but before that I did the $ JLvl my job level does not change when it should normally fall to 1 since I change class

**Comment by MasterDomino** [comment]
When you dont use $jlvl, doest it change then?

**Comment by Uppermost** [comment]
Example, I am level 20 adventurer profession and I decide to use the command to change class. The level should be required to return to one since I change class. (Sorry i'm bad in English)

**Comment by 0Lucifer0** [comment]
Its volonteer verification on jlvl is just for real changejob system not for gm
