### ISSUE TITLE
Unnormal Error [Maybe on my side]

### ISSUE THREAD

**Issue by CrazyMaster18** [OpenNos/OpenNos#1933]
Hey there! Everytime i try to use an Item from the Main inventory (Where Wings or a mount is stored) my OpenNos.World is crashing with this Error: system.runtime version=4.1.0.0 culture=neutral publickeytoken=b03f5f7f11d50a3a 
Here a Screenshot: https://www.pic-upload.de/view-34114765/Unbenannt.png.html

I try'd very hard to fix this error, but i could not get into it. Please help me :)

**Comment by BlowaXD** [comment]
Just read the error it's kinda obvious.

**Comment by josephito123** [comment]
I have your same error, you fixed it?
