### ISSUE TITLE
Im the only with this error ?

### ISSUE THREAD

**Issue by Uportorst** [OpenNos/OpenNos#1934]
![image](https://user-images.githubusercontent.com/24213444/31707352-60d10350-b3ec-11e7-9bcf-b6b96e7759ee.png)

**Comment by unknownforces** [comment]
Run master server as administrator

**Comment by 0Lucifer0** [comment]
Or use 127.0.0.1 for webapi instead of +

**Comment by Uportorst** [comment]
thx!
