### ISSUE TITLE
Create New Family = crash server

### ISSUE THREAD

**Issue by xWhyNotx** [OpenNos/OpenNos#1938]
Hello , when i creat the new family, my server crash, and i have this error on VS
https://cdn.discordapp.com/attachments/373764759398514688/373764895264473088/image.png
Can you help me?

**Comment by MyTaleON** [comment]
same crash but a other error.
![screenshot_2](https://user-images.githubusercontent.com/22244296/32416142-c3bf13ba-c244-11e7-9775-92aae23d1c06.png)

**Comment by 0Lucifer0** [comment]
Mytaleon the Line is uselsss without the error
