### ISSUE TITLE
Error when Starting OpenNos.MasterServer

### ISSUE THREAD

**Issue by vinixie** [OpenNos/OpenNos#1940]
Hi,
I've got this when i try to start OpenNos Master server :
![error](https://user-images.githubusercontent.com/33284176/32273724-e3d60f6c-bf03-11e7-8f58-584f08a77f3c.png)

please can you help me
thanks

**Comment by Xenok5** [comment]
I don't know why Lucifer, you close all this posts with errors... Why you don't help them, i have the same error and i wanted to see how to fix it.

**Comment by vinixie** [comment]
Yeah, i've always this error.
What is your OS ? 
Sorry for bad english i'm french...
