### ISSUE TITLE
Bug Save world

### ISSUE THREAD

**Issue by skr4w** [OpenNos/OpenNos#1942]
![sans titre 1](https://user-images.githubusercontent.com/24233423/32365873-fb29868e-c07b-11e7-82c1-4e131ddfeb28.jpg)

Help me , thank you .

**Comment by 0Lucifer0** [comment]
Any details to reproduce ?

**Comment by skr4w** [comment]
I look in the folder OpenNos.DAL.EF it is missing files .cs
