### ISSUE TITLE
Not all Data's was saved in the database. (Parse)

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#1943]
Hello,

i parse the portals: https://image.prntscr.com/image/H48Pv2H2Q7WoyDmAK6SuiA.png

and then i look in the database: https://image.prntscr.com/image/qqNpOg4KQUGblCdKZygkZg.png

same by shops, scriptedInstance, shopItems and so on.

**Comment by 0Lucifer0** [comment]
Will Check
