### ISSUE TITLE
[WORLD-SERVER] Add itemtype Enum

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#197]
Add itemtype Enum

**Comment by 0Lucifer0** [comment]
00 sword
01 armor
02 mask
03 amulet
04 sp
05 pet
06 runes(shell)

10 main object
11 amelioration object
12 produce object
13 object of map
14 magic object
15 potion
16 event
17 quest

20 sold
21 food
22 snack
24 magic item
25 component
26 object for nosmat
27 ammo
28 i dont know

**Comment by MasterDomino** [comment]
done
