### ISSUE TITLE
[WORLD-SERVER] Add Config menu system

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#198]
add configuration menu (group,whisper block... with flag on character)

**Comment by 0Lucifer0** [comment]
need to add an enum

**Comment by 0Lucifer0** [comment]
need to add msg and see loadoption : GenerateStat

**Comment by 0Lucifer0** [comment]
just need to add msg

**Comment by MasterDomino** [comment]
Done
Full list of keys to add:
BUFF_BLOCKED
BUFF_UNLOCKED
EMO_BLOCKED
EMO_UNLOCKED
EXCHANGE_BLOCKED
EXCHANGE_UNLOCKED
FRIEND_REQ_BLOCKED
FRIEND_REQ_UNLOCKED
GROUP_REQ_BLOCKED
GROUP_REQ_UNLOCKED
HERO_CHAT_BLOCKED
HERO_CHAT_UNLOCKED
HP_BLOCKED
HP_UNLOCKED
MINI_INV_BLOCKED
MINI_INV_UNLOCKED
MOUSE_LOCKED
MOUSE_UNLOCKED
QUICK_GET_UP_ENABLED
QUICK_GET_UP_DISABLED
WHISPER_BLOCKED
WHISPER_UNLOCKED
FAMILY_REQ_LOCKED
FAMILY_REQ_UNLOCKED

**Comment by MasterDomino** [comment]
done
