### ISSUE TITLE
$AddMonster Not Work All MAP

### ISSUE THREAD

**Issue by NosTale8** [OpenNos/OpenNos#1980]
Hello I have a problem with the command $AddMonster apply its mark but no monster appears.
![20171127-0-sergio](https://user-images.githubusercontent.com/34033892/33273973-23e23ad2-d38f-11e7-80ab-8f63291b3aa1.jpg)
![20171127-1-sergio](https://user-images.githubusercontent.com/34033892/33273974-23faee60-d38f-11e7-8fdb-3153ff7ef2be.jpg)

**Comment by NosTale8** [comment]
how to. fix?

**Comment by NosTale8** [comment]
@0Lucifer0

**Comment by 0Lucifer0** [comment]
This is not a support system... https://github.com/OpenNos/OpenNos/issues/1969
