### ISSUE TITLE
Error OpenNos-Login  -- OpenNos-World

### ISSUE THREAD

**Issue by Xenok5** [OpenNos/OpenNos#1981]
So the problem is this... I really don't know how to fix this, i tried with IP: 127.0.0.1 and my IP Port: 6968  -  4002  - 4001  - 6969   , and still nothing, I'm waiting for your answer! ^·^

Screenshot:
https://gyazo.com/b994b93c66d5ee6215977101ad4e0a11

**Comment by 0Lucifer0** [comment]
this is not a support place and seriously this is not even the current version of OpenNos

**Comment by Xenok5** [comment]
Ok fixed... Thank you! But now i have the same error like https://github.com/OpenNos/OpenNos/issues/1940

How can i fix it, can you help me pls?
Thank you.

Regards, Xenok5.  Saludos, Xenok5.
