### ISSUE TITLE
Bug right click

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#199]
We must correct the packet : req_info 1 3
tc_info 1 Kenaa 0 0
 0 1 0 Aucun 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 Aucun message de présentation.

by :  0 1 0 - 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 Aucun message de présentation.

(Delete Aucun and remplace by " - " )

**Comment by 0Lucifer0** [comment]
done
