### ISSUE TITLE
Double exit portal in Arena and no exit portal in Family arena

### ISSUE THREAD

**Issue by BubbleGuardian** [OpenNos/OpenNos#1994]
OpenNos.GameObject\Networking\ServerManager.cs (1240 - 1242)
 FamilyArenaInstance = GenerateMapInstance(2106, MapInstanceType.ArenaInstance, new InstanceBag());
 FamilyArenaInstance.IsPVP = true;
 ArenaInstance.Portals.Add(new Portal
 Please change to 

 FamilyArenaInstance = GenerateMapInstance(2106, MapInstanceType.ArenaInstance, new InstanceBag());
 FamilyArenaInstance.IsPVP = true;
 FamilyArenaInstance.Portals.Add(new Portal

**Comment by 0Lucifer0** [comment]
Just do a pool request if the code is already done
