### ISSUE TITLE
Going To Oasis and returning

### ISSUE THREAD

**Issue by BubbleGuardian** [OpenNos/OpenNos#1999]
add:
OpenNos-master\OpenNos.GameObject\Npc\NRunHandler.cs
  
              case 313:
                    tp = npc?.Teleporters?.FirstOrDefault(s => s.Index == packet.Type);
                    if (tp != null)
                    {
                        if (Session.Character.Gold >= 50000)
                        {
                            Session.Character.Gold -= 50000;
                            Session.SendPacket(Session.Character.GenerateGold());
                            ServerManager.Instance.ChangeMap(Session.Character.CharacterId, tp.MapId, tp.MapX, tp.MapY);
                        }
                        else
                        {
                            Session.SendPacket(
                                Session.Character.GenerateSay(Language.Instance.GetMessageFromKey("NOT_ENOUGH_MONEY"), 10));
                        }
                    }
                    break;

             case 314:
                    if (npc != null)
                    {
                        ServerManager.Instance.ChangeMap(Session.Character.CharacterId, 145, 50, 38);
                    }
                    break;

**Comment by 0Lucifer0** [comment]
Pull request it
