### ISSUE TITLE
Cannot get off the boat (ACT 4 angel/devil)

### ISSUE THREAD

**Issue by BubbleGuardian** [OpenNos/OpenNos#2000]
Please add to 
OpenNos-master\OpenNos.GameObject\Npc\NRunHandler.cs

                case 5004:
                    if (npc != null)
                    {
                        ServerManager.Instance.ChangeMap(Session.Character.CharacterId, 145, 50, 41);
                    }
                    break;

**Comment by 0Lucifer0** [comment]
No hardcoded things like this please
