### ISSUE TITLE
[WORLD-SERVER]Check trade dialog

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#211]
![image](https://cloud.githubusercontent.com/assets/15254478/13019649/fc3eebf4-d1d0-11e5-9737-7481f92ee4e5.png)
![image](https://cloud.githubusercontent.com/assets/15254478/13019654/04a7d7a6-d1d1-11e5-87fb-58e82f45394a.png)

Problem on they dialogs

**Comment by 0Lucifer0** [comment]
fix
