### ISSUE TITLE
[WORLD-SERVER]Morph command bug

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#212]
When I morph me, and i demorph my level job is gone

Exemple normal mode Lvl 50 job
I use morph command > Lvl 1
I demorph > Lvl = 1 and not 50

I think it will not charge the job when I démorph

What I mean is that if I morph me after even being demorph I can not change my level business remains on block 1 and above it is outdated compared to the true level

After demorph : 

![image](https://cloud.githubusercontent.com/assets/15254478/13020089/a4ae1cae-d1d3-11e5-8946-4e643fec7207.png)

![image](https://cloud.githubusercontent.com/assets/15254478/13020098/b78230d6-d1d3-11e5-9dde-0e6c38d74a58.png)

#Solved I thought morph 0 0 0 0 took away all the effects, while not

Close please

**Comment by 0Lucifer0** [comment]
Will see to unmorph on 0

**Comment by 0Lucifer0** [comment]
fix
