### ISSUE TITLE
[WORLD-SERVER] HP Not fully regaining

### ISSUE THREAD

**Issue by genyx** [OpenNos/OpenNos#213]
![unbenannt](https://cloud.githubusercontent.com/assets/17216038/13033896/a7810000-d326-11e5-8a7a-4d93212adc3e.PNG)
sitting there for hours..
(maybe this is just at mine?)

**Comment by 0Lucifer0** [comment]
hum interesting will see :D

**Comment by 0Lucifer0** [comment]
fix
