### ISSUE TITLE
Namespace names inconsistent

### ISSUE THREAD

**Issue by genyx** [OpenNos/OpenNos#222]
All Classes and Sub-namespaces in the OpenNos.Core.Networking folder are not in the namespace "Networking" as the filestructure declares that.

![unbenannt](https://cloud.githubusercontent.com/assets/17216038/13053765/81abf7fa-d406-11e5-9efe-93cc84f231c3.png)

**Comment by chucktheripper** [comment]
namespaces are always project based, just if its improving the structure, so in this case the namespace is OpenNos.Core

**Comment by 0Lucifer0** [comment]
so we need to change it?

**Comment by genyx** [comment]
Its better to have the Namespace-Classes Structure as same as folder-structure.
So Namespace=Folder and Class=File
So all Subnamespaces and Classes in OpenNos.Core.Networking Namespace must be in the folder named Core\Networking\...

**Comment by chucktheripper** [comment]
approved, do it where it make sense, but ain't with for instance GameObject / Item, so not in DAO, GO, DTO
