### ISSUE TITLE
[LOGIN-SERVER] Silently stops working if there no world

### ISSUE THREAD

**Issue by genyx** [OpenNos/OpenNos#224]
If LS is started without a world server, there are many Exceptions caught by debugger. The Console Output is empty and no user is able connect (because of LS is asking IfOnline)

**Comment by MasterDomino** [comment]
its because Lucifer changed that: `MapId` smallint NOT NULL AUTO_INCREMENT UNIQUE, 
to that: `MapId` smallint NOT NULL, 
you need to regenerate db

**Comment by genyx** [comment]
i had reloaded the db. but problem reappears. i think the LS tries to connect to the world server?!

**Comment by genyx** [comment]
atm i cannot reproduce it. 
issue closed!
