### ISSUE TITLE
Create parser for Item

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#225]
Create parser for Item

**Comment by 0Lucifer0** [comment]
basic parser done.
need to parse data with some template
need to parse buff (easy) but we need to see how to handle buff before

**Comment by 0Lucifer0** [comment]
ok so masterdomino i let you find all data from item type and put them in the parser :D

**Comment by MasterDomino** [comment]
Im actually kinda confused with box because we're missing pets and miniland handling :/ soo i can create surrogate columns

**Comment by 0Lucifer0** [comment]
You just need to parse data i think that all box have the same data xD
