### ISSUE TITLE
Create parser for shopitem

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#229]
Create parser for shopitem
need to do parser for item.

**Comment by MasterDomino** [comment]
n_inv 2 8835 0 110 1.0.1624.-1.55000 1.1.1625.-1.55000 1.2.1626.-1.330000 1.3.1627.-1.330000 // cold fabian
n_inv 2 1838 0 110 1.0.1047.-1.2200 0.1.200.0.0.44 0.2.201.0.0.44 0.3.500.0.0.2772 0.4.504.0.0.13200 0.5.505.0.0.14414 0.6.506.0.0.15681 0.7.511.0.0.30030 0.8.512.0.0.31917 0.9.513.0.0.33862 0.10.519.0.0.55440 0.11.520.0.0.58088 0.12.521.0.0.60799 2.13.2050.-1.440 2.14.2051.-1.440 2.15.2052.-1.440 2.16.2053.-1.440 2.17.2054.-1.440 2.18.2055.-1.440 2.19.2056.-1.440 2.20.2057.-1.440 2.21.2058.-1.440 // soraya style

**Comment by MasterDomino** [comment]
n_inv 2 <NpcId> 0 110 <Type>.<ShopItemId>.<VNum>.<Upgrade?>.<Value>

**Comment by 0Lucifer0** [comment]
Yes i Know but we need item parser before :)

**Comment by MasterDomino** [comment]
i just wanted to save it here to remember this ;)

**Comment by MasterDomino** [comment]
added beginning of ShopItem parser i leave rest to you

**Comment by 0Lucifer0** [comment]
done :D
