### ISSUE TITLE
[PARSER] Fix multi portal issue

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#231]
when parsing portals in place wheres 3 portal to the same map ex. port avelus to avelus market it makes only 1 teleport to this place and teleports to another than first teleport is http://i.imgur.com/ATGNJ7y.png

**Comment by 0Lucifer0** [comment]
we can't fix it without walk packet...

**Comment by Martazza** [comment]
I don't have this type of prolem
My portals work aswell

**Comment by 0Lucifer0** [comment]
problem is with parser
