### ISSUE TITLE
add function quick get up when flagged

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#236]
add function quick get up when flagged

**Comment by genyx** [comment]
is there already the store (variables) for the game option flags?

**Comment by 0Lucifer0** [comment]
Yes :)

**Comment by genyx** [comment]
no its not. its just handling with gop paket.... ill do it

**Comment by genyx** [comment]
are gameoptions not stored over logoff?

**Comment by 0Lucifer0** [comment]
they are stored

**Comment by genyx** [comment]
that is not yet implemented, is it?

**Comment by 0Lucifer0** [comment]
the flag is implemented... the function when flagged isn't
