### ISSUE TITLE
review parsers functions

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#243]
Clean functions

**Comment by MasterDomino** [comment]
whole code cleaned, need optimalization for parser functions.

**Comment by genyx** [comment]
What is meant with "Clean functions" there is not even a file named... ?

**Comment by 0Lucifer0** [comment]
sry not for you it's for chuck just to clean the code and verify it's not too bad :D (parser)

**Comment by chucktheripper** [comment]
its pretty ok, but anyone could clean it up, try to improve it

**Comment by genyx** [comment]
so, where? give me some filenames to review :smile:

**Comment by MasterDomino** [comment]
he propably meant ImportFactory.cs and Program.cs in Import.Console

**Comment by 0Lucifer0** [comment]
yeap

**Comment by genyx** [comment]
cleanup done. (#4816fdb1bcb548d45d41fdcde2a3659db64eb143) 
close this?
