### ISSUE TITLE
Purge .dat from Project

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#244]
Purge the *.dat files from Repository, the whole history should he vanished or filtered.

**Comment by 0Lucifer0** [comment]
done

**Comment by chucktheripper** [comment]
remove the items from history

**Comment by genyx** [comment]
but if we provide the .dat files which ARE extracted from client, thats illegal too?!

**Comment by 0Lucifer0** [comment]
Yes

**Comment by MasterDomino** [comment]
Done cleared whole project
