### ISSUE TITLE
Generalize parsing function

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#245]

**Comment by chucktheripper** [comment]
Create a PacketParser in OpenNos.Core.Import, the Functionality should generate a Class of specified type for each line matching the given argument. (Look at DatParser for generic implementation)

Target (Example):
- Call PacketParser.Deserialize<Map>("VNUM", "Parser.txt"); the return value should be IEnumerable<MapDTO>
- The MapDTO has Import Attributes on the corresponding Properties, for Instance on Id is [Import(2)] to load the value from index 2 in line VNUM)

**Comment by 0Lucifer0** [comment]
the problem is that PacketParser need to keep the right order of packet like gp(portal) packet need to be linked to at packet

**Comment by chucktheripper** [comment]
Idea renewed, we will use a Singleton Factory with the function to create a Mapping configuration for our import. Based on the Type & maybe some conditions & Mappings, the PacketParser will return the parsed txt
