### ISSUE TITLE
review ClientLinkManager

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#246]

**Comment by genyx** [comment]
Fixed:

- Possible NullReferenceException (@ReceiverType.OnlySomeone) by setting paranthesis right
- @BuyValidate() line 1-3 => there was three times nearly the same code.
- some refactoring

**Comment by 0Lucifer0** [comment]
need to redo the same and let this open for chuck plz

**Comment by chucktheripper** [comment]
i just wanted to check what it does, how its implemented and if its improvable, because it the ReceiveProperties method returns objects, that was my point to take a look at it

**Comment by genyx** [comment]
you should set that into issue description, so that the others (me) know for what to imporove ;)

**Comment by 0Lucifer0** [comment]
i think we cant get properties on other way... 
Cause properties could be an int or double or string or other type...
and var is just define in method scope so we can't do something like 
 public var RequiereProperties(long charId, string properties)

and i think this is impossible 
public int||double||short||string||somethingelse RequiereProperties(long charId, string properties)

**Comment by chucktheripper** [comment]
it is possible, public T RequireProperties<T>()

**Comment by 0Lucifer0** [comment]
Ok Will try to do It :)

**Comment by 0Lucifer0** [comment]
done

**Comment by MasterDomino** [comment]
soo whats left to do in ClientLinkManager?

**Comment by 0Lucifer0** [comment]
idk lets chuck tell us and close it if finished :D

**Comment by chucktheripper** [comment]
it's improvable, but atm not important
