### ISSUE TITLE
need to add sex to item and parse it

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#254]
need to add sex to item and parse it

**Comment by 0Lucifer0** [comment]
i think it's only used on suites and suitehat and hat

**Comment by MasterDomino** [comment]
Yep only on suits and hats in fashion

**Comment by 0Lucifer0** [comment]
this data is in flag so you can use it on all item without problem :D 
there is a flag for femal and male :D
this is only boy
FLAG 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0
and this female
FLAG 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0
so 15 = onlymale 16 = only female
so if 15 you put 1 in sexe
if 16 you put 2
[09:19:22] joly erwan: else you put 0

**Comment by MasterDomino** [comment]
Done
