### ISSUE TITLE
add npc data in database, generateEinfo(in npc) and parse them

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#259]
![20160229-4-test](https://cloud.githubusercontent.com/assets/15112753/13406648/f25e2206-df24-11e5-9c80-13bbc00b949f.jpg)

**Comment by MasterDomino** [comment]
done needs optimalization

**Comment by 0Lucifer0** [comment]
optimisations done :D and we need to add sitted in npc database

**Comment by 0Lucifer0** [comment]
replace fireelement waterelement ect by fireresistance ...
