### ISSUE TITLE
improve ClientSession PacketHandler

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#260]
Currently calling the PacketHandler thru the client session is slow (Reflection is outdated), handle this call thru an expression tree which is cached into a Dictionary to quickly find the right PacketHandler method in runtime

**Comment by 0Lucifer0** [comment]
same with #246 right?

**Comment by chucktheripper** [comment]
its another improvement but has actually nothing to do with the review (:

**Comment by 0Lucifer0** [comment]
yep but it use reflection too

**Comment by chucktheripper** [comment]
you could use an action or a delegate here probably also an expression

**Comment by chucktheripper** [comment]
http://www.palmmedia.de/Blog/2012/2/4/reflection-vs-compiled-expressions-vs-delegates-performance-comparision
