### ISSUE TITLE
Review Database

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#262]
Review Database and optimise database if possible
and reorder values

**Comment by 0Lucifer0** [comment]
1 idea would be to split inventoryItem but not sure it's a good idea...

**Comment by 0Lucifer0** [comment]
we need to split InventoryItem with multi 1 to 0-1 entity by item type like sp ect with there special stats

**Comment by 0Lucifer0** [comment]
what do you think about this : https://gyazo.com/2548afe59a19c5afc5b43de2c0a83faa

**Comment by 0Lucifer0** [comment]
it's too difficult in fact the cause we need something like double automapper... when we save inventory it should save inventoryitem whitch save wearableinfo but it need to map werableinfo into werableinfodto and put it in an inventoryitemdto and put it in a inventorydto so it's very complicated...

**Comment by chucktheripper** [comment]
You can create mappings for specified types, like TypeA -> TypeB, .ForMember(dest => dest.PropA, opts => opts.MapFrom(src => src.PropB)) to override the default mapping by name

**Comment by chucktheripper** [comment]
Or ignore the specified references

**Comment by 0Lucifer0** [comment]
hum i already try it but i think i miss something cause it was not working...

**Comment by chucktheripper** [comment]
Please create a new issue about that inventoryitem mapping thing with a detailed description
