### ISSUE TITLE
add sp stone upgrade

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#280]
add sp stone upgrade

**Comment by Ciapa1** [comment]
Is on my Schedule for today. Does anyone know from when you get Mord than
one point and how it behaves? I already have the Rates for success/fail,
but not how many points per upgrade.
Am 19.03.2016 18:56 schrieb "MasterDomino" <notifications@github.com>:

**Comment by 0Lucifer0** [comment]
1point by upgrade
