### ISSUE TITLE
add jewelery upgrade

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#281]
add jewelery upgrade

**Comment by 0Lucifer0** [comment]
need to find a way to do #262

**Comment by Ciapa1** [comment]
Do we have the full DB Setup for this? If so, I can implement the Algo for Cellon. If someone else wants to implement:
- There is no real "fail" chance.
- If you already have an effect, and it already is on the jewelery, it shows as failed.

**Comment by 0Lucifer0** [comment]
For the moment we need to wait for the review of inventoryitem

**Comment by chucktheripper** [comment]
change should be possible (Y)

**Comment by Ciapa1** [comment]
Is the issue still blocked due to the inventory Review?

**Comment by 0Lucifer0** [comment]
Nope

**Comment by Ciapa** [comment]
Will be implemented tomorrow. Finally...

**Comment by Uppermost** [comment]
Do you need packets for that?

**Comment by Ciapa** [comment]
@Uppermost No, but thanks

**Comment by Ciapa** [comment]
Domeone can take ofer for me? Since I'm busy with other fixes and internal things, I prolly won't do it until the Deadline...

**Comment by 0Lucifer0** [comment]
will be done in another milestone
