### ISSUE TITLE
Armor stat is wrong

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#286]
![image](https://cloud.githubusercontent.com/assets/15254478/13732603/bcb6df32-e986-11e5-8f65-7fdbe0434778.png)

The defense is too High compared to stats

**Comment by MasterDomino** [comment]
No basic data algorithm

**Comment by MasterDomino** [comment]
And actually i think its proper, because: 2x354=708+100=808

**Comment by Uppermost** [comment]
ok is good closed !

**Comment by 0Lucifer0** [comment]
Will fix It :) i was thinking about yesterday

**Comment by MasterDomino** [comment]
Because 200% of upgrade

**Comment by Uppermost** [comment]
Are you sure upgrade is calculate on this info ?

**Comment by MasterDomino** [comment]
Idk Lucifer will do it, but i think not :smiling_imp:

**Comment by 0Lucifer0** [comment]
Nope not calculate but i Know exactly where is the problem

**Comment by Uppermost** [comment]
Nice
