### ISSUE TITLE
Bug Damage of rarity

### ISSUE THREAD

**Issue by carmine996** [OpenNos/OpenNos#289]
![bug](https://cloud.githubusercontent.com/assets/16310181/13752182/d59db1ec-ea0d-11e5-8356-4c4fdf81135c.jpg)

The Damage is wrong, because, In all rarities the damage is equal.

**Comment by Uppermost** [comment]
It's not a bug, we simply have not yet find the right algorithms

**Comment by 0Lucifer0** [comment]
rarity and upgrade are not coded in damage for the moment
