### ISSUE TITLE
implement rarity in stats

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#291]
implement rarity in stats

**Comment by carmine996** [comment]
Nice Work!!

**Comment by Uppermost** [comment]
Can be improve 

*Really algo
*Add R8 stats
*Add random stat in same rarity example sword 95 7+8 > 475 dmg and 510 rate and same rarity 491 dmg 493 rate

**Comment by 0Lucifer0** [comment]
it use really algo and we don't know real algo for r8 XD

**Comment by Uppermost** [comment]
Ok
