### ISSUE TITLE
World Server Crash - SP Remove

### ISSUE THREAD

**Issue by Dactylr** [OpenNos/OpenNos#295]
When you remove the SP-Card while Transforming the World Server Crashes.

**Comment by 0Lucifer0** [comment]
i don't have this problem how do you get this error?

**Comment by 0Lucifer0** [comment]
https://i.gyazo.com/09bdc2339a6b06a082acd97596bc8af2.gif

**Comment by Dactylr** [comment]
Remove the SP in the Delay when the Character is Dancing

**Comment by 0Lucifer0** [comment]
ok thx will fix this :D
