### ISSUE TITLE
Optimize Task Cycle system if possible

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#296]
Optimise Task Cycle system if possible or let me know if it's a good way :D

**Comment by chucktheripper** [comment]
Where is the "TaskCycle" implemented?

**Comment by 0Lucifer0** [comment]
in the ClientLinkManager

**Comment by chucktheripper** [comment]
as i already suggested, using the sequentialitemsprocessor would be some improvement, because its only triggering a task when someone adds something to the queue

**Comment by chucktheripper** [comment]
Maybe the Rx extensions could help us out, but we need to figure out if thats the right way to do it

**Comment by chucktheripper** [comment]
will be done with #479
