### ISSUE TITLE
add multi channel - Server support

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#297]
add multi chanel - Server support

**Comment by chucktheripper** [comment]
Todo here is to Register / Unregister a Channel to the WCF, and let the WCF decide which servers / channels are online and connectable

**Comment by MasterDomino** [comment]
And add population on channel ex. Empty,busy,full

**Comment by Uppermost** [comment]
Not for 1.0.4 see milestone to more informations !

**Comment by 0Lucifer0** [comment]
That should be a part if the milestone >< technicly its 1.0.2 part

**Comment by Ciapa** [comment]
Add it to 1.0.5, size-wise fits perfectly

**Comment by Uppermost** [comment]
Multichannel part can begin we you've the time :)

**Comment by MasterDomino** [comment]
its here, needs work

**Comment by Ciapa** [comment]
fixed
