### ISSUE TITLE
Loop amount of monsters

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#315]
set max value of monsters for 1 map and loop it(despawn old monsters - spawn new ones)

**Comment by MasterDomino** [comment]
set MapMonsterId to double and 
![zrzut ekranu 386](https://cloud.githubusercontent.com/assets/16002990/13849899/43c21a40-ec58-11e5-91f3-d745a12df355.png)

**Comment by 0Lucifer0** [comment]
no need to add a max^^ and i think int is enought and pop by 255 too ^^ cause there is absolutly no goal to add more than in max monster and double = 1.5 monster for exemple how do you want to take only an half monster?
