### ISSUE TITLE
Fix $AddMonster command

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#316]
Monster not appear ? i have test some map and it work once

and impossible to click to him

![image](https://cloud.githubusercontent.com/assets/15254478/13858137/8c4e8a30-ec7d-11e5-88c5-f880691e308b.png)
ps. command work only once and spawn monster that cant be clicked ~MasterDomino

**Comment by Arcanncz** [comment]
maybe add a command to delete a monster before they can kill

**Comment by 0Lucifer0** [comment]
the command works like $AddMonster 1 1 there is no way to delete easily this command need to be used when you sure you want to save a monster in database in other case use Summon
