### ISSUE TITLE
Check snack

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#322]
By the time the snack does not work, (Do not make me hp/mp)

**Comment by 0Lucifer0** [comment]
we need more information about this ;D how to get this bug

**Comment by Uppermost** [comment]
This bug is random and strange, use food, get up when you use snack and you retrieves still life, and sometime snack doesn't work. This bug is easy to bring up, but difficult to explain the cause

**Comment by 0Lucifer0** [comment]
ah so we get in whan we mix snack and food?
