### ISSUE TITLE
develop standalone app for wcf

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#324]
http://stackoverflow.com/questions/24669003/hosting-wcf-service-on-linux

**Comment by chucktheripper** [comment]
What do you mean with standalone app?

**Comment by 0Lucifer0** [comment]
i mean without iis to run it (like on the link)
many advantage
-simplify install
-exportable on linux
-no more iis 80 port used

**Comment by chucktheripper** [comment]
okay, but it dont know if its really compatible with linux, its a good idea but if you really want to run a stable and resource optimized wcf you should run it in production mode thru iis. Create a WCF.Run project which is just for the standalone implementation

**Comment by 0Lucifer0** [comment]
yes of course ;D

**Comment by Ciapa1** [comment]
Not required anymore, as the server would run inperformant nevertheless and would require multiple code changes. WCF is easy to deploy, so we don't need to develop a standalone wcf app

**Comment by 0Lucifer0** [comment]
we need to do a video tutorial in this case cause ppl don't know how to install it^^ btw this don't work on windows 2008 and 2003 right? ...
