### ISSUE TITLE
improve parser for NpcMonster data

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#328]
we need to find a different way than e_info parsing to parse damage/armor etc. for npc and monsters

**Comment by 0Lucifer0** [comment]
in the worst case we can parse infopacket

**Comment by 0Lucifer0** [comment]
in all case we will need to parse monster e_info i think...

**Comment by MasterDomino** [comment]
We will need to just once click for e_info on monster type

**Comment by 0Lucifer0** [comment]
yes like HP/MP

**Comment by 0Lucifer0** [comment]
all is algoritm in fact
