### ISSUE TITLE
Fix monster stuck wall bug

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#329]
on some maps there are monsters that teleport to walls and run around because of bad pathfinding

**Comment by 0Lucifer0** [comment]
need to review isBlockedZones but i think it's a wall file problem and not a bad algoritm

**Comment by MasterDomino** [comment]
bug still persists and monsters seems to be stuck in walls but not trying to walk opposite way, need to find a way to make monsters go other way the IsBlockedZone is

**Comment by 0Lucifer0** [comment]
they walk oposite if they aren't on the wall

**Comment by MasterDomino** [comment]
look at the gif i sent it makes character to walk to place they actually are in and it makes you go out of the bounds

**Comment by 0Lucifer0** [comment]
Are you sure this Monster is supposed to move ?

**Comment by 0Lucifer0** [comment]
https://gyazo.com/2d5aa04854ca27b413253e9c0f47cbd6

**Comment by MasterDomino** [comment]
even if they walk theres still issue with them blocking you

**Comment by MasterDomino** [comment]
https://gyazo.com/e1f6a123f90eabee0b8adea24e267e03
