### ISSUE TITLE
fix Movement of NpcMonsters

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#331]
we need to optimize it and find the right algorithm to make them most similar
[![https://gyazo.com/cbb20667f7201b18135aa614a2a1cb16](https://i.gyazo.com/cbb20667f7201b18135aa614a2a1cb16.gif)](https://gyazo.com/cbb20667f7201b18135aa614a2a1cb16)
[![https://gyazo.com/935e28001aeb1dea07364532a4d5b050](https://i.gyazo.com/935e28001aeb1dea07364532a4d5b050.gif)](https://gyazo.com/935e28001aeb1dea07364532a4d5b050)

**Comment by 0Lucifer0** [comment]
i don't see a lot of difference XD

**Comment by MasterDomino** [comment]
movement of NpcMonsters are more synchronized we dont want it, we need more randomization, like i said its hard to explain but:
walking of monsters can be divided by parts
we need to do it like this 
- randomize destination(done)
- randomize delay(done)
- implement cycles of movement (monsters can walk without delay up to 6 times) - not imitate it

**Comment by 0Lucifer0** [comment]
that's already what we do (cycle is random from 2 to 4) delay is random destination is random

**Comment by MasterDomino** [comment]
the problem is that we imitate that its not the right way of walking
you dont understand that by cycle i mean the whole  function that will randomize the amount of times monster will start designate the destination, the problem is that monster can walk from its place to destination in 1 move or change destination 6 times with max distance of 5meters(grid amount)

**Comment by 0Lucifer0** [comment]
no we randomize position too with a max distance  so it can change destination too

**Comment by MasterDomino** [comment]
thats the issue were just imitating that thing, we need to not set delay, we need to set whole cycle, and delay after cycle

**Comment by 0Lucifer0** [comment]
a delay is beetween 2 cycle ... it's random so it can use 6 cycle in like 1movement so 6 time change destination

**Comment by MasterDomino** [comment]
done by commit 75bbfe00baee17da51512d1d4eb1ac6a49043e1a
