### ISSUE TITLE
optimize Parser and clean code

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#339]
we need to speed up process of parsing data to database because now it takes about 1minute on 15 4460 and longer on slower cpus, propably implement task/thread system

**Comment by 0Lucifer0** [comment]
no we just need to stop saving each information as soon as possible will see with bulkinsert if it speedup the process

**Comment by Ciapa1** [comment]
The Problem is that C# is slow with parsing strings.
