### ISSUE TITLE
add skill-item bar

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#344]
add skill-item bar

**Comment by MasterDomino** [comment]
qset 0 0 0.1.18.0
qset 0 1 0.1.19.0
qset 0 2 0.1.20.0
qset 0 3 0.1.21.0
qset 0 4 0.1.22.0
qset 0 5 0.1.23.0
qset 0 6 0.1.24.0
qset 0 7 0.1.25.0
qset 0 8 0.1.26.0
qset 0 9 0.1.27.0
qset 1 0 0.1.28.0
qset 1 1 0.1.29.0
qset 1 2 0.1.30.0
qset 1 3 0.1.42.0
qset 1 4 0.1.43.0

**Comment by genyx** [comment]
I already implemented the fully "quicklist" System on my old server. Let me have a look next weekend! :)

**Comment by 0Lucifer0** [comment]
Thats why i assigned you ;)

**Comment by genyx** [comment]
_Have an exam on friday. So i wont have time before saturday..._

**Comment by 0Lucifer0** [comment]
no problem ;D but try to fix your 1.0.3 issue before :D
