### ISSUE TITLE
add portal spawn command

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#350]
$Portal ...

**Comment by carmine996** [comment]
And $RemovePortal ?

**Comment by MasterDomino** [comment]
whats the need of this command?

**Comment by SoraPlays** [comment]
it's normally a gm command and as example for the future as Events.

**Comment by 0Lucifer0** [comment]
Yes temporary portal like summon (dont need to be saved)

**Comment by MasterDomino** [comment]
done
