### ISSUE TITLE
need to find gold drop amount algoritm

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#362]
need to find gold drop amount algoritm(i think it depends on monster lvl)

**Comment by MasterDomino** [comment]
propably same as exp difference between monster and player levels

**Comment by 0Lucifer0** [comment]
No amount is random in range only With Monster lvl its probability that change With char lvl

**Comment by MasterDomino** [comment]
exactly

**Comment by Ciapa1** [comment]
The amount of gold is totally random, within a predefined range
Just the chance for it reduces when the lvl difference gets bigger(as with every item)

**Comment by 0Lucifer0** [comment]
it seem's amount is random between 6*moblvl and 12*moblvl but it's approximation

**Comment by Ciapa1** [comment]
Doesn't work. A5.2 Monsters drop about 3-9k per drop, so this cant be the value, atleast not for those mobs. For others, it could actually work(everything Act1-5.1)
