### ISSUE TITLE
Portal Bug (map 88)

### ISSUE THREAD

**Issue by Heltack** [OpenNos/OpenNos#372]
I sync today and have skills, well... https://gyazo.com/45ce4ac5b84cb63d1486a03b6b277912

**Comment by 0Lucifer0** [comment]
you just don't have the map in your database or something like that.

**Comment by Heltack** [comment]
I have the map... before update today i can go to map 88

**Comment by 0Lucifer0** [comment]
Reparse all cause we didnt change anything and It works With others maps
