### ISSUE TITLE
add default spawn point system

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#375]
add default teleport place system

**Comment by chucktheripper** [comment]
Is this already imported?

**Comment by 0Lucifer0** [comment]
Nope

**Comment by Uppermost** [comment]
http://pastebin.com/nXEMthHw all informations here, if you want don't hesite to ask me "packet"

**Comment by Uppermost** [comment]
Little precision they spawn work only by act. If you assign act 5 but you dead in act 1 you respawn at your town in act 1 and not in act 5.

**Comment by 0Lucifer0** [comment]
MapType 1..1 - N SpawnType 
Character 1..1 - N Spawn
Spawn N - 1..1 SpawnType
Spawn N - 1..1 Map
SpawnType  N - 1..1 Map

Spawn (SpawnId, SpawnTypeId, MapId, X, Y )
SpawnType (SpawnTypeId, DefaultMapId, DefaultX, DefaultY)

**Comment by 0Lucifer0** [comment]
system done.
