### ISSUE TITLE
review damage calculation

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#380]
- [x] 1.) Fix damage whitout weapon (much high now)
- [x] 2.) Add skill element damage, and if your skill don't have element, attack is increase only by 5,10,15 and 20%...

Fire to water = 700 damage +20%
darkness to water = 650 damage +15%
Water to water = 550 damage +5%
Light to water = 500 damage +0%
- [x] 3.) Need to fix sp points set damage (wrong refresh problem)
- [x] 4.) Add critical hit / miss rate
- [x] 5.) Correct sp damage to have the same like official
- [x] 6.) Add chicken sp can't never miss
- [x] 7.) Add miss when magician use gun / remove critical hit on sp8 magician
- [x] 9.) Correct damage whitout weapon (like official)
- [x] 10.) Increase a little bit damage for fairy 0% (on official fairy 0% increase damage a little bit)

Uppermost Edit : 
- [x] 11.)
  
  Damage whitout sp are wrong. Whitout sp damage at only increase like this :
  Source : Official NosTale

(Whitout SP) with fairy with the same % (50% + bow 63 R7+5 on basic hit)

Fire to water = 700 damage +20%
darkness to water = 650 damage +15%
Water to water = 550 damage +5%
Light to water = 500 damage +0%

Elementary damage is very lower if the attack don't have any element.
As you can see only 20% win to stronger element, if the attack don't have element.

For the moment on OpenNos : Water to water = 1k2 fire to water 2k4 it's very wrong. Should be 1440~

- [x] 12.) Correct fairy damage 

Seem's to be the same problem : Try on official just now dagger 92 7+9, and sp2 99+15 archer 24k critical and 48k cc aug, on OpenNos it's like 71k whitout damage up I have find the problem, fairy damage seem's to be very much high (maybe it's just damage on monster whitout element) whitout fairy damage on official and opennos seem's to be the same. 5k damage whitout fairy and 14k with fairy 50% (0 points in element) on official it's like 7k~ Need to have a look at this
- [x] Add secondary weapon damage, for the moment example in sp2 archer it use bow and not dagger and send a message "You can't attack whitout weapon" 

- [x] 13.) Increase a little bit damage for adventurer, on official lvl 1 damage are like 30/40 by hit, on opennos 15~ we need to add something like damage +20 for adventurer

- [x] 14.) ![image](https://cloud.githubusercontent.com/assets/15254478/19417951/e5d621c4-93b9-11e6-819e-9a9df3291da2.png) We need to add stat critical chance and damage critical increase by the sp in stat, on my example you can see my cut give me 350% +50% SP I need to see 400%, and same for critical chance :)

also I see sp give 400 HP with 100 attack but I have only win 200 HP.

**Comment by Ciapa1** [comment]
Based on what Algo should i Implement, or just basic calculation based on approximations?

**Comment by 0Lucifer0** [comment]
Approximate :)

**Comment by Ciapa1** [comment]
Should be done until Friday.

**Comment by Ciapa1** [comment]
Basic Damage is now implemented. Now we need to add:
Elemental Damage
Element Boost
Skill Damage
Skill Elemental Damage
SP Stats

**Comment by Uppermost** [comment]
And add augmentation ( stuff 88 90 etc )

**Comment by chucktheripper** [comment]
Is this already closable?

**Comment by Ciapa1** [comment]
Not yet, still missing Elemental Damage, true crit and so on.

**Comment by Uppermost** [comment]
Where are you ? Do you need help ? packet, other things?

**Comment by unknownforces** [comment]
Probably doesn't work on this anymore

**Comment by MasterDomino** [comment]
everyone has real life soo maybe he is busy didnt you thought about that?

**Comment by unknownforces** [comment]
For 3 months? I doubt it xD

**Comment by Uppermost** [comment]
He have all damage etc, he just need to code it i don't know when but it will be done

**Comment by MasterDomino** [comment]
all team members contact through skype, soo we are quite well informed whats going on and propably all of us are busy sometimes.

**Comment by Uppermost** [comment]
#571 true damage can fix that.

**Comment by Ciapa1** [comment]
##BRANCH: UNTESTED##
Normal/Crit/Elemental Damage implemented.
Waiting for BCard Extension/rewrite for easier handling
Going to implement miss rate next

**Comment by Ciapa1** [comment]
Crit implemented,
6) uses BCard, BCard support is coming later
7) We don't have debuffs
Miss is coming soon

**Comment by Uppermost** [comment]
- [ ] Damage whitout sp are wrong. Whitout sp damage at only increase like this : 

Source : Official NosTale

(Whitout SP) with fairy with the same % (50% + bow 63 R7+5 on basic hit)

Fire to water = 700 damage +20%
darkness to water = 650 damage +15%
Water to water = 550 damage +5%
Light to water = 500 damage +0%

Elementary damage is very lower if the attack don't have any element.
[08/09/2016 18:27:44] Anthony: As you can see only 20% win to stronger element, if the attack don't have element.

**Comment by Ciapa1** [comment]
How should shell damage be implemented, when Shells are Act4 Content, which is Milestone 1.0.11 or .12 iirc

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/19417951/e5d621c4-93b9-11e6-819e-9a9df3291da2.png)
- [ ] We need to add stat critical chance and damage critical increase by the sp in stat, on my example you can see my cut give me 350% +50% SP I need to see 400%, and same for critical chance :)

**Comment by Uppermost** [comment]
I have test on sp, with basic skill 3k3 and with skill 2k9 why the skill is lower than my basic hit? xD (Sp2 archer)

**Comment by Uppermost** [comment]
Critical damage seem's to have a problem now wtf damage are too much high was good some day ago oO

**Comment by Ciapa** [comment]
crit damage got fixed again. Was due to critHit Value being 100 too high
