### ISSUE TITLE
implement proper pathfinding for monsters

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#386]

**Comment by MasterDomino** [comment]
and set offset for monsters to not stand in player

**Comment by 0Lucifer0** [comment]
i'm on it ;D

**Comment by Ciapa1** [comment]
See #373

**Comment by 0Lucifer0** [comment]
hum i was tired i think i answered bad issue and close bad too...

**Comment by 0Lucifer0** [comment]
ah no there was 3 pathfinding issue XD
