### ISSUE TITLE
change drop, make it harder

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#391]
if you know what i mean it should be more like original :D

**Comment by 0Lucifer0** [comment]
change probability?

**Comment by MasterDomino** [comment]
Yup
6 kwi 2016 00:05 "0Lucifer0" <notifications@github.com> napisał(a):

**Comment by 0Lucifer0** [comment]
tell me if it's good now

**Comment by MasterDomino** [comment]
drop is doubled now, it means it drops 2x the items, and rates should be lower too

**Comment by MasterDomino** [comment]
drop fixed need to regen clean db with clear new packet.txt and new data files :+1:
