### ISSUE TITLE
Fix Speed-Hack

### ISSUE THREAD

**Issue by genyx** [OpenNos/OpenNos#392]
Example:
(Portal at 100|100, Character at 1|1)
Character sends "walk 100 100 ..." and "preq" within <1 second and the portal triggers.
That should not be.

There must be a check on how fast it may be possible to reach that position...

**Comment by Ciapa1** [comment]
Only trigger portals when player is within a range of 5-10 fields.

**Comment by genyx** [comment]
That won't do it because Server sets new position instantly after recieving "walk" packet.

**Comment by 0Lucifer0** [comment]
will fix it

**Comment by genyx** [comment]
Not yet done:
Example:
Client is at 1|1
Client sends "walk 1 5.." "walk 1 10.." "walk 1 15.." .... All at once.

**Comment by 0Lucifer0** [comment]
Ah... So we need to calculate Time to walk ...

**Comment by 0Lucifer0** [comment]
my idea : session need to have a LastPacketTimeStamp and for each packet change this dateTime. If 2 walk packet are send to quick just disconnect
@chucktheripper What do you think about it?

**Comment by chucktheripper** [comment]
Maybe not disconnect but ignore the packet

**Comment by 0Lucifer0** [comment]
Why did You closed it ?

**Comment by MasterDomino** [comment]
its fixed thats why i closed it, now theres no disconnection but we ignore the packets

**Comment by 0Lucifer0** [comment]
We need disconnection... If we ignore Packet people can continue to cheat ><

**Comment by MasterDomino** [comment]
no they cant like i said you at least need to stay 20 cells away of portal and spam 80 packets but in actually the same time you could walk

**Comment by 0Lucifer0** [comment]
If There is no disconnection You can completly loose the emulator and we Will need position verification everywhere... If your system works There is no need to delete disconnection because this Will never happen until user cheat. If It disconnect users without cheating the verification is bad.

**Comment by MasterDomino** [comment]
it was disconnecting admins using speed 59 but after i removed disconnection it worked alright also if they can spam the emulator its not what this issue is about its about removing speed-hack, if you wish to timeout packets lets open next issue, we will see later ;) if you know what i mean

**Comment by 0Lucifer0** [comment]
If It disconnect admin that proof that Its not good ><

**Comment by 0Lucifer0** [comment]
No one should enter in the speed hack if Its not an Hack... That only proof that your condition dont work

**Comment by MasterDomino** [comment]
fixed and added disconnection at wrong speed, please add disconnection for all when portal issue is done, for now this issue is fixed.

**Comment by 0Lucifer0** [comment]
should be fixed now with antispam
