### ISSUE TITLE
replace skills dont add next ones(for passive skills)

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#394]
![zrzut ekranu 415](https://cloud.githubusercontent.com/assets/16002990/14320970/9036c94c-fc17-11e5-9cee-7b0a3865fa64.png)

**Comment by chucktheripper** [comment]
Is this a parser problem?

**Comment by 0Lucifer0** [comment]
Nope Its à function advanced skill need to replace the same skill in basic for exemple
