### ISSUE TITLE
add heal/buff

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#398]
add heal/buff/summon/tp/combo... skill

**Comment by MasterDomino** [comment]
added db and parsing for buff

**Comment by unknownforces** [comment]
Also this, if you added db and parsing for buff, why can't we parse it?

**Comment by MasterDomino** [comment]
because buff is not yet hardcoded for now you can kill using buff

**Comment by 0Lucifer0** [comment]
The problem is not to parser them like item Its to make each function

**Comment by Uppermost** [comment]
What help is needed ? I can, help you ?

**Comment by Uppermost** [comment]
We need to open an other issue for debuff part or is the same? If yes maybe need to rename this issue

**Comment by 0Lucifer0** [comment]
Same Its skill effect

**Comment by Digitalis87** [comment]
What can we do to help ?

**Comment by Ciapa1** [comment]
Going to implement some Basic Stuff, >NO COMPLETE BCARD STUFF<

**Comment by Uppermost** [comment]
This issue will be complete after all version and need to keep open.

**Comment by Uppermost** [comment]
This part begin today. I need information on official about

* Heal packet
* Refresh buff packet
* Buff (add, remove...)
* Same for debuff.

**Comment by Uppermost** [comment]
- [ ] Packet definition are added !

**Comment by Uppermost** [comment]
when you lose a buff 

say 1 playerid 20 Tu perds l'effet : Esprit de l'ours.
bf 1 playerid 0.155.0 90
sr 9

**Comment by Ciapa** [comment]
We sould prolly move it to 1.0.5 R2, since there I'm going to be working on the whole Admin stuff in that Milestone. For now, Buff and BCard should be moved to a future Milestone, it is not realistic to also put it in 1.0.4. And since we have correct algo for most things, Buffs aren't even that required.

**Comment by Ciapa** [comment]
Moved to 1.0.5, maybe even 1.0.5 R2

**Comment by MasterDomino** [comment]
let the fire begin :D

**Comment by 0Lucifer0** [comment]
#1359
