### ISSUE TITLE
add SpSkill only when lvl(adventurer too)

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#399]
add SpSkill only when lvl

**Comment by MasterDomino** [comment]
add skill auto-learning for sp and adventurer

**Comment by 0Lucifer0** [comment]
jajamaru 	0 2 4 6 8 11 14 17 20 
chicken    0 10 20
pirate	0 3 5 10 15 20
other	0 2 4 6 8 10 12 14 16 18 20 

this is old level need to find how much skill there is by default for each sp (i think other is 5)

**Comment by 0Lucifer0** [comment]
why this was closed ?

**Comment by MasterDomino** [comment]
@0Lucifer0 KrisYiu closed it in https://github.com/OpenNos/OpenNos/commit/22eec5677cd210478916b997d208dac4f945608e
