### ISSUE TITLE
Vary shoot

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#402]
Vary the shots, such as SP4 Archer made a sudden left boomerang, right boomerang boomerangs and then both at the same time, the same for almost all basic skill sp. and power changes according to the skill, the second stronger than the first and third stronger than the second. (Increases the damage of about 5~)

**Comment by 0Lucifer0** [comment]
need packets of basic skill sp4

**Comment by Uppermost** [comment]
And all sp ^^

**Comment by 0Lucifer0** [comment]
seem's to be combo ;D
