### ISSUE TITLE
Act 5 craft missing

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#409]
Craft stores Act 5, are missing. (All) Need to find why (packet is present in packet.txt)

**Comment by 0Lucifer0** [comment]
i think it's another packet

**Comment by MasterDomino** [comment]
need to use filtering for packets and i think theres some issues on global with packets

**Comment by Uppermost** [comment]
mv 2 9404 12 68 4
m_list 2 4014 4017 4020 4032 4027 4901 4904 4907 4910 4913 4916 4919 4922 4925 -100
wopen  27 0
st 2 9414 80 100 100 11612 2272
mv 2 9408 27 28 4
mv 2 9406 14 125 4
mv 2 9405 96 60 4
mv 2 9404 14 66 4
wopen  0 0
st 2 9414 80 100 100 11612 2272
mv 2 9409 69 109 4
stat 9530 9530 3885 3885 0 32
mv 2 9405 95 60 4
mv 2 9404 15 67 4
n_inv 2 9414 0 100 2.0.2082.-1.300 2.1.2083.-1.120 2.2.2084.-1.500
mv 2 9409 68 110 4
st 2 9414 80 100 100 11612 2272
mv 2 9406 14 123 4
st 2 9414 80 100 100 11612 2272
mv 2 9409 67 108 4
stat 9530 9530 3885 3885 0 32
stat 9530 9530 3885 3885 0 32
mv 2 9408 28 29 4
mv 2 9407 28 104 4
wopen  0 0
mv 2 9406 13 124 4
mv 2 9404 14 65 4
st 2 9414 80 100 100 11612 2272
wopen  0 0
mv 2 9408 28 28 4
mv 2 9406 15 123 4
mv 2 9405 94 58 4
m_list 2 4014 4017 4020 4032 4027 4901 4904 4907 4910 4913 4916 4919 4922 4925 -100
wopen  27 0
mv 2 9404 14 66 4
stat 9530 9530 3885 3885 0 32
st 2 9414 80 100 100 11612 2272
mv 2 9408 28 29 4
m_list 3 1 4012 1 2394 30 2356 15 2355 15 2367 5 -1
mv 2 9405 95 58 4
mv 2 9404 13 67 4
m_list 3 1 4015 1 2352 30 2356 15 2355 15 2368 5 -1
mv 2 9409 69 107 4
st 2 9414 80 100 100 11612 2272
m_list 3 1 4018 1 2353 30 2356 15 2355 15 2369 5 -1
mv 2 9408 26 28 4
m_list 3 1 2353 20 2355 10 2370 2 -1
mv 2 9410 77 23 4
stat 9530 9530 3885 3885 0 32
stat 9530 9530 3885 3885 0 32
st 2 9414 80 100 100 11612 2272
mv 2 9408 24 29 4
m_list 3 1 2352 20 2355 10 2372 2 -1
mv 2 9406 16 122 4
mv 2 9405 96 58 4
m_list 3 1 2505 50 2506 30 2394 80 2357 20 2360 10 2369 3 2500 3 -1
mv 2 9410 76 23 4
mv 2 9409 69 109 4
st 2 9414 80 100 100 11612 2272
mv 2 9407 29 105 4
m_list 3 1 2505 50 2506 30 2354 80 2357 20 2360 10 2367 3 2500 3 -1
mv 2 9406 14 122 4
mv 2 9404 15 65 4
m_list 3 1 2505 50 2506 30 2354 80 2357 20 2360 10 2368 3 2500 3 -1
stat 9530 9530 3885 3885 0 32
st 2 9414 80 100 100 11612 2272
m_list 3 1 2505 35 2506 20 2354 60 2358 10 2359 5 2368 3 2501 3 -1
mv 2 9406 16 123 4
mv 2 9405 95 59 4
m_list 3 1 2505 35 2506 20 2394 60 2358 10 2359 5 2369 3 2501 3 -1
mv 2 9409 71 108 4
st 2 9414 80 100 100 11612 2272
mv 2 9408 24 28 4
m_list 3 1 2505 35 2506 20 2394 60 2358 10 2359 5 2367 3 2501 3 -1
mv 2 9406 15 125 4
mv 2 9404 16 67 4
m_list 3 1 2505 40 2506 20 2394 70 2356 10 2355 10 2367 3 2502 3 -1
mv 2 9409 69 109 4
stat 9530 9530 3885 3885 0 32
stat 9530 9530 3885 3885 0 32
m_list 3 1 2505 40 2506 20 2352 70 2356 10 2355 10 2368 3 2502 3 -1
st 2 9414 80 100 100 11612 2272
mv 2 9406 14 124 4
mv 2 9404 14 67 4
m_list 3 1 2505 40 2506 20 2353 70 2356 10 2355 10 2369 3 2502 3 -1

**Comment by 0Lucifer0** [comment]
it's just that your packetlogger forget npc_req ><

**Comment by MasterDomino** [comment]
future ;)

**Comment by Uppermost** [comment]
Is here just not in infos on this post ^^

**Comment by MasterDomino** [comment]
fixed
