### ISSUE TITLE
Add packet official like on first upgrade

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#412]
say 1 839749 12 Un bonus te procure une énergie nouvelle.
say 1 839749 12 Pour gagner un niveau, tu dois remplir complètement la barre de niveau.

Add this packet when you upgrade your level for the first time ( this message appear only 1x; for the first upgrade level (Official packet)

**Comment by 0Lucifer0** [comment]
It Will be done With quest
