### ISSUE TITLE
Skill Bug 

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#413]
[Skill Bug](http://sendvid.com/hn7ej73n)

When I use the skill "slash" of the Assassin the I will teleport to X:1 - Y:-1 and at other maps I can't walk more. ([example](http://sendvid.com/0bh7q6je))

**Comment by 0Lucifer0** [comment]
Yes cause the function is not coded yet like volcanor jump area targeted zone ...
