### ISSUE TITLE
Add random rarity on reputation shop

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#422]
Add random rarity when you buy an item on the reputation shop

R0 R1 R2 R3 R4 R5 R6 R7 (Random)

**Comment by Ciapa1** [comment]
This just contains basic logic for Rare, we still need to implement proper
Rates, which are the following:
R1: 100
R2: 70
R3: 50
R4: 30
R5: 15
R6: 5
R7: 1
Am 18.04.2016 23:20 schrieb "0Lucifer0" <notifications@github.com>:

**Comment by 0Lucifer0** [comment]
that can't be possible cause sometime rare = 0

**Comment by Ciapa1** [comment]
Never had that before
Am 19.04.2016 14:30 schrieb "0Lucifer0" <notifications@github.com>:
