### ISSUE TITLE
Spacebar bug

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#424]
When targeting a monster away and you press the space bar, you can not enter it. Your character will stop. But if you simply press the competence you will not have this problem. Also from time to time, when you press the space bar nothing will happen and it will not attack the monster. And press the space bar when you target a monster seems to remove combat mode your character ...

PS : I don't have this problem on the test server, only on the new version

**Comment by 0Lucifer0** [comment]
stay not fixed
