### ISSUE TITLE
Not Parsed skill war/mage/Adventure

### ISSUE THREAD

**Issue by Goblinek** [OpenNos/OpenNos#427]
Pleas repair parse skill for war, mage and adventure. Parse only Archer skills :-)

**Comment by Ciapa1** [comment]
Parsing Skills work for magician, warrior and adventurer for me. Please provide further detail about what doesn't work, so we can further investigate.

**Comment by Goblinek** [comment]
skill not add to shop

**Comment by Ciapa1** [comment]
Are you using the latest commit?

**Comment by Goblinek** [comment]
yeah

**Comment by 0Lucifer0** [comment]
You just Forget skill in packet.txt xD
