### ISSUE TITLE
Clean up worldpackethandler

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#428]

**Comment by chucktheripper** [comment]
Any Suggestions on new Handlers?
MapPacketHandler
CharacterPacketHandler
WorldPacketHandler
SkillPacketHandler 

??!!

**Comment by 0Lucifer0** [comment]
CommandPacketHandler ShopPacketHandler BasicPacketHandler BattlePacketHandler

**Comment by 0Lucifer0** [comment]
Basic= move/inventory/talk ...

**Comment by chucktheripper** [comment]
Sounds good and straight forward, actually the PacketHandler should only include methods which are based on a packet, best practice would be creating a Logic layer for the businesslogic combining the Handler / DAO and sibling Logics

**Comment by chucktheripper** [comment]
The functionality is here, also the CommandPacketHandler has been taken out of the WorldPacketHandler, some code duplication has been made as there are references from CommandPacketHandler to anything else, is there a way to wrap those methods into any depending GameObject?

**Comment by chucktheripper** [comment]
is this done?

**Comment by 0Lucifer0** [comment]
yep forget that there was an issue :P
