### ISSUE TITLE
need to parallelize disconnection/connection

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#429]
we need to parallelize disconnection/connection to avoid this bug
https://www.youtube.com/watch?v=hMfEKtUrrh4

**Comment by chucktheripper** [comment]
Tasking this operation should do it

**Comment by chucktheripper** [comment]
Its not possible to run this logic asynchronous as its synchronous  with the client connection, we would get problems with encryption and connection state of the TCPIP connection
