### ISSUE TITLE
Nobody can open a shop Bug

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#431]
If someone sends the m_shop 0... packet often (?) then no one can more open a shop on the map
[Shop Bug](http://sendvid.com/nk98snk0) (It's clientside only the shop owner can see that he owns a shop)

**Comment by 0Lucifer0** [comment]
i don't find a way to get that error what's the trick exactly 
i've tried spam m_shop 1 but no problem

**Comment by SoraPlays** [comment]
here a video about it 
[m_shop Bug](http://sendvid.com/jfbztoo8)

**Comment by 0Lucifer0** [comment]
should be fixed now
