### ISSUE TITLE
add monster summon and defenceSkill

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#436]
add monster summon

**Comment by Uppermost** [comment]
Tortle rest in gard when you're beside her (3/4 case)

/PII
ncif 3 3740
st 3 3740 55 0 100 100 3919 969

stat 4172 9730 2354 3985 0 32

stat 4172 9730 2422 3985 0 32

ncif 3 3740
st 3 3740 55 0 100 100 3919 969

u_s 0 3 3740
su 1 793751 3 3784 855 8 11 4001 0 0 0 0 1354 0 0

stat 4172 9730 2422 3985 0 32

ct 1 626114 3 3740 -1 -1 240

su 1 626114 3 3740 240 8 11 257 0 0 1 72 1078 0 0

ncif 3 3740
st 3 3740 55 0 72 100 2841 969

in 3 43 335240 192 202 2 100 100 0 0 0 -1 1 0 -1 - 0 -1 0 0 0 0 0 0 0 0

in 3 43 335241 193 200 2 100 100 0 0 0 -1 1 0 -1 - 0 -1 0 0 0 0 0 0 0 0

sr 0

u_s 0 3 3740
stat 4172 9730 2422 3985 0 32

ct 1 626114 3 3740 -1 -1 240

eff 1 626114 15

su 1 626114 3 3740 240 8 11 257 0 0 1 14 2265 0 0

ncif 3 3740
st 3 3740 55 0 14 100 576 969

sr 0

u_s 2 3 3740
ms_c 0

ncif 3 3740
stat 4172 9730 2371 3985 0 32

ct 1 626114 3 3740 -1 286 242

su 1 626114 3 3740 242 50 11 287 0 0 0 0 4926 3 0

lev 92 527973608 80 995 1225326000 790000 575079 3 0 1 949560

st 3 3740 55 0 1 100 0 969

in 2 319 329211 11 97 2 100 100 0 0 3 772123 1 0 -1 Kliff 1 2 0 0 0 0 0 0 0 0

in 2 176 329208 11 96 2 100 100 0 0 3 772123 1 0 -1 Ratufu^père^Noël 0 -1 0 0 0 0 0 0 0 0

in 3 42 335248 8 134 2 100 100 0 0 0 -1 1 0 -1 - 0 -1 0 0 0 0 0 0 0 0

in 3 42 335249 10 136 2 100 100 0 0 0 -1 1 0 -1 - 0 -1 0 0 0 0 0 0 0 0

eff 3 335249 5000

eff 3 335248 5000

out 9 1604011

ct 3 335249 1 626114 -1 -1 0

su 3 335249 1 626114 0 12 11 200 0 0 1 39 375 0 0

stat 3797 9730 2371 3985 0 32

ct 3 335248 1 626114 -1 -1 0

su 3 335248 1 626114 0 12 11 200 0 0 1 39 0 1 0

// TORTLE
ncif 3 3875
st 3 3875 58 0 100 100 4252 1065

stat 3818 9730 3380 3985 0 32

ncif 3 3875
st 3 3875 58 0 100 100 4252 1065

ncif 3 3875
walk 59 148 0 12
st 3 3875 58 0 100 100 4252 1065

cond 1 626114 0 0 12

cond 1 626114 0 0 12

stat 3882 9730 3380 3985 0 32

stat 3882 9730 3448 3985 0 32

walk 63 148 1 12
ncif 3 3875
cond 1 626114 0 0 12

cond 1 626114 0 0 12

st 3 3875 58 0 100 100 4252 1065

walk 64 147 1 12
cond 1 626114 0 0 12

cond 1 626114 0 0 12

qnaml 100 #rl Le joueur suivant cherche des membres pour le raid Sire Draco :xPyk

ncif 3 3875
u_s 0 3 3875
st 3 3875 58 0 100 100 4252 1065

stat 3882 9730 3448 3985 0 32

ct 1 626114 3 3875 -1 -1 240

su 1 626114 3 3875 240 8 11 257 0 0 1 75 1062 0 0

walk 61 147 1 12
cond 1 626114 0 0 12

cond 1 626114 0 0 12

npinfo 0
p_clear

sc_p 3 1508 334395 1 1000 0 1 0 92 135 40 10 100 0 21 34 21 34 20 4 60 60 60 60 221 221 60 60 0 15 0 Ratufu^pirate^(Obsc 0

sc_p 4 1506 334394 1 1000 0 1 0 92 135 40 10 100 0 21 34 21 34 20 1 60 60 60 60 221 221 60 60 0 15 0 Ratufu^pirate^(Feu) 0

sc_p 5 821 334393 4 1000 75 0 0 59 77 56 10 100 0 25 50 28 50 24 0 2 2 2 2 445 445 78 78 0 165 0 Mini^Kangpen 0

sc_p 6 535 334392 5 1000 26 2 0 56 92 70 14 75 0 37 64 40 64 37 2 -10 8 5 4 295 295 97 97 0 273 0 Bonhomme^de^neige 0

sc_p 0 333 334391 3 1000 33 0 0 40 52 37 4 70 0 23 41 22 41 18 0 0 0 0 0 195 195 20 20 0 90 0 Poule 0

sc_n 1 319 334390 50 1000 1536 990.0.0 997.0.0 -1 -1 0 0 0 0 260 324 234 4 70 0 149 238 133 238 135 0 0 0 0 0 9576 9576 3270 3270 0 2293816 Kliff -1 0 -1 -1 -1 -1

sc_n 0 317 334389 24 1000 0 991.0.0 996.0.0 -1 -1 0 0 1 0 124 156 196 4 70 0 66 140 77 140 63 0 0 0 0 0 1738 1738 681 681 0 117720 Bob -1 0 -1 -1 -1 -1

sc_p 7 176 334388 1 1000 0 0 0 30 38 30 4 70 0 17 34 19 34 17 2 0 0 0 0 121 121 60 60 0 15 0 Ratufu^père^Noël 0

sc_p 1 9 334387 1 1000 0 0 0 37 35 27 4 70 0 38 31 17 31 13 0 0 0 3 13 156 156 10 10 0 15 0 Joyeux^Mouton 0

ncif 3 3875
sr 0

st 3 3875 58 0 75 100 3190 1065

sr 3

rest 1 692453 1

remove 10 0
u_s 0 3 3875
stat 3882 9530 3448 3985 0 32

stat 3882 9530 3448 3785 0 32

pairy 1 626114 0 0 0 0

cond 1 626114 0 0 12

bf 1 626114 0.62.0 92

stat 3882 9730 3448 3785 0 32

stat 3882 9730 3448 3985 0 32

stat 3882 9730 3448 3985 0 32

sc 1 0 800 948 943 14 190 0 0 722 778 782 16 350 0 104 195 115 195 93 4 4 4 4

ivn 0 15.803.0.0.0

equip 5 0 0.4903.5.0.0 2.340.0.0.0 5.4912.6.0.0 9.227.0.0.0 11.347.0.0.0 12.904.0.0.0 13.625.0.0.0 14.654.0.0.0

in 1 Shiro` - 790038 11 97 2 0 1 0 14 3 204.271.154.293.227.802.4150.4142 100 55 0 19 4 3 0 0 1 7 56 2 -1 - 13 0 5 0 0 55 0 0 0 10 0

gidx 1 790038 -1 - 0

in 2 417 329227 12 98 2 56 60 0 0 3 790038 1 0 -1 Princesse^Sakura 1 2 0 0 0 0 0 0 0 0

ncif 3 3875
stat 3882 9730 3448 3985 0 32

ct 1 626114 3 3875 -1 -1 240

eff 1 626114 15

su 1 626114 3 3875 240 8 11 257 0 0 1 27 2040 0 0

st 3 3875 58 0 27 100 1150 1065

walk 60 148 1 12
cond 1 626114 0 0 12

cond 1 626114 0 0 12

sr 0

ncif 3 3875
walk 64 148 0 12
st 3 3875 58 0 27 100 1150 1065

cond 1 626114 0 0 12

cond 1 626114 0 0 12

walk 65 149 1 12
ncif 3 3875
cond 1 626114 0 0 12

cond 1 626114 0 0 12

st 3 3875 58 0 27 100 1150 1065

walk 64 149 0 12
cond 1 626114 0 0 12

cond 1 626114 0 0 12

u_s 1 3 3875
ncif 3 3875
ms_c 0

stat 3882 9730 3448 3985 0 32

ct 1 626114 3 3875 -1 -1 241

su 1 626114 3 3875 241 8 23 258 0 0 1 14 535 0 0

st 3 3875 58 0 14 100 615 1065

ct 3 3875 1 626114 -1 -1 418

su 3 3875 3 3875 418 10 11 1049 0 0 1 14 0 -2 0

su 3 3875 1 626114 418 10 11 1049 0 0 1 39 0 7 0

walk 62 146 1 12
cond 1 626114 0 0 12

cond 1 626114 0 0 12

sr 1

ncif 3 3875
st 3 3875 58 0 14 100 615 1065

ncif 3 3875
st 3 3875 58 0 14 100 615 1065

say 1 -1 6 [NiZzAr]:lancé koi?

spk 1 701843 1 NiZzAr lancé koi?

ncif 3 3875
c_mode 2 329227 2333 0 0

out 2 329227

in 2 417 329227 12 98 2 57 61 0 0 3 790038 1 0 2333 Diablotin^Hongbi 1 2 1 0 0 1317 0 0 0 0

st 3 3875 58 0 14 100 615 1065

u_s 1 3 3875
ms_c 0

stat 3946 9730 3448 3985 0 32

stat 3946 9730 3448 3985 0 32

ct 1 626114 3 3875 -1 -1 241

su 1 626114 3 3875 241 8 23 258 0 0 1 1 539 0 0

ncif 3 3875
st 3 3875 58 0 1 100 76 1065

ct 3 3875 1 626114 -1 -1 418

walk 61 143 0 12
su 3 3875 3 3875 418 10 11 1049 0 0 1 1 0 -2 0

su 3 3875 1 626114 418 10 11 1049 0 0 1 35 458 5 0

stat 3488 9730 3448 3985 0 32

sr 1

cond 1 626114 0 0 12

cond 1 626114 0 0 12

c_mode 3 3875 462 0 0

say 1 735833 13 <Total> [Atchoul]:Vend tunique 93 r7 +8 Mage (anti debuff)/ Tunique Archer 93 r7 +8 (Full esquive)/ Achete boite R7 act 4 me mp :)

walk 63 145 1 12
rest 1 692453 0

ncif 3 3875
cond 1 626114 0 0 12

cond 1 626114 0 0 12

st 3 3875 58 0 1 100 76 1065

in 3 201 3835 152 174 2 100 100 0 0 0 -1 0 0 -1 - 0 -1 0 0 0 0 0 0 0 0

say 1 763446 13 <Total> [Shirotsume]:vend cost oto me mp

ncif 3 3875
st 3 3875 58 0 1 100 76 1065

out 2 329227

c_mode 1 790038 2433 0 0 0

ncif 3 3875
st 3 3875 58 0 1 99 76 1055

stat 3552 9730 3448 3985 0 32

ncif 3 3875
in 3 223 3931 156 198 2 100 100 0 0 0 -1 0 0 -1 - 0 -1 0 0 0 0 0 0 0 0

st 3 3875 58 0 1 99 76 1055

ncif 3 3875
st 3 3875 58 0 1 98 76 1045

stat 3616 9730 3448 3985 0 32

stat 3616 9730 3516 3985 0 32

ncif 3 3875
st 3 3875 58 0 1 98 76 1045

in 3 201 3836 146 200 2 100 100 0 0 0 -1 0 0 -1 - 0 -1 0 0 0 0 0 0 0 0

in 3 200 3807 159 166 2 100 100 0 0 0 -1 0 0 -1 - 0 -1 0 0 0 0 0 0 0 0

in 3 200 3802 148 195 2 100 100 0 0 0 -1 0 0 -1 - 0 -1 0 0 0 0 0 0 0 0

ncif 3 3875
st 3 3875 58 0 1 97 76 1035

stat 3680 9730 3516 3985 0 32

say 1 -1 6 [LEDIABOLIQU]:le raid act6

spk 1 41365 1 LEDIABOLIQU le raid act6

ncif 3 3875
st 3 3875 58 0 1 97 76 1035

out 1 790038

ncif 3 3875
st 3 3875 58 0 1 96 76 1025

stat 3744 9730 3516 3985 0 32

stat 3744 9730 3584 3985 0 32

ncif 3 3875
st 3 3875 58 0 1 96 76 1025

say 1 -1 6 [LEDIABOLIQU]:on a plusieur sceau la

spk 1 41365 1 LEDIABOLIQU on a plusieur sceau la

ncif 3 3875
st 3 3875 58 0 1 95 76 1015

stat 3808 9730 3584 3985 0 32

ncif 3 3875
st 3 3875 58 0 1 95 76 1015

walk 59 145 0 12
cond 1 626114 0 0 12

cond 1 626114 0 0 12

walk 58 145 0 12
cond 1 626114 0 0 12

cond 1 626114 0 0 12

walk 57 145 1 12
cond 1 626114 0 0 12

cond 1 626114 0 0 12

ncif 3 3875
st 3 3875 58 0 1 94 76 1005

stat 3872 9730 3584 3985 0 32

stat 3872 9730 3652 3985 0 32

ncif 3 3875
st 3 3875 58 0 1 94 76 1005

c_mode 3 3875 -1 0 0

ncif 3 3875
st 3 3875 58 0 1 93 76 995

stat 3936 9730 3652 3985 0 32

ncif 3 3875
st 3 3875 58 0 1 93 76 995

ncif 3 3875
st 3 3875 58 0 1 93 76 995

stat 4000 9730 3652 3985 0 32

stat 4000 9730 3720 3985 0 32

walk 58 145 0 12
cond 1 626114 0 0 12

cond 1 626114 0 0 12

u_s 1 3 3875
ms_c 0

stat 4000 9730 3720 3985 0 32

ct 1 626114 3 3875 -1 -1 241

eff 1 626114 15

su 1 626114 3 3875 241 8 23 258 0 0 0 0 1368 0 0

lev 92 527976394 80 995 1225326000 790000 575079 3 0 1 949560

sr 1

in 3 223 3919 34 145 2 100 100 0 0 0 -1 0 0 -1 - 0 -1 0 0 0 0 0 0 0 0

**Comment by 0Lucifer0** [comment]
ok tortle seem's to be a simple skill
