### ISSUE TITLE
cleanup Packetwait

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#44]
Wait for Packet implementation in ClientSession needs to be cleaned up, its a bit dirty

**Comment by 0Lucifer0** [comment]
i just add   packetNumber = 0;
public int packetNumber { get; set; }
this.packetNumber++;
 and add this
if (this.packetNumber != 1 && packetHeader != "0" && !TriggerHandler(packetHeader, packet, false))
                    {
                        Logger.Log.ErrorFormat(Language.Instance.GetMessageFromKey("HANDLER_NOT_FOUND"), packetHeader);
                    }
so the packet handler message is not shown if the packet is the first one or the second one

**Comment by chucktheripper** [comment]
fixed bug with packet wait (username & password)

removed packet number
