### ISSUE TITLE
Level < 20 not use seed

### ISSUE THREAD

**Issue by earthnash** [OpenNos/OpenNos#442]
you miss some condition.

**Comment by 0Lucifer0** [comment]
What condition ?

**Comment by earthnash** [comment]
if(Session.Character.Level < 20)
                        {
                            Session.Client.SendPacket(Session.Character.GenerateSay(string.Format(Language.Instance.GetMessageFromKey("SEED_USED"), 10), 10));
                            Session.Character.Hp = (int)(Session.Character.HPLoad() / 2);
                            Session.Character.Mp = (int)(Session.Character.MPLoad() / 2);
                            Session.Client.SendPacket(Session.Character.GenerateTp());
                            ClientLinkManager.Instance.Broadcast(Session, Session.Character.GenerateTp(), ReceiverType.AllOnMap);
                            ClientLinkManager.Instance.Broadcast(Session, Session.Character.GenerateRevive(), ReceiverType.AllOnMap);
                        }

**Comment by 0Lucifer0** [comment]
So we just miss a message différent

**Comment by earthnash** [comment]
Session.Character.Level >= 20? ??
