### ISSUE TITLE
Set Options via Command Line Arguments

### ISSUE THREAD

**Issue by Ciapa1** [OpenNos/OpenNos#443]
Need to be able to set options via Command Line Arguments to be able to import data automatically via Jenkins.

for example:
OpenNos.Import.Console.exe [Path_To_Folder_With_Data]

It should automatically import everything if called from CLI

**Comment by 0Lucifer0** [comment]
Good idea :)

**Comment by Ciapa1** [comment]
Not just a good idea, it's required for Jenkins ;)
