### ISSUE TITLE
Split InventoryItem

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#446]
there was some pictures already sent, no need for long descryption
[![https://gyazo.com/2548afe59a19c5afc5b43de2c0a83faa](https://i.gyazo.com/2548afe59a19c5afc5b43de2c0a83faa.gif)](https://gyazo.com/2548afe59a19c5afc5b43de2c0a83faa)

**Comment by chucktheripper** [comment]
because of splitting the entities is much much much busier with entity framework than just putting everything in one table, we use the entity framework inheritance TPH structure.

**Comment by chucktheripper** [comment]
Anything regarding this topic can be announced for me

**Comment by chucktheripper** [comment]
fixed with branching back inventoryitem branch
