### ISSUE TITLE
instant healing items stack

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#449]
if you spam instant health items e.g. potions you can use more than you actually have hp
[![https://gyazo.com/0583e881cf7ad76b3b708c0439ce2214](https://i.gyazo.com/0583e881cf7ad76b3b708c0439ce2214.gif)](https://gyazo.com/0583e881cf7ad76b3b708c0439ce2214)

**Comment by 0Lucifer0** [comment]
same as #447

**Comment by MasterDomino** [comment]
not same issue still persists even if youre full health and mana is regenerating you can use hp potion

**Comment by 0Lucifer0** [comment]
Why reopen ?

**Comment by 0Lucifer0** [comment]
How can It be possible...

**Comment by 0Lucifer0** [comment]
Ok i think i Know why and yes It the same issue ;) but not fixed

**Comment by MasterDomino** [comment]
soo "JUST DO IT!"

**Comment by 0Lucifer0** [comment]
Yes as soon as possible
