### ISSUE TITLE
Monsters can attack 2 characters at the same time

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#450]
happens sometimes

**Comment by 0Lucifer0** [comment]
Ah yes (when they are at the same place) need to find a way to fix this

**Comment by MasterDomino** [comment]
nope i was standing near chuck and they just shot 2 targeted skills at the same time

**Comment by 0Lucifer0** [comment]
Yes need to change something in the su and in the Target system

**Comment by 0Lucifer0** [comment]
fixed
