### ISSUE TITLE
revive confuses characters

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#451]
![zrzut ekranu 427](https://cloud.githubusercontent.com/assets/16002990/14760466/15a25bb6-0945-11e6-828b-5cd8ae67af97.png)
![zrzut ekranu 426](https://cloud.githubusercontent.com/assets/16002990/14760467/18f90a76-0945-11e6-898a-8ff6025b6c75.png)
![zrzut ekranu 425](https://cloud.githubusercontent.com/assets/16002990/14760469/1c095482-0945-11e6-8fee-704cdbfcf7f3.png)

**Comment by 0Lucifer0** [comment]
Whats the problem ?

**Comment by 0Lucifer0** [comment]
Ah ok ;) i think i Know why :)
