### ISSUE TITLE
Equipping possible with open shop

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#452]
This shouldnt be possible and it's causing errors

**Comment by chucktheripper** [comment]
i mean NPCShop, not private shop

**Comment by chucktheripper** [comment]
damn closing button

**Comment by 0Lucifer0** [comment]
what's the problem with it? npcshop is real time not like exchange or trade so i don't see any way to cause error...

**Comment by 0Lucifer0** [comment]
same problem as #453
