### ISSUE TITLE
add HeroLevel system

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#454]
leveling and wear requirement

**Comment by MasterDomino** [comment]
added level requirement

**Comment by 0Lucifer0** [comment]
You did It ?

**Comment by MasterDomino** [comment]
yup i leave leveling for you

**Comment by 0Lucifer0** [comment]
You mean xp right ? Give It to markus i have no more 88+ on official to test ...

**Comment by Ciapa1** [comment]
Level is bigger than 30
XP Gain only in Act6 PVE
If you die, you loose 5% on Lv1, whereas it doesn't matter where you die. PVP, PVE, Raid, Act4 Raid, doesn't matter

**Comment by Ciapa1** [comment]
I think we should make the value static, for example always ~5% XP Loss on death
But t should be possible to disable XP Loss

**Comment by MasterDomino** [comment]
Maybe add something like server config ex enableXPLoss = 1 or 0

**Comment by 0Lucifer0** [comment]
this will be added in V6.0.0.0 cause it's only act6 system
