### ISSUE TITLE
add monster/npc talk

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#459]
add monster/npc talk

PS: some monster have a random talk some others have a dead shout(mandra)

**Comment by 0Lucifer0** [comment]
need to find a way to get their message and when to send it (parse it)

**Comment by MasterDomino** [comment]
we can log packets and see what that monsters send might be that they just send some info to client and it can be generalized soo no need to parse it, for now i want to ask someone to test it by logging packets on krem for example
