### ISSUE TITLE
While trade open a shop 

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#460]
When you trade you can open a shop and ensures for duplication of the items
[Video](http://sendvid.com/wx400aq6)

**Comment by 0Lucifer0** [comment]
nice trick :D will fix it :D btw i think it can be interesting to test on official it's possible that they have this issue to :P

**Comment by SoraPlays** [comment]
unfortunately is that not possible :p 

Other issue: you can open a npc shop and sell your item, however persons can buy out of your shop  the item too
