### ISSUE TITLE
add InVisible status

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#464]
add InVisible status
![invisible](https://cloud.githubusercontent.com/assets/18089510/14763020/d3e49faa-0989-11e6-8f15-baf96b87c7c7.png)

c_info Test - -1 -1 - ID **6** 0 1 5 0 1 0 0 0 0 0 0

it's not very important, but why not :p

**Comment by MasterDomino** [comment]
humm doesnt seem to work for me

**Comment by 0Lucifer0** [comment]
the problem is that we can't do this without refresh cinfo and we don't want too... we should find the real packet that add invisible status with cmode
