### ISSUE TITLE
create generic BaseDAO

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#471]
Add a BaseDTO with some informations
Implement a generic BaseDAO with following Methods
InsertOrUpdate(ref BaseDTO)
InsertOrUpdate(IEnumerable<BaseDTO)
Delete(id)
Delete(BaseDTO)
Delete(IEnumerable<Id>)
Delete(IEnumerable<BaseDTO>)
LoadById(id)
LoadAll()

**Comment by MasterDomino** [comment]
Shouldnt we also add 
Insert
Update
^separate ones show up often

**Comment by chucktheripper** [comment]
--this is not necessary as we dont have a general structure of our entities
