### ISSUE TITLE
Impossible to connect

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#473]
![capture](https://cloud.githubusercontent.com/assets/16693364/14767544/74857328-0a28-11e6-88fe-795af8b7737f.PNG)

I get the connection to the world but you are stuck on the channel of choice

**Comment by Uppermost** [comment]
Yes is bug for the moment :)

**Comment by MasterDomino** [comment]
how and when does it occur

**Comment by Uppermost** [comment]
When what we are trying to connect from the new update
