### ISSUE TITLE
0 inventory 0 equipment when connect

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#477]
This bug does not apear every time
![20160424-4-kevin](https://cloud.githubusercontent.com/assets/16693364/14770068/5f991b5a-0a68-11e6-9333-d42f63938544.jpg)

and when i $Teleport to me or change map i see my equipment but i don't see [GM] with my pseudo and inventory is empty when i move item i see the old item
![buginventory](https://cloud.githubusercontent.com/assets/16693364/14770130/1d589c28-0a6a-11e6-8ef2-99ddbec4cd9d.PNG)

**Comment by 0Lucifer0** [comment]
it seem's your client have a problem^^ the 4th xp bar should be called mode C (i think you use new client with an old launcher)
