### ISSUE TITLE
review ClientLinkManager

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#479]
review ClientLinkManager (change the whole system)/optimise it

**Comment by chucktheripper** [comment]
We should use the Rx extensions to manage observing clientsessions.

**Comment by chucktheripper** [comment]
ill do both and that #296 at once

**Comment by 0Lucifer0** [comment]
i think it's directly linked to #554

**Comment by chucktheripper** [comment]
Will be done with #554
