### ISSUE TITLE
we get very often the message already connected

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#482]
we get very often the message already connected

**Comment by chucktheripper** [comment]
Servers are too quick ;) the already connected thing also happens on official :P ill do my bester after the inventoryitem thing

**Comment by 0Lucifer0** [comment]
yep the problem is that it show the message with a not connected account too (not on official) if i try to quick to connect to account at first connection it send already connected ^^

**Comment by chucktheripper** [comment]
This maybe happens when the wcf hasnt been cleaned up after restarting of world-server
