### ISSUE TITLE
Optimise fight system 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#486]
https://gyazo.com/ce5a6bc428816abe206a22aa7af55261

The last shoot have a problem, (stop the attack) 

find the problem (This problem happens when changing position when we tapes (when we move and clap at the same time)

**Comment by Uppermost** [comment]
Not resolve

**Comment by 0Lucifer0** [comment]
What is exactly the problem ?

**Comment by Uppermost** [comment]
When we go back and we try to attack at the same time, the character stops typing desfois hang ~ 1 second

**Comment by Uppermost** [comment]
Example 

Opennos : https://gyazo.com/c18317cdf7fd4cffc5b4062d41c39ce2 > Attack stop every attack

Official : https://gyazo.com/778dcf2e0b6e4285f844b6d772cda1ee > Attack not stop after every attack
