### ISSUE TITLE
Dead bug

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#487]
![image](https://cloud.githubusercontent.com/assets/15254478/14805672/598563c0-0b6e-11e6-9ec6-cce1fbf758f4.png)
not dead? (0 HP)

https://gyazo.com/5fb1772798ec423937cf0a99c468375e

**Comment by MasterDomino** [comment]
It was fixed, when does it occur

**Comment by 0Lucifer0** [comment]
i forget to reput dead system in new battle system XD
