### ISSUE TITLE
add MapItem delay (Remove from Map, Remove owner)

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#495]
add MapItem delay
-disapear delay
-owner delay

**Comment by Uppermost** [comment]
Ok is 180 seconds on official, but not for all item

**Comment by MasterDomino** [comment]
180 seconds for dissapear? also check for remove owner, and what item you mean(propably power seed)

**Comment by Uppermost** [comment]
This is what was said on the official forum "Objects in Act 6 disappear after 180 seconds as on any other map" by the community manager.
