### ISSUE TITLE
sum shoes with gloves 

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#499]
you can sum shoes with gloves
[pic](http://img5.fotos-hochladen.net/uploads/20160429164bwnr4miagt.gif)

**Comment by 0Lucifer0** [comment]
i forget the () will fix asap
 if ((this.InventoryItem.Upgrade + item2.InventoryItem.Upgrade) < 6 &&
 
 (((iteminfo2.EquipmentSlot == (byte)EquipmentType.Gloves) && (iteminfo2.EquipmentSlot == (byte)EquipmentType.Gloves)) || ((iteminfo.EquipmentSlot == (byte)EquipmentType.Boots) && (iteminfo2.EquipmentSlot == (byte)EquipmentType.Boots))))

**Comment by SoraPlays** [comment]
@0Lucifer0 it still works:
[sum bug](http://sendvid.com/80zjbzeh)
