### ISSUE TITLE
Cleanup Database

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#5]
- Create foreign key constraints (new Association)
- Use naming conventions based on account / character
- create 1 long key property per entity
- generate new database script

**Comment by chucktheripper** [comment]
EntityNames are always singular, underlying set has always the same name as the entity (set will be added by EDMX automatically)

this is not the final state of the database, just the formatting of the exisiting one

**Comment by chucktheripper** [comment]
Take a look at underlying entities, as we use c# for EF and MySQL for DB, the Entity Name is Account but the underlying table account

**Comment by 0Lucifer0** [comment]
need to add type value in portals
