### ISSUE TITLE
inventory Bug

### ISSUE THREAD

**Issue by Fadeur** [OpenNos/OpenNos#500]
https://gyazo.com/e980da161fd8a34ece36e4ecc90db976

**Comment by 0Lucifer0** [comment]
i don't understand the problem it delete item?

**Comment by MasterDomino** [comment]
after using herolvl and wear hero item inventory refreshes and doesnt load current items then after changing places its getting updated and it shows up

**Comment by 0Lucifer0** [comment]
i don't find a way to get that bug i think it was fixed by the new inventory system right?
