### ISSUE TITLE
Exchange Bugs 

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#505]
- When you drag any item into the transfer window and confirm your item and send for example 'exc_list 500000' but you only have 500 gold the trading partner will get 500000 gold and you have then -499500 gold.

- The same thing with items the partner gets nothing (other packet exc_list 0 0 22 **-1**):
[Video](http://sendvid.com/of71gra0) when you do this on official the trade will canceled. 
You can also lost your item and the trading partner gets two of them [Video](http://sendvid.com/gdicm60v)
the exchange order is important!

**Comment by SoraPlays** [comment]
> When you drag any item into the transfer window and confirm your item and send for example 'exc_list 500000' but you only have 500 gold the trading partner will get 500000 gold and you have then -499500 gold.

Video: [exc_list bug](http://sendvid.com/10ekjbmy)
it still works :-)

**Comment by 0Lucifer0** [comment]
erf yes my bad will fix this

**Comment by SoraPlays** [comment]
@0Lucifer0 can you also fix this bug:
[exc_list double](http://sendvid.com/2eq20f4i)
or should I open a new issue?

**Comment by 0Lucifer0** [comment]
Open new issue ;) btw Nice trick ;)
