### ISSUE TITLE
prevent some monsters from attacking 

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#510]
add new table to parse and add if CanAttack == 1 attack method

**Comment by 0Lucifer0** [comment]
What do you mean?

**Comment by MasterDomino** [comment]
https://i.gyazo.com/26fb2ffac5416e2e5e0ad1b270363480.png this should not attack

**Comment by 0Lucifer0** [comment]
This Will be fix by buff the problem is that They use à skill as a buff and for the moment we only hit With all skills
