### ISSUE TITLE
find a way to calculate morphid by vehicle item vnum

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#511]
find a way to calculate morphid by vehicle item vnum

**Comment by MasterDomino** [comment]
if theres no way to calculate it we might need to hardcode it, other idea i have is to add file with morph data eg. "morph.id" and just parse it, update when new added etc.

**Comment by 0Lucifer0** [comment]
we will hardcode it in the parser. Need to add a new table :D
