### ISSUE TITLE
Remove icon aggressive on the ice peaks 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#518]
![image](https://cloud.githubusercontent.com/assets/15254478/15001990/c00f5d6a-119c-11e6-8116-888777b3791f.png)

(is a invisible monster)

**Comment by MasterDomino** [comment]
not only ice peaks, for example there are missions in which you need to kill devil dogs and the ranges in which they are spawned are invisible monsters too
![img_04052016_181630](https://cloud.githubusercontent.com/assets/16002990/15025794/4e813a2a-123b-11e6-81ae-43ba501d887f.png)

**Comment by Uppermost** [comment]
I have remove this monster quest in my last packet.txt i think but in act 4 is different we need this monster

**Comment by 0Lucifer0** [comment]
Yes we Know but quest should be just a bug for the act4 Its différent

**Comment by 0Lucifer0** [comment]
we need a way to determine if the monster is invisible or not...

**Comment by Uppermost** [comment]
ok in raid, circle is too monster not only ice peaks
