### ISSUE TITLE
monster can hit you when you're invisible[GM]

### ISSUE THREAD

**Issue by earthnash** [OpenNos/OpenNos#521]
![invisible](https://cloud.githubusercontent.com/assets/15151087/15006020/05fdd03c-11f6-11e6-97b3-1865b04f6148.jpg)

**Comment by SoraPlays** [comment]
also monster can hit you when you're only in the near and a other person hit them.
![3323](https://cloud.githubusercontent.com/assets/18089510/15025181/53f3c778-1238-11e6-91a2-3af82aa43959.gif)

**Comment by 0Lucifer0** [comment]
Add an other issue When not part of the same problem ;)
