### ISSUE TITLE
dead bug

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#523]
![bugdie](https://cloud.githubusercontent.com/assets/16693364/15013113/d101f540-11fd-11e6-8e41-34d9ac495a22.PNG)
![bugdie2](https://cloud.githubusercontent.com/assets/16693364/15013116/d5db15ce-11fd-11e6-819a-a776fc5c4ee8.PNG)

when i'm dead monster continue hit me

**Comment by Dactylr** [comment]
[Bug vid](http://sendvid.com/f30312y1)
@0Lucifer0 still bugy

**Comment by 0Lucifer0** [comment]
Are you sure your uptodate because if you Life is under 0 Monster cant attack you

**Comment by Dactylr** [comment]
test it with lot of this monster id = `2531`

**Comment by 0Lucifer0** [comment]
So this is not the same problem the first problem was With only 1
