### ISSUE TITLE
inventorylist exception

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#527]
this bug just randomly when I drop an item or when I buy an item or I sp up or I use the skills

> Exception non gérée : System.InvalidOperationException: La séquence contient plu
sieurs éléments correspondants.
   à System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`
2 predicate)
   à OpenNos.GameObject.InventoryList.LoadInventoryBySlotAndType(Int16 slot, Byt
e type) dans C:\Users\Administrateur\Documents\GitHub\OpenNos\OpenNos.GameObject
\InventoryList.cs:ligne 267
   à OpenNos.GameObject.Character.Save() dans C:\Users\Administrateur\Documents\
GitHub\OpenNos\OpenNos.GameObject\Character.cs:ligne 1180
   à OpenNos.GameObject.ClientLinkManager.<>c.<SaveAllProcess>b__35_0(ClientSess
ion s) dans C:\Users\Administrateur\Documents\GitHub\OpenNos\OpenNos.GameObject\
Networking\ClientLinkManager.cs:ligne 572
   à System.Collections.Generic.List`1.ForEach(Action`1 action)
   à OpenNos.GameObject.ClientLinkManager.<SaveAllProcess>d__35.MoveNext() dans
C:\Users\Administrateur\Documents\GitHub\OpenNos\OpenNos.GameObject\Networking\C
lientLinkManager.cs:ligne 572
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duq
uel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6
_1(Object state)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object stat
e)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCon
text, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, Co
ntextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWork
Item.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by chucktheripper** [comment]
there is a bug in inventory, slot and type are unique together, add a unique constraint index also to the table

**Comment by aerzy** [comment]
![inventory](https://cloud.githubusercontent.com/assets/16693364/15030442/8d80d49e-1252-11e6-8f32-cb3ef88a12fb.PNG)
inventoryId or CharacterId ?

**Comment by chucktheripper** [comment]
this is actually a todo according to the fix of the problem, needs to be done in the entity model

**Comment by chucktheripper** [comment]
can you provide a scenario where this happens? Reproducable?

**Comment by aerzy** [comment]
upgrade sp / drop / buy on pnj but not all time

**Comment by aerzy** [comment]
when disconect too

**Comment by chucktheripper** [comment]
hmm are you up to date?

**Comment by aerzy** [comment]
yes

**Comment by aerzy** [comment]
![crash](https://cloud.githubusercontent.com/assets/16693364/15091860/5ae5be3a-1457-11e6-978f-35f787a9bae3.PNG)
when connect

**Comment by chucktheripper** [comment]
it's really weird i never had that error, how many people are at once on your server when something like this happens?

**Comment by aerzy** [comment]
When one is ten it does fairly frequently

**Comment by chucktheripper** [comment]
When one is ten? Do you mean 10 Players?

**Comment by aerzy** [comment]
yes sry for my bad english

**Comment by chucktheripper** [comment]
Hmm this could probably be a multithreading problem

**Comment by chucktheripper** [comment]
The error itself actually means that when he saves the inventory, he wants to load two items from the same slot / type which shouldnt be possible

**Comment by aerzy** [comment]
ah if i have create shop with sp 
![sp](https://cloud.githubusercontent.com/assets/16693364/15106477/ec53c736-15c9-11e6-8d4a-e4d349cf3e5f.PNG)

is the probleme ? 'type' 0

**Comment by chucktheripper** [comment]
This actually has to do with inventory of the character and seems to be a problem, if there were some bug absuses to duping, it could cause this problem

**Comment by aerzy** [comment]
ok i delete this shop ?

**Comment by chucktheripper** [comment]
It should have nothing to do with the shop

**Comment by aerzy** [comment]
yes this bug produce only when i create shop and in shoplist sp type 0

**Comment by aerzy** [comment]
http://pastebin.com/sceDj7AA

**Comment by chucktheripper** [comment]
We're talking about the InventoryList exception, and yea i still couldnt reproduce it
