### ISSUE TITLE
Command bug?

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#530]
After trying to create a Item with the command "$CreateItem"... This happens only if i try to create a specialists like (Wildkeeper)
[http://ddlw.org/img/riksud0a.jpg](url)

I also get an error if i try to summon... i dont know why but a couple of days ago everything worked fine..
[http://ddlw.org/img/ep6cet5h.jpg](url)

**Comment by aerzy** [comment]
item create invisible , moves item in you inventory

**Comment by The-Art-Of-War** [comment]
Dafuq :D thats a bit weird, but whats up with the $Summon thing ?

**Comment by aerzy** [comment]
for me summon work but i don't see u screenshot

**Comment by aerzy** [comment]
personaly i don't get error

**Comment by The-Art-Of-War** [comment]
Yeah i failed a bit linking the images xD...
u need to copy and paste it manualy and if i try to $Summon the Consol say's only [ERROR] ---

**Comment by aerzy** [comment]
open with ctrl+F5

**Comment by chucktheripper** [comment]
are there images?

**Comment by chucktheripper** [comment]
ok i found the bug and ill fix it
