### ISSUE TITLE
Can't use $createitem

### ISSUE THREAD

**Issue by earthnash** [OpenNos/OpenNos#531]
but some item can create
![can t createitem](https://cloud.githubusercontent.com/assets/15151087/15036995/ced1f068-12c0-11e6-8e67-088617ea1c04.jpg)

**Comment by 0Lucifer0** [comment]
What is this item ? More détails

**Comment by earthnash** [comment]
Blue Crystal Gemstone 2195

**Comment by earthnash** [comment]
VNUM 1000-3999 @0Lucifer0

**Comment by chucktheripper** [comment]
fixed with #530
