### ISSUE TITLE
restore dignity

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#532]
restore dignity when killing a monster

**Comment by 0Lucifer0** [comment]
just if it a +1->+5 lvl monster

**Comment by Ciapa1** [comment]
Nope
only when monster between lvl-5 and lvl+5

**Comment by 0Lucifer0** [comment]
Ok ;)

**Comment by aerzy** [comment]
when lvl -20 don't lose dignity

**Comment by 0Lucifer0** [comment]
aerzy this part is already done we just need a way to restore it

**Comment by unknownforces** [comment]
@Uppermost It didn't fix it xd

**Comment by Uppermost** [comment]
Is not finish yet

**Comment by MasterDomino** [comment]
dignity changed to float you can continue your work

**Comment by 0Lucifer0** [comment]
Thanks ;)

**Comment by 0Lucifer0** [comment]
Because Its only lvl over you and 1time each 2 monster

**Comment by unknownforces** [comment]
Ah I see, my bad.
