### ISSUE TITLE
Parse problem!

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#534]
![parser1](https://cloud.githubusercontent.com/assets/17483888/15046541/9139b162-12e0-11e6-88a3-a79532adc382.PNG)

Like that it should look like, but if i parse the same Packet.txt twice it shows (0 Recipes parsed)
but ingame it looks like that

![parser2](https://cloud.githubusercontent.com/assets/17483888/15046573/c054c428-12e0-11e6-8872-1d73e7dca65d.PNG)

**Comment by aerzy** [comment]
u have fail u packet.txt for me work

**Comment by The-Art-Of-War** [comment]
how the hell can i fail the packet.txt :D? it cant be me i think because if i parse it for the first time its all okay, only if i parse recipes twice that problem appears to be honest its not realy a problem because the value to produce is the same for example: i dont need to have twice as much items (like shown) to produce the health potion

**Comment by aerzy** [comment]
made a second packet.txt with only the recipe for see

**Comment by 0Lucifer0** [comment]
I think There is a problem in the parser that parse twice this part Will see
