### ISSUE TITLE
Sell Bugs 

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#537]
n_inv in exchange:
[Video](http://sendvid.com/39msokzu)
(on official you can do this well, but you can't sell items)

another problem is, that you can send any send/recieve packet like shopping, n_run, n_inv, wopen... and when you on exchange and send one of this packets then the trading window will be closed and you can walk for example to an npc and sell the item which you have register on exchange after that the trading partner must only click on 'trade', the exchange is complete and he got the items which you have been sold. 
example for it: [https://gyazo.com/b3ce2abf9e2d3c92f5366d580dd85472](https://gyazo.com/b3ce2abf9e2d3c92f5366d580dd85472) on official server the trading window will closed too, but when you walk to an npc you can't sell your items.

**Comment by SoraPlays** [comment]
I think the bugs are already fixed, but you can also register your maximum gold and buy out of an npc shop the trading partner gets the gold what you have registered

**Comment by chucktheripper** [comment]
Thats pretty weird
