### ISSUE TITLE
Too many Connections

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#540]
![unbenannt](https://cloud.githubusercontent.com/assets/17483888/15056569/80322980-1312-11e6-813f-4ee16ee001ff.PNG)

I dont know why this keep happening but it slow down everthing..

**Comment by chucktheripper** [comment]
When does this happening?

**Comment by The-Art-Of-War** [comment]
It sometimes happens if i disconnect :D

**Comment by chucktheripper** [comment]
i couldnt reproduce it, can you offer any informations what you did before or while disconnecting when this happened?

**Comment by The-Art-Of-War** [comment]
I will look after it :)

**Comment by The-Art-Of-War** [comment]
It is realy weird... i cant tell when it exactly happens, sometimes it appears if i connect but sometimes also if i disconnect..

**Comment by The-Art-Of-War** [comment]
Now i know why the problem appears, not exactly why! but i created my own patcher and linked it to a patch server who downloads datas to stay up to date. I've done this because some friends become tired of downloading the latest datas that i changed also to get easy the my launcher :D... Now like i said i linked it with the ports of the emulator or "server" to see Whether the Login or World-server is on or off to informate people. But if i start the patcher it checks the status of the server and i think the server tries to build a connection and thinks its a client who want to connect.. realy weird...

**Comment by The-Art-Of-War** [comment]
Here: [https://gyazo.com/52b1bda21f0fb0bbdccb051917968705](url)

**Comment by chucktheripper** [comment]
this would have been a nice information

**Comment by The-Art-Of-War** [comment]
Yeah :D i didnt know before why that problem appears

**Comment by MasterDomino** [comment]
its not a problem its just a warning

**Comment by The-Art-Of-War** [comment]
Okay :D but why is everthing sooo slow if this happens? without it all is fine

**Comment by MasterDomino** [comment]
your imagination.... no youre opening sockets and alot of them too many disconnections and connections at the same time same like spamming packet to login its not a thread so everything waits until rest messages finish

**Comment by The-Art-Of-War** [comment]
No way that this is my imagination :'D...
