### ISSUE TITLE
implement act dependant drop

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#541]
Implement the general monster drops, like seed, SP-Loader (if this item still exist), feather, and so on

**Comment by 0Lucifer0** [comment]
This is not already done ? In drops?

**Comment by chucktheripper** [comment]
I dont think so, i never had a seed drop and killed alot of monsters ;)

**Comment by 0Lucifer0** [comment]
Its only on act3 monsters

**Comment by chucktheripper** [comment]
I always farmed seed on danders, did they change it?

**Comment by 0Lucifer0** [comment]
yes danders is act1 so no feather ^^

**Comment by chucktheripper** [comment]
But seeeed ;)

**Comment by 0Lucifer0** [comment]
Yep all drops dépends on Monster There is no global drops i think

**Comment by chucktheripper** [comment]
But there is no drop for seed in dander dude

**Comment by 0Lucifer0** [comment]
Ah power seed ;) It seems There is a lvl drop and a Monster drop

**Comment by chucktheripper** [comment]
yes ;)

**Comment by chucktheripper** [comment]
blocked as the algorithm needs to be specified #567

**Comment by MasterDomino** [comment]
also make sure to add data parsing for it
