### ISSUE TITLE
full hp => 1k hp

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#543]
When a mob hits me sometimes I spend all my hp hp 1 K

**Comment by 0Lucifer0** [comment]
any screen or something ?

**Comment by aerzy** [comment]
how? because it's going direct full hp => 1k

**Comment by 0Lucifer0** [comment]
Idk We need to Know How to get that error

**Comment by aerzy** [comment]
0 error in emulator

**Comment by 0Lucifer0** [comment]
I mean We need to Know How to reproduce this bug

**Comment by MasterDomino** [comment]
it will be most efficient if you tell us all steps you took to create it

**Comment by aerzy** [comment]
This product, when many people hit

**Comment by 0Lucifer0** [comment]
Is the Life of someone is 1k ? I think you get the Life of an other one right ?

**Comment by aerzy** [comment]
the life of the first hit mobs go to 1k when many people hit the same monster

**Comment by 0Lucifer0** [comment]
The Life of who ? I dont understand exactly try to take a gyazo from It

**Comment by aerzy** [comment]
https://gyazo.com/daaaa911e0b28070af82baf5c483975d

**Comment by 0Lucifer0** [comment]
Ok i think you get the Life of the man near you Will look why
