### ISSUE TITLE
trade not tradable items

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#546]
- You can trade not tradable items
[Video](http://sendvid.com/qvjd7qec) for example: 'exc_list 0 0 5 1' position 5 = wild keeper sp 
- you can also sell not tradable items with a shop:
[Video](http://sendvid.com/60j4rrhl)

**Comment by SoraPlays** [comment]
@chucktheripper 

> you can also sell not tradable items with a shop:
[Video](http://sendvid.com/60j4rrhl)

Bug Nr. 2 still works

**Comment by chucktheripper** [comment]
check your IsSoldable flag on your item in the DB

**Comment by chucktheripper** [comment]
ah i got what you mean LOL, gonna check it
