### ISSUE TITLE
bug pnj

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#549]
![malcom](https://cloud.githubusercontent.com/assets/16693364/15080606/5229ccca-13bf-11e6-9819-1b85a4953eb0.PNG)
when i have disconect reconect i don't see the shop of pnj and in the minimap too but possible 2 click to pnj for learn skill etc..

**Comment by 0Lucifer0** [comment]
Ive test disconnect reconnect and i see all shop... Are you sure the problem dont happen When something else ? We seriously need to Know the way to get the bug for fix It...

**Comment by aerzy** [comment]
when don't disconect a see this pnj

**Comment by 0Lucifer0** [comment]
Are you sure its not just your client cause There is only 1 Packet for shop and map shop

**Comment by aerzy** [comment]
but the server disconect me because i have use speed when i walk and when reconect don't see this pnj

**Comment by aerzy** [comment]
i have the last nostalex.dat

**Comment by 0Lucifer0** [comment]
So your bug is just an exception but We need more detail to do something... Bug without Way to get It is just useless ;)
