### ISSUE TITLE
chicken hit 3 player

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#552]
![bug](https://cloud.githubusercontent.com/assets/16693364/15091127/d9c25fba-143e-11e6-8690-65bc3bf9ee68.PNG)

if several people are around a chicken he hits every person

**Comment by 0Lucifer0** [comment]
Are you up to date cause ive fixed It like 10min ago

**Comment by aerzy** [comment]
yes u have fixed 1 bug but this is another bug

**Comment by 0Lucifer0** [comment]
Ok
