### ISSUE TITLE
Friend Request, Group invite, nearly everything is based on map, fix ClientLinkManager 

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#554]
Fix ClientLinkManager => split it into maps and find a way to broadcast to all or just the map

**Comment by chucktheripper** [comment]
this is a bug according to the ClientLinkManager wont be bound to the Server but to the Map, this will be done with review ClientLinkManager

**Comment by aerzy** [comment]
not only say we receive all on all map

**Comment by chucktheripper** [comment]
This is a known issue.

**Comment by chucktheripper** [comment]
All interactions with other Sessions are only possible on the same map. The functions like Inviting or Private chat also. Shouting should still work worldwide. Ill fix this asap.

**Comment by chucktheripper** [comment]
Cleanup of RX is necessary, testing and Groupwide broadcast needs to be tested

**Comment by chucktheripper** [comment]
fixed
