### ISSUE TITLE
find a way to parse IsAOE for basic skill (turtle)

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#556]
find a way to parse IsAOE for basic skill (turtle)

**Comment by L3niaK** [comment]
Look in skill.dat, if the first value of "TYPE" is 4 then it is a mobs skill. Now look on "TARGET", if the first two value are 1 1 or 0 3 then it is a aoe skill. (the third and forth value are the "range" and the "aoe range")

**Comment by 0Lucifer0** [comment]
I talk about basic skill not skill so It cant be in skill.dat

**Comment by L3niaK** [comment]
mmh... but if you search in monster.dat, the mountain turtle skill is 418 and than you have to search this value in skill.dat beacuse only here you can see if this skill are an aoe or not, i guess.

**Comment by 0Lucifer0** [comment]
No its not i mean There is 2 thing skill and zskill tortle zskill is aoe so We need to find How to Know It

**Comment by 0Lucifer0** [comment]
No need to parse isAoe as a bool just find a way to calculate if aoe

**Comment by MasterDomino** [comment]
but as issue its proper gramatically and everyone what you mean
