### ISSUE TITLE
Mixed languages

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#557]
![unbenannt](https://cloud.githubusercontent.com/assets/17483888/15092399/f362c5c0-1468-11e6-91b7-71daa3177bf4.PNG)
As you can see German and Egnlish is mixed, i debugged it in DE.

**Comment by aerzy** [comment]
https://github.com/OpenNos/OpenNos/commit/669ac0aefbd32f91b488c80238a51e628fbd4d2b

**Comment by The-Art-Of-War** [comment]
Oh okay im sorry :D

**Comment by MasterDomino** [comment]
i put line that changes all messages and errors to english its not an issue its better for efficiency and bugfixing
