### ISSUE TITLE
Quicklist bug

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#564]
![unbenannt](https://cloud.githubusercontent.com/assets/17483888/15094240/5c85d6b6-149e-11e6-9856-60c2c29ec3a2.PNG)

Sometimes if i login or create a new char the rest skill is in my quicklist.. i didnt even set it there :D

**Comment by aerzy** [comment]
when you create a new character it does on the official also

**Comment by The-Art-Of-War** [comment]
For real ?

**Comment by The-Art-Of-War** [comment]
no way dude xD i played it since 2010 and didnt even realized it...
