### ISSUE TITLE
parse general and act dependant drop data

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#567]
The rate of drop some items like power seed

**Comment by MasterDomino** [comment]
anyone who knows exact drop rates from global and all general drop could help me
- thats why "help wanted" :)

**Comment by unknownforces** [comment]
So does this mean we have to parse this or..? 

Also how do you find exact drop rates? I thought this was something only entwell would know

**Comment by MasterDomino** [comment]
This means i need to hardcode some data into parser to automatically parse it to db.
yeah we need to decide about dropchance by ourselves or maybe theres someone who knows it xD

**Comment by MasterDomino** [comment]
for now parsing is done left for future purposes to add act dependant drops

**Comment by unknownforces** [comment]
@MasterDomino Is this only for danders and such or all?

**Comment by 0Lucifer0** [comment]
No Its for all

**Comment by unknownforces** [comment]
I mobbed pigeons like 10 times and not 1 woa dropped
It's higher rate on official.. xd

**Comment by MasterDomino** [comment]
woa isnt general drop its act dependant we work on implementing that its also a lot of items soo idk how much i will need to hardcode :P

**Comment by 0Lucifer0** [comment]
Whats woa if Its feather It Will be a mapgroup drop

**Comment by unknownforces** [comment]
Woa = Wing of angel (stuff you need to upgrade SP)

**Comment by 0Lucifer0** [comment]
Yes ok ;) so Its mapgroup drop

**Comment by MasterDomino** [comment]
parsing of map groups added same with connection table, vehicles need 1 more group for Pink Unicorn which works only in Nosville and Port Avelus(we might just code that it will have speed boost on that 2 maps). **We need info about act dependant drops eg. WoA, Green Souls etc.** thanks for your participation in this issue it was a long road but thanks!

**Comment by Uppermost** [comment]
Ok guys i want information of drop you can drop by act, example like this

Act 1 : This this this
Act 2 : This this this this
Act 3 This this
etc...

with all item you can drop by act , thanks.

**Comment by unknownforces** [comment]
Including monster specific drops or no?

**Comment by 0Lucifer0** [comment]
Monster spécific is already done we talk about wings of angel and so one

**Comment by unknownforces** [comment]
http://nostale.wikiwiki.jp/?%A5%E2%A5%F3%A5%B9%A5%BF%A1%BC%2F%A5%C9%A5%ED%A5%C3%A5%D7%A1%CAACT3%A1%CB

This website has all the info

**Comment by MasterDomino** [comment]
how did you find that? thanks dude i think we have more info, we now need the rates which are not the easiest thing in the world because we need to +/- balance them :P

**Comment by 0Lucifer0** [comment]
Hum Google translate dont work on It xD

**Comment by MasterDomino** [comment]
it does go to your searching tab and theres this icon https://gyazo.com/1dacd0e7d11e9548ae68ac1a6b1bd551 click it and change primary language to japaniese and translate to french ;)

**Comment by unknownforces** [comment]
I asked on nostale forums if someone had a list of item drops and someone directed me to it lol

**Comment by MasterDomino** [comment]
gg, will create a google sheet of it soo we will have it translated properly and it will be more readable

**Comment by Uppermost** [comment]
Think i try to translate it i have find some usefull information

**Comment by unknownforces** [comment]
Let me know if there's something you have problem with translating, because I got a friend who's Japanese, she can translate for me xD
I read items and I didn't understand some, google translate badly translated I guess

**Comment by Uppermost** [comment]
It's ok guys i have find, the only problem is the next drop not depend act only for comete map have a drop different of nosville you can't drop an apple on the dander but you can in the comete map and is on the same act.

**Comment by 0Lucifer0** [comment]
Thats why we have mapgroup and not map act juste Create à group for each spécial group

**Comment by Uppermost** [comment]
Ok perfect the bord is almost finish

**Comment by Uppermost** [comment]
Ok now i want information of drop in act 1, act 6 and act 6.2.  And if you can test it and tell me if drop is good, thanks !

**Comment by unknownforces** [comment]
Why a lot of mobs drop items that they don't drop in official (example : SP recharge drops on like all mobs) ? this is bug or meant to be like that?

**Comment by MasterDomino** [comment]
no map dependant drop coded yet -,-

**Comment by Uppermost** [comment]
If there is problem with drop on map please tell him here

PS : We know the problem with sp point card on dander for example, only tell us if item are missing etc...
---------------------------------------------------------------------------------------------------------------------

**Comment by unknownforces** [comment]
Pii pods don't drop beans
