### ISSUE TITLE
quicklist bug

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#570]
![bug](https://cloud.githubusercontent.com/assets/16693364/15141723/beced732-16a1-11e6-8835-e942c44c560a.PNG)
when i puts SP

**Comment by 0Lucifer0** [comment]
sometime it happens i don't know why... will try to find

**Comment by aerzy** [comment]
![sp2](https://cloud.githubusercontent.com/assets/16693364/15144379/519574e2-16af-11e6-8292-e7ac7ffc3a65.PNG)
when I remove the sp
and my inventory
![sp3](https://cloud.githubusercontent.com/assets/16693364/15144414/90393ecc-16af-11e6-99a5-a3612955334c.PNG)

**Comment by 0Lucifer0** [comment]
Not only Its on each reload of quickllst so It can happen on reconnect change sp/class
