### ISSUE TITLE
No Damage

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#571]
https://gyazo.com/2417b61bedc9a7f42a248e99100c0ba3

Sometimes some skills dont do dmg but triggers the enemies around

**Comment by chucktheripper** [comment]
sometimes the GenerateDamage method returns 0 damage if the method is TargetHit and the type is for no special target (i guess its 3)

**Comment by Uppermost** [comment]
This problem appear very often with some different sp and same whitout sp.

**Comment by Uppermost** [comment]
#522 is the same issue I think, I need confirmation to close 522, and just a detail, Chicken SP never miss on official ;)

**Comment by Uppermost** [comment]
Ok 522 is the same issue
