### ISSUE TITLE
sp not transform

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#572]
https://gyazo.com/309447985cc3751a0cf291be262b4cd3

but only when i change class if i don't change class work

**Comment by 0Lucifer0** [comment]
Not only Its on each reload of quickllst so It can happen on reconnect change sp/class

**Comment by 0Lucifer0** [comment]
How to get this error ?

**Comment by aerzy** [comment]
when i don't changeclass i don't get this error only when i changeclass

**Comment by chucktheripper** [comment]
So changing class causes sp transform problem

**Comment by 0Lucifer0** [comment]
Change at what Time ? Explain exactly How to get the error cause class have nothing todo With sp transform

**Comment by aerzy** [comment]
I changed class with a sp archer with me I pressed G and after I put a mage SP

**Comment by chucktheripper** [comment]
So you changed your class from archer to magician while you we're transformed to an archery SP? Then you tried to put on a magician SP and it crashed?

**Comment by aerzy** [comment]
I equipped the sp but don't morph only equipped and change class

**Comment by chucktheripper** [comment]
Can you provide a step by step manual to reproduce this error?
