### ISSUE TITLE
Error on World Server | Translation Error .

### ISSUE THREAD

**Issue by KeepM8** [OpenNos/OpenNos#574]
![immagine](https://cloud.githubusercontent.com/assets/19212217/15180579/b7417f4c-1782-11e6-90a8-f1b69915f43a.png)
Error after my IT fix ?

https://gyazo.com/b5a206c088b7e0216ea5da3fb2fec20d
Error on World Server .

**Comment by aerzy** [comment]
for the language => https://github.com/OpenNos/OpenNos/commit/669ac0aefbd32f91b488c80238a51e628fbd4d2b
and for error characterskill i get too this eror

**Comment by KeepM8** [comment]
Look "Thread failed to start" After i press G for put SP

**Comment by aerzy** [comment]
is too https://github.com/OpenNos/OpenNos/issues/573 no ?

**Comment by KeepM8** [comment]
I think yes ...

**Comment by chucktheripper** [comment]
Italian client & English server config?

**Comment by KeepM8** [comment]
Yes , i've missed the commits of unify language sorry .

**Comment by chucktheripper** [comment]
The unification of language is only for errors
