### ISSUE TITLE
Multithreading cycle problem

### ISSUE THREAD

**Issue by CryForMe9** [OpenNos/OpenNos#575]
Everytime when a User Logged out, my CPU gets 20-30% Higher and Stays, When it Reaches 100% the World Server Cannot load Anymore.
2.93 Ghz (Quadcore)

**Comment by chucktheripper** [comment]
i already fixed a few bugs according to this problem

**Comment by CryForMe9** [comment]
The release comes later?

**Comment by aerzy** [comment]
https://github.com/OpenNos/OpenNos/commit/bbb18f8838ce075abbff9aa0eed550b874d9568d
https://github.com/OpenNos/OpenNos/commit/562421ff2470c38958d039661adb28d2489cb8f0
https://github.com/OpenNos/OpenNos/commit/1403d99ebdf5c70b3bcc4b1e9264fd7aa9c2dece

**Comment by CryForMe9** [comment]
Okay Ty.

**Comment by CryForMe9** [comment]
Okay, it isnt fixed.

**Comment by aerzy** [comment]
i have this problem too but they think is a problem with VPS

**Comment by The-Art-Of-War** [comment]
They said it where in my imagination :b... i got the same problem

**Comment by chucktheripper** [comment]
There is a bug when multiple players are connected. Actually it should work with a bad cpu also

**Comment by chucktheripper** [comment]
It should be fixed
