### ISSUE TITLE
Split Errorlanguage and Translationlanguage

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#576]
![image](https://cloud.githubusercontent.com/assets/15254478/15195782/a9be219e-17c9-11e6-9069-62bf44d68c3e.png)

Traduction fr is good in LocalizedResources.fr.resx but don't show in game

**Comment by aerzy** [comment]
yes https://github.com/OpenNos/OpenNos/commit/669ac0aefbd32f91b488c80238a51e628fbd4d2b

**Comment by chucktheripper** [comment]
Whats your .config language?

**Comment by aerzy** [comment]
since you made the https://github.com/OpenNos/OpenNos/commit/669ac0aefbd32f91b488c80238a51e628fbd4d2b all time is in english

**Comment by chucktheripper** [comment]
This should only be for the error messages, we will  find a way to make the multilinguality possible ;)

**Comment by chucktheripper** [comment]
The Translation-Language should not use the CurrentUI, it should use a preconfigured language from app.config. The ResourceManager should be initialized once and not on every GetMessageFromKey

**Comment by chucktheripper** [comment]
.NET Magic only allows us to use the current Language.
