### ISSUE TITLE
Chinese characters

### ISSUE THREAD

**Issue by KrisYiu** [OpenNos/OpenNos#577]
Hi all.. i'm Kris from HongKong.
i meet a problem when i change the words to Chinese in Mysql DB. eg. Char ID (Rename by mysql command), shop name, item name, monster name.

img: [http://postimg.org/image/l50cg0bsx/](http://postimg.org/image/l50cg0bsx/)

and i test the words not form mysql.
added the words at the last of the $Help. (Error sill here)
chat system in game. (Shown correctly)
img: [http://postimg.org/image/ihcqb5eip/](http://postimg.org/image/ihcqb5eip/)

May i know how to solve please?
:) thx a lot

**Comment by chucktheripper** [comment]
This could be an encoding problem as we send and receive ascii i guess, utf8 will fix it

**Comment by KrisYiu** [comment]
Thanks :)..
I should work in WorldEncryption or where..?

**Comment by chucktheripper** [comment]
No more in send & receive packet, encryption / decryption works

**Comment by 0Lucifer0** [comment]
The problem is that We need to send and receive byte but utf-8 use 2 byte so We need to change decryption encryption and send/receive

**Comment by chucktheripper** [comment]
Do we really need to change the Encryption/Decryption?

**Comment by 0Lucifer0** [comment]
Just modify a little bit i think

**Comment by KrisYiu** [comment]
big5 is ACSII? 
i do it already w/ big5 codepage.

**Comment by KrisYiu** [comment]
img: [http://postimg.org/image/jvfvb5cg1/](http://postimg.org/image/jvfvb5cg1/)

**Comment by chucktheripper** [comment]
So did you fix it?

**Comment by KrisYiu** [comment]
yup. but i duuno how to set it be multi-lang.

may i know ur id in elitepvpers.

**Comment by chucktheripper** [comment]
its the same as here

**Comment by KrisYiu** [comment]
plx check PM.
i sent it to chucktheripper & 0Lucifer0

**Comment by MasterDomino** [comment]
seems like it came back

**Comment by earthnash** [comment]
i send packet from client-->  say ทดสอบ
but server receive my packet-->  say ?????
if i had server send packet--> say ทดสอบ
client receive--> say ทดสอบ
my language is Thai 
sorry i don't know how to explain
again sorry for my bad English :(

**Comment by 0Lucifer0** [comment]
so encryption works and decryption don't ?

**Comment by 0Lucifer0** [comment]
should be fixed reopen if not

**Comment by 0Lucifer0** [comment]
Already in other issue
