### ISSUE TITLE
packet receiving problem delimiter

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#58]
sometimes the decryption crashes because the byte[] to decrypt starts with a 255 which seems not to be valid for the decryption.

**Comment by chucktheripper** [comment]
<img width="622" alt="index_outofrange" src="https://cloud.githubusercontent.com/assets/15075386/11101671/85a5df7c-88b8-11e5-91dd-515639a674f4.PNG">

**Comment by 0Lucifer0** [comment]
i think i found a way to fix it (need more time to test)

**Comment by 0Lucifer0** [comment]
![capture d ecran 2015-11-27 09 45 38](https://cloud.githubusercontent.com/assets/15112753/11437647/ad91e13c-94ef-11e5-85b5-626d7a7a16d3.png)
![capture d ecran 2015-11-27 09 46 56](https://cloud.githubusercontent.com/assets/15112753/11437648/adb221b8-94ef-11e5-95a3-3814710a49eb.png)
problem is in reception not in decryption

**Comment by chucktheripper** [comment]
Bug must be in WireProtocol / Factory, find a way to remove the delimiter

**Comment by 0Lucifer0** [comment]
if we put a little sleep just after the decrytion function call there is no more problem... so i think it's an thread protect error

**Comment by 0Lucifer0** [comment]
![capture d ecran 2015-12-08 23 54 49](https://cloud.githubusercontent.com/assets/15112753/11671257/437964d4-9e07-11e5-9a82-3a80bacf4aaa.png)

**Comment by 0Lucifer0** [comment]
it's seem's that we don't get all the packet sended by the client (sometime it miss information)
![ffc2b9ea23a26f607d2186269e3565b3](https://cloud.githubusercontent.com/assets/15112753/11671325/cfb82ba6-9e07-11e5-90bc-3a411313345f.gif)

**Comment by 0Lucifer0** [comment]
after many research it seem's that if there is an 0xFF bit in the message the message is splitted... so we need to find a way to avoid this split
![i76 cimgpsh_orig](https://cloud.githubusercontent.com/assets/15112753/11729183/37c440b8-9f8e-11e5-99dc-5e0d11dbe270.png)

**Comment by 0Lucifer0** [comment]
deleted framing from network manager
