### ISSUE TITLE
attack range is too far

### ISSUE THREAD

**Issue by SoraPlays** [OpenNos/OpenNos#589]
Attack range is too far
https://gyazo.com/c5b02ee8ae1481df409bd4a8fd020b1f

**Comment by KrisYiu** [comment]
No problem for me.
DB config error, plx check the setting of table `Skill`

**Comment by chucktheripper** [comment]
I guess there needs to be a check on TargetHit, if the Mob is in range ?!

**Comment by SoraPlays** [comment]
> No problem for me.
 DB config error, plx check the setting of table  Skill 

tested with the skill 'Snake Rush' from wild keeper, normal attack works ;-)

**Comment by KrisYiu** [comment]
i tested the same skill...............but I cant attack so far lol

**Comment by SoraPlays** [comment]
> i tested the same skill...............but I cant attack so far lol

use packetlogger

what is happened with @0Lucifer0 ? :p

**Comment by 0Lucifer0** [comment]
Im just busy With exam ;) the range is Check With database range...

**Comment by 0Lucifer0** [comment]
i don't have this issue
