### ISSUE TITLE
delay beetween connection and canal show

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#59]
there is a lag beetween connection and canal show

**Comment by chucktheripper** [comment]
only once or everytime a client connects?

**Comment by 0Lucifer0** [comment]
only once

**Comment by chucktheripper** [comment]
its the db, ill add a call to db like count of accounts, its a bit shitty..

**Comment by 0Lucifer0** [comment]
this seem's to be a good help to fix it : http://www.dotnet-tricks.com/Tutorial/entityframework/J8bO140912-Tips-to-improve-Entity-Framework-Performance.html
