### ISSUE TITLE
character waits for su

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#595]
Sometimes it happens that the character is waiting for to be allowed to move again.

**Comment by 0Lucifer0** [comment]
when? in what condition? battle?

**Comment by chucktheripper** [comment]
sometimes it happens that the character cant move anymore

**Comment by chucktheripper** [comment]
Wasnt it cond? The packet which the attacking character is waiting for

**Comment by 0Lucifer0** [comment]
No in battle mode the character Wait for su... In official the Target system stay un break 1-2 seconds of the skill can not be launched

**Comment by chucktheripper** [comment]
My fault sorry, but the problem here is that anywhere the su isnt sent
