### ISSUE TITLE
Skill SP x28

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#598]
when up sp we win all skill sp x28
![20160515-1-test](https://cloud.githubusercontent.com/assets/16693364/15272632/778987e6-1a7f-11e6-9d24-09a76e151f0b.jpg)

but when u create sp it already has all skill but when kill one monster win skill sp x28
![20160515-3-test](https://cloud.githubusercontent.com/assets/16693364/15272649/372a1386-1a80-11e6-82dd-bc056171ab1f.jpg)

**Comment by KrisYiu** [comment]
i know.. that's my fault. 
i hv fixed it in the pull request #597. but not yet update only
