### ISSUE TITLE
Monster attack too fast

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#599]
https://i.gyazo.com/b1789645b83b938b2fa503874916d3d6.gif

**Comment by KrisYiu** [comment]
Monster No.?

**Comment by aerzy** [comment]
?

**Comment by KrisYiu** [comment]
which monster attck u too fast?

**Comment by aerzy** [comment]
283

**Comment by KrisYiu** [comment]
if u still feel too fast, 
set NpcMonster - BasicCooldown
