### ISSUE TITLE
invit grp don't work all time

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#604]
invit grp don't work all time

**Comment by chucktheripper** [comment]
When doesnt it work? Where is the receiver of the invitation? Has anyone been in a Group before? What error does it tell?

**Comment by aerzy** [comment]
the receiver receive the invitation but when accept groupe not create

**Comment by chucktheripper** [comment]
ah okay

**Comment by chucktheripper** [comment]
if you can provide more informations what state both the characters have when this error happens that would be fine

**Comment by chucktheripper** [comment]
http://pastebin.com/BcnkMXs6

**Comment by chucktheripper** [comment]
http://pastebin.com/zY1vWhhN

Log seems to contain useful information

**Comment by Uppermost** [comment]
We can maybe close it because never appear again?

**Comment by Uppermost** [comment]
I think is solved with the review group system by MasterDomino I close it because it does it again
