### ISSUE TITLE
Inventory duplicate entry

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#605]
Anywhere in the Inventory-system is a leak which allowes the server to set two items on the same slot. The DB will thro an error on this

http://pastebin.com/a8nM51C8

**Comment by aerzy** [comment]
http://pastebin.com/iCG7gWqD

**Comment by chucktheripper** [comment]
We need to make a save check if the slot is already used.

**Comment by 0Lucifer0** [comment]
As far as i remember we use à insert or update méthod for this

**Comment by chucktheripper** [comment]
I mean in the InventoryList before, here should be the check

**Comment by chucktheripper** [comment]
i guess this is fixed with the latest synchronizable changes
