### ISSUE TITLE
server instability caused by Inventory

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#608]
https://gyazo.com/c44e72a321c50c4f6906e4531b2d61ee

I do not see anything move
player / monster / pnj

but not crash it's possible smiley but when kill monster go to 0 hp :
https://gyazo.com/aaddc8d7882f94a504522bf424ea6f27

http://pastebin.com/4e45SEtk

**Comment by chucktheripper** [comment]
This happens according to #605 which drives the server to an inconsistant state.

**Comment by chucktheripper** [comment]
The problem could be caused by upgrading SP

**Comment by chucktheripper** [comment]
===============================================================================
WORLD SERVER VERSION 1.0.3.0 - PORT : 1337 by OpenNos Team
===============================================================================
[ERROR] 14:21:07 -- Handler Error
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at OpenNos.GameObject.SpecialistInstance.UpgradeSp(ClientSession Session, Upg
radeProtection protect) in C:\Users\Administrateur\Documents\GitHub\OpenNos\Open
Nos.GameObject\Item\Instance\SpecialistInstance.cs:line 300
at OpenNos.Handler.InventoryPacketHandler.UpgradeCommand(String packet) in C:
\Users\Administrateur\Documents\GitHub\OpenNos\OpenNos.Handler\InventoryPacketHa
ndler.cs:line 1002
at lambda_method(Closure , Object , String )
at OpenNos.GameObject.ClientSession.TriggerHandler(String packetHeader, Strin
g packet, Boolean force) in C:\Users\Administrateur\Documents\GitHub\OpenNos\Ope
nNos.GameObject\Networking\ClientSession.cs:line 417
