### ISSUE TITLE
upgrade ( +100 ) not (+15)

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#610]
![20160517-1-kevin](https://cloud.githubusercontent.com/assets/16693364/15319709/986b27c2-1c2c-11e6-9fcc-b2d905989423.jpg)
when u win upgrade if you don't disconect reconect not possible re upgrade

**Comment by 0Lucifer0** [comment]
can you give me the correct packet on official for this ? :D

**Comment by unknownforces** [comment]
If you click another tab and then go back to perfecting it lets you continue, it's annoying but it works.

**Comment by Uppermost** [comment]
Problem fix
