### ISSUE TITLE
dissapearing skills from norm

### ISSUE THREAD

**Issue by CryForMe9** [OpenNos/OpenNos#613]
Skills for Norm Mage, Archer and Swordi dissaperd after relogg

**Comment by chucktheripper** [comment]
How did you change class? Please provide a few more informations

**Comment by CryForMe9** [comment]
Normaly with Lvl 15 and Job 20 with the NPC, after a little time then after a relogg are the skill away. I fixed it on my Server with Command ChangeClass.

**Comment by KrisYiu** [comment]
do u mean the basic skill?

**Comment by 0Lucifer0** [comment]
@KrisYiu is it already done? if yes close the issue ;D

**Comment by Uppermost** [comment]
It's ok i have test 
#613
