### ISSUE TITLE
Perfecting Sps

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#614]
When perfecting sps, past +50 it still gives you +1 to each stat instead of +2, +3, +4 etc.

**Comment by Martazza** [comment]
1 - 60  gives +1 
Past +60(61-80) gives +2 
Past +80(81-99) gives +3 ~ +5

**Comment by unknownforces** [comment]
Well i'm up to perf 72 and it's still +1

**Comment by MasterDomino** [comment]
does this still occur?

**Comment by unknownforces** [comment]
Yes, I made an issue about this again
