### ISSUE TITLE
Group

### ISSUE THREAD

**Issue by Kubixiorek** [OpenNos/OpenNos#615]
If you'll create a group, right after friend join the group - you're stuck. You cannot do nothing until reconnect.

**Comment by Kubixiorek** [comment]
NOTICE: By 'nothing' i mean a leader can't attack monsters. If he try, he will be stuck. Other members still can kill them. & I don't know if this is a bug but there's still no EXP sharing

**Comment by MasterDomino** [comment]
this but is quite often its as Kubixiorek says youre stuck and cant move when you try to attack after adding monsters.
[![https://gyazo.com/b2c8614e0364d25fbff0a05dd317066e](https://i.gyazo.com/b2c8614e0364d25fbff0a05dd317066e.gif)](https://gyazo.com/b2c8614e0364d25fbff0a05dd317066e)

**Comment by DarkCacos** [comment]
Hello, guys. This bug also happens if you double click on the character of another member of the group. After, you can only sit with C, but you can't move.

From the Debug Log:
`2016-05-28 12:54:57,987 [29] DEBUG OpenNos.World.Program [(null)] - Session: 6 Method: UseSkill Packet: 15751 u_s 0 1 3`

**Comment by 0Lucifer0** [comment]
yes normal we need to cancel the u_s if we try to skill a user cause it's not already done and it wait for a su.

**Comment by 0Lucifer0** [comment]
same as #595
