### ISSUE TITLE
Phenomenal stats

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#621]
Currenly r8 is only giving r0 base stats, instead of the bonus +300 or whatever it is for rare differences.

**Comment by Kyoraku** [comment]
how much it's higher than r7 in state ? :)

**Comment by unknownforces** [comment]
With hellord sword, it is 156. 
idk about the rest.

**Comment by unknownforces** [comment]
Okay actually nvm, I don't know the differences. Since the current r7 stats on phenomenal gear is incorrect.
