### ISSUE TITLE
Wrong map regions for monsters?

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#622]
Monsters can walk through every wall

**Comment by 0Lucifer0** [comment]
Are you sure you have correct zone files because i dont have this problem

**Comment by The-Art-Of-War** [comment]
i extracted them out of the .Nos i think i have the correct ones

**Comment by 0Lucifer0** [comment]
Yes could you send me a screen plz

**Comment by The-Art-Of-War** [comment]
Its solved, you was right... i tried older zones it all work now i think there was only a problem while extracting or my client was corrupted i dont really know.. but thank you for your advice
