### ISSUE TITLE
Problem with nostale updating dont update all nostale

### ISSUE THREAD

**Issue by NosReturn** [OpenNos/OpenNos#623]
Last night i updated all in nostale and this happen:   <a href="http://es.tinypic.com?ref=2upqtm1" target="_blank"><img src="http://i64.tinypic.com/2upqtm1.jpg" border="0" alt="Image and video hosting by TinyPic"></a>
So dont update nostale all if not working try to update nostale just 70% 80% or something like that
if you update nostale 100% this is what happen

**Comment by The-Art-Of-War** [comment]
I have the same problem like u said it appears after updating Nostale.. Client-Build = 0.9.3.3059

**Comment by The-Art-Of-War** [comment]
Btw the ERROR appears if u try to login... Something wrong with the password decryption?

**Comment by SoraPlays** [comment]
they have changed the pw crypt

**Comment by The-Art-Of-War** [comment]
I thought something like that ^^

**Comment by 0Lucifer0** [comment]
issue fixed! password is now sha512 and there is no more decryption only hash
