### ISSUE TITLE
Login problem 

### ISSUE THREAD

**Issue by woowpoof** [OpenNos/OpenNos#627]
Hi guys when i try login i have that message from login.exe, i can resolve this problem? 

![immagine](https://cloud.githubusercontent.com/assets/20017463/16173067/1adce1dc-3596-11e6-803e-b4de6459c330.png)
![immagine2](https://cloud.githubusercontent.com/assets/20017463/16173068/1ae05984-3596-11e6-85a0-b05ac39bd1e9.png)
![immagine3](https://cloud.githubusercontent.com/assets/20017463/16173069/1ae366f6-3596-11e6-8017-794881f3bb70.png)
![immagine4](https://cloud.githubusercontent.com/assets/20017463/16173070/1ae70f4a-3596-11e6-82cb-654038463948.png)

**Comment by chucktheripper** [comment]
Password is Sha-512
