### ISSUE TITLE
Ammo problem

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#630]
The Ammo system dont work as Adventurer and if u dont wear or equip a secondary weapon it shows the message "NO_AMMO" but it should show something for example "NO_WEAPON_EQUIPED" as an "Global Message" (dunno how to say that..... a message that appears in front of you screen an is only available for you.)

Also if you dont equip a weapon as an archer it also should cancel the "attack event" and show a Global Message "NO_WEAPON_EQUIPED"

**Comment by 0Lucifer0** [comment]
Ok so Its a msg not a say i Will look at It :) thanks

**Comment by The-Art-Of-War** [comment]
Oh okay thanks i really dont know how to say that xD

**Comment by 0Lucifer0** [comment]
is it good now? perhaps the color of message is not good so don't hesitate to tell me

**Comment by The-Art-Of-War** [comment]
Yeah everything is good now :D good job
