### ISSUE TITLE
normal skills / ammo problem 

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#631]
When I press them it goes red arrow then back to yellow and my char just stands there.
and when I use targetted stab (archer normal skill) my char runs to the mob and uses bow norm hit??

**Comment by unknownforces** [comment]
also, piercing shot for example kills the mobs around the one I targetted but doesnt kill the one I target (it doesn't use animation either)

**Comment by unknownforces** [comment]
And also zerk skill sonic rush says no ammo, but it uses sword ??

**Comment by unknownforces** [comment]
Gladiator also saying it needs ammo to use all skills ?

**Comment by 0Lucifer0** [comment]
Ok so distance is not a good way to split skill need to find a other way

**Comment by unknownforces** [comment]
Also, idk what causes it but, when I try to use AOE skills, my char just stands there and it doesn't work.
I have to relog for it to work again.
