### ISSUE TITLE
Bug with effect on teleporter

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#632]
![20160616-2-sobad](https://cloud.githubusercontent.com/assets/15254478/16194502/254249a4-36f5-11e6-958c-69b997ed0d39.jpg)

(Server is up to date)
The bug occurs after a few seconds.

**Comment by MasterDomino** [comment]
this is propably caused because theres more than one npc or just effect bug in packet, someone need to add verification for effect parsing

**Comment by 0Lucifer0** [comment]
Not parsing just delay i think this use an effect on each cycle

**Comment by Uppermost** [comment]
Same problem...

**Comment by Uppermost** [comment]
fix now is the same of the official NosTale
