### ISSUE TITLE
[World] Upgrade ammunition system

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#634]
![upgrade](https://cloud.githubusercontent.com/assets/15254478/16194898/5ef2f5ac-36f7-11e6-9e45-13d57746c870.png)

Ammunition is always / 100
Quantity Remaining / 100

And not as 0 on Opennos

**Comment by 0Lucifer0** [comment]
It set to 0 in your database and There is always an issue about make 100 in parser
