### ISSUE TITLE
change $Mute and $Ban to add timed information and reason

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#635]

**Comment by Uppermost** [comment]
When you get a sanction, this packet appear (official like) 

Packet : info You have been sanctioned TIME minutes.

**Comment by Uppermost** [comment]
Ok, want to block talk and attack now. Good job

**Comment by 0Lucifer0** [comment]
will change this and ban asap

**Comment by Uppermost** [comment]
Problem, when you use $Mute PLAYERID, you receive the avertissing message << I suffered a sanction >>

Only the punish player get this the packet.

**Comment by MasterDomino** [comment]
done \o/
