### ISSUE TITLE
Review skill system

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#639]
https://gyazo.com/a279091a905d10ce1169321a993e8b4e
https://gyazo.com/7122f47bcc3443f9d3d302064d291a19

In 1st video, whenever  I use this skill, it doesn't do any dmg and just aggros the group of mobs, but it is a single target skill.

In 2nd video, I didn't use mighty hurricane, yet it still used effect when I used seven stabs (it also didnt go on CD) 

Seems theres an issue with a lot of skills using 2 skills during 1 attack (or using 2 effects)
For example ; Sader uses debuff skill (holy breath) when you use other skills

**Comment by unknownforces** [comment]
AOE skills don't work for this sp either now (as of latest commit)

**Comment by unknownforces** [comment]
There is an issue with effects facing the wrong way too (Like in DG for example)

**Comment by Uppermost** [comment]
Skill problem (two skill in the same time) same problem

**Comment by unknownforces** [comment]
DG doesnt use Gun, or atleast it never misses. Cause I was using it earlier and killed like 30 mobs and no misses.

**Comment by Uppermost** [comment]
Other problem, sometime, the skill is loaded and I can't use it, for example sp4 archer, all skill can be used bug after one use, I can't use again the s20

**Comment by Uppermost** [comment]
new issue for that
