### ISSUE TITLE
Problem with skill refresh

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#641]
![image](https://cloud.githubusercontent.com/assets/15254478/16266495/7e01c01a-3885-11e6-88b6-060c508c0009.png)

The skills do not completely rafraichissent
(Test without SP)

**Comment by 0Lucifer0** [comment]
i don't have this problem... https://gyazo.com/9ca6af9c02e9bbe2f99b77d11d8d72e6 i think it was fixed by an other issue
