### ISSUE TITLE
Price change

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#643]
![image](https://cloud.githubusercontent.com/assets/15254478/16266788/dd0195b2-3886-11e6-90bb-badb5c88792b.png

On this screen we can see that the price is 100, it should be 150

150 shows that the price compared to NosVille for example, is 50% High.

We need a way to determine the cards that prices are rising, and thus be able to modify the displayed price

**Comment by 0Lucifer0** [comment]
This system Will be made With act4 :)
