### ISSUE TITLE
Problem revive HP

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#646]
![image](https://cloud.githubusercontent.com/assets/15254478/16287311/81f54022-38e2-11e6-9855-8a8cdcbdae24.png)
When I review my hp does not update well and remain at 0 awhile

**Comment by unknownforces** [comment]
It happens to me too, but then it goes back to half, it's just delayed.

**Comment by 0Lucifer0** [comment]
Yes i Seen that.yesterday Will look at It

**Comment by Sl4yZ** [comment]
Uppermost, I know how to fix this, can you add me on skype ?
