### ISSUE TITLE
Add attack of monster for morph command

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#648]
When you use morph command, you can't attack monster. We need to add they attack of they monsters when you morph.

**Comment by Uppermost** [comment]
The Morph id can be easily compare with the .dat file

example, in the dat file. Caligor have the id 2305 and 3305 when i use morph command.

If we add 1000 we obtain the value of all the monsters example of 1001-3558 now with morph control, and 1-2558 in dat files

**Comment by Uppermost** [comment]
On official when Game Master uses morph command, they have monster skill. how can you find a way to add it ?

**Comment by Uppermost** [comment]
@0Lucifer0  what exactly we need to do?

**Comment by 0Lucifer0** [comment]
after verification it seem's it's not possible attack of monsters don't have any icon

**Comment by Uppermost** [comment]
We can maybe just use random to skill and not icon like true monster no?

**Comment by Uppermost** [comment]
We can do like the official and morph to add skills etc? should be very cool :( On official GM use packet in 2 to be a monster and they use random skills like monster

**Comment by Ciapa** [comment]
Well, it looks like our whole $Morph command is somehow broken... Sometimes it morphes correctly, sometime you can't move afterwards. Since It's no required feature, instead more like a fun tool, it has no priority to be fixed directly for any milestone.
