### ISSUE TITLE
Fix Character Selection Screen

### ISSUE THREAD

**Issue by Ciapa1** [OpenNos/OpenNos#65]
The Charakter Selection Screen is a little bit buggy, depending on how many Chars you have. If you only have one character in the middle(slot 1), it does result in a blackscreen(IIRC, games_start is not sent. If you have multiple chars, the you get logged in as a different character depending on your Selection. Currenty looking at the code dedicated to char loading and see what's wrong.

**Comment by chucktheripper** [comment]
Check if character exists for selected slot & index values, fix the problem described above

**Comment by 0Lucifer0** [comment]
think you don't get the last version because there is no problem with just 1 character in the middle

**Comment by chucktheripper** [comment]
#58 could make problems here, it seems to create  inconsistent data

**Comment by Ciapa1** [comment]
Could be, just wrote the issue today while in train after finding the issue yesterday. Probably still had an old commit. Test with the latest Version proves it's working as expected

**Comment by chucktheripper** [comment]
no problem, thanks for contributing

**Comment by Ciapa1** [comment]
You're welcome. Is there anything to help with? Implementing chat/gm commands or recent update features for example?

**Comment by chucktheripper** [comment]
contact me in skype: aleqs92

**Comment by Ciapa1** [comment]
done

**Comment by chucktheripper** [comment]
are u sure? i didnt receive a message, please provide your contact data
