### ISSUE TITLE
Add sp destroy system

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#650]
When you missed a tentivative, it may be that your sp "destroyed" it will appear grayed out. You can not equip unless using SP résuresction stone

Currently we miss when attempting the sp is never "destroyed".

When you equip a destroy sp you receive the packet : wear 29 0
msg 0 C'est maintenant impossible de l'utiliser, car l'âme a été détruite.

Destroy packet : ivn 0 29.4491.-2.3.0

**Comment by Uppermost** [comment]
Resurection packet :
eff 2 645377 3007
eff 2 645383 3007
umi 5060.627
pulse 660 0
eff 1 521919 4546
u_i 1 521919 1 42 0 1 0 17
msg 0 L'âme reprend vie.
guri 13 1 521919 1
sp 994745 1000000 10000 10000
ivn 1 42.-1.0.0
ivn 0 17.4491.0.3.0
eff 2 645377 3007
eff 2 645383 3007
eff 1 521919 4546
stat 13105 13105 18761 18761 0 32

**Comment by MasterDomino** [comment]
Also we should add item protection (scrolls) as for example on how to create functions for items

**Comment by 0Lucifer0** [comment]
Like all fonctional item

**Comment by MasterDomino** [comment]
no because we should add everything step by step soo like scrolls are needed to finish whole upgrade/destroy system, at least thats what i think... correct me if im wrong :)
