### ISSUE TITLE
code MapObject function

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#651]
It seems that some "mapobjects" got the shop function

https://gyazo.com/4728ba2e4075a4e4907eb4185541b185

https://gyazo.com/913185a2c0a654ec732118b776adf00c

**Comment by 0Lucifer0** [comment]
Are you sure you didnt put a fake dialog id ?cause this is not shop function but shop dialogu

**Comment by MisterBenju123** [comment]
I have create my packet.txt and i have the same problem

**Comment by Uppermost** [comment]
Same problem...

**Comment by 0Lucifer0** [comment]
we need to compare the in packet from official and opennos on one of these "mapitem"

**Comment by Uppermost** [comment]
Opennos  : in 2 858 2117 92 49 0 100 100 1 0 0 - 1 0 0 - 1 - 0 - 1 0 0 0 0 0 0 0 0
Official : in 2 858 2132 102 51 0 100 100 1 0 0 -1 1 0 -1 - 0 -1 0 0 0 0 0 0 0 0
--------------------------------------------------------------------------------------

http://pastebin.com/gzbcLq9g

**Comment by Uppermost** [comment]
ncif 2 2132
ncif 2 2132
ncif 2 2132
npc_req 2 2132
npc_req 2 2132
delay 5000 4 #guri^400^2132

guri 2
guri 5 1 521919 0 4
delay 5000 4 #guri^400^2132

guri 2
guri 5 1 521919 0 4
guri 2 1 521919

guri 2 1 521919

ncif 2 2132
guri 5 1 521919 20 4
ncif 2 2132
guri 5 1 521919 40 4
ncif 2 2132
guri 5 1 521919 60 4
ncif 2 2132
guri 5 1 521919 80 4
ncif 2 2132
guri 5 1 521919 100 4
#guri^400^2132
msg 0 La tentative a échoué !

ncif 2 2132
ncif 2 2132
ncif 2 2132
ncif 2 2132
ncif 2 2132

**Comment by MasterDomino** [comment]
does it also mean that we want to add function to mapobjects aka. farming on wells?

**Comment by 0Lucifer0** [comment]
Nope only avoid bad dialogu for the moment

**Comment by MasterDomino** [comment]
soo we will need to get NoDialog from monster.dat and parse that to data and add if to npc_req soo it wont show the dialog just return and leave that for future to add the farming

**Comment by MasterDomino** [comment]
finish delay first ;)

**Comment by 0Lucifer0** [comment]
This is only used by mission system Its useless without It.

**Comment by unknownforces** [comment]
This issue happens with Ice flower too

**Comment by 0Lucifer0** [comment]
Yes all npc in fact ^^ but i was thinking It was object in fact There is 2 kind of mapobject (item,npc)

**Comment by MasterDomino** [comment]
unknown forces yes we know please before adding issues comments etc. look into our discord ;)
