### ISSUE TITLE
Speed command

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#652]
Sometimes if i use the $Speed command i get kicked. (not everytime)

https://gyazo.com/569b6e9d371514a09723755eaf9f9618

**Comment by Uppermost** [comment]
Yes this problem is know, we need to find a way to fix it

**Comment by MasterDomino** [comment]
often caused by using 59 and clicking on npc then clicking space to target him

**Comment by Uppermost** [comment]
The solution could be to lower the rate (currently 59) and set a limit of 50?

**Comment by 0Lucifer0** [comment]
Nope Its the same With 50 or 40 or all others speed need to see why client send bad speed to server
