### ISSUE TITLE
fairy % not on reqinfo

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#655]
the fairy % is not on reqinfo

**Comment by Uppermost** [comment]
After test, no problem found

**Comment by 0Lucifer0** [comment]
If someone reqinfo on you It Will show 0%

**Comment by Uppermost** [comment]
I see 50% when i right click on me with another character

 Are you sure that there is a problem?

On official when you have not fairy "No Element(0%) " appear on the right click

**Comment by unknownforces** [comment]
He is right, try it a few times sometimes it says 50% some times it says 0%, it changes.

**Comment by Uppermost** [comment]
This bug appear randomly

**Comment by MasterDomino** [comment]
it can be done now

**Comment by Uppermost** [comment]
Do you have this bug recently?

**Comment by unknownforces** [comment]
I haven't had this bug in ages.

**Comment by Uppermost** [comment]
I count on you to tell me if the problem returns

**Comment by MasterDomino** [comment]
Martazza's tester told me it came back

**Comment by unknownforces** [comment]
I don't get this issue and I sat there spamming it o.o

**Comment by MasterDomino** [comment]
idk he told us something like this happen when you set fairy to high lvl
