### ISSUE TITLE
$ChangeClass Issue

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#656]
You can change class with wrong equip:

https://gyazo.com/fb726b1587d11076599de4f95e13bfa0

You can change also class with different sp types like "Wildkeeper" equipt as Magician, you can also transform as Magician --> WK

https://gyazo.com/d819e723add33082af0c12b1fb24178a

Solution can be add "unequip everything before $ChangeClass" like if you change your class as adventurer (lv15 jlvl 20) or reset the whole equip into the inv. after using $ChangeClass

**Comment by Uppermost** [comment]
I think it is voluntary, and it has no impact... Only GameMaster can do that so I do not think it is a real problem

**Comment by The-Art-Of-War** [comment]
U r rigth it isnt a real problem but i dont know it can be a enhancement

**Comment by Uppermost** [comment]
No after I could not do this anymore :( 
![image](https://cloud.githubusercontent.com/assets/15254478/16457206/e74625f8-3e1a-11e6-9745-d2ca2347abc1.png)

**Comment by 0Lucifer0** [comment]
This is volonteer Gm are lazy They dont want to unwear before transform
