### ISSUE TITLE
damage effect of upgraded skills

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#657]
- [x] add skill replacing you cant have 2 upgrades of the same type
- [x] add effects on upgraded skills
- [ ] add additional damage of upgraded skills

**Comment by MasterDomino** [comment]
also add skill replacing you cant have 2 upgrades of the same type

**Comment by Ciapa1** [comment]
Same as in #380, waiting for bcard rewrite/restructure.

**Comment by MasterDomino** [comment]
then this issue will be closed down and i will leave damage for you ;)
