### ISSUE TITLE
in each insert list of dao need to put a AutoDetectChangesEnabled = true; 

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#658]
We need to put back a context.Configuration.AutoDetectChangesEnabled = true;  after the foreach before saving context

**Comment by chucktheripper** [comment]
This configuration is Context wide, why should we put it in each call?

**Comment by 0Lucifer0** [comment]
Because in list insert we put It to false but never back to true xD

**Comment by chucktheripper** [comment]
Oh, to speed up insert?

**Comment by 0Lucifer0** [comment]
Yes for import console (this is not used in world server )
