### ISSUE TITLE
Act 6.1 EQ stats

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#668]
https://www.youtube.com/watch?v=1XRoU7YzDNI
As you can see at the end of this video 9:35, the difference between 95 bow and the new bow in stats, currently in game it is 612~784 with same bow and stats.

**Comment by 0Lucifer0** [comment]
Need to find the R8/R7 difference (additional point amount)

**Comment by 0Lucifer0** [comment]
seem's to be +30 on r8 than on r7

**Comment by 0Lucifer0** [comment]
already done in fact
