### ISSUE TITLE
skill thread allowing to use multiple potions

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#672]
https://youtu.be/cBKCXc5vVfE

**Comment by 0Lucifer0** [comment]
we need to add a delay for potion / ps it depends on MapType ^^ so we will need a PotionDelay on MapType

**Comment by MasterDomino** [comment]
PotionDelay added to MapType its (short) tell if you need to use different type

**Comment by unknownforces** [comment]
Isn't this fixed?

**Comment by MasterDomino** [comment]
nope its caused on skill usage and allows you to spam potions how much you want, havent you watched the video, check out on your system :P

**Comment by unknownforces** [comment]
I tested just now and it doesn't happen, it just takes my hp back to full when I get hit but doesnt allow spamming like this video

**Comment by MasterDomino** [comment]
ok seems like it got fixed but idk when it shouldnt be, now its different you can lock your character in place and when you die youre stuck in that death state

**Comment by unknownforces** [comment]
Okay so from what I tested, it seems that the client can't register spamming like with #728 
but the death state bug has nothing to do with either of these, because it happens without skills too.

**Comment by MasterDomino** [comment]
yeah you get freezed when using both of this methods, spamming potions or skills, also snacks soo something that has delay or task on it. and actually it has pretty much to do with them because its caused by these issues
