### ISSUE TITLE
Wrong password when deleting character

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#674]
I type test (thats the password) and it keeps saying wrong password, I can't delete my char lmao.

**Comment by 0Lucifer0** [comment]
Will fix this asap

**Comment by chucktheripper** [comment]
Has this to do with the sha512?

**Comment by 0Lucifer0** [comment]
yes exactly ^^ this caused by sha512 ^^ i forget to replace it at this place^^

**Comment by chucktheripper** [comment]
Please implement it on a central place so login and delete character use the same implementation ;)

**Comment by 0Lucifer0** [comment]
Nope I just Forget to delete one method >< It the same implémentation
