### ISSUE TITLE
Staying dead after pressing "Revive"

### ISSUE THREAD

**Issue by Sl4yZ** [OpenNos/OpenNos#675]
I've just created a character (level 1), then I started attacking a lvl 1 Dander, it killed me, I died, then the messagebox asked me if I wanted to revive, it's free for people below level 20, I pressed "Yes" and I was still dead, couldn't move, my HP and MANA were regenerating though
Screen : http://prntscr.com/bq58yv

**Comment by Sl4yZ** [comment]
It only happened 1 time though.

**Comment by 0Lucifer0** [comment]
seem's to be a delay problem (there is the same problem on official)

**Comment by 0Lucifer0** [comment]
try to press enter directly when there is the dead animation ^^ i think it's caused by client that can't receive revive on dead animation >< try it if it works we will add better delay for dead ^^

**Comment by Uppermost** [comment]
Same bug on official i think, i'm not sure

**Comment by unknownforces** [comment]
On official, you can't revive in Nosville, if you die, you teleport straight back to respawn point. In other maps revive works ok on official.

**Comment by MasterDomino** [comment]
my tests showed that its often caused by #739

**Comment by unknownforces** [comment]
@MasterDomino wrong, because this also happens when you have no skills. happens to me everytime I die from just using normal hits

**Comment by MasterDomino** [comment]
yep thought it was that but its like you say the regen starts in death state soo the revive cant progress and youre stuck
