### ISSUE TITLE
 disconnection / reconnection

### ISSUE THREAD

**Issue by aerzy** [OpenNos/OpenNos#676]
when u disconect reconnect many time

world
http://pastebin.com/RjuiPwjt
login
http://pastebin.com/Pd5HdpLG

**Comment by MasterDomino** [comment]
can you give us your hardware info: cpu,ram and does your pc tend to slow down?

**Comment by aerzy** [comment]
2x Intel® Xeon® E5‑2620
vCPU : 4 Coeurs 
12Go ram
is on VPS but no slow

**Comment by MasterDomino** [comment]
do you know how many accounts and also after how many connections does this occur?

**Comment by aerzy** [comment]
20 ~ 50

**Comment by 0Lucifer0** [comment]
nosreturn has the same problem

**Comment by aerzy** [comment]
but i think is when install IIS because when open with VS with my PC and player com don't have crash for this reason :/

**Comment by itemhack** [comment]
This happen too in my vps

**Comment by itemhack** [comment]
if someone need this happen too 
![untitled](https://cloud.githubusercontent.com/assets/8602131/17193380/0bd4c070-5453-11e6-8d13-5b5386cf709f.png)

**Comment by itemhack** [comment]
this happen too if someone need (it is a repost because i have censured some thing) 
![untitled](https://cloud.githubusercontent.com/assets/8602131/17194441/50418c3e-5458-11e6-8b9c-c98eaa032914.png)

**Comment by Uppermost** [comment]
Need to be fix asap

**Comment by Uppermost** [comment]
Now I think this problem is the first priority :)

**Comment by Uppermost** [comment]
What's up with that?

**Comment by chucktheripper** [comment]
I wanted to reproduce that but i was not fast enought ;), if i can reproduce, i can fix it

**Comment by Uppermost** [comment]
Sometime people can't be connect again because "You account is already use" it occur after big lag etc.

**Comment by Uppermost** [comment]
Can you add something like a delay to disconnect the account from the loginserver? because sometime people can't be connected anymore the loginserver think the player is again connected but it's false.

**Comment by 0Lucifer0** [comment]
that's occure only if you crash the world server
