### ISSUE TITLE
NuGet Update Issue

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#680]
Everytime i want to update the database because there are new commits, it shows me that all the tables already exists... i know its not a problem to simply delete all  but thats not how "updating things" should work :D 
My question is: can there be a simple check or ignore function, to solve this annoying issue?

https://gyazo.com/bb318dc7acdea90cd953f53a858a73c6

**Comment by MasterDomino** [comment]
Its not an issue, its caused by me adding new tables to db and then removing old migration and creating a new one, idk if we want to create migration every single time we change anything in db
