### ISSUE TITLE
bug when i change class 

### ISSUE THREAD

**Issue by itemhack** [OpenNos/OpenNos#681]
when i change class the equip don't recive the equipment for my class's chosen

is it a bug or an incomplete packet.txt ?

**Comment by aerzy** [comment]
is not in packet is in opennos

**Comment by itemhack** [comment]
so it is not implemented ?

**Comment by aerzy** [comment]
not yet

**Comment by Uppermost** [comment]
We have to do it

**Comment by Sl4yZ** [comment]
Half of the work is done, I need to find how to equip the items that are created now.

**Comment by 0Lucifer0** [comment]
Just Create in in the equipment

**Comment by itemhack** [comment]
i think if you resend the "in" with the new stats it can work 
like in bla.bla.bla.bla.vnumweapon.bla.bla.bla etc etc

**Comment by 0Lucifer0** [comment]
Nope not in Its eq Packet

**Comment by itemhack** [comment]
oh yes i forgot ahaha if someone need i can map the packet

**Comment by Sl4yZ** [comment]
@0Lucifer0 What is the method to equip items?

**Comment by 0Lucifer0** [comment]
Just add It to equipment look at wear Packet

**Comment by Sl4yZ** [comment]
Work is done
#Close
