### ISSUE TITLE
Can't go to act 5 or FC without $Teleport

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#685]
As far as I know you can't parse to teleport to act 5 or fc, am i mistaking or this needs to be implemented?

**Comment by 0Lucifer0** [comment]
because it's not teleporter it's map instance (boat)

**Comment by unknownforces** [comment]
What about npc teleports like the one to teleport to sp 6 and to arena, they dont work either
also sp 5 draco place doesnt parse

**Comment by unknownforces** [comment]
or to act 6

**Comment by 0Lucifer0** [comment]
Draco place is an instance too the act6 tp is for later ;)
