### ISSUE TITLE
Bug Changeclass command + mimi

### ISSUE THREAD

**Issue by itemhack** [OpenNos/OpenNos#686]
![untitled](https://cloud.githubusercontent.com/assets/8602131/16803562/599b0ffa-4907-11e6-887d-05d3fce5ad1d.png)
When i use the command $ChangeClass "class" the server don't reload the new class and i need to change map 

the same act happen when i change class by mimimentor

edit = when i change class everyclass give me knife and a hammer

**Comment by 0Lucifer0** [comment]
Ah yes my bad >< need to change something ;)

**Comment by itemhack** [comment]
if you can reput the sly4z option (rare and upgrade) that was rly nice :+1:

**Comment by 0Lucifer0** [comment]
What option ? I didnt deleted Any option. Ps we make like official r0+0 It should be fixed now
