### ISSUE TITLE
Parsing mob location

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#687]
I spent 6 hours yesterday parsing and now, in a lot of maps the mobs are stuck in 1 place and dont move..??

**Comment by 0Lucifer0** [comment]
You Forget mv Packet ><

**Comment by unknownforces** [comment]
No, I got this in every map, it's just, if they arent in the original spot on normal server, they are put where they are bugged and now i cant change it unless i start all over and spend another 6 hours.. 
some mobs are half way through a wall and thats why they dont move

**Comment by unknownforces** [comment]
@0Lucifer0  So any solution to this? :s

**Comment by 0Lucifer0** [comment]
Parse correctly the map ;) With all mv or rearange manualy in the database
