### ISSUE TITLE
Level up/drop before monster dead

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#690]
When I attack a monster and I'm going up, I'm instance 92% I do a skill before the end of the movie I already have the message "level up" when it should only appear when the monster dies and not before he died

https://gyazo.com/4c8f8615a7e9379369c8b27cdc8d062b

**Comment by Uppermost** [comment]
same for drop, drop before the monster dead.

**Comment by MasterDomino** [comment]
we can now utilize delay in packets if im right, just tell me and i will take a look at it

**Comment by Ciapa1** [comment]
delay would be skill based, so we need to send the packet after the effect timer, not the cooldown.
