### ISSUE TITLE
Add the good JOB / JOB SP / LEVEL XP / GOLD algo by level

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#692]
- [x] Add proper level dependant jobexp algo
- [x] Add proper level dependant sp jobexp algo
- [x] Add proper level dependant exp algo
- [x] Add proper level dependant gold algo
- [x] Add SP optimisation (xp for normal job when you use sp (50% of the xp win~)

**Comment by 0Lucifer0** [comment]
need to find all the correct algoritm for amount of xp gived by monster with level difference and sp xp sharing

**Comment by SC909** [comment]
http://pastebin.com/nCqJvgPp
http://pastebin.com/hyTFDDva

In future I will add Act 4 exp from monsters & both penalties (1. level between ... 2. level higher from enemy). 
I will try to complete it without warmth system but it depends on you.

I nearly finished the Act 4 but I only need to finish penalty 1. level between, and understand why do I gain 12 to job from monsters when I should get only 6 but I think you gain 12 as the warmth does so only for the lowest of job level gain which is 60. But on SP I also get 12, and I gain the same amount even from chickens lv1.

**Comment by Uppermost** [comment]
Thanks good job

A vulonter for this issue?

**Comment by SC909** [comment]
Well I can say I finished my job for now.

Please read it carefully, if you don't understand something you can always ask.
http://pastebin.com/KKeQ5QFj

I will also have a look at Act 4 moobs again as I might have done some errors, I will publish more stuff soon.

**Comment by Uppermost** [comment]
Go at the LoD and try to kill Giant Knight on opennos it give you 0.02%. there is maybe a problem with the level xp by level

You win 0.04 / 0.05 on official by giant knight.

**Comment by Uppermost** [comment]
Now it's ok with official for fight level. Exactly the same XP for fight but I don't know for job. Keep it like that it's ok ;)

**Comment by MasterDomino** [comment]
do the gold algo pleb @Martazza
