### ISSUE TITLE
Complete the aventurer bar and add capture skill for all class

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#695]
*

**Comment by 0Lucifer0** [comment]
can you give us the correct bar of a new sp and the change class? and the start bar

**Comment by Uppermost** [comment]
Aventurer first connexion : 
![image](https://cloud.githubusercontent.com/assets/15254478/16855324/1671610c-4a15-11e6-8749-432de9e4059e.png)
Magician : None
Archer : None
Swordman : None
Sp : None
(it is for us to add them to the bar)

**Comment by Uppermost** [comment]
All capture skill added, 
now we need to add auto quicklist after character creation
