### ISSUE TITLE
hero chat dont work

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#699]
I try to type in hero chat and it doesn't work.

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/16853662/8ecd1ae0-4a0d-11e6-9a8a-255dc8432535.png)

The chat work only if you have the good reputation ( they 3 first ) and if you are not game master 
(Crown reputation to use it) like official

I have test and it work, Syntax "+TEXTE"

**Comment by unknownforces** [comment]
Ahh, I tried but I thought command was ! , my bad.
