### ISSUE TITLE
Add the sp skill lvl

### ISSUE THREAD

**Issue by MisterBenju123** [OpenNos/OpenNos#700]
If your sp is lvl 1 you have 5 skills and so on...

**Comment by MasterDomino** [comment]
isnt it done already, specify what do you mean

**Comment by unknownforces** [comment]
I think once you  have +15 sp of the same sp, you get all skills on a new sp, cause I just used lv 1 ranger and it gave me all skills and added them to bar

**Comment by MisterBenju123** [comment]
I want to say that each earned joblevel we have new skill on our sp

**Comment by MisterBenju123** [comment]
because at the moment the lvl1 sp have already all skills

**Comment by itemhack** [comment]
maybe it is usefull to rework this function (IMHO)

**Comment by 0Lucifer0** [comment]
same as #399
