### ISSUE TITLE
Items like costumes/fairies need to be untradeable after first use

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#702]

**Comment by 0Lucifer0** [comment]
please let a description it's easier for us^^

**Comment by unknownforces** [comment]
Well, you know how in official, when you use something it says "are you sure you want to use this item?" and then after use, you can't trade it to other people or put the items in shop. 
On open nos, even if you use this item, you can still list it in shop and trade it.

**Comment by 0Lucifer0** [comment]
yes i understand it was just to tell you than sometime for searching a issue description is better^^

**Comment by unknownforces** [comment]
oh, alright. My bad ^^
