### ISSUE TITLE
Transforming out of sp mid attack

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#703]
As you can see in video, I use final and then remove sp before it even uses skill. This should make you wait until after the skill is done until you can go back to normal.

https://gyazo.com/fa0b62351ecb26e4cd3541cf1242f82b

**Comment by unknownforces** [comment]
Don't forget you can rest/loot etc mid attack aswell. So there needs to be a limit so you can't do anything while attack animations happen

**Comment by 0Lucifer0** [comment]
is this bug still here ?

**Comment by unknownforces** [comment]
Yes

**Comment by unknownforces** [comment]
This doesn't work for click to use skills and you can also still remove SP from inventory (transforming you back to normal)
