### ISSUE TITLE
Add amulet effect (Over the head)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#707]
Like draco, glacerus amulet, Ghost amulet, Halloween amulet and other...

**Comment by Uppermost** [comment]
INDEX	0	3	4	11	332	852

852 is the value of the effect  (on the item.dat)

**Comment by MasterDomino** [comment]
parsing for EffectValue changed

**Comment by Uppermost** [comment]
Need to add task for effect

**Comment by 0Lucifer0** [comment]
Task already exist.
