### ISSUE TITLE
Party Exp don't work 

### ISSUE THREAD

**Issue by itemhack** [OpenNos/OpenNos#708]
I don't know if someone has report this problem 

The exp when you are in group cant be shared with your ally/allies

**Comment by 0Lucifer0** [comment]
Already in issue ;) please read all issue before post

**Comment by itemhack** [comment]
but i cant find nothing :) are you sure m8 ?

**Comment by Uppermost** [comment]
I don't find too this issue, strange, need to reopen ?

**Comment by 0Lucifer0** [comment]
Yes but It was closed by mistake

**Comment by Uppermost** [comment]
#467
