### ISSUE TITLE
monsters killing where in death state

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#711]
when you're in death state aggroed monsters can kill you many times

**Comment by 0Lucifer0** [comment]
@MasterDomino should be fix now. Can you confirm?

**Comment by DarkCacos** [comment]
Unfortunately it is not yet fixed: They continue to kill you a bit of times, and then they walk away. Now for "one" death you lose the dignity multiple time and receive many message asking for respawn.
I tried with aggroed mobs of the LOD.

[Screenshot](https://s22.postimg.io/yt9lcx1oh/Problem_with_deaths.jpg)

**Comment by MasterDomino** [comment]
ass @DarkCacos said still persists
