### ISSUE TITLE
RateGold problem

### ISSUE THREAD

**Issue by itemhack** [OpenNos/OpenNos#722]
when the goldrate is high when you kill a mob the server crash 
maybe because the gold value is a "short"

**Comment by The-Art-Of-War** [comment]
Its not exactly a crash the character freezes you can for example Teleport to another map whitout problem :D

**Comment by itemhack** [comment]
in my server visual studio get a break and i need to press continue..after this i need relog

**Comment by The-Art-Of-War** [comment]
Yeah but in my case other functions work only attacking or walking is blocked after relog like you said everything works

**Comment by 0Lucifer0** [comment]
Need to limite the rate to 1000 i think
