### ISSUE TITLE
Character Freeze if Gold Rate is to high

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#723]
It seems that if you increase the gold rate (Im not sure what value exactly causes this problem but i quess a really fucked up  rate like 2000-10000 :D) to a really high level the character freezes if the mob tries to drop gold, mobs also freeze with 0 hp and 0 mp after death untill they respawn

**Comment by 0Lucifer0** [comment]
Need to forbed a to high gold rate to avoid the overflow

**Comment by 0Lucifer0** [comment]
Btw Its useless to use bad value in gm commands >< gm have all right so if They want to shut the server They can
