### ISSUE TITLE
Detele character bug (?)

### ISSUE THREAD

**Issue by itemhack** [OpenNos/OpenNos#725]
sometimes when i delete a character the server say "password wrong" 

and when i delete a charcter (when it work) the character stay in the db forever

**Comment by 0Lucifer0** [comment]
The character Will always stay in database if It say Wong Its because you miss a key ;)

**Comment by itemhack** [comment]
nope the gameserver give me the right password but the client say "password wrong" :\ 
i need to relog in the server to fix it ;)
