### ISSUE TITLE
Equipping SP before cooldown timer is completed

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#727]
Uppermost did a commit to fix this but the issue still persists, I can equip a SP straight away even tho the timer isnt completed

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/17077683/4bf57762-50d9-11e6-9913-59ce05aa70a5.png)

You are not on the latest update

**Comment by unknownforces** [comment]
Oh, I thought you meant something else. Well, this issue is that it allows me to change SP's even while the timer isnt completed. Like in official, you can't change sps until it is done. @Uppermost

**Comment by 0Lucifer0** [comment]
Ah ok Will fix It asap

**Comment by Uppermost** [comment]
is fix :D

**Comment by unknownforces** [comment]
It isn't for me and i'm on latest o.o

**Comment by Uppermost** [comment]
https://gyazo.com/462da096624ce35121e2887e6e1f68d3

**Comment by unknownforces** [comment]
Okay, I downloaded the latest AGAIN, updated database and this problem still happens. What am I doing wrong??
