### ISSUE TITLE
Problem with skill (freeze)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#728]
Freeze when i attack, very often (tested on Sp1 Swordman)

**Comment by 0Lucifer0** [comment]
So read this https://github.com/OpenNos/OpenNos/commit/521dda3b85ab672e129ce770e56397806397fe47

**Comment by 0Lucifer0** [comment]
Re add

**Comment by Uppermost** [comment]
Problem not solved, need review

**Comment by 0Lucifer0** [comment]
So remove It i dont Know why There is a problem ...

**Comment by MasterDomino** [comment]
Please test before commiting, dont re-add anything if it can damage other systems

**Comment by Uppermost** [comment]
Tested before, but the problem is randomly

**Comment by Uppermost** [comment]
Add information, bug appear only when you use a skill, never appear on the basic skill

**Comment by unknownforces** [comment]
I don't have this issue, i just sat here spamming skills and it worked fine?

**Comment by Uppermost** [comment]
Strange, are you on the latest update ?

**Comment by unknownforces** [comment]
I'm on the one before you added task factory. Which you said it occured in aswell

**Comment by Uppermost** [comment]
Please try on the latest update and tell me if is ok for you, for me the problem is appear after 30 seconds

**Comment by unknownforces** [comment]
I tested and I still don't have this issue?

**Comment by MasterDomino** [comment]
ok soo i think the issue is that when you spam skills server queues them and then waits until cooldown is done and then removes 1 queued command :P

**Comment by Uppermost** [comment]
fix with my latest commit

**Comment by MasterDomino** [comment]
not fixed when you spam skills you can lock yourself in state when character is waiting until cooldown is finished and then uses the skill again which causes freeze in death state

**Comment by 0Lucifer0** [comment]
Its not the same problem xD

**Comment by MasterDomino** [comment]
its freezing you on skill usage when you spam, soo its like the title says

**Comment by unknownforces** [comment]
Freeze in death state has nothing to do with spamming skills.. It happens without skills too.

**Comment by Uppermost** [comment]
Problem solve ? Never had again this problem :/

**Comment by MasterDomino** [comment]
when you change into sp try spamming skill on some monster as fast as possible and you will be stuck untill skill refreshes and then it will automatically use itself

**Comment by 0Lucifer0** [comment]
Thats volonteer an appear only if skill couldown is near end
