### ISSUE TITLE
Some AoE hits the monster, but it does not lose HP

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#729]
Sometimes when you attack a monster with an area attack (maybe it does not occur only with an area attack) monsters will be affected, but they will not lose HP, (test with SP1 Swordsman)

This problem is randomly.

**Comment by unknownforces** [comment]
It also happens with monk a lot, like seven stabs and targetted stab, they often don't do any dmg.
also it's AOE skills don't do dmg either.

**Comment by itemhack** [comment]
This skill too don't make damage 
all flying to enemy skills don't make damage (sorry i don't know how to translate what i think in english) 
![untitled](https://cloud.githubusercontent.com/assets/8602131/17078095/60fd89c8-50e9-11e6-8c79-9c13b8e58cf5.png)

**Comment by 0Lucifer0** [comment]
yes there is already an issue on this

**Comment by Uppermost** [comment]
Are you sure, i have watch but not find :/
