### ISSUE TITLE
Issue with equipping SP

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#731]
https://gyazo.com/52c91e47a32579fafb9f059298f21c5b
I don't even know how to explain this one. Basically it just keeps counting up in timer and won't let me equip it. It does the same thing when I try to equip SP while already in SP.

**Comment by Uppermost** [comment]
Do you use your skills before removing SP?
If so, this is simply the normal time.

**Comment by unknownforces** [comment]
I don't have any skills. I just left SP and then I go to change it and this happens. Keep in mind, this timer only counts up not down.

**Comment by unknownforces** [comment]
I think might be to do with lucifers commit cause, It allows me to change SP when the timer is counting down after I leave SP but, when the timer is done it doesnt allow me to change it. So basically the opposite xD

**Comment by Uppermost** [comment]
I don't know the problem, i don't have this problem... Very very strange
