### ISSUE TITLE
Still crashes because of "$RateGold"

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#732]
If i kill some 45lvl mobs the server still crashes (btw the rate was only at 70) is it possible that only 16bit numbers are stored? for exmaple highest gold drop = 32.767 because the highest i've got was = 32k gold

**Comment by 0Lucifer0** [comment]
Yes Its possible but Its à mistake... So item amount should be long ><

**Comment by The-Art-Of-War** [comment]
Oh okay :D

**Comment by MasterDomino** [comment]
ok i think i found i also when creating issues i want to ask you to include screenshot of error in console because its easier to find :)

**Comment by The-Art-Of-War** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/17483888/17080385/4c0d55c2-512d-11e6-89fe-ba56e0c68b62.PNG)

**Comment by MasterDomino** [comment]
its okay now i fixed it
just for future purposes and rest of issues, thank you.
