### ISSUE TITLE
Too much gold

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#734]
![unbenannt](https://cloud.githubusercontent.com/assets/17483888/17081127/922f11b6-514c-11e6-918c-c39bfb1df6fc.PNG)

Doesn't matter wich rate is activ the gold drop is exactly = 1073741823

**Comment by MasterDomino** [comment]
Ooh sorry i forgot to remove my test line xD
Will commit in a second

**Comment by The-Art-Of-War** [comment]
Haha :'D
