### ISSUE TITLE
SP skills not appearing

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#735]
Seems they only have the first 5 skills and then don't get the others once i make sp level 99
![20160724-4-zyzz](https://cloud.githubusercontent.com/assets/19580091/17082592/f7e773e2-51c7-11e6-91f9-c44aa73828da.jpg)

**Comment by itemhack** [comment]
when you relog the skill appear?

**Comment by unknownforces** [comment]
It appears when I leave SP and go back into it. But this shouldn't happen. It should change without needing to leave.

**Comment by 0Lucifer0** [comment]
Yes so when levelup we need to reload skills ;)

**Comment by MasterDomino** [comment]
Ok will add it asap. Need to add generateski on changesplvl
