### ISSUE TITLE
SP Skills remain when changing from Lvl 99 -> 1

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#736]
When I change SP to lvl 99, I acquire all skills but then when I change back to level 1 they still remain.

**Comment by MasterDomino** [comment]
its useless only admin can use this option soo why you try to find issues in that xD if youre admin you can bug as much as you want we dont want to have perfect commands they're just for fun soo its redundant in my opinion.

**Comment by unknownforces** [comment]
Idk, i'm just reporting bugs.
most players will play in GM mode rather than normally in my opinion.
but its up to you whether you fix or not :s

**Comment by Uppermost** [comment]
@unknownforces 
For there to be a real purpose in the private server, only a few players will be GM. Otherwise it will be void, be GM should not be reserved for everyone ...
As the true NosTale after if they shit that's their problem :/

PS : Thanks to report bugs :D

**Comment by unknownforces** [comment]
@Uppermost I agree in case of private server.. but most people will probably play with friends or for their own use.. So I'm sure they want to experience both sides (gm and normal) bugless xD
