### ISSUE TITLE
wear SP when cooldown and no sp item equipped

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#737]
In official, you cannot remove SP while you have cooldown

**Comment by 0Lucifer0** [comment]
Are you sure because we can remove It during sp and It Will unmorph you

**Comment by unknownforces** [comment]
Didn't know you could do that but yeah you can't remove it on official

**Comment by itemhack** [comment]
unknow says "in the official i cant equip another sp if i have a cooldown"

right ?

**Comment by MasterDomino** [comment]
he means that when you demorph, you cant unequip your sp on cooldown, also iirc on official we can remove sp without demorphing.

**Comment by unknownforces** [comment]
No, i'm saying you CAN unequip your sp on cooldown, on official you can't do that unless you unequip it while in SP (which is already in emulator)

**Comment by MasterDomino** [comment]
unwear part done now need to add wear on cooldown when no spitem equipped
