### ISSUE TITLE
SP XP is bugged when leveling then going back to lvl 1

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#738]
After leveling a bit then going back to level 1, XP is bugged. But on combat LVL it goes back to 0%
![20160725-0-zyzz](https://cloud.githubusercontent.com/assets/19580091/17084524/57657cf2-5203-11e6-8b31-3166dfb592e5.jpg)

**Comment by 0Lucifer0** [comment]
Thats because you have more xp than the lvl allow but Will fix It

**Comment by unknownforces** [comment]
Yeah.. but should reset to 0.00 like level does xD
