### ISSUE TITLE
wrong displaying skills on sp cards

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#739]
![20160725-1-zyzz](https://cloud.githubusercontent.com/assets/19580091/17092912/1fe658ba-5289-11e6-8384-f8c869c1f64f.jpg)

**Comment by MasterDomino** [comment]
how is it done please always add explanation what you did

**Comment by 0Lucifer0** [comment]
It should be fixed now

**Comment by unknownforces** [comment]
I editted the post, the other bugs are fixed but this one still happens. I just made the SP and those skills are in the slots when I right click it. It should be blank

**Comment by MasterDomino** [comment]
does this happens for that particular SP? or for others too?

**Comment by unknownforces** [comment]
Others with combo like DH

**Comment by MasterDomino** [comment]
does this still occur?

**Comment by 0Lucifer0** [comment]
This is not a parser error Its world error

**Comment by unknownforces** [comment]
Yeah it does

**Comment by Uppermost** [comment]
Ok there is an error too when you try to use one skill, sometime it do 2 skills in the same time.

**Comment by 0Lucifer0** [comment]
Thats not the same error xD

**Comment by MasterDomino** [comment]
issue is called review soo person who will work on it should also check this issue its pointless to create another issue when this one is called this way

**Comment by 0Lucifer0** [comment]
The name isnt good this is not a review but à bug

**Comment by MasterDomino** [comment]
better?

**Comment by 0Lucifer0** [comment]
Yes

**Comment by 0Lucifer0** [comment]
partialy fix but need to fix parser

**Comment by 0Lucifer0** [comment]
We Will need to hardcode all sp skills Level i think...

**Comment by 0Lucifer0** [comment]
(In parser)

**Comment by friends111** [comment]
Can't you just add first (natural sorting) 10 skills from the SP in the card display?

**Comment by 0Lucifer0** [comment]
Nope because some sp have combo skills >< look at the screen

**Comment by friends111** [comment]
Yes, but the combo IDs are later than normal skills. You don't see combo in SP-RMB. First 10 skills are always normals skills.
For example (not real but you get the point)
1200 - basic attack
1201 - 1st skill
...
1210 - last skill
1211 - combo

**Comment by Ciapa** [comment]
we could to it by a little "hack", using only the Entries at position 1-10 of all Specialist skills and then check for each skill if the minimum level is reached. If so, add it to the RMB window

**Comment by 0Lucifer0** [comment]
seem's to work :) but we need to use this "hack" on parser too for lvlmin

**Comment by Ciapa** [comment]
just copycat it there, if (SKILLVNUM > firstskillvnum+10) level=20;

**Comment by 0Lucifer0** [comment]
nope in fact because you can get combo before lvl 20 so the combo enabled should be directly in the code and for the lvl we should keep the < vnum+10 will do it asap

**Comment by Ciapa** [comment]
@0Lucifer0 In fact you can't. Not on official atleast
