### ISSUE TITLE
Ammo needed for Dash-Skills

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#741]
![47ec6ac24d34d209785b387d60d23570](https://cloud.githubusercontent.com/assets/17483888/17087164/fd8eb67a-5203-11e6-9cce-1d86fc5e10fc.gif)

Its the same with the other Dash-Skills not only for "Assassin"

**Comment by The-Art-Of-War** [comment]
Okay :D if you find it just close that one

**Comment by Uppermost** [comment]
we must not forget that sp8 archer uses the dagger on some shots

**Comment by The-Art-Of-War** [comment]
So in that case there must be a separation from some skills like that :D ?

**Comment by 0Lucifer0** [comment]
There is already an issue no need to make one for each skills

**Comment by Uppermost** [comment]
#631
