### ISSUE TITLE
$Box idplayer itemvnum number

### ISSUE THREAD

**Issue by itemhack** [OpenNos/OpenNos#746]
when the box will be implemented can be added this packet ? 
if it is useless close it :)

**Comment by Uppermost** [comment]
You speak about raid box ?

**Comment by 0Lucifer0** [comment]
Its for raid so not this milestones

**Comment by itemhack** [comment]
nope bro i mean the box near the note 
i don't know how to explain it 

when in official nostale the gm give to all a box 
![maxresdefault](https://cloud.githubusercontent.com/assets/8602131/17174482/2296b8dc-5402-11e6-814f-8588a50c89b6.jpg)

**Comment by 0Lucifer0** [comment]
This is for the next milestone

**Comment by itemhack** [comment]
okok sorry ^_^

**Comment by Uppermost** [comment]
Good idea i will be done in the future
