### ISSUE TITLE
$RateDrop cant upgrade the gold rate

### ISSUE THREAD

**Issue by itemhack** [OpenNos/OpenNos#748]
the ratedrop don't incressed the droprategold but only itemdrop 
can be change ?

**Comment by 0Lucifer0** [comment]
Its volonteer to have 2 drop rate and gold rate

**Comment by itemhack** [comment]
ok m8 but goldrate incressed only the amout of gold not the dropfrequency :\

**Comment by MasterDomino** [comment]
we dont need drop frequency for gold when its already high. now when you set high gold drop amount you will get max gold in no time i locked max gold amount dropped to 1,000,000,000 soo its pretty high.
