### ISSUE TITLE
I can see a player that is not even on the map than I

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#749]
![image](https://cloud.githubusercontent.com/assets/15254478/17195259/1e8c44c2-545d-11e6-83b0-cf6a0de5735d.png)

it should show only the players on the same map

When the player leaves the map, it is still considered on the same map as me.

**Comment by itemhack** [comment]
@MasterDomino  it is fixxed now or..?

**Comment by Uppermost** [comment]
no fix x)

**Comment by 0Lucifer0** [comment]
will be fixed in #789
