### ISSUE TITLE
Add review act scene

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#750]
![image](https://cloud.githubusercontent.com/assets/15254478/17196778/4d8424fc-5467-11e6-8558-7e5aca87eb2a.png)

it should not be very hard to do

"guri 40" send "scene 40 1"

and for the future is the same for other act example for act 2

guri 41
scene 41 1

PS : When you click, scene stop.

**Comment by 0Lucifer0** [comment]
Not for the moment
