### ISSUE TITLE
x-mask disappearing

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#751]
When I log in it says "Item is no longer valid" and my x-mask is gone and it also changes the fairy element type so I have 2 of one and i'm missing one..

**Comment by unknownforces** [comment]
Why'd you close this? this issue has been happening to me for awhile now.

**Comment by Uppermost** [comment]
We want more information please if is possible, please retry this problem is probably fix now

**Comment by MasterDomino** [comment]
I thought it was because my commit

**Comment by Uppermost** [comment]
Is possible, but not test ^^

**Comment by unknownforces** [comment]
There isn't much information to give.. just a lot of the time when i start it and log in, my x-mask disappears and the fairy i have equipped changs to a different ele, I doubt it is fixed cause it's been like this for over a month..

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/17220863/7cdc9d1c-54f1-11e6-8954-d0479b9159bd.png)
There is a problem with the backup server at the moment but I do not have this problem

**Comment by unknownforces** [comment]
You've never had it ever?
I get this a lot but it's random..

**Comment by Uppermost** [comment]
What synthax use you when you get Mask X, the correct synthax is : $CreateItem 227

**Comment by unknownforces** [comment]
Yeah, I use that.

**Comment by unknownforces** [comment]
I can't get it to do it again, so i'll just make a new issue when I can ss it next time.

**Comment by unknownforces** [comment]
Okay so, I logged in and this is what happens.
![20160730-0-ancelloan](https://cloud.githubusercontent.com/assets/19580091/17254898/0ea5d520-55fa-11e6-8eba-6e1ae4a2d7df.jpg)

**Comment by MasterDomino** [comment]
found theres problem with parser several items have this issue need to propably hardcode some vnums :(

**Comment by 0Lucifer0** [comment]
No xD There is no temporary mask only amulet and costume so we only need to disapear amulet and costume

**Comment by Uppermost** [comment]
tell us if this problem reappeaar

**Comment by MasterDomino** [comment]
it should not because it was parser fault soo it wont ever do it again :P
