### ISSUE TITLE
review packets and all sendpacket

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#753]
need for little optimalization and little cleanup of redundant packets, if any found check if found on official also update any outdated packets

**Comment by Uppermost** [comment]
I can help you master, tell me what you want (skype easier)

**Comment by MasterDomino** [comment]
i wanted to mainly sort "game_start" answer and "changemap" function because they seem to have some redundant packets also check all packet handlers and i have problem with it i already told rest of the team about it waiting for respone.

**Comment by MasterDomino** [comment]
we need to check Session registering to make game_start handling similar without usage of ChangeMap

**Comment by 0Lucifer0** [comment]
Why ? Using changemap is Logic...

**Comment by MasterDomino** [comment]
if you look at packets on official and on changemap for game_start there differently ordered and i want to check all packets already existing for update, for now i was able to reorder everything with usage of changemap but without it im not able to make monsters move xD some stupid PEBKAC

**Comment by MasterDomino** [comment]
okay soo now we want to just update all packets that we have
