### ISSUE TITLE
Add that when you fight you can not receive any invitation to trade and group

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#754]
![20160729-0-uppermost](https://cloud.githubusercontent.com/assets/15254478/17233885/163df0ea-5534-11e6-8c3e-674426820310.jpg)
And add message like this, same for group PS : I don't know if you want i create 2 issues for that, tell me i modify the tittle if you want (Lucifer)

DONT FORGET, IF YOU ATTACK A MONSTER YOU CAN T ASK A SHOP !

**Comment by unknownforces** [comment]
This was in issue before but with trade, but i cant find it..
