### ISSUE TITLE
add $FLvl level and $FairyXpRate rate Command

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#756]
can there be a command like $RateXp for fairy's? for example $RateFairyXp

**Comment by Uppermost** [comment]
Wille be done, but i don't think is very useful

**Comment by unknownforces** [comment]
I think should be changed to be able to change fairy %
but just my opinion.

**Comment by MasterDomino** [comment]
we should also add max fairy level like 50 for basic fairies 70 for nosmall ones and 80 for big nosmall ones(already maxed out) i think if im not mistaken

**Comment by Uppermost** [comment]
Is done, i commit it when masterdomino the work on fairy level

**Comment by Martazza** [comment]
https://github.com/OpenNos/OpenNos/commit/471b94ce51a972832ef0d8fb4c052e4a03acb918

**Comment by MasterDomino** [comment]
work done FairyXp displayed on wear, use $FLvl for changing fairy level and $FairyXpRate for changing xp acquiring rate, thanks for commits.
