### ISSUE TITLE
Group and "Player get hit" health synchronization issue

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#758]
![unbenannt](https://cloud.githubusercontent.com/assets/17483888/17270425/819badf8-5662-11e6-9669-dd0eed455843.PNG)

As you can see if the health in group of an member is beneath 100% it will be shown as 0 HP at the group information

![e82419e6ab9078fd2f47282405eeb502](https://cloud.githubusercontent.com/assets/17483888/17270460/53459c1a-5663-11e6-99c6-e7ec61fda8aa.gif)

Also if other player get hit by an enemy the health bar dissapears for a short time and then come back with the true health that is left after one hit, i think it should stay and only show how the other player lose his health (if you know what i mean)

**PS. Master's note:** also theres a issue when someone create a group and one person logs out and other is attacking a monster the person attacking can stuck and sometimes you need a relog.

**Comment by Martazza** [comment]
https://github.com/OpenNos/OpenNos/commit/19d69547272db89bc523b8d2236a2cd561dc8ecd

the party stat fixed

**Comment by Uppermost** [comment]
not fix completly

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/17271875/58cebf2a-5688-11e6-8a9f-ba79620e91ec.png)

**Comment by itemhack** [comment]
the party now work the hearlbar nope 
(pacchet stat yes | st nope)
