### ISSUE TITLE
$FLvl wrong value

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#759]
When I type $FLvl 80 it goes to 130% ?

**Comment by 0Lucifer0** [comment]
Its seems There is an error With the basic ;) si we need to fix It

**Comment by unknownforces** [comment]
Okay well since you said put it in one, there is also this aswell. ![20160731-1-zyzz](https://cloud.githubusercontent.com/assets/19580091/17272716/3fa643d4-56e1-11e6-9c1e-2d0533fe9e0b.jpg)

**Comment by MasterDomino** [comment]
admin has more rights soo it can have fairy with high level

**Comment by unknownforces** [comment]
That's not the issue though?

**Comment by MasterDomino** [comment]
it is because its only admin command

**Comment by 0Lucifer0** [comment]
Yes but we need to substract sur basic level

**Comment by Uppermost** [comment]
" test now 00:32 and not fix for the moment "
