### ISSUE TITLE
Monster with friends

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#761]
For example, when I attack fat pidgeon, the others should be aggro when i walk past them, but they don't.

**Comment by 0Lucifer0** [comment]
will need a list of monsters that have a friend protect mode (when you hit a friend of them they attack you)

**Comment by Uppermost** [comment]
List
---------
Pidgeon
Wolf
Minor (When you attack minor chief)

**Comment by 0Lucifer0** [comment]
Try to find a common point in Monster.dat

**Comment by Uppermost** [comment]
VNUM	200
	NAME	zts194e
	LEVEL	57
	RACE	0	1
	ATTRIB	0	0	8	10	7	9
	HP/MP	0	0
	EXP	0	0
	PREATT	0	5	8	7	1800
	SETTING	200	0	-1	0	0	0
	ETC	8	1	0	0	0	0	0
	PETINFO	7	3	0	64
	EFF	1047	0	0
	ZSKILL	0	1	5	2	8	0	0
	WINFO	0	0	3
	WEAPON	57	1	30	0	0	2	60
	AINFO	0	4
	ARMOR	57	-20	-20	0	0
	SKILL	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
	PARTNER	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
	BASIC	0	0	4	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
	CARD	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
	MODE	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
	ITEM	2073	7000	1	715	400	1	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0
		
	
    VNUM	181
	NAME	zts181e
	LEVEL	70
	RACE	0	1
	ATTRIB	3	55	15	10	30	-10
	HP/MP	7000	0
	EXP	6500	150
	PREATT	0	5	12	7	1200
	SETTING	181	0	0	0	0	0
	ETC	0	0	0	0	0	0	0
	PETINFO	0	0	0	0
	EFF	1006	0	0
	ZSKILL	0	1	3	0	9	0	0
	WINFO	0	0	2
	WEAPON	70	1	80	160	5	2	90
	AINFO	0	2
	ARMOR	70	0	-10	0	0
	SKILL	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
	PARTNER	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
	BASIC	0	0	0	0	0	0	0	0	0	0	25	8	508	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
	CARD	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
	MODE	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
	ITEM	1314	1000	1	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0	-1	0	0

**Comment by Uppermost** [comment]
Why someone close it? it's not fixed.

**Comment by 0Lucifer0** [comment]
You closed it...

**Comment by Uppermost** [comment]
Because this issue was in double but someone close the other.

**Comment by Uppermost** [comment]
@0Lucifer0 Close then?
