### ISSUE TITLE
Mobs are laggy

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#763]
When I was mobbing pigeons, it's like they were lost puppies.. they would just stand there and walk around on the spot for a bit until they started walking to attack me again, idk how to explain.. but it makes mobbing really bad. I tried to video but, my laptop too slow. Maybe one of you can test it and better explain it xD

**Comment by Uppermost** [comment]
Strange, if I have some information about this bug I tell you

**Comment by unknownforces** [comment]
https://youtu.be/88pcwsJDiEs
I made a video, you can see what i mean towards the end.

**Comment by Uppermost** [comment]
Yes, they seem slow

**Comment by 0Lucifer0** [comment]
will be fix in #788
