### ISSUE TITLE
Mobs don't respawn at normal place

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#764]
https://youtu.be/JtwGdep2moA
Sometimes they spawn where I killed them, then lag over to their normal place

**Comment by unknownforces** [comment]
I'm not sure if i should make a new issue or if this would be counted as similar
But basically, when the mob stops following the character, it just stands there and doesn't do anything,

**Comment by 0Lucifer0** [comment]
Dépends on the mob ><

**Comment by unknownforces** [comment]
Are you sure? Cause I tried with pigeons as well and it did the same thing

**Comment by 0Lucifer0** [comment]
I mean in official Monster like dander go to the origine place

**Comment by 0Lucifer0** [comment]
Ah no i didnt understand the issue yes Its not normal ;)

**Comment by 0Lucifer0** [comment]
so just to know for fix this bug we only need to reset the position when dead right?

**Comment by unknownforces** [comment]
Yeah back to where it respawns

**Comment by 0Lucifer0** [comment]
should be fixed now.

**Comment by MasterDomino** [comment]
seems to reappear again
