### ISSUE TITLE
The images of emoticons are showed behind the image of the wings

### ISSUE THREAD

**Issue by DarkCacos** [OpenNos/OpenNos#765]
In the emulator the images of emoticons are showed behind the image of the wings.
This is quite evident when the character is in certain positions:
[Emoticon Problem Screenshot](https://s32.postimg.org/jy1rozzxh/emoticon_problem.jpg)

**Comment by 0Lucifer0** [comment]
Not our problem Its your client fault we dont do anything graphics ;)
