### ISSUE TITLE
Mob bosses don't leave the spot they're parsed

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#766]
They always return back to the spot they're parsed, on official they can go all over the map and don't have a specific "spot". Obviously it's not that important, but it's still a bug nonetheless.

**Comment by Uppermost** [comment]
You mean, monster return always on spot on opennos ?

**Comment by unknownforces** [comment]
Yeah, but on official they walk all over the map and don't return

**Comment by 0Lucifer0** [comment]
On official most of Monster go to their old position ;)

**Comment by unknownforces** [comment]
Ah nvm, I tested on official and i'm wrong xd
