### ISSUE TITLE
on game_start character is visible in death state by others

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#767]
![image](https://cloud.githubusercontent.com/assets/16002990/17288395/23a8b082-57d5-11e6-87bc-a6bc561cc3de.png)

**Comment by unknownforces** [comment]
@MasterDomino How did you get 2 nostales on 1 computer..?

**Comment by Uppermost** [comment]
ProcessExplorer, Sandboxie or use multiclient hack on epvp

**Comment by unknownforces** [comment]
I mean on opennos xD he is running 2 on 1 computer o.o

**Comment by MasterDomino** [comment]
is it that hard to run 2 clients on 1 pc theres multiclient creator on epvpers, btw im using hyperslow notebook now intel pentium b960 with integrated graphics on old 650 hdd with 6gig ram soo our emulator is pretty optimized xD

**Comment by unknownforces** [comment]
the problem is, it says multiple instance is already running cause it uses same port.. unlike official, so i didn't think this was possible ? and isn't the multiclient creators on epvp used for official only..?

**Comment by MasterDomino** [comment]
multiclient creator works for me and if you want to login from same ip you just need to wait like 3 seconds

**Comment by unknownforces** [comment]
I try it but it just keeps connecting to official ..

**Comment by MasterDomino** [comment]
Then change ip to 127.0.0.1 xD

**Comment by MasterDomino** [comment]
untill now it only happened to me once its caused when i logged out when still in death state and then logged in fast enough with both clients

**Comment by MasterDomino** [comment]
i leave it for anyone that want to fix this
