### ISSUE TITLE
Add correct gem stones and gold needed for perfecting SP's and message to say when you run out

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#769]
Currently, there is no message to say you have no gem stones left
and it is always showing 5k and 1 gem stone needed instead of correct amount

**Comment by 0Lucifer0** [comment]
this is not a problem with price and number it's set by the client so we will need a real packet ivn/inv of an sp with perfecting on official

**Comment by 0Lucifer0** [comment]
ivn 0 22.4499.0.11.22
