### ISSUE TITLE
You can attack when you are muted

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#771]
(After lucifer commit)

**Comment by Turoid** [comment]
Cause isMuted() returns:  return Session.Account.PenaltyLogs.Any(s => s.Penalty == PenaltyType.Muted && s.DateEnd > DateTime.Now);

Look at the ">".

And Lucifer has made a lil mistake with this:
http://i.epvpimg.com/QDwgh.png

**Comment by Uppermost** [comment]
Yes is the problem fix by lucifer now :p
