### ISSUE TITLE
The time for mute is always 60 minuts

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#772]
you can't change it, ever 60 minuts

**Comment by Uppermost** [comment]
Ever not fix after last commit.

**Comment by unknownforces** [comment]
You also can't remove mute (as far as I know)

**Comment by Uppermost** [comment]
Yes, and we have not the message if the synthax is wrong example when you write $Mute or $Ban

**Comment by MasterDomino** [comment]
We dont care about minutes i already told you i set it to hours and in my opinion its the best, redundant.

**Comment by Uppermost** [comment]
The problem is not this, the value can't be change. Always 1 hour

**Comment by MasterDomino** [comment]
it can be changed just the syntax looks like this $Mute NAME REASON TIME and it was working before changes xD
