### ISSUE TITLE
$Ban command seems not work

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#773]
Ban command not work. I already had a muted and I was banned. but I managed to reconnect without problems

$Ban DevTeam Injures 10 (on my test)

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/17311327/c081afd8-584a-11e6-9147-097186e0231e.png)

**Comment by 0Lucifer0** [comment]
this should be fix with the correct parameters number in if case

**Comment by Uppermost** [comment]
Tested, not fix

**Comment by Turoid** [comment]
Heres an other error too:
![captura](https://cloud.githubusercontent.com/assets/20781816/17329424/e496a3d8-58c2-11e6-9d46-5e7e70e59606.PNG)

if packets length is more than 3: the if (packet.Length == 3) is never executed!

Should be corrected by adding a "=" near ">".

**Comment by Uppermost** [comment]
Ever not work :/

**Comment by Turoid** [comment]
Yes, thats why I said it was ANOTHER problem xd

**Comment by MasterDomino** [comment]
@Turoid i want to tell you that you can commit into our project by pull requests just make your own branch and then pull request your changes to our repo :p
