### ISSUE TITLE
[Add Command] I Release it here, I f you want you implement it.

### ISSUE THREAD

**Issue by Turoid** [OpenNos/OpenNos#774]
**Command:** $MakeGM USER
**Function:** Makes someone GM if is USER. Makes someone USER if is GM. Once used the command, character gets disconnected automatically to apply changes.

**IAccountDAO.cs**
Add: 
![captura](https://cloud.githubusercontent.com/assets/20781816/17311793/3a1dfdda-584e-11e6-8593-375b2ffdaad5.PNG)

**AccountDAO.cs**
Add: 
![captura2](https://cloud.githubusercontent.com/assets/20781816/17311799/45fd31f2-584e-11e6-9402-ba07c1e49cfa.PNG)

**CommandPacketHandler.cs**
Add:
![captura](https://cloud.githubusercontent.com/assets/20781816/17311857/a559b38c-584e-11e6-857e-e83358d81b5a.PNG)

Consider it :)

**Comment by Uppermost** [comment]
This idea can be interesting and I may be convenient, but you have thought of Lucifer before could have put it out

**Comment by Turoid** [comment]
I just leave it here, he can tell me if is a convenient contribution or not :+1:

**Comment by Uppermost** [comment]
It is a good idea but in general when normal player becomes GM recreates it must account for only part of the playing team

**Comment by unknownforces** [comment]
I like it

**Comment by Turoid** [comment]
Thanks guys, I'll try to implement new things now, just testing some stuff

**Comment by Uppermost** [comment]
You can they  fix issue if you want is better for we xD

**Comment by Turoid** [comment]
Which issue they have? I'm implementing pets now xd

**Comment by Uppermost** [comment]
We have not planned pet for this version of opennos, we are on the 1.0.4 pet is on 1.0.5 we need to respect milestone order, if you want to contribute on the project you can maybe join the team.

**Comment by Turoid** [comment]
Oh, I was just implementing them on my own, nothing about contributing to the project. Well, tell me which issue you have?

**Comment by Uppermost** [comment]
All issue open you can see, if you have a fix for them don't hesitate to propose that

**Comment by unknownforces** [comment]
Would be better if you worked with them to further this emulator faster for everyone ;)

**Comment by Uppermost** [comment]
The teamwork is the best thing 😎

**Comment by MasterDomino** [comment]
No need for new issuea make your own branch and then work on it then send us your pull request :P

**Comment by 0Lucifer0** [comment]
that's not a good way to do it... use game object avoid at the maximum to touch directly the database^^ and kick an user to promote it it's a nonsens^^
