### ISSUE TITLE
[Release] Mute - 60 minutes fix

### ISSUE THREAD

**Issue by Turoid** [OpenNos/OpenNos#775]
**On CommandPacketHandler**

**Before:**
![captura](https://cloud.githubusercontent.com/assets/20781816/17313917/590c041e-5860-11e6-905b-7a048053c30c.PNG)

**After:**
![captura2](https://cloud.githubusercontent.com/assets/20781816/17313918/5d14034a-5860-11e6-9c4d-9590209f8b9c.PNG)

I hope I solved it :)

**Comment by Uppermost** [comment]
Thanks i try this in 30 minuts and commit if is ok, please next time don't open issue for fix, post the fix directiy on the open issue :D !

**Comment by Turoid** [comment]
Oh ok, sorry xd

**Comment by Uppermost** [comment]
Tested, not work :x
