### ISSUE TITLE
When sanction is finish, the value is negative and the sanction continue

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#776]
![image](https://cloud.githubusercontent.com/assets/15254478/17314475/feff4116-5864-11e6-8fd0-76bff179eaa5.png)

**Comment by MasterDomino** [comment]
Its not a bug its after your last fixes you turned < around xD

**Comment by 0Lucifer0** [comment]
this is good like that       return Session.Account.PenaltyLogs.Any(s => s.Penalty == PenaltyType.Muted && s.DateEnd > DateTime.Now); so there is a problem somewhere

**Comment by MasterDomino** [comment]
Idk it was working for me will try fixing it when i have time today

**Comment by MasterDomino** [comment]
its caused because we insert a new log into database and we read the first entry from database but the first entry was already used. we need to think about way to avoid it, like get amount of entries and then choose last entry
