### ISSUE TITLE
move account creation

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#777]
we need to move the account creation from the update-database to the parser.
It will avoid problem with already existing account.

**Comment by Uppermost** [comment]
Good thing

**Comment by unknownforces** [comment]
It worked before, but it says account already exists again.

**Comment by unknownforces** [comment]
@MasterDomino  Solution ?

**Comment by Uppermost** [comment]
Ok it not work? want to reopen?

**Comment by unknownforces** [comment]
Yeah it doesn't work, I had to delete my opennos from mysql and start over again because it said "Account already existing" xD

**Comment by MasterDomino** [comment]
when does it say that?
on prasing or when using update-database?

**Comment by unknownforces** [comment]
When using update-database

**Comment by MasterDomino** [comment]
its caused because you already have full database it wont update without additional migration, and im not creating additional migrations every time

**Comment by 0Lucifer0** [comment]
@masterdomino the account création shoudnt be on database-update... It should be on parser...

**Comment by MasterDomino** [comment]
its already in parser update-database issue is caused because i dont create additional migrations soo it finds a copy of "Account" table

**Comment by unknownforces** [comment]
You realize the whole point of moving it was to fix this issue..?

**Comment by unknownforces** [comment]
But the point of moving it was to fix this issue..

**Comment by MasterDomino** [comment]
The point of this issue was to fix the already existing account not whole table, i cant fix this its impossible, its how the ef works
