### ISSUE TITLE
Player be GM after bug ?!

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#778]
![image](https://cloud.githubusercontent.com/assets/15254478/17350458/1c90b54e-5927-11e6-8d45-7ecfd75b574c.png)

As you can see, DevTeam is not GM but randomly he appear GM and OpenNos is GM and is not displayed... after reconnection OpenNos is GM but DevTeam is GM too, then it is not GM

I do not know how it happened but the character DevTeam has access to GM commands without that I assign myself

I don't have more information from this bug, we want to find the problem in the code...

**Comment by 0Lucifer0** [comment]
if there is no way to reproduce i will close it it's possibly a client bug.
