### ISSUE TITLE
Error Exception when i use catapult skill from adventurer and same for swordsman skill use arbalet

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#779]
![image](https://cloud.githubusercontent.com/assets/15254478/17350591/3e1f4cec-5928-11e6-8c28-6828d58d53ad.png)

I can attack whitout munitions, it show munition 100/100 and after the first attack it crash.

Same problem with arbalet skill (swordsman)

**Comment by 0Lucifer0** [comment]
This is not a skill problem but à Monster problem i dont Know why this happen

**Comment by 0Lucifer0** [comment]
will be fix with #788
