### ISSUE TITLE
When being muted it still says 1 day

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#780]
When being muted it says 1 day instead of hour, also need a function to unmute/unban
![20160803-0-squizzy](https://cloud.githubusercontent.com/assets/19580091/17353538/fcaf519c-5983-11e6-9902-9750e1d7be80.jpg)

**Comment by MasterDomino** [comment]
we wont add function in my opinion its redundant and its kinda painful to code

**Comment by unknownforces** [comment]
But how else will we unban/unmute..?

**Comment by 0Lucifer0** [comment]
You can delete in database. On official There is no way (inGame) to unban people Its on an other interface. Btw It could be interesting to do something for remove but not nescessary ( i Will do It when Free Time)

**Comment by MasterDomino** [comment]
well like i said its painfull, but i had idea to implement something like removing old keys in log soo it will auto clean itself and the database would be smaller

**Comment by 0Lucifer0** [comment]
No we just need to remove the current entry before each sanction no need to have 2 same sanction at the same Time and for unban unmute we just need to remove the current sanction ;)

**Comment by MasterDomino** [comment]
yeah but i mean like for optimalization enable removing entries after some time so lts say the entries older than 30 days will get removed because theyre old, unles theyre still current/work soo the db would be cleaned and all longer bans will stay :P

**Comment by 0Lucifer0** [comment]
No... Thats the goal of log to keep history xD
