### ISSUE TITLE
Why you not want add system reputation 

### ISSUE THREAD

**Issue by valdek1999** [OpenNos/OpenNos#782]
Hello from Russia I want to ask why you are not adding the reputation system to opennos ,like I did ??? If the mob is your level or higher ,his reputation and Dignity is calculated by the formula = monster level * rate the reputation / (the number of people in group)
My system " rep " in opennos: https://youtu.be/6w5ArDOBwRM
Sorry for english....

**Comment by Uppermost** [comment]
We respect official nostale, we add reputation on mob only like official. Act 4 etc...
