### ISSUE TITLE
Long delays when I run 2 nostales

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#785]
As soon as I start the 2nd nostale, the skills are delayed really long and i get massive lags.. Seems the client can't handle it

**Comment by itemhack** [comment]
or maybe just cpu problem

**Comment by unknownforces** [comment]
Nah, my cpu can run 10 nostales on official without lag xD

**Comment by Uppermost** [comment]
Need some test.

**Comment by Uppermost** [comment]
mhmm with 2 account connected on opennos i have 30% of my CPU use, and i have test some skill with my sp etc and i have not this problem...

**Comment by unknownforces** [comment]
Hmm.. I tested earlier and I had same problem, like I said previously, I can run a lot of nostales on my laptop without lagging like this, I have 5 second delay on skills, but I will test on my other PC later (it's far better)

**Comment by 0Lucifer0** [comment]
I think You dont have enought upload...

**Comment by unknownforces** [comment]
It uses upload speed? I didn't know xd
that would probably be why xD

**Comment by 0Lucifer0** [comment]
Of course your client use upload speed in order to send Packet and opennos too

**Comment by unknownforces** [comment]
You mean on official? Cause I don't have lag issues on official..

**Comment by 0Lucifer0** [comment]
No You dont have this problem on official cause You dont host official files ^^
