### ISSUE TITLE
Character invalid

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#787]
On opennos we can't use é à è ù on and all accent on our nickname, (invalid character)
in official we can

maybe we can add this ?

**Comment by MisterBenju123** [comment]
And special character like ¤, ~ etc ..

**Comment by Uppermost** [comment]
done

**Comment by valdek1999** [comment]
yet" я "add???

**Comment by Uppermost** [comment]
No, is valid on the official ?

**Comment by unknownforces** [comment]
Why not just add every letter/symbol etc? I mean it's just a name.. I don't think it will kill if it is different than official xD 
It'd be cool to add symbols to your name

**Comment by 0Lucifer0** [comment]
Because client cant handle them and Will show 2 account With same name for exemple.

**Comment by MasterDomino** [comment]
character creation doesnt work
