### ISSUE TITLE
review astar/agro system

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#788]
we need to review/optimise astar/agro system

**Comment by MasterDomino** [comment]
[![https://gyazo.com/2a36d06d4e0f0676ded243f513efba14](https://i.gyazo.com/2a36d06d4e0f0676ded243f513efba14.png)](https://gyazo.com/2a36d06d4e0f0676ded243f513efba14)
[![https://gyazo.com/100ef572fafed497f61222715c89fc4a](https://i.gyazo.com/100ef572fafed497f61222715c89fc4a.png)](https://gyazo.com/100ef572fafed497f61222715c89fc4a)
running through act6 best way set speed to 59

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/18111477/4269814c-6f20-11e6-88cd-bf3fcc223ff3.png)
Sometime monster, is impossible to attack, because he are out the map I think.

**Comment by Uppermost** [comment]
Ok when your quit the map monster continue to want to attack you and it cause some latency
