### ISSUE TITLE
review broadcast to all/all on map

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#789]
review broadcast to all/all on map

**Comment by Kubixiorek** [comment]
What about this issue? Any progress?

**Comment by 0Lucifer0** [comment]
No. Its useless to use issue for question like that. There is our discord for question.

**Comment by Uppermost** [comment]
* #Bug  Map.broadcast in MonsterLife(Of a single mob) sometimes took 30% of cpu and it will be stuck (Martazza report)

**Comment by Uppermost** [comment]
What is the problem now? all is done?
