### ISSUE TITLE
Abuse.dat

### ISSUE THREAD

**Issue by Xhinoclas** [OpenNos/OpenNos#790]
Can be import the abuse.dat for removing some words from the characters name?

**Comment by Uppermost** [comment]
It can be a good idea, i wait Lucifer to that :P

**Comment by 0Lucifer0** [comment]
No Its a complete nonsens we use dat only for get usefull information

**Comment by Xhinoclas** [comment]
Ok but everybody can set "[GM]" or others words like "dick"

**Comment by itemhack** [comment]
it could be nice maybe not a dat but a table in the db ...
