### ISSUE TITLE
Error message when deleting character

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#791]
When I try to delete my character
![jyrjrjr](https://cloud.githubusercontent.com/assets/19580091/17466095/6f2f81e6-5d4a-11e6-9cad-9f3043efbd62.png)
 I get this error message and it doesn't delete the character.

**Comment by MasterDomino** [comment]
does it happen only once or you still cant remove the character?

**Comment by unknownforces** [comment]
It happened a lot before, but seems the issue is fixed ^^
