### ISSUE TITLE
Npc's are resting

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#796]
They are resting instead of standing up

![20160811-1-pussycat](https://cloud.githubusercontent.com/assets/19580091/17582454/207dd1cc-5fef-11e6-8b2a-e04ba303c388.jpg)

**Comment by 0Lucifer0** [comment]
@masterdomino what have You done xD

**Comment by MasterDomino** [comment]
fixed :D it was caused because someone doesnt know how ternary work xD, also doesnt it look cool?
