### ISSUE TITLE
Error while importing data, after last commits

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#797]
![unbenannt](https://cloud.githubusercontent.com/assets/17483888/17587134/97c38a16-5fc6-11e6-9522-9673bd5935f3.PNG)

**Comment by MasterDomino** [comment]
unpack files from latest updates it wont work because theres 550maps now not 534.

**Comment by 0Lucifer0** [comment]
Masterdomino we need to verify that map exist before import map type map ;)

**Comment by The-Art-Of-War** [comment]
Oh sry i forgot the new update :D

**Comment by MasterDomino** [comment]
done
