### ISSUE TITLE
add verification beetween login and world to know if account is connected

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#80]
we need too add verification beetween login and world to know if account is connected.
I suggest to use a socket beetween login and world in order to send the list of client on each connexion and disconnexion.

**Comment by chucktheripper** [comment]
we could create a pipe between those servers (WCF) and handle communication within this pipe

**Comment by chucktheripper** [comment]
Named Pipes: https://msdn.microsoft.com/en-us/library/bb762927.aspx

**Comment by chucktheripper** [comment]
a decision need to be made which of the technologies should be used, WCF or Pipes, actually there is another question like, where to host the wcf / pipe, will it be only login to game (authorization) or also game to game (channelwide talk) ?

**Comment by 0Lucifer0** [comment]
game to game is better :D
