### ISSUE TITLE
Dying infinitely

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#801]
So, I used skill on monster, my character froze and then wouldnt move and the mobs killed me, then it spam died like you can see in the picture (I had no chance to revive)

I tested again and when I died once, it counted as 2 deaths and -100 dignity, (the box to revive came up twice but i died once)

![20160812-0-squizzy](https://cloud.githubusercontent.com/assets/19580091/17613471/19dd1992-60a1-11e6-9439-3c851767ee1e.jpg)

**Comment by MasterDomino** [comment]
you can specify it under issue #711 its same

**Comment by unknownforces** [comment]
Wow, I looked at all issues and I missed that xd my bad
