### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by Skaterkeks** [OpenNos/OpenNos#804]
I see a spelling mistake on 

OpenNos.World/Resource/LocalizedResources.de.resx

When "Die Drop-Rate wurde erfolgreich geänder" the t at the end is missing.

**Comment by Uppermost** [comment]
Is normal for the moment deutsche member of the team are absent, we can give a good translation for this reason we let it empty.

**Comment by Skaterkeks** [comment]
I can translate too, i'm german :dancer:

**Comment by Uppermost** [comment]
You can sugest a commit on the section pull request

**Comment by Skaterkeks** [comment]
And how?
