### ISSUE TITLE
Add a trigger someone 

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#81]
add a way to send a packet to someone

**Comment by chucktheripper** [comment]
We need to find a solution to communicate between clients completely thread-safe (kinda async), the map or other instances arent allowed to touch the character / client / session in any way except threadsave HandlePacket

**Comment by 0Lucifer0** [comment]
we need to have this receivertype All, AllExceptMe, AllOnMap, AllOnMapExceptMe, OnlyMe, OnlySomeone

**Comment by 0Lucifer0** [comment]
broadcast is now from session with All, AllExceptMe, AllOnMap, AllOnMapExceptMe, OnlyMe. We need to find a way to add OnlySomeone (by CharacterId and by CharacterName)
