### ISSUE TITLE
Red dots showing up on map 

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#811]
When you go to a place like act 5.2 or act 6 (where red dots are shown on map for monsters), it shows it again if you go back to nosville ![20160818-1-style](https://cloud.githubusercontent.com/assets/19580091/17774206/d1953350-6595-11e6-893d-2459ecc97579.jpg)

**Comment by unknownforces** [comment]
?? why'd you close it

**Comment by MasterDomino** [comment]
because i dont have it
check after last commit

**Comment by unknownforces** [comment]
This issue has been around for over a month, it's still the same after latest commit

**Comment by MasterDomino** [comment]
soo how to get it, lol?

**Comment by Uppermost** [comment]
Same on official, we can't do nothing to this i think ^^

**Comment by unknownforces** [comment]
I just tested on official and it doesn't do it to me oO

**Comment by Uppermost** [comment]
Ok the problem on official is maybe fix, we need to compare packet from act 5 ^^

**Comment by MasterDomino** [comment]
we need to use "evnt 10 0 - 1 - 1" at the end of instance that will remove all existing events that happen in game for now we cant fix that because we would need to add instances

**Comment by unknownforces** [comment]
I tested this without event and it did it as well

**Comment by MasterDomino** [comment]
no i mean you need to send that packet to client to disable this dots and this packet is sent always at the end of instance soo we cant fix it for now

**Comment by Uppermost** [comment]
Ok some test and not reproductile, Is a client bug like official but occur very not often, I have try 10x whitout have this problem.

**Comment by MasterDomino** [comment]
Like i said its disabled by evnt 10 -1 1 packet we will need to send after
exiting the instance map

3 wrz 2016 22:09 "Uppermost" <notifications@github.com> napisał(a):
