### ISSUE TITLE
WigColor not permanent

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#812]
It disappears and goes back to original colour when you relog, this is intended or bug?
Edit : also shows the changed colour on character select, so i assume its a bug

**Comment by Uppermost** [comment]
No is a bug ^^

**Comment by MasterDomino** [comment]
okay i think its packetfault because actually it should save all to db properly
will check that asap

**Comment by MasterDomino** [comment]
soo i found out that adding GenerateEq packet in changemap fixes the issue but normally GenerateEquipment should be enough we need to check equip packet or use GenerateEq

**Comment by 0Lucifer0** [comment]
I dont think Its générate equipment but in and cinfo that have thèse information ;)
