### ISSUE TITLE
problem with last defence

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#815]
when casually running through act3 the changing of map causes LastDefence to get NullReferenced which is propably caused because we're on different map and monster that last attacked us gets unloaded

[![https://gyazo.com/f0fca1f6b25f48fd9318d2dbf333c225](https://i.gyazo.com/f0fca1f6b25f48fd9318d2dbf333c225.png)](https://gyazo.com/f0fca1f6b25f48fd9318d2dbf333c225)
[![https://gyazo.com/f43602e13a7ab2088805dadfd0e980ff](https://i.gyazo.com/f43602e13a7ab2088805dadfd0e980ff.png)](https://gyazo.com/f43602e13a7ab2088805dadfd0e980ff)

**Comment by unknownforces** [comment]
Is this reproducible ? Cause I don't get this issue xD

**Comment by MasterDomino** [comment]
go to act 3 and run through maps like with the ice spikes and to teleport on speed 59 is the best try

**Comment by unknownforces** [comment]
ice spikes are in act 4

**Comment by MasterDomino** [comment]
same problem exists for GodMode that was fixed still didnt found way to fix this

**Comment by MasterDomino** [comment]
i determined that its caused by GodMode command soo i think i will need to work on it :/

**Comment by 0Lucifer0** [comment]
seem's to be an astar problem.
