### ISSUE TITLE
AOE skills don't work

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#818]
I think skill system needs reviewing, some skills use other effects ontop of the skill you used like #639 (2nd issue)
and atm no aoe skills or debuffs work, only single target skills work.

**Comment by MasterDomino** [comment]
theres issue buggy skills its name tells much can you please add comment to this soo i will edit name of whole issue to Review skill system

**Comment by MasterDomino** [comment]
also i see that we made a little mistake soo this issue should be fixed now

**Comment by unknownforces** [comment]
You want me to close the other issue and comment it on the review system issue?

**Comment by MasterDomino** [comment]
This issue is already fixed xD

**Comment by unknownforces** [comment]
I know, I just didnt know what you meant by "add comment" xD
