### ISSUE TITLE
Add function of $Command 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#819]
When you write on the chat $Command in french, you can see some command like

invitation group
invitation mini-lands
invitation friend
...
etc

we can maybe add this and finish it on the 1.0.5

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/17831141/654a15f6-66e1-11e6-8a5f-d644afcfd450.png)

the problem is the text for this command is in function of the language...

**Comment by 0Lucifer0** [comment]
Its clientside if You have a correct client It works exactly like official

**Comment by Uppermost** [comment]
It not work on Opennos but it work on official example $Invitation NAME work fine on official but nothing appear on opennos :/

**Comment by MasterDomino** [comment]
we should leave that commands out of $Help command because actual help for it is in $Command

**Comment by 0Lucifer0** [comment]
I didnt understand firstly as You masterdomino... He talk about add command fonctionnalites

**Comment by MasterDomino** [comment]
yeah i know just i mean we should ignore all commands in $Command in command $Help

**Comment by 0Lucifer0** [comment]
Of course ;) $help is for admin. We Will need a fopt enum

**Comment by 0Lucifer0** [comment]
in fact we have no idea yet will see later.
