### ISSUE TITLE
monsters drop objects in random place

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#820]
monsters drop objects in random place sometimes beside character, soo you see death of monster and you stand like 3 cells away but items popup around you

**Comment by unknownforces** [comment]
Where does this happen? Cause I killed danders/pigeons and mobs using $Summon and the items always spawned where the mob died

**Comment by MasterDomino** [comment]
just kill any monster fast enought when he still walks towards you or just one shot him

**Comment by 0Lucifer0** [comment]
so when you shot it with distance attack it drop random on you and not random arround monster?

**Comment by Uppermost** [comment]
arround monster I think (90% sure)

**Comment by 0Lucifer0** [comment]
So Its normal xD

**Comment by Uppermost** [comment]
Maybe the drop distance is too high I don't know but yes is around the monster the drop ^^

**Comment by MasterDomino** [comment]
no the issue here is that it drops not in place where monster died but at the last calculated point

**Comment by 0Lucifer0** [comment]
point is calculated every 500ms... so it's near the same place are you sure there is a bug?
