### ISSUE TITLE
Monsters from $Summon respawning after death 

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#823]
Need to remove monster respawning from $Summon

**Comment by Uppermost** [comment]
Respawn ? Why respawn is tempory monster for event etc. We don't want the respawn of the monster there is AddMonster for that. Move 1 for monster can move and move 0 for the monster can't move

**Comment by unknownforces** [comment]
You missed what I said.. monsters already respawn xD I want to turn it off..  and how come you can go past 1 in numbers for move? xd

**Comment by Uppermost** [comment]
$Summon VNUM AMOUNT MOVE, 
* we want to remove the respawn of the monster with the $Summon command

**Comment by 0Lucifer0** [comment]
So thats not only the command but the respawn system that we need to review we need a bool in mapmonster respawn and if dead and not respawn delete Monster from the list
