### ISSUE TITLE
Add rarity -2 and -1 on drop object equip

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#826]
Add rarity on weapon , secondary weapon and armor because i drop always R0 on the monster.

**Comment by MasterDomino** [comment]
strange when it dropped for me it was rarified if im not wrong will test that

**Comment by Uppermost** [comment]
I have test in act 4 monster, On 7 weapons and 2 armor, all is R0

**Comment by MasterDomino** [comment]
use $RateDrop 1000 its easier maybe its only for act4 and i also noticed that rarity likes to stick to R0 in opennos this needs review(drop rarify)

**Comment by Uppermost** [comment]
I try on act 4 now to see if it work

**Comment by MasterDomino** [comment]
i tested it on sunny meadows and its alright just like i said it likes to stick to R0 and doesnt go to R- often

**Comment by Uppermost** [comment]
Ok just no chance, it work ^^

**Comment by unknownforces** [comment]
I think the rare chance is okay, but getting r5-7 seems to be high chance, maybe it could be lowered.

**Comment by Uppermost** [comment]
I reopen it because Rarity -1 and Rarity -2 is missing.
