### ISSUE TITLE
can't attack some of bigger enemies

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#829]
https://gyazo.com/f41c24937b4bea12b01e42eefe6126ba
when trying to attack you automatically cancel the attack using ranged attack doesnt change anything

**Comment by 0Lucifer0** [comment]
Is It possible that It dépends on the Monster size ?

**Comment by 0Lucifer0** [comment]
Look in debug why It send cancel

**Comment by MasterDomino** [comment]
not sure sometimes it does happen other times doesnt its like lottery

**Comment by MasterDomino** [comment]
okay its caused because of that line
if (ski != null && Session.Character.Mp >= skill.MpCost)
it jumps straight into else and cancels

**Comment by 0Lucifer0** [comment]
if (ski != null && Session.Character.Mp >= skill.MpCost) ?

**Comment by MasterDomino** [comment]
nope if (skills != null) doesnt allow it to go through and notcancel is still false

**Comment by 0Lucifer0** [comment]
If notcancel is false that mean we cancel ^^ so we need to look why Its not true ><

**Comment by MasterDomino** [comment]
because it doesnt go through if (skills != null) soo in this example skills are null idk why xD

**Comment by 0Lucifer0** [comment]
look at skill assignment
