### ISSUE TITLE
Add all npc function teleport and get item function

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#832]
All npc to teleport like labo map (map 42), and add npc with delay to have item, like map 2,4 etc...

For item we can find it on monster.dat

I have too forget well npc
![image](https://cloud.githubusercontent.com/assets/15254478/17950010/b5509686-6a58-11e6-90c4-b956f2be1847.png)

And other like that, teleport you only if you have XX amount of apple 

![image](https://cloud.githubusercontent.com/assets/15254478/17974138/247b3250-6ae5-11e6-9fe9-b12ee7bb9c0f.png)

**Comment by Uppermost** [comment]
Need to add : 
Teleporter NPC functions | Statut : Not done, fix npc like blue teleporter (have again a dialog...) etc.
Have object with NPC      | Statut : Partielly done, missing fail rate, time needed to continue when you try to spam and fix npc like well ( you need item to use it )

**Comment by unknownforces** [comment]
and Evil Circle (teleport npc) 
Map 80 X 69 Y 68

**Comment by Uppermost** [comment]
Yes unknowforces I have forget this thanks to the report xD

**Comment by MasterDomino** [comment]
same as opening issue called "code all items"
