### ISSUE TITLE
portal distance issue

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#834]
if you use portals several times on high speed (eg. 59) the distance will get set to huge numbers like: 220, 198, because of that walk packet has issues sometimes with distance

**Comment by unknownforces** [comment]
You can close this, I tested on my home internet and it works fine xD

**Comment by 0Lucifer0** [comment]
No It dont Its just disabled

**Comment by unknownforces** [comment]
Oh, I thought this was to do with the issue I talked about yesterday on discord, my bad xD
