### ISSUE TITLE
Add experience in function of level monster / level user 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#836]
Example on opennos i win 0.01% 1/2 on "René monster from LoD" at the level 89.

On official you win very very less xp because monster level is 75. I drew the following conclusion, If characterlevel is +10 to the level monster, you win very less xp i don't know the for moment the amount but I think the xp is divide by 2 or 3.

**Comment by 0Lucifer0** [comment]
Already an issue for that

**Comment by Uppermost** [comment]
I have don't find that
