### ISSUE TITLE
Error while compiling project

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#837]
If i try to compile the project it shows me the error that, "OpenNos.Handler.dll" and "OpenNos.GameObject.dll" dont exist :D

![unbenannt](https://cloud.githubusercontent.com/assets/17483888/18017917/380207dc-6bd4-11e6-9d40-6d37a43e4ef8.PNG)

**Comment by Uppermost** [comment]
fix now
