### ISSUE TITLE
review anti-speed hack

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#841]
It dcs almost instantly when I use speed hack at high speeds
Shouldnt it be an exception not to kick admins or something?

**Comment by MasterDomino** [comment]
prediction of movement is proper, we need to find a way to avoid badly send packets

**Comment by unknownforces** [comment]
Well, not sure if relevant but i meant $Speed not speed hack*

**Comment by MasterDomino** [comment]
yeah i know but i mean my method of fixing it wasnt the best but for now we used temporary fix
