### ISSUE TITLE
Some problems with Veichles

### ISSUE THREAD

**Issue by DarkCacos** [OpenNos/OpenNos#843]
This is a list of problems that I found:
1) If you are not already transformed into an sp and you put yourself on the vehicle, if you press G it begin the trasformation into the sp.
2) If you are transformed in an sp and put yourself on the vehicle, the wings remains.
3) If you attack the monsters when you are on a veichles, the server return an error and your character froze. (It happened with the mage's sp, but with those of the swordsman seems to attack without going into error.)
4) If you use the command $ChangeSex when you are on a veichle, the graphic does not change.

**Comment by 0Lucifer0** [comment]
Yep we Know we Will fix that ;)
