### ISSUE TITLE
skills reset when entering vehicle

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#845]
thanks for HardFoxy for telling us about it. when you use skill and transform to vehicle it will reset the skill cd's

**Comment by 0Lucifer0** [comment]
only graphics right? is it the same on official?

**Comment by MasterDomino** [comment]
this bug appears randomly

**Comment by Uppermost** [comment]
I don't have the problem now, I close reopen if this bug reappear.
