### ISSUE TITLE
Player can invite you if monster attack you

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#847]
This bug appear if you are attacked and player wait 20 seconds for example and player can invite you if he wait hang you do attacked

**Comment by MasterDomino** [comment]
propably caused by GodMode command needs testing

**Comment by Uppermost** [comment]
Reopen because I have test whitout godmod and I can invit the player in group after 20 secs.

**Comment by MasterDomino** [comment]
also in issue but seems to be fixed
