### ISSUE TITLE
Problem with exchange when player is in shop

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#850]
On official you can invite player in shop if the player is in shop and if he accept, it remove the shop etc,
When you try to invite in shop a player you receive the msg "The player have blocked exchange invitation"
the text is wrong we don't want to have this message

**Comment by MasterDomino** [comment]
just change the message

**Comment by Uppermost** [comment]
The problem is, there are nothing message about this things I don't understand why blocked exchange is here when you try to exchange with a player already in shop

**Comment by MasterDomino** [comment]
there is ALREADY_EXCHANGE in refused packet soo theres all that you need
