### ISSUE TITLE
GodMode problem

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#854]
Sometime when you try to attack why $GodMode command, you can't move

(Randomly)

**Comment by DarkCacos** [comment]
In the past I had sometimes leave the character afk in Krem with the active GodMode, so the mosquitoes respawned and returned to hit me without kill me. But when I returned on the game, many times I found myself with the character blocked.
It may be the same problem?

**Comment by MasterDomino** [comment]
Already in issue #815

**Comment by 0Lucifer0** [comment]
not the same issue in fact.

**Comment by MasterDomino** [comment]
but its caused by this, also if it means that you cant attack look at vs and send the error info

**Comment by MasterDomino** [comment]
need to fix #788 firstly needs review

**Comment by Uppermost** [comment]
Sometime when you try to attack why $GodMode command, you can't move

(Randomly) caused by issue #883 I'm almost sure.
