### ISSUE TITLE
Problem when you insert some name in a private shop

### ISSUE THREAD

**Issue by DarkCacos** [OpenNos/OpenNos#855]
When you insert some strange name into a private shop (Maybe because of the special characters or maybe the lenght, or other, I don't know), the world server return an error.

I tried with "Essence of Lime & Ru" and "Essence of Lime $ Ru".

[Screenshot](https://s4.postimg.org/fjplkvxnx/Problem_Shop_Name.png)

**Comment by 0Lucifer0** [comment]
seem's fix since my last update of crypto 
https://gyazo.com/d6d5464059581ec60b8178ba050b1999
