### ISSUE TITLE
Item upgrade above the Standard (+10)

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#866]
![093e02e7a2fc09ba33d389c91be13655](https://cloud.githubusercontent.com/assets/17483888/18107859/07346d96-6f0a-11e6-993b-a2131a1013a8.png)

For example $CreateItem 4904 8 "100"

**Comment by Uppermost** [comment]
Is not a problem because is for GM :/, GM are not stupid and set rarity so 10 and is not a problem for the game, we need to change the value because this command is used by other object like $CreateItem 904 15 0
If we set to 10 you can't have sp +15 xD

**Comment by 0Lucifer0** [comment]
We can set the max by item

**Comment by The-Art-Of-War** [comment]
Ah i understand but its a bit weird :D

**Comment by Uppermost** [comment]
Ok need to add, weapon, secondary weapon and armor, but maybe in the future stuff +11 ? :/ xD

**Comment by MasterDomino** [comment]
its GM command so we should not care about max upgrade :)

**Comment by 0Lucifer0** [comment]
Some problem may happen With other function if the item overflow the max

**Comment by 0Lucifer0** [comment]
Its like if You change your level in database by something over 99 It Will crash.

**Comment by MasterDomino** [comment]
done. latest commit.
