### ISSUE TITLE
I've problem about "İd and password is wrong"

### ISSUE THREAD

**Issue by Brvortex** [OpenNos/OpenNos#870]
Guys My 2 friend and i trying to make a server with my friends but we are have a problem to like title.
Now I am trying to enter server but this fault is coming to i trying everytime. İf someone is can help me please add me of skype, my adress is legendsgoktug please guys need a programmer hand.

http://i.hizliresim.com/lEjbBB.png  <-- PICTURE

**Comment by earthnash** [comment]
Check client IP and port

**Comment by Brvortex** [comment]
Are u kidding to me You thinking am i a idiot? Man I did everything i did check to all informations but
isn't work -_-

**Comment by 0Lucifer0** [comment]
You dont use correct client... i s'impose You get a random launcher on internet right? By the way issues is for real issues not Any problem You have when You dont Know How to install. There is discord for that.

**Comment by Brvortex** [comment]
Yes, I got "Patcher v1.5.0000 r 3 - OMG" My old times it is was working but now my friend and i get same problem

**Comment by 0Lucifer0** [comment]
Just to be sure can You Copy your Channel configuration line ;)

**Comment by Brvortex** [comment]
<appSettings>
    <add key="LoginPort" value="4001" />
    <add key="language" value="en" />
    <add key="ClientSettingsProvider.ServiceUri" value="" />
  </appSettings>
  <Servers>
    <server Name="S1-OpenNos" WorldPort="1337" WorldIp="25.91.208.61" channelAmount="1" />

**Comment by 0Lucifer0** [comment]
Your port 1337 is open from outside ?

**Comment by Brvortex** [comment]
Oh I have update of nostale de and i am updating now.

**Comment by 0Lucifer0** [comment]
There is a problem With your port 1337 It is not open

**Comment by Brvortex** [comment]
But My server is hamachi bro

**Comment by Brvortex** [comment]
Ok man I am tryig now thx for the helps

**Comment by Brvortex** [comment]
Lucifer if u there i hope u can understand that. When i start login and world server i am getting "General Error Server" with red words can u help me about that if u are not disband?

**Comment by 0Lucifer0** [comment]
Read the error read the readme (the Help is in...)

**Comment by Brvortex** [comment]
Can you give me the link because you have so more issue.

**Comment by 0Lucifer0** [comment]
I never Tell You to read issues just your error message... And the readme

**Comment by Brvortex** [comment]
Bro, When i see red words it is closing so fastest then i cant say anything about words in red things

**Comment by Brvortex** [comment]
Only I can see to title i mean to "general error server"

**Comment by 0Lucifer0** [comment]
There is a log file... Btw this is because You already have something on port 80 (Skype,Apache...)

**Comment by Brvortex** [comment]
Oh Yes u said true wait i doing

**Comment by Brvortex** [comment]
Thanks man this is was about on skype because skype is using "port 80" Now Thats all working than u
thanks man really thanks

**Comment by 0Lucifer0** [comment]
Next Time read the readme.
