### ISSUE TITLE
character block when you press space or skill + c in the same time

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#872]
When you are sitdown, and monster attack you, you rest seated, we want to take off the character if attacked by a monster

**Comment by itemhack** [comment]
and if you press space (or a skill) + c in the same times the character will rest stucket too

**Comment by Uppermost** [comment]
Not solved : and if you press space (or a skill) + c in the same times the character will rest stucket too

Need to find an other way

**Comment by Uppermost** [comment]
Is fixed but now you can sitdown when you use skill (like official)
