### ISSUE TITLE
Wrong image in group character list when transformed in a Veichle.

### ISSUE THREAD

**Issue by DarkCacos** [OpenNos/OpenNos#873]
When a character in a group transforms in a Veichle, his "avatar" is updated in that of the veichle only for a fraction of a second, then it turn back to normal.

[Screenshot](https://s15.postimg.io/koh2fs01n/Wrong_Group_Image.jpg)

**Comment by Uppermost** [comment]
Is the same on official DarkCacos xD @0Lucifer0 close ?

**Comment by Uppermost** [comment]
Ok same on official close for the moment, maybe fix later but is exactly the same on official ^^'
