### ISSUE TITLE
Add drop in inventory when you kill boss

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#877]
![image](https://cloud.githubusercontent.com/assets/15254478/18149736/4adf55be-6fe2-11e6-96ff-f7c017be9587.png)
Like act 4 when you kill monster type boss they drop are directly inside you inventory ( say 10 ) exactly same like act 4 :)

**Comment by 0Lucifer0** [comment]
all boss should have a parametter like type or something else that tell that it's a boss :)

**Comment by Uppermost** [comment]
Yes the green point is for boss monster, just need to find how to have this green point.

**Comment by Kyoraku** [comment]
I've done a data mining in the monster.dat and concluded that Elite Monsters have the "ETC 2052" i'm working on finishing the task it will soon be resolved but there too many unique values int ETC[1] so need to hard code a little bit :D

**Comment by Uppermost** [comment]
fix by Kyoraku
