### ISSUE TITLE
Problem with accent etc (language problem)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#878]
![image](https://cloud.githubusercontent.com/assets/15254478/18150834/2f3dffba-6fea-11e6-894d-e0f95d8437ba.png)
Problem after my latest commit... I don't know why

Sorry, my bad. I have only change in import console wtf?

I think is your change @0Lucifer0

**Comment by 0Lucifer0** [comment]
Only for language ? When You write directly It show accent ?

**Comment by Uppermost** [comment]
Yes only for key, when I write directly it work

**Comment by 0Lucifer0** [comment]
Ok so Its language issue ;)

**Comment by Uppermost** [comment]
Have you an idea to fix it ? I don't know the cause

**Comment by 0Lucifer0** [comment]
Its language method or resx file Will see

**Comment by Uppermost** [comment]
After test, is a problem with byte[] StrBytes = System.Text.Encoding.UTF8.GetBytes(str);
I have test with the older code and it work.

**Comment by 0Lucifer0** [comment]
No Its not the encrypt is good but need to report on language
