### ISSUE TITLE
Guys Can İ change [Crew] to [GM] or [OY]

### ISSUE THREAD

**Issue by Brvortex** [OpenNos/OpenNos#879]
Guys Can İ change [Crew] to [GM] or [OY]

Please I want to do guys Someone can help me ?

**Comment by Uppermost** [comment]
You can't is on the client

**Comment by Brvortex** [comment]
Oh oky thax man

**Comment by Brvortex** [comment]
Oh bro i have 1 question more my server is release version and i can open server in tr launcher?

**Comment by Uppermost** [comment]
I think you can yes ^^
