### ISSUE TITLE
When i write russian words in chat write other words

### ISSUE THREAD

**Issue by valdek1999** [OpenNos/OpenNos#880]
![image](https://cloud.githubusercontent.com/assets/17438672/18212581/a47f0e82-714c-11e6-88a0-9e46909c6370.png)
When i write russian words in chat write other words

**Comment by 0Lucifer0** [comment]
because you use de client.

**Comment by valdek1999** [comment]
Excuse me then why is such a problem in previous versions it was not ?

**Comment by valdek1999** [comment]
Excuse me then why is such a problem in previous versions it was not ?

**Comment by 0Lucifer0** [comment]
ah so that's supported by client but your default encoding of your computer is bad ><

**Comment by 0Lucifer0** [comment]
does it work now?
