### ISSUE TITLE
Shop bug when I use ctrl+z 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#883]
![image](https://cloud.githubusercontent.com/assets/15254478/18224523/bedcd156-71d8-11e6-9c12-e5535b8111d6.png)
I see only the name of my shop and it's impossible to close it...

**Comment by Uppermost** [comment]
PS : Same problem on official but we can optimise it ;)

**Comment by Dactylr** [comment]
You can put items for 0 Gold in Shops:
[0 Gold Shop](http://sendvid.com/tuxyowx7)
