### ISSUE TITLE
when use teleport your speed transport = 0;

### ISSUE THREAD

**Issue by valdek1999** [OpenNos/OpenNos#886]
![image](https://cloud.githubusercontent.com/assets/17438672/18225569/48d95de6-71fe-11e6-939f-1ab024ca8cdd.png)

**Comment by 0Lucifer0** [comment]
You mean You cant move anymore ?

**Comment by valdek1999** [comment]
No if you use teleport your speed become with 21 on 15

**Comment by valdek1999** [comment]
i say about speed for transport

**Comment by 0Lucifer0** [comment]
yes i think it's like that every time the inventory is reloaded will see. We will need to delete LastSpeed

**Comment by valdek1999** [comment]
Yet i think problem not in launcher when write russian letter

**Comment by valdek1999** [comment]
when i was in german in old version i can use я б г д ж з и and other letters but now write latins letter you can check it problem

**Comment by 0Lucifer0** [comment]
are you sure you are up to date and please use the correct issue... i ask you yesterday if it was working since my update

**Comment by valdek1999** [comment]
Ok now update  opennos check russian words

**Comment by 0Lucifer0** [comment]
You mean that It works ?

**Comment by valdek1999** [comment]
![image](https://cloud.githubusercontent.com/assets/17438672/18226104/81fae2d6-720b-11e6-87f3-6221a62a239f.png)
![image](https://cloud.githubusercontent.com/assets/17438672/18226107/86342e5c-720b-11e6-834a-24e8a371ab95.png
yes,russian letter not work

**Comment by 0Lucifer0** [comment]
Are You up to date ?
