### ISSUE TITLE
Disconnecting at the portal 

### ISSUE THREAD

**Issue by Kyoraku** [OpenNos/OpenNos#892]
When you disconnect and you're at the portal you'll be stack the next connection. Can't move, either if you create another character.

**Comment by MasterDomino** [comment]
I never had it happen when i was logging out, please can someone test it and tell the results?

**Comment by unknownforces** [comment]
I think he means when you disconnect not log out, but i've dced on portal a lot of times and i had no issues after i logged back in so idk

**Comment by chucktheripper** [comment]
i couldnt reproduce it
