### ISSUE TITLE
Zerk hitting twice but with 1 normal hit

### ISSUE THREAD

**Issue by unknownforces** [OpenNos/OpenNos#898]
For example ; numbers come up twice (1 hit 1 miss) but i only use 1 normal hit
it hits 3 times sometimes too
![20160906-10-squizzy](https://cloud.githubusercontent.com/assets/19580091/18254912/66c32aaa-73e6-11e6-9c9b-3735b9c8dab9.jpg)

it also doesnt do animation that it hits twice

**Comment by unknownforces** [comment]
Not just zerk btw, happens in WK too. it hits 4 times with a skill that is suppose to only hit twice xD

**Comment by unknownforces** [comment]
When I use WK final, etc it misses with 1 hit sometimes and the rest hit, but the hits are suppose to be just 1 hit divided into a lot.

**Comment by 0Lucifer0** [comment]
still happen? or fixed with yesterday's commits?

**Comment by unknownforces** [comment]
Yeah it still happens

**Comment by Uppermost** [comment]
Again not solved

**Comment by Uppermost** [comment]
This packet is send 2x

walk 164 110 1 11
cond 1 1 0 0 11
walk 167 108 0 11
cond 1 1 0 0 11
ncif 3 5849
st 3 5849 70 0 100 100 11429 4429
walk 168 109 1 11
cond 1 1 0 0 11
walk 166 106 0 11
cond 1 1 0 0 11
ncif 3 5849
st 3 5849 70 0 100 100 11429 4429
ncif 3 5849
st 3 5849 70 0 100 100 11429 4429
u_s 0 3 5849
ms_c 0
ct 1 1 3 5849 10 -1 900
su 1 1 3 5849 900 8 11 3500 166 106 1 79 2344 0 0
su 1 1 3 5849 900 8 11 3500 0 0 1 58 2344 5 0
ncif 3 5849
walk 165 103 1 11
st 3 5849 70 0 58 100 6741 4429
cond 1 1 0 0 11
stat 18513 18613 3327 3327 0 256
su 3 5849 1 1 0 9 11 1006 0 0 1 0 100 0 0
sr 0
walk 166 104 0 11
u_s 0 3 5849
cond 1 1 0 0 11
ms_c 0
ct 1 1 3 5849 10 -1 900
su 1 1 3 5849 900 8 11 3500 166 104 1 58 0 1 0
su 1 1 3 5849 900 8 11 3500 0 0 1 58 0 5 0
walk 164 101 1 11
ncif 3 5849
cond 1 1 0 0 11
st 3 5849 70 0 58 100 6741 4429
walk 166 103 0 11
u_s 0 3 5849
cond 1 1 0 0 11
ms_c 0
sr 0
ct 1 1 3 5849 10 -1 900
su 1 1 3 5849 900 8 11 3500 166 103 1 58 0 1 0
su 1 1 3 5849 900 8 11 3500 0 0 1 58 0 5 0
walk 165 100 1 11
cond 1 1 0 0 11
ncif 3 5849
walk 166 102 1 11
u_s 0 3 5849
st 3 5849 70 0 58 100 6741 4429
cond 1 1 0 0 11
ms_c 0
sr 0
ct 1 1 3 5849 10 -1 900
su 1 1 3 5849 900 8 11 3500 166 102 1 38 2344 0 0
su 1 1 3 5849 900 8 11 3500 0 0 1 17 2344 5 0
walk 168 105 0 11
cond 1 1 0 0 11
ncif 3 5849
sr 0
walk 167 104 1 11
u_s 0 3 5849
st 3 5849 70 0 17 100 2053 4429
cond 1 1 0 0 11
ms_c 0
ct 1 1 3 5849 10 -1 900
su 1 1 3 5849 900 8 11 3500 167 104 1 17 0 1 0
su 1 1 3 5849 900 8 11 3500 0 0 1 17 0 5 0
walk 168 106 1 11
cond 1 1 0 0 11
walk 167 104 1 11
u_s 0 3 5849
sr 0
cond 1 1 0 0 11
ms_c 0
ct 1 1 3 5849 10 -1 900
su 1 1 3 5849 900 8 11 3500 167 104 1 17 0 1 0
su 1 1 3 5849 900 8 11 3500 0 0 1 17 0 5 0
ncif 3 5849
st 3 5849 70 0 17 100 2053 4429
stat 18413 18613 3327 3327 0 256
su 3 5849 1 1 0 9 11 1006 0 0 1 0 100 0 0
sr 0
u_s 0 3 5849
ms_c 0
drop 1046 585804 166 103 820 0 0 -1
lev 99 0 18 100640 2081909000 185000 2362236 200 0 50 949560
ct 1 1 3 5849 10 -1 900
su 1 1 3 5849 900 8 11 3500 167 104 0 0 2344 0 0
sr 0
stat 18439 18613 3327 3327 0 256

**Comment by Uppermost** [comment]
new issue
