### ISSUE TITLE
Big bug on wear equip

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#901]
https://gyazo.com/439c31b2c7964aa86b2bc0ee246c40b8 
https://gyazo.com/ff0b5a32c825537223f559ccd75fabda
You click the item take some seconds to appear on item inventory and when you change weapon, you want to move to have the change

* I'm on the latest update
* This problem appear very often on my account. (But sometime I have not this problem, randomly problem)

Ps : There are no exception error.

**Comment by unknownforces** [comment]
Works ok for me?

**Comment by Uppermost** [comment]
Random bug

**Comment by Uppermost** [comment]
[16:47] Martazza: 

<<< #BUG WeaponLoaded
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenNos.GameObject.Character.WeaponLoaded(CharacterSkill ski) in C:\Users\Administrator\Desktop\Opennos\OpenNos.GameObject\Character.cs:line 1795
but line 1795 is just a
  else return true;

Maybe is the problem I don't know

**Comment by 0Lucifer0** [comment]
that's because it's an old log so line change^^

**Comment by 0Lucifer0** [comment]
seem's to be since @chucktheripper update

**Comment by chucktheripper** [comment]
this problem is caused because no packet is sent after the wear packet

**Comment by Uppermost** [comment]
fix
