### ISSUE TITLE
About Blue Name

### ISSUE THREAD

**Issue by Brvortex** [OpenNos/OpenNos#908]
Guys I have one question more. How I can make a blue name i hope i can do?Like that

http://i.hizliresim.com/88PqAA.jpg

**Comment by Uppermost** [comment]
Is not here for issue, and you want some admiration like official or change in database...

**Comment by Brvortex** [comment]
Where is in database I wondering that man only that.

**Comment by Uppermost** [comment]
Character > Compliment et change the default value by 50 for example

**Comment by Brvortex** [comment]
Thanks bro
