### ISSUE TITLE
fix cooldown system

### ISSUE THREAD

**Issue by MasterDomino** [OpenNos/OpenNos#910]
we need to implement server sided cooldown system, no client sided cooldown existing.

**Comment by Ciapa1** [comment]
I'll look at it when back in Germany. Should be fairly simple to implement(for each session skill, store the timestamp of last successful use and check/enable it from there

**Comment by 0Lucifer0** [comment]
It was already done but need to fix It I think we use ienumerable and not list Will see ;)

**Comment by Uppermost** [comment]
#1505

**Comment by Ciapa** [comment]
Will be fixed when hitqueue is merged to master

**Comment by MasterDomino** [comment]
got fixed after merge
