### ISSUE TITLE
So high magician damage

### ISSUE THREAD

**Issue by salucroso** [OpenNos/OpenNos#911]
With a lvl 45 magician with lvl 15 wand r0+0, no fairy and low red magician i do a damage about 10~19k with some skills.
![20160907-0-s3rl](https://cloud.githubusercontent.com/assets/22038995/18292930/48394ccc-7490-11e6-82b9-3cb8a2121fd3.jpg)
![20160907-3-s3rl](https://cloud.githubusercontent.com/assets/22038995/18292931/4839f96a-7490-11e6-8a8d-6cfe4b209189.jpg)
![20160907-4-s3rl](https://cloud.githubusercontent.com/assets/22038995/18292932/48409d42-7490-11e6-86b2-e7a8815dd46e.jpg)

**Comment by 0Lucifer0** [comment]
Already issue
