### ISSUE TITLE
Problem with some monster

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#916]
![image](https://cloud.githubusercontent.com/assets/15254478/18329110/3e8cffa8-7552-11e6-8b0f-cc6385d8c4bf.png)

They monster, and other monster like that attack, but on official they monster can't attack you...

**Comment by Kyoraku** [comment]
in MonsterType there a type how is Peapod it will generate "Pii" and don't hint just waiting for MonsterType to be added to fix this too :D

**Comment by MasterDomino** [comment]
You can fix it and push into your fork it will automatically be added to your pr ;) thanks for your work

**Comment by 0Lucifer0** [comment]
Pii summon is a skill right ?

**Comment by MasterDomino** [comment]
yes(buff propably) that toggles on on death

**Comment by 0Lucifer0** [comment]
Thats what i remember ;)

**Comment by Kyoraku** [comment]
I ment by Pii is thes monsters xD 
![image](https://cloud.githubusercontent.com/assets/18296580/18360835/8b996ade-75f7-11e6-9329-9b7e65700e4e.png)

**Comment by 0Lucifer0** [comment]
Yes but that is the effect of the skill of the pii pod

**Comment by Uppermost** [comment]
fix
