### ISSUE TITLE
Optimisation SP and JobLevel (XP)

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#918]
* You can XP your JobLevel with your SP if you sp is Level 20+ (You XP only 50% of the XPJOB and not 100% if SP is equiped.)

**Comment by 0Lucifer0** [comment]
Always 50% ? There is an issue about that ^^

**Comment by Uppermost** [comment]
Yes the jobxp is divide by 2 when sp is quiped, and I have not see the issue sorry

**Comment by 0Lucifer0** [comment]
#692
