### ISSUE TITLE
Problem with tradable item

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#930]
item like weapon etc is not tradable (problem)

**Comment by 0Lucifer0** [comment]
replace this kind of line  if ((iteminfo.EquipmentSlot == (byte)EquipmentType.CostumeHat || iteminfo.EquipmentSlot == (byte)EquipmentType.CostumeSuit || iteminfo.EquipmentSlot == (byte)EquipmentType.WeaponSkin) && !DelayUsed && !inventory.ItemInstance.IsUsed && IsTradable)
                   by something is !DelayUsed && iteminfo.EquipmentSlot == (byte)EquipmentType.CostumeHat || iteminfo.EquipmentSlot == (byte)EquipmentType.CostumeSuit ... and the else by an elseif(costume or other item that you want to block)
