### ISSUE TITLE
 Exchanges bugged

### ISSUE THREAD

**Issue by salucroso** [OpenNos/OpenNos#934]
Sometimes items or gold dont arrive to the other person or dubling.

**Comment by chucktheripper** [comment]
is there any message or anything which you can offer to reproduce the Problem?

**Comment by chucktheripper** [comment]
I found a problem in VerifyExchange, Item assumed in cSession2 is in cSession1...

**Comment by Martazza** [comment]
You can force exchange if you send:
https://i.gyazo.com/bbb3385deba6ec6bf925e649230febf5.gif
https://gyazo.com/bbb3385deba6ec6bf925e649230febf5

**Comment by Uppermost** [comment]
#1151

**Comment by Digitalis87** [comment]
https://gyazo.com/9ab87244bfbc00b915e200ba3839f201

After trading, the reciever (the one who don't send the Trade) is disconnected.
Items are duplicated.
Problem is not everytime.

**Comment by Uppermost** [comment]
PS one trouble cause disconnection and duplication.

**Comment by Digitalis87** [comment]
As Uppermost asked, details about duplication.

After trading something if the **reciever** is disconnected, then items will be duplicated.
The bug looks not happend if we trade money. 

NOTE: Dident try yet with other item than from EQUIP. inventory.

**Comment by Uppermost** [comment]
Need to be fixed asap

**Comment by Uppermost** [comment]
GalaxyCat : 

When you trade with someone, you have to give him for example 10 000 Gold and a random item. Then you have to klick trade first, after you, the second person has to click trade. Then when you click the second time trade to complete it, the person who wants the item gets an DC and you have to relog to, to be able to trade again. After loggin in again, the second person has the items from the trade, but you have them also.

**Comment by chucktheripper** [comment]
After a few changes, the Exchange works perfectly except a bug which is contained by another issue
