### ISSUE TITLE
not LogIn -  when two players at the same time Login  can't one player login

### ISSUE THREAD

**Issue by ShidoEPVP** [OpenNos/OpenNos#940]
Gif 1: https://gyazo.com/82293fc32ab4705eb7c87c0035d549c8

Gif 2: https://gyazo.com/70747edc9ce6d604142e4d50be4c2822

**Comment by Uppermost** [comment]
Two player on the same computer? If yes I think is a security (Chucktheripper work) to miss double connect on the same account
