### ISSUE TITLE
add the reset of combo when you don't attack monster after like 10 seconds 

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#946]
Reset combo system when you don't attack monster (after like 10 seconds) the combo is reset

**Comment by 0Lucifer0** [comment]
Its volonteer and after 3 second

**Comment by Uppermost** [comment]
No my bad, we want to fix it because it doesn't work xD

**Comment by 0Lucifer0** [comment]
in fact it's caused by cooldown problem :)
