### ISSUE TITLE
[GLOBAL]remove auto-generated files

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#95]
The auto-generated files from the EDMX should be excluded from source control, it makes the commits less clear. Check up if there are files like this in the project.

**Comment by Ciapa1** [comment]
This is partly done. If auto-generated cs files should be removed aswell, one either has to execute the T4-Template before building, or add TemplateTransformation to the Pre-Build-Events.

**Comment by chucktheripper** [comment]
re-add the sql script itself, actually this issue was created because of confusing auto-generated files which obfuscated the change itself.

**Comment by Ciapa1** [comment]
I didn't found an easy way to execute the T4-Template before building. Does someone know a way to do this which doesn't rely on external programs? If not, this should probably be closed, and one has to execute it by hand after cloning the Repository.

**Comment by chucktheripper** [comment]
the problem is the multilinguality of the auto generated files by the t4 template, maybe we can configure that to universal english or we force 0lucifer0 to use the english version of visual studio :P

**Comment by 0Lucifer0** [comment]
i now use vs in english
