### ISSUE TITLE
Problem with $SkillAdd

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#951]
https://gyazo.com/39c6df117e3748b382fc2f2baeea67e4

Sometime, this problem appear, and you can't use this skill

**Comment by Uppermost** [comment]
It's caused after class verification. After remove, maybe we need to re add skill verification to fix that?

**Comment by 0Lucifer0** [comment]
this is caused by casting id >< you can re add skill if you want yes but it will do the same with SP skill when no sp ><
