### ISSUE TITLE
Review monster, skill...

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#953]
- [ ]  Sometime monster stop to attack you for a few moment (watch the GIF) and do anything (Priority if possible)
  https://gyazo.com/af0c6dd6dd0548e3e9c28029d3afb849

- [ ] Monster don't attack and don't have basic skills. https://gyazo.com/f354a41379879fbf3956004d46327714

- [ ] Monster have the effect of the attack but nothing animation.. (Not everyone, try with Kenko for example at Fernon.)

- [ ] Player one is focus by monster and Player two is beside, player one dead, after revive monster don't attack the player two but go search player one.

- [ ] Lower the speed when the monster is far to you (For the moment monster follow you too much faster)

- [ ] On caligor for example, he inflict you damage but it's not displayed for some skills. On official you can show of much damage you get.

https://gyazo.com/51f138de993d9cc82391d15562bbfafa
(I use potion for not die but you can see nothing about damage displayed)

**Comment by MasterDomino** [comment]
next one to focus on :D
