### ISSUE TITLE
In act 4 inventory can't never be full

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#954]
Your inventory is never full in act 4 we need to add item to "parcel" because for the moment when your inventory is full, you continue to have item from monster and your character is blocked if we need to do like official just add parcel 20 items max, and after this say Not enough place or just Add a message for the moment to say you don't have enought inventory place
Need to add the message in act 4 when you receive a parcel "You have got an item from the geant monster" (msg 0)
Link to issue #955 we need to finish it before.

**Comment by 0Lucifer0** [comment]
just in waiting add something that block if inventory full and a message like InventoryFullWaitParcel(without adding it to language it will be deleted when done ) :)

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/18477500/23ccc0e2-79ce-11e6-9fbc-397e4ae16d72.png)
