### ISSUE TITLE
All untradable item after first use doesn't work

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#957]
![image](https://cloud.githubusercontent.com/assets/15254478/18469166/61b2745a-79a7-11e6-9e8a-b924a0334eb7.png)
When you try to equip a pairy you get an exception message.

**Comment by DarkCacos** [comment]
I just synchronized to the latest commits and erased the database. For me the normal Fairies work well, both from normal character and transformed in an SP, but I have problems with the sealed Fairies. After the message, even if you press confirm, it does nothing. :/
