### ISSUE TITLE
Review TargetHit

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#958]
- [ ] \* Sp6 S / Sp5 M (teleportation skill) is buggy. When you try to use this skill very often your character don't teleporter to the monster.
Packet for teleportation skill SP6 S from official (Thank you markus)
in 3 24 1786 54 153 2 100 100 0 0 0 -1 0 0 -1 - 0 -1 0 0 0 0 0 0 0 0
ms_c 0
qslot 0 1.1.10 1.1.1 1.1.2 1.1.6 1.1.4 0.7.-1 0.7.-1 0.7.-1 0.7.-1 0.1.47
qslot 1 1.1.5 1.1.3 1.1.7 1.1.8 1.1.9 1.1.10 1.1.1 1.1.2 1.1.8 1.1.4
qslot 2 0.7.-1 0.2.-1 0.7.-1 0.7.-1 0.1.47 1.1.5 1.1.3 1.1.7 1.1.6 1.1.9
ct 1 PLAYERID 3 1909 34 4351 1091
scp 1
su 1 PLAYERID 3 1909 1091 120 13 4331 27 154 0 0 33070 0 0
visible with swordsman)

**Comment by Elendan** [comment]
https://gyazo.com/aebd103208efc70e72c4d35d00f86b18

Sometimes, when you use the left skill, it repetively uses the right skill

**Comment by 0Lucifer0** [comment]
I dont need Any of this for review skill Its not a bug fix Its a review i Will redo all and Will see if error after ><

**Comment by Uppermost** [comment]
#971 need to see that

**Comment by Uppermost** [comment]
#996

**Comment by unknownforces** [comment]
https://gyazo.com/4d7bb25380e720086c3d80113f91b9af

**Comment by Martazza** [comment]
Fix https://gyazo.com/4d7bb25380e720086c3d80113f91b9af

**Comment by Uppermost** [comment]
#1154

**Comment by Uppermost** [comment]
This system need to be fix asap

**Comment by MasterDomino** [comment]
we need testing again after merging hitqueue some of this bugs should have been fixed

**Comment by Uppermost** [comment]
it's already tested and I have already check box for fix issues.

**Comment by earthnash** [comment]
https://gyazo.com/84f0d36bf5e937cd9eec9de51246b35d
it has a problem with hp window when player attack monster

**Comment by Uppermost** [comment]
Now it's a priority if we need to close 1.0.4 targethit need to be finish same for monsters skills

**Comment by 0Lucifer0** [comment]
because on the su packet we should use the monster position not the characterposition.
