### ISSUE TITLE
Cercle de Temps BUG

### ISSUE THREAD

**Issue by Legend92** [OpenNos/OpenNos#963]
BUG ALL! TELEPORT CERCLE.
![20160914-0-leggendario](https://cloud.githubusercontent.com/assets/22172114/18510561/0160bc78-7a7f-11e6-8080-b28da3b1c7fb.jpg)

**Comment by MasterDomino** [comment]
not coded yet -,-

**Comment by Legend92** [comment]
WHAT CODED?

**Comment by 0Lucifer0** [comment]
THE FUNCTION THAT ALLOW YOU TO USE LOWER CASE AND A PART OF YOUR BRAIN.
