### ISSUE TITLE
add $SearchItem command

### ISSUE THREAD

**Issue by chucktheripper** [OpenNos/OpenNos#966]
Create the $SearchItem command, this should look for the Item-Name in the table and return all results which contain the search Parameter.

Command structure: $SearchItem ItemName
ItemDAO Method: FindItemByName(string name)

The results should be listed with VNUM + NAME to the Chat window, maybe Format it a bit.

**Comment by 0Lucifer0** [comment]
USE * in It for a like could be usefull ;)
