### ISSUE TITLE
add group sharing mode system in act4

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#972]
add group sharing mode system in act4
@need information about it ? how did it function?

**Comment by Uppermost** [comment]
All player on the same group drop the same items if they attack.
The item is directly inside the inventory if there is no share it change nothing in act 4 I think because you need to attack the monster to win an item. If you attack and cause like 10% of damage of the monster you can have the drop.

**Comment by SC909** [comment]
You have to at least take 10% of monster hp to have a chance of getting anything.
You can not die by monsters or opposite camp (the count will reset, and you will get nothing even if you respawn, which means you have to deal 10% damage to every monster again).
You can not lose a target of a monster on yourself - it is something like agro monsters or attacking any of them and letting them to follow you.
If you change maps (even if you go back) the count will reset.

**Comment by Ciapa** [comment]
Basic implementation done. In official, you don't have to make at least 10% damage. So the Code is actually the full implementation.
