### ISSUE TITLE
Problem with monster dead refresh

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#979]
When character 1, kill some monster, character 2 see all monster even if they monster are dead
![image](https://cloud.githubusercontent.com/assets/15254478/18553169/bdfd36b4-7b5f-11e6-8cf8-d347d83a5936.png)

Wrong refresh maybe ?

PS : This problem is caused by $Invisible command, we can maybe close it

**Comment by 0Lucifer0** [comment]
Will be fix in review
