### ISSUE TITLE
Add command shutdown/reboot 

### ISSUE THREAD

**Issue by 0Lucifer0** [OpenNos/OpenNos#98]
Add command shutdown/reboot

**Comment by chucktheripper** [comment]
checking character permission was actually ment for this issue.

**Comment by 0Lucifer0** [comment]
oh ok^^ but what do you mean by checking character permission? we just need to show a message shutdown and close the executable or restart it

**Comment by chucktheripper** [comment]
if the character which sends this command is permitted to do this (admin)

**Comment by 0Lucifer0** [comment]
sure (like all commands)

**Comment by chucktheripper** [comment]
just to be sure :P
