### ISSUE TITLE
Problem with NPC speed

### ISSUE THREAD

**Issue by Uppermost** [OpenNos/OpenNos#980]
This npc is very more fast than the official server, there is a problem with speed (There problem is new, I don't have this problem before but I don't know how time ago)
https://gyazo.com/9d11720bc167c3d58711669b6e3a20b7

**Comment by 0Lucifer0** [comment]
other npc have this problem too? because if not it's only because the parsed speed on dat is not correct.

**Comment by Uppermost** [comment]
It was good before and idk for others

**Comment by Uppermost** [comment]
fix by lucifer commit
