### ISSUE TITLE
World server crash sp unequip while $Speed = 59

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#983]
![sssd](https://cloud.githubusercontent.com/assets/17483888/18571922/9645695a-7bb6-11e6-9def-67659d366f8e.PNG)

**Comment by Uppermost** [comment]
I have test sometime and I don't have this problem.

**Comment by The-Art-Of-War** [comment]
Okay i will have a look and update everthing and then talk to you later

**Comment by Uppermost** [comment]
ok

**Comment by The-Art-Of-War** [comment]
Okay it wokrs perfectly i will close that one :D
