### ISSUE TITLE
World server crash too much Monster's ($Summon)

### ISSUE THREAD

**Issue by The-Art-Of-War** [OpenNos/OpenNos#984]
![dddd](https://cloud.githubusercontent.com/assets/17483888/18572247/dafdb914-7bb9-11e6-864d-c864ad5731b1.PNG)

**Comment by chucktheripper** [comment]
Use ConcurrentList/Dictionary for MapMonsters to avoid problems like that

**Comment by chucktheripper** [comment]
This seems to happen in MapMonsterTask when using Array.CopyTo, so previous suggestion is only a general approach

**Comment by chucktheripper** [comment]
should not be crashing anymore

**Comment by 0Lucifer0** [comment]
seem's fixed
