### ISSUE TITLE
NPC are double

### ISSUE THREAD

**Issue by Evening99** [OpenNos/OpenNos#986]
I use the parser and now the NPC that are NosVille are double

**Comment by 0Lucifer0** [comment]
You just parsed Packet With différent id... never add something in Packet.txt You should remove all and redo

**Comment by Uppermost** [comment]
It's because you relog in NosVille after an update and the id of they monster is changed after all update. You need to disable map already done when you use packetlogger again

**Comment by Evening99** [comment]
Ok thank you, Fortunately I kept my old Packet.txt
