### ISSUE TITLE
can't login when password capitalized

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#989]
Hello,
i can login when the password is lowercase. 

![lit](https://cloud.githubusercontent.com/assets/22244296/18600834/f3f16c3a-7c5f-11e6-9f9a-d74027f55fdc.png)

but when the password capitalized is then I can't login
![big](https://cloud.githubusercontent.com/assets/22244296/18600848/187d4bf0-7c60-11e6-8999-8f11775179f3.png)

Error when password capitalized:

![er](https://cloud.githubusercontent.com/assets/22244296/18600892/4c9028cc-7c60-11e6-9dcd-cea03a543192.png)

PS: both passwords was with SHA512 encrypt.

**Comment by 0Lucifer0** [comment]
It work great With uppercase... i think 2nd Is not sha512 seems to little to be sha512 (all password in sha512 have the same size)

**Comment by 0Lucifer0** [comment]
Ah no You talk about world ok
