### ISSUE TITLE
Server Crash when people remove sp

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#991]
![crash1](https://cloud.githubusercontent.com/assets/22244296/18608447/c1ef582a-7ce9-11e6-8af8-28be47dbb07e.png)

**Comment by MyTaleON** [comment]
It crashes not every time when remove you're SP.

**Comment by Uppermost** [comment]
Compile the emulator with CTRL+F5 and click on button "continue" there is an example or send the exception error if there is an exception. Thanks. Impossible to reproduce it on my test server
