### ISSUE TITLE
 If someone is in group  it does not appear

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#992]
![bug2](https://cloud.githubusercontent.com/assets/22244296/18608491/df1befac-7cea-11e6-98c1-b053fdf5bdfc.png)

**Comment by Uppermost** [comment]
Random problem? more information ?

**Comment by MyTaleON** [comment]
I wanted to test it , but then passes through the: https://gyazo.com/993a9bee4f78ffe04da8aa1a86b92750

**Comment by Uppermost** [comment]
![image](https://cloud.githubusercontent.com/assets/15254478/18608528/198c561c-7cec-11e6-8477-0d8ccc23993b.png)
Try to update the emulator, is not normal I don't have this problem.

**Comment by MyTaleON** [comment]
here is the problem replay -> https://gyazo.com/6e8ed0d0525b87f55fad54e6ed131517 
i hope you see the problem. :D

**Comment by Uppermost** [comment]
Probably a refresh problem

**Comment by MasterDomino** [comment]
test now please

**Comment by MyTaleON** [comment]
@MasterDomino same problem.. 
![group](https://cloud.githubusercontent.com/assets/22244296/18614725/b2ee7242-7d94-11e6-9f3b-0b21c9a75afb.png)

**Comment by Uppermost** [comment]
I think is solved after the martazza commit ;) I test and close it if is finish.
