### ISSUE TITLE
when use a skill (not all skills) comes a error on the World Server Console

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#994]
![error1](https://cloud.githubusercontent.com/assets/22244296/18608812/f3947428-7cf3-11e6-981c-7474bd2af40b.png)

**Comment by chucktheripper** [comment]
same question here, which skill did you use?

**Comment by 0Lucifer0** [comment]
Ok Its because we parse to short Target and not to int in u_s mtlist

**Comment by 0Lucifer0** [comment]
will be fix in the review
