### ISSUE TITLE
Find new solution DeepCopy crosssave of character

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#995]
![error2](https://cloud.githubusercontent.com/assets/22244296/18608976/43eba524-7cf7-11e6-8559-8eeb4dce1ce6.png)

**Comment by chucktheripper** [comment]
This is a Problem with DeepCopy of character

**Comment by chucktheripper** [comment]
DeepCopy should avoid enumerable changes when saving, we need a better solution here
