### ISSUE TITLE
Error in World Console when SpecialZoneHit

### ISSUE THREAD

**Issue by MyTaleON** [OpenNos/OpenNos#997]
![error3](https://cloud.githubusercontent.com/assets/22244296/18609457/da44135c-7d02-11e6-9ceb-b7ac6ebac196.png)

**Comment by chucktheripper** [comment]
which skill did you use?

**Comment by MyTaleON** [comment]
@chucktheripper i don't know.. it's from my community. sorry.

**Comment by 0Lucifer0** [comment]
same as the other
